### ISSUE TITLE
For July 2018

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#101]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `14,057`
 - BSQ address: B1HGxmhfWJwwvvDgTRrWpZ1QsEZn7rMEaVE

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

### Roles documentation and infrastructure

We've been working with the concept of roles since the inception of Phase Zero, but this month I took the time to formally document everything and comprehensively update the associated infrastructure.

 - Produce [Roles](https://docs.bisq.network/roles.html) doc: bisq-network/bisq-docs#46
 - Update [Proposals](https://docs.bisq.network/proposals.html#maintainer) doc to conform to the instructions in the doc above (changes included in the PR above), and also to serve as an example / template for how role documentation should be written.
 - Updated (and created as necessary) [GitHub teams](https://github.com/orgs/bisq-network/teams) in accordance with the doc above, such that primary role owners are the maintainers of their GitHub teams and can manage them independently. 

The next step with this work is for individual role owners to write up their own docs; in most cases this should by a minor effort. @m52go has [agreed to co-write](https://github.com/bisq-network/roles/issues/66#issuecomment-407640304) @sqrrm's btcnode maintainer documentation as a first step, and after we see how that goes, we'll ask other role owners to get involved and take care of their own documentation as well.

**BSQ requested:** `3000`

### Pricenode rewrite

 - Refactor (rewrite) pricenode: https://github.com/bisq-network/bisq-pricenode/pull/7

Since merging the pricenode rewrite PR in April, I've held off on requesting compensation for it, but as it's now abundantly clear that it works well and that all @bisq-network/pricenode-operators have long since updated to the latest version, I'll claim compensation now.

**BSQ requested:** `9000`

### Otherwise

I delivered little else beyond minor changes this month due to my ongoing health issue.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I have a number of [WIP PRs in the bisq-docs repository](https://github.com/bisq-network/bisq-docs/pulls), many in a very raw draft state, but I'll be taking a break from writing for the next weeks to focus on build infrastructure and coding. Interested parties are free to pick up the ball with those PRs or to write other docs that are called out at https://docs.bisq.network. The Payment Methods documentation would be a very useful place to start!

The first thing I'll be focusing on in the coming month is reconsolidating most of our bisq-* repositories into a single multi-module repository. You can read more about this in the doc [here](https://github.com/cbeams/bisq/blob/reconsolidation-dryrun/RECONSOLIDATION-GOALS). In any case, this change will be made in the least disruptive way possible, likely on the back of the v0.7.2 release in early–mid August. In the meantime, as described in the doc above, I'll be working on a dry run of the change that people will be able to play with and review.

## Roles performed

> _Provide summary line items for each role you own per the instructions at https://docs.bisq.network/roles.html#compensation._

### Substantive reports

 - Arbitrator: https://github.com/bisq-network/roles/issues/13#issuecomment-409163443 `(NA)`
 - Bisq Docs Maintainer: https://github.com/bisq-network/roles/issues/29#issuecomment-409165887 `(100 BSQ)`
 - Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12#issuecomment-409176789 `(100 BSQ)`
 - DNS Admin: https://github.com/bisq-network/roles/issues/18#issuecomment-409237387 `(25 BSQ)`
 - Founder: https://github.com/bisq-network/roles/issues/1#issuecomment-409296376 `(NA)`
 - GitHub Admin: https://github.com/bisq-network/roles/issues/16#issuecomment-409241105 `(50 BSQ)`
 - Proposals Maintainer: https://github.com/bisq-network/roles/issues/30#issuecomment-409281851 `(150 BSQ)`
 - Roles Maintainer: https://github.com/bisq-network/roles/issues/28#issuecomment-409243674 `(25 BSQ)`
 - Slack Admin: https://github.com/bisq-network/roles/issues/23#issuecomment-409244657 `(25 BSQ)`
 - Support Maintainer: https://github.com/bisq-network/roles/issues/76#issuecomment-409253177 `(25 BSQ)`
 - Twitter Admin: https://github.com/bisq-network/roles/issues/21#issuecomment-409261397 `(1500 BSQ)`

### Nothing to report

 - Bisq Pricenode Maintainer: https://github.com/bisq-network/roles/issues/5#issuecomment-409167689 `(25 BSQ)`
 - Bisq Pricenode Operator: https://github.com/bisq-network/roles/issues/14#issuecomment-409169038 (`32 BSQ`)

### Secondary roles

The following are roles where I play a _secondary_ role, and do not (necessarily) do monthly reports:

 - Compensation Maintainer: https://github.com/bisq-network/roles/issue/31

### Decommissioned roles

 - DAO Maintainer: https://github.com/bisq-network/roles/issues/4#issuecomment-409230714 `(0 BSQ)` 

## Notes to self
<details>

My contributions this month were created by reviewing the results of this GitHub Issues search query: [org:bisq-network involves:cbeams updated:2018-07-01..2018-07-31 sort:updated-desc ](https://github.com/issues?page=1&q=org%3Abisq-network+involves%3Acbeams+updated%3A2018-07-01..2018-07-31+sort%3Aupdated-desc)

The list of roles above was generated by the following `ghi` command run within my clone of the bisq-network/roles repository:

```
ghi list --assignee=cbeams --no-labels \
| grep -v '^#' \
| cut -b7- | rev | cut -d' ' -f3- | rev | sort \
| xargs -Irole echo " - role: "
```

Also useful to opening all of these issues is the following command:
```
for role in $(\
ghi list --mine \
  | grep -v '^#' \
  | cut -d'[' -f1 \
  | sed 's/^ *//' | sed 's/  /:/' \
  | awk -F':' '{print $2 ":" $1}' \
  | sort | cut -d':' -f2\
); do ghi show --web $role; done;
```
</details>

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/94#issuecomment-410437521
