### ISSUE TITLE
For July 2018

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/compensation#102]
## Summary
- BSQ requested: 950
- BSQ address: B16kMZonmnNXrZvSqGuXVjpWWTZnSVG3xJb
## Contributions delivered
- [Payment Methods Slack](https://bisq.slack.com/messages/C89R6FQS3/) 100
- [Payment Methods Community](https://bisq.community/c/payment-methods) 100
- [Payment Methods Tracking and Report](https://docs.google.com/spreadsheets/d/1AeWAz5w_IzIQ3-QS9yEzZBOTH_83DT503IhLg_PQD10/edit?usp=sharing) 750
## Contributions in progress
- [Payment Methods Knowledge Base: Cash Deposit](https://github.com/bisq-network/bisq-docs/pull/52)
- [Payment Methods Knowledge Base: Revolut](https://github.com/bisq-network/bisq-docs/pull/51)
- [Adding Payeer](https://github.com/bisq-network/payment-methods/issues/14)
- [Adding Serve](https://github.com/bisq-network/payment-methods/issues/7)
- [Adding Hal Cash](https://github.com/bisq-network/payment-methods/issues/3)
- [Adding Qiwi](https://github.com/bisq-network/payment-methods/issues/15)
- [Adding Advanced Cash](https://github.com/bisq-network/payment-methods/issues/17)
## Roles performed
- Payment Methods Maintainter. Report for July: https://github.com/bisq-network/roles/issues/38#issuecomment-409177198

**Comment by ripcurlx** [comment]
<img width="598" alt="bildschirmfoto 2018-08-01 um 09 56 45" src="https://user-images.githubusercontent.com/170962/43508857-4fdc6410-9571-11e8-8611-0705128c6352.png">
In this chart from your report sheet it is even more obvious what big effect on total volume altcoin trading has on Bisq atm.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/94#issuecomment-410437521
