### ISSUE TITLE
For July 2018

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#103]
## Summary

 - BSQ requested: 85
 - BSQ address: B1FGfKZQrpbLN9UNMogyJAVTR5PJNRkGPXJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- Review for blabno's HTTP API getting-started doc ([link](https://github.com/bisq-network/bisq-docs/pull/54#pullrequestreview-133427587)) - 65 BSQ

- Review for cbeams' Roles doc ([link](https://github.com/bisq-network/bisq-docs/pull/46#issuecomment-404890381)) - 20 BSQ

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Will be working with sqrrm on a Bitcoin Node maintainer doc (per [this issue](https://github.com/bisq-network/roles/issues/66#issuecomment-407640304)) and ManfredKarrer on f2f doc (per [this issue](https://github.com/bisq-network/bisq-desktop/pull/1607#issuecomment-408988435) and [this slack conversation](https://bisq.slack.com/archives/C701A4NNS/p1532180030000078)).

After this I will consider taking on the role of mailing list maintainer [per this approved proposal](https://github.com/bisq-network/proposals/issues/20), which looks like it might require proposing a new role since Mailchimp Admin is now gone. Will discuss further when the time is right.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

N/A.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/94#issuecomment-410437521
