### ISSUE TITLE
For July 2018

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/compensation#104]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `2700`
 - BSQ address: B19yxYCRTVaDfRfucrH6aEzeZpoVTv8Je8S

This is my second compensation request. 
I tried to follow the https://docs.bisq.network/roles.html#compensation recommandations
I apply the 1BSQ=1USD rule.
I’ll read comments with attention in order to correct what must be.

### Substantive reports

- Support staff | https://github.com/bisq-network/roles/issues/64#issuecomment-409169322 | (BSQ  requested = 2000)
Evaluation is based and intended in line with : previous (june) compensation request, https://github.com/bisq-network/compensation/issues/24 , and other support compensation requests.

- Reddit ambassador | https://github.com/bisq-network/roles/issues/35#issuecomment-409177403 | (BSQ requested = 700)
Evaluation is based and intended in line with : comparison with support work, time spent, comparison with analog existing role : twitter admin -> https://github.com/bisq-network/roles/issues/21#issuecomment-401554300

## Contributions in progress

Development work :
Monitoring pricenodes : https://github.com/bisq-network/bisq-monitor/issues/7

Ecosystem :
I continue to investigate peertube (I bought a bunch of good domain names) : maybe will do something next month.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/94#issuecomment-410437521
