### ISSUE TITLE
For July 2018

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#105]
## Summary

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 250
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

### Hosting
Monthly costs nodes: 50 / node * 5: 250 BSQ

Running:
1 Price node + bitcoinaverage subscription
1 Seed node
2 Bitcoin full nodes
1 Monitoring node + 1 messaging sync node (on one server)

Actual costs of nodes + subscription = 162 USD, 50 USD per server average seems fair considering general maintenance and standby for issues. Consolidating sync node and monitoring node into e.g. pricenode would be possible to reduce this to 4 servers, will monitor resource usage.
  
## Roles performed

Pricenode Operator at https://github.com/bisq-network/roles/issues/14#issuecomment-409362698
Seednode Operator at https://github.com/bisq-network/roles/issues/15#issuecomment-409363287
Bitcoin Node Operator at https://github.com/bisq-network/roles/issues/67#issuecomment-409363521
Monitoring Operator / Maintainer at https://github.com/bisq-network/roles/issues/10#issuecomment-409364207
Freenode IRC Admin at https://github.com/bisq-network/roles/issues/22#issuecomment-409364509

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/94#issuecomment-410437521
