### ISSUE TITLE
[WIP] For cycle 37

### ISSUE THREAD

**Issue by alkum** [bisq-network/compensation#1062]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[BSQ amount]`** 
- USD requested: [USD amount] 
- BSQ rate: [rate] USD per BSQ 
- Previous compensation request (if applicable): #1037  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Per-module logging | dev | 200 | https://github.com/bisq-network/bisq2/pull/306 | |
| | | |  | Small PRs. See total below.
| | dev | TBD |  | Total for items above.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- https://github.com/bisq-network/bisq2/issues/238
- https://github.com/bisq-network/bisq2/pull/244

Small PRs:
- https://github.com/bisq-network/bisq2/pull/307

**Comment by MwithM** [comment]
Closed as not submitted.
