### ISSUE TITLE
[WIP] For Cycle 37

### ISSUE THREAD

**Issue by opticbit** [bisq-network/compensation#1091]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[1]`** 
- USD requested: [1.22] 
- BSQ rate: [rate] USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| Consultant | dev | 1.22 | meet.jit.si/ redacted | 1hr discussion on CBM security |

## Contributions in progress

> available for followup

**Comment by w0000000t** [comment]
That was a cheap private consultation! ;-) You should update the BSQ rate to 1.03USD, also it would be uneconomical/impossible to request such compensation as you will have to pay 2BSQ on minting, plus 100sats as minting cost which is below dust limit, and also less than the 282sats fee at 2sat/vB from Bisq application. Also, dust limit on BSQ is 5.46.
So I'd say, go for at least 10BSQ.

**Comment by MwithM** [comment]
Closed as not submitted.
