### ISSUE TITLE
For August 2018

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#111]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 400
 - BSQ address: B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE

## Contributions delivered
> Provide links to contributions you have delivered, the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value.

None.

## Contributions in progress
> Provide links to work you're involved with that is still in progress. This section is optional, and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same.

None.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

### Substantive reports

none

### Nothing to report

- Bisq Pricenode Operator at bisq-network/roles#14 (50)
- Bisq Seednode Operator at bisq-network/roles#15 (50)
- Bisq Bitcoin Node Operator at bisq-network/roles#67 (250)
- Bisq Mailman Operator at bisq-network/roles#26 (50)

## Compensation calculation:

no Setup, only maintenance 

Monthly costs nodes: 5* VPS (50 / node) -> 250
Monthly costs dedicated node 100
Monthly costs mailinglist server: 50
=400

**Comment by cbeams** [comment]
@emzy, please review the (approved) proposal at https://github.com/bisq-network/proposals/issues/30 around how to itemize your compensation requests. As a shortcut, just look at how I and @ripcurlx did it this month at https://github.com/bisq-network/compensation/issues/114 and https://github.com/bisq-network/compensation/issues/109. In particular, look at how the roles are itemized on both sides with regard to how much BSQ is being requested. Thanks.

**Comment by Emzy** [comment]
@cbeams ok. I will try to create my compensation requests that way next time. It is now to late to edit the old one.

**Comment by Emzy** [comment]
@cbeams I changed it.

**Comment by cbeams** [comment]
Thanks, @Emzy. I didn't mean for you to go back and change this one, just for the future, but thanks for doing so in any case!
