### ISSUE TITLE
For August 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#112]
## Basic information

 - BSQ amount requested: **10900**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

### Development work:
Some past dev work from previous months got shipped with 0.8.0:
- [Rounding of fiat values to improve privacy](https://github.com/bisq-network/bisq-desktop/pull/1623)
- [Add mobile notifications](https://github.com/bisq-network/bisq-desktop/pull/1624)
- [Fix transaction broadcast issue](https://github.com/bisq-network/bisq-desktop/pull/1639)
- [Add HalCash](https://github.com/bisq-network/bisq-desktop/pull/1619)
- [Add Face to Face payment](https://github.com/bisq-network/bisq-desktop/pull/1607)
- [Added DAO code](https://github.com/bisq-network/bisq-desktop/pull/1627)
- [Refactoring of generics](https://github.com/bisq-network/bisq-desktop/pull/1610)
- [Relay node for Bisq notifications](https://github.com/bisq-network/bisq-relay)
- Testing for Bisq notifications mobile app
Request for dev work shipped in 0.8.0: 8000 BSQ

A big part of my dev work that month was for the DAO but as it is not shipped I do not include it to that compensation request (though its mostly merged to master). 
I will consider next months to add all my past DAO work if [that proposal](https://github.com/bisq-network/proposals/issues/38) gets accepted.

Beside that I helped @blabno with integration of the API and started review of did some refactoring.
- https://github.com/ManfredKarrer/bisq-http-api/tree/http-api
- https://github.com/ManfredKarrer/bisq-core/tree/http-api
- https://github.com/ManfredKarrer/bisq-desktop/tree/http-api

As that work is not merged to master and not shipped I do not include it to that compensation request.

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1 `(500)`
- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8 `(500)`
- Seed node maintainer: https://github.com/bisq-network/roles/issues/6 `(25)`
- Statsnode Maintainer: https://github.com/bisq-network/roles/issues/7 `(25)`
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14 `(25)`
- Events Maintainer: https://github.com/bisq-network/roles/issues/65 `(25)`
- Markets Website+API Maintainer: https://github.com/bisq-network/roles/issues/9 `(25)`

Operator roles:
- Markets Website+API Operator: https://github.com/bisq-network/roles/issues/9 `(50)`
- Seed node operator: https://github.com/bisq-network/roles/issues/15 `(6 nodes: 300)`
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10 `(50)`
- Price node Operator `(2 nodes: 100)`
- Relay node (mobile notifications) Operator `(50)`
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67 `(2 nodes: 100)`
- BSQ explorer node `(50)`

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

Major roles:
- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63 `(500)`
- GitHub Admin: https://github.com/bisq-network/roles/issues/16 `(500)`
- Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12 `(50)`
- Slack Admin: https://github.com/bisq-network/roles/issues/23 `(25)`

Minor roles:
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Freenode Admin: https://github.com/bisq-network/roles/issues/22
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31
- Transifex Admin: https://github.com/bisq-network/roles/issues/20
- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Support Staff: https://github.com/bisq-network/roles/issues/64

Requested for all the listed roles: 2900 BSQ

[1] https://github.com/ManfredKarrer/bisq-core/tree/voting

**Comment by cbeams** [comment]
@ManfredKarrer, I just noticed that you requested BSQ for the Founder role. I've been treating that role as not applicable for compensation because it doesn't directly add value, i.e. there's nothing I really do in the specific capacity of "founder" (except write a monthly report). Everything I do that I request compensation for is in the context of some more specific role or in the context of an individual contribution of code, etc.

If you see this differently, that's fine, but we should probably be consistent about it between us.

Also, where you have "minor roles" above, do you mean "secondary roles"?

Thanks.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/107#issuecomment-418244359
