### ISSUE TITLE
For August 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#113]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 190
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

No development work to ask compensation for yet.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

DAO work has now been merged to master but not activated. Holding off with the request for this. Further work on bonds in progress.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bitcoin node maintainer - https://github.com/bisq-network/roles/issues/66#issuecomment-417622371
Bitcoin node operator - https://github.com/bisq-network/roles/issues/67#issuecomment-415526831
Tor relay operator - https://github.com/bisq-network/roles/issues/72#issuecomment-417624043

Requesting 190 for the roles

- 50 for the node maintainer
- 50x2 = 100 for running two bitcoin nodes
- 10x4=40 for the tor relay operator

**Comment by cbeams** [comment]
@sqrrm, please review the (approved) proposal at https://github.com/bisq-network/proposals/issues/30 around how to itemize your compensation requests. As a shortcut, just look at how I and @ripcurlx did it this month at https://github.com/bisq-network/compensation/issues/114 and https://github.com/bisq-network/compensation/issues/109. In particular, look at how the roles are itemized on both sides with regard to how much BSQ is being requested. Thanks.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/107#issuecomment-418244359
