### ISSUE TITLE
For August 2018

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#114]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 582
 - BSQ address: B1HGxmhfWJwwvvDgTRrWpZ1QsEZn7rMEaVE

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

None.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

None.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

### Substantive reports

 - Bisq Docs Maintainer: https://github.com/bisq-network/roles/issues/29#issuecomment-417648299 `(50)`
 - Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12#issuecomment-417678216 `(25)`
 - Founder: https://github.com/bisq-network/roles/issues/1#issuecomment-417680811 `(NA)`
 - Proposals Maintainer: https://github.com/bisq-network/roles/issues/30#issuecomment-417681962 `(25)`
 - Roles Maintainer: https://github.com/bisq-network/roles/issues/28#issuecomment-417682329 `(25)`
 - Slack Admin: https://github.com/bisq-network/roles/issues/23#issuecomment-417688555 `(25)`
 - Twitter Admin: https://github.com/bisq-network/roles/issues/21#issuecomment-417686483 `(300)`

### Nothing to report

 - Arbitrator: https://github.com/bisq-network/roles/issues/13#issuecomment-417646788 `(NA)`
 - Bisq Pricenode Maintainer: https://github.com/bisq-network/roles/issues/5#issuecomment-417675658 `(25)`
 - Bisq Pricenode Operator: https://github.com/bisq-network/roles/issues/14#issuecomment-417676753 `(32)`
 - DNS Admin: https://github.com/bisq-network/roles/issues/18#issuecomment-417679238 `(25)`
 - GitHub Admin: https://github.com/bisq-network/roles/issues/16#issuecomment-417680981 `(25)`
 - Support Maintainer: https://github.com/bisq-network/roles/issues/76#issuecomment-417683674 `(25)`

## Notes to self
<details>

My contributions this month were created by reviewing the results of this GitHub Issues search query: [org:bisq-network involves:cbeams updated:2018-08-01..2018-08-31 sort:updated-desc ](https://github.com/issues?page=1&q=org%3Abisq-network+involves%3Acbeams+updated%3A2018-08-01..2018-08-31+sort%3Aupdated-desc)

The list of roles above was generated by the following `ghi` command run within my clone of the bisq-network/roles repository:

```
ghi list --assignee=cbeams --no-labels \
| grep -v '^#' \
| cut -b7- | rev | cut -d' ' -f3- | rev | sort \
| xargs -Irole echo " - role: "
```

Also useful to opening all of these issues is the following command:
```
for role in $(\
ghi list --mine \
  | grep -v '^#' \
  | cut -d'[' -f1 \
  | sed 's/^ *//' | sed 's/  /:/' \
  | awk -F':' '{print $2 ":" $1}' \
  | sort | cut -d':' -f2\
); do ghi show --web $role; done;
```
</details>

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/107#issuecomment-418244359
