### ISSUE TITLE
For Cycle 39

### ISSUE THREAD

**Issue by Android-X13** [bisq-network/compensation#1152]
## Summary

- **BSQ requested**: **`201`** 
- USD requested: 175 
- BSQ rate: 0.87 USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| Fix/improve clickable areas of toggle buttons | dev | 45 | [bisq-network/bisq/pull/6307](https://github.com/bisq-network/bisq/pull/6307)
| Show Peer Info window only when left-clicking on avatar | dev | 25 | [bisq-network/bisq/pull/6309](https://github.com/bisq-network/bisq/pull/6309)
| Cleanup blockchain explorer URL code & add tests | dev | 60 | [bisq-network/bisq/pull/6319](https://github.com/bisq-network/bisq/pull/6319)
| Fix NPE when accessing DAO > BSQ SUPPLY | dev | 45 | [bisq-network/bisq/pull/6323](https://github.com/bisq-network/bisq/pull/6323)

## Contributions in progress

[Fix issue with offers getting disabled for no apparent reason](https://www.github.com/bisq-network/bisq/pull/6342)
[Prevent NPE when editing offer while not fully connected](https://www.github.com/bisq-network/bisq/pull/6345)
[Refresh all avatars upon setting a peer's tag](https://www.github.com/bisq-network/bisq/pull/6348)
[Prevent NPE in Open Proposals when last column is empty](https://www.github.com/bisq-network/bisq/pull/6352)

**Comment by Android-X13** [comment]
This is my first CR and I have just realized that there are deadlines announced in the compensation repo... I see that the deadline has been reached but people are still submitting CRs so I made this one too.

One question:
Since the total amount requested is relatively low, can I bring this to the next cycle or do I have to submit it to the DAO?

**Comment by MwithM** [comment]
I would prefer if you wait for next cycle to submit it. Indeed, that's the only choice you have right now, as  the DAO proposal phase has concluded.
I leave it open for review, though, so it can be pre-approved by the team lead.

You'll have to use the BSQ rates for Cycle 40, while maintain the same USD amounts.

**Comment by MwithM** [comment]
Closed as not submitted.
