### ISSUE TITLE
For Cycle 40

### ISSUE THREAD

**Issue by Android-X13** [bisq-network/compensation#1166]
## Summary

- **BSQ requested**: **`457`** 
- USD requested: 375 
- BSQ rate: 0.82 USD per BSQ 
- Previous compensation request: #1152  

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| Fix/improve clickable areas of toggle buttons | dev | 45 | [bisq-network/bisq/pull/6307](https://github.com/bisq-network/bisq/pull/6307)
| Show Peer Info window only when left-clicking on avatar | dev | 25 | [bisq-network/bisq/pull/6309](https://github.com/bisq-network/bisq/pull/6309)
| Cleanup blockchain explorer URL code & add tests | dev | 60 | [bisq-network/bisq/pull/6319](https://github.com/bisq-network/bisq/pull/6319)
| Fix NPE when accessing DAO > BSQ SUPPLY | dev | 45 | [bisq-network/bisq/pull/6323](https://github.com/bisq-network/bisq/pull/6323)
| Fix issue with offers getting disabled for no apparent reason | dev | 50 | [bisq-network/bisq/pull/6342](https://github.com/bisq-network/bisq/pull/6342)
| Prevent NPE when editing offer while not fully connected | dev | | [bisq-network/bisq/pull/6345](https://github.com/bisq-network/bisq/pull/6345)
| Prevent NPE in Open Proposals when last column is empty | dev | 50 | [bisq-network/bisq/pull/6352](https://github.com/bisq-network/bisq/pull/6352) | Total for items above.
| Refresh all avatars upon setting a peer's tag | dev | 100 | [bisq-network/bisq/pull/6348](https://github.com/bisq-network/bisq/pull/6348)

**Comment by ripcurlx** [comment]
As dev team lead I approve this compensation request for dev. Please submit your CR for voting to the DAO and post your transaction ID here afterwards. Thanks!

**Comment by Android-X13** [comment]
TxID:

02f2a180563274f101fba1bdd30bee5e742a240ed0f7c3b97987f2261ae359a3

**Comment by MwithM** [comment]
Closed as accepted.
