### ISSUE TITLE
For August 2018

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#117]
## Summary

 - BSQ requested: 890
 - BSQ address: B1FGfKZQrpbLN9UNMogyJAVTR5PJNRkGPXJ

## Contributions delivered

**Initiatives**
- Make fee explanation clearer on faqs page ([pull request](https://github.com/bisq-network/bisq-website/pull/73)) - 250
- Add mobile notifications doc ([pull request](https://github.com/bisq-network/bisq-docs/pull/79)) - 300
- Add face-to-face section on trading rules doc ([pull request](https://github.com/bisq-network/bisq-docs/pull/82)) - 300

**Miscellaneous**
- Contribute feedback on mobile notifications ui ([issue](https://github.com/bisq-network/bisq-desktop/issues/1622)) - 20
- Contribute feedback on android app ([issue](https://github.com/joachimneumann/bisqremote_Android/issues/2)) - 20

## Roles performed

N/A.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/107#issuecomment-418244359
