### ISSUE TITLE
[WIP] For Cycle 40

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#1172]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`243.9`** 
- USD requested:  200 
- BSQ rate:  0.82 USD per BSQ 
- Previous compensation request (if applicable):  https://github.com/bisq-network/compensation/issues/1151

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Pricenode operator | ops* | 50 | https://github.com/bisq-network/roles/issues/14#issuecomment-1273820170 | 1 node, 1 month |
| Seednode operator | ops* | 100 | https://github.com/bisq-network/roles/issues/15#issuecomment-1273821460 |  2 torv3 nodes for 1 month |
| Bitcoin node operator | ops* | 50 | https://github.com/bisq-network/roles/issues/67#issuecomment-1273822020 | 2 nodes, 1 month |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by MwithM** [comment]
Proposal phase finished yesterday, so you  won't be able to submit this for Cycle 40.

**Comment by MwithM** [comment]
Please open a new compensation request For Cycle 41, you'll have to use the new BSQ/USD rates.

Closed as not submitted.
