### ISSUE TITLE
Bisq September Market Kick-Start Day bounty

### ISSUE THREAD

**Issue by bugrasan** [bisq-network/compensation#119]
## Summary

 - BSQ requested: 10
 - BSQ address: B12Q5Uis5eZHUHmv2gNksuxWRPxD4c6CDuz

## Contributions delivered

Participated in September Market Kick-Start Day [September 20th]

**Comment by clearwater-trust** [comment]
## Summary
- BSQ requested: 10
- BSQ address: B15VTptnSAUURnacM9MV736yjUmF4Qta6E2

## Contributions delivered
Participated in September Market Kick-Start Day [September 20th]

**Comment by fedegrc** [comment]
### Summary

- BSQ requested: 10
- BSQ address: B1961fVVFMnQunrKVtWVsBsReLvL6q6VT3R

### Contributions delivered

Participated in September Market Kick-Start Day [September 20th]

**Comment by princeofeth** [comment]
### Summary
 
    

-  BSQ requested: 10

-  BSQ address: B145pKGNBEyCiZxU1bbrzPmv2Y7j2WASf9A



 ### Contributions delivered
 
 Participated in September Market Kick-Start Day [September 20th]

**Comment by pfergi42** [comment]
### Summary

- BSQ requested: 10
- BSQ address: B1D3KUonHEcCg9tuvYXVRbWivdGfCHtnA8n

### Contributions delivered
Participated in September Market Kick-Start Day [September 20th]

**Comment by ripcurlx** [comment]
@pfergi42 @princeofeth @fedegrc @clearwater-trust Could you please create your own issue (compensation request) for the upcoming voting round. Each request is linked within the voting sheet, so we need a separate issue for each of you. Thanks!

**Comment by pfergi42** [comment]
Done. Thanks, @ripcurlx. My first BSQ request and hopefully not my last!

Please let me know if there's any issue.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/121#issuecomment-426911712
