### ISSUE TITLE
For September 2018

### ISSUE THREAD

**Issue by joachimneumann** [bisq-network/compensation#120]
## Summary

 - BSQ requested: 25,000
 - BSQ address: B1HjazHawa5LD3j8o4gStJYyZFSnZqx8R7H

## Contributions delivered

- iOS and Android notification app. Both apps are in the app store. Code and more info: https://docs.bisq.network/bisq-mobile.html
- Number of installations as of September 24: iOS: 295, Android 310
- The development included several rounds of testing and UI improvements, mostly with Manfred Karrer
- During the early stage I have implemented a dummy notification server in Java (https://github.com/joachimneumann/bisqremote). This was the base for the Bisq relay node which Manfred implemented (https://github.com/bisq-network/bisq-relay)
- Some marketing in slack and Reddit
- Special effort to persuade the Apple Reviews to accept the iOS app
- My contributions stated in mid May and I have worked on the apps in June, July, August and September of 2018 

## Contributions in progress
I plan to adopt the new icon and colors in the next days and plan to maintain both apps

## Why 25,000 BSQ?

The amount that I ask for is substantial and I am open to discussions.

There are several ways to evaluate the value of a contribution and none of them are perfect:
- Contribution to Bisq. If I assume that the value of Bisq is 2,500,000 BSQ and I evaluate that the mobile apps increase the value by 1%, the resulting increase of value is 25,000 BSQ. 
However, the value of the project can easily be off by a factor of 3 and the percentage by which the mobile apps increase this value could also be evaluated anywhere between 0.001% (mostly useless) and 5% (very important). There is quite a bit of guesswork and estimation going on in this approach.
- Effort invested. From May to September 2018, I have spent a total of 360 hours on the project: 60 hours discussions, concept and early prototype iterations, 120 hours iOS implementation, 90 hours Android implementation, 25 hours administrative stuff (app stores, marketing) and 20 hours additional testing and bug-fixing. If I apply the hourly rate that I take as an independent software developer in Europe (80 Euros) I would end up at Euro 24,400.
However, the effort invested is not a good measure – for example if someone invests a large effort into a useless contribution.

Of course, I am open to discuss the value of my contribution.

**Comment by ManfredKarrer** [comment]
@joachimneumann 
Thanks for the detailed overview and reasoning about the valuation.

I personally would have seen it more in the 20 000 BSQ range, but 25 000 is OK for me as well. As you pointed out it is very difficult to find the right number for the value added to the project. 
It is good that you are doing the request with sufficient time before the voting so stakeholders can add their comments and discuss.

@bisq-network/contributors: It would be good to make that a rule to make the compensation requests earlier. @ripcurlx Could you send out the invites for requests a week earlier and mention that?

I would like to invite all stakeholders (@bisq-network/contributors) to add their opinion to the above valuation. We are in an important process to find out the best model how we valuate such bigger efforts and there will be more in future (API, redesign/rebranding, Mobile app from @blabno,  DAO,...). So it is good to have an active process how we as a community find a consensus how to deal with valuation and what is considered a fair value.

**Comment by ripcurlx** [comment]
@joachimneumann Thanks for the great work you put into the mobile app!
I would also see it more in the 20 000 BSQ range if I would estimate the development effort, but as I think the marketing value of the mobile app could bring easily additional 5000 BSQ of worth I'll give a :+1: for this request as well.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/121#issuecomment-426911712
