### ISSUE TITLE
For Cycle 43

### ISSUE THREAD

**Issue by dije733** [bisq-network/compensation#1211]
## Summary

- **BSQ requested**: **`10`** 
- USD requested: 6.60
- BSQ rate: 0.66 USD per BSQ

## Compensation request for attaching a custom Burningman address to a genesis output receiver. [1]

Dummy request amount: 10 BSQ

Requester name: `Bisq co-founder 26`

Transaction ID for proving that I own that genesis output address: `6ca1ccc3a986c3c9df493216cb1d10b14b1ed6b9293170df6f4ce3f875459439`

Burn BSQ transaction ID for proving that I burned 10 BSQ: `9e3fe9eeeb04ddcee4d14b1e4bb58d07047bf1b955ae0f1786117b5acb3c8be0`
The pre-image used at the Burn BSQ transaction is transaction ID from above.

Custom Burningman address: `bc1qmafvhrek2euluajs4jyurreep99g9zw7h7wfg2`

OpReturn data as hex: `626331716d6166766872656b3265756c75616a73346a79757272656570393967397a7737683777666732`

How to verify?
- Check the transaction at a block-explorer and see if the input is from the output of the genesis tx. The output index need to match the index in the "Bisq co-founder-x" name.
- Copy the opReturn data of that transaction from the transaction details and use a hex converter tool [2] to get the custom receiver address. Check if the receiver address matches the one in the compensation request.
- Check that the burn BSQ transaction was made and that the opReturn data matches the hash of the transaction ID.

Please only vote on the proposal if you have verified all the data.

[1] https://github.com/bisq-network/proposals/issues/390#issuecomment-1306075295
[2] https://www.online-toolz.com/tools/decode-hex.php

**Comment by dije733** [comment]
Compensation request Tx ID: 4d88571fe723f66a3891e602dfe3f9700532a288588a30d3a85ea492067baecf

**Comment by MwithM** [comment]
Closed as accepted.
