### ISSUE TITLE
Timeout Fee Reimbursement

### ISSUE THREAD

**Issue by pfergi42** [bisq-network/compensation#122]
## Summary

 - BSQ requested: 26
 - BSQ address: B1D3KUonHEcCg9tuvYXVRbWivdGfCHtnA8n

## Contributions delivered

This is the first compensation request period I am participating in, and would prefer to be reimbursed with BSQ if possible for this timeout error.

Reported bug here:
- https://github.com/bisq-network/bisq/issues/1604

Blockchain explorer link:
- https://www.blockchain.com/btc/tx/d81ef07166c34032ff98179e0ed39abc095e513a22370dfb7149d4e38fcc87fe

**Comment by ManfredKarrer** [comment]
@pfergi42 Please request the refund in BTC as compensation requests are only for added work on Bisq, not for reimbursements.

**Comment by pfergi42** [comment]
Sure thing.

I submitted here, hopefully correctly: https://github.com/bisq-network/support/issues/137
