### ISSUE TITLE
For Cycle 43

### ISSUE THREAD

**Issue by Bisq-co-founder-85** [bisq-network/compensation#1223]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[10]`** 
- USD requested: [6.60] 
- BSQ rate: [0.66] USD per BSQ 

## Compensation request for attaching a custom Burningman address to a genesis output receiver.

Dummy request amount: 10 BSQ

Requester name: "Bisq co-founder-85"

Transaction ID for proving that I own that genesis output address: d4b80848d49c50a8db782915e40fac0e75539087e317eba1e1fbdd2ad7a15a94

Burn BSQ transaction ID for proving that I burned 10 BSQ: 6f6dd8ebb457aa93624f8753e889d4d997fdc09ef04941706a79902c5fb22864
The pre-image used at the Burn BSQ transaction is transaction ID from above.

Custom Burningman address: bc1qcgrcr330we7yg9yuhsh65ycuyngmt94kjkez2x

OpReturn data as hex: 62633171636772637233333077653779673979756873683635796375796e676d7439346b6a6b657a3278

How to verify?
- Check the transaction at a block-explorer and see if the input is from the output of the genesis tx. The output index need to match the index in the "Bisq co-founder-x" name.
- Copy the opReturn data of that transaction from the transaction details and use a hex converter tool [1] to get the custom receiver address. Check if the receiver address matches the one in the compensation request.
- Check that the burn BSQ transaction was made and that the opReturn data matches the hash of the transaction ID.

Please only vote on the proposal if you have verified all the data.

[1] https://www.online-toolz.com/tools/decode-hex.php

**Comment by Bisq-co-founder-85** [comment]
~~Tx ID: 3051b3dac540f49e5ff378486b59619d97d7c00893f128246cb43955100ae236~~

The name is wrong in the first compensation request, correct one is this:
Tx ID: ce03718d9952900c98d5fb9621efe6a4449ce1e81c33b0374c99d9ece3f3af79

**Comment by MwithM** [comment]
Closed as accepted.
