### ISSUE TITLE
For September 2018

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/compensation#123]
## Summary 
- BSQ requested: 800
- BSQ address: B16kMZonmnNXrZvSqGuXVjpWWTZnSVG3xJb 

## Contributions delivered

- [Payment Methods Slack](https://bisq.slack.com/messages/C89R6FQS3/) --> 0
- [Payment Methods Community](https://bisq.community/c/payment-methods) --> 0
- [Payment Methods Tracking and Report](https://docs.google.com/spreadsheets/d/1AeWAz5w_IzIQ3-QS9yEzZBOTH_83DT503IhLg_PQD10/edit?usp=sharing) (Aug + Sept) --> 600
- [Adding Hal Cash](https://github.com/bisq-network/payment-methods/issues/3) --> 200 

## Contributions in progress 

- [Payment Methods Knowledge Base: Cash Deposit](https://github.com/bisq-network/bisq-docs/pull/52) 
- [Payment Methods Knowledge Base: Revolut](https://github.com/bisq-network/bisq-docs/pull/51)

- [Adding Payeer] (https://github.com/bisq-network/payment-methods/issues/14) 
- [Adding Serve] (https://github.com/bisq-network/payment-methods/issues/7) 
- [Adding Qiwi](https://github.com/bisq-network/payment-methods/issues/15) 
- [Adding Advanced Cash](https://github.com/bisq-network/payment-methods/issues/17) 

## Roles performed

- Payment Methods Maintainter. Report for May: https://github.com/bisq-network/roles/issues/38https://github.com/bisq-network/roles/issues/38#issuecomment-424623541

**Comment by ripcurlx** [comment]
@alfsbs Is this request still in WIP by intent?

**Comment by alfsbs** [comment]
> @alfsbs Is this request still in WIP by intent?

completed, thanx!
