### ISSUE TITLE
Cycle 45 deadline is March 11th

### ISSUE THREAD

**Issue by MwithM** [bisq-network/compensation#1246]
The deadline for submitting compensations requests for review is **March 11**. 

More details at: https://bisq.wiki/Compensation
[Calendar](https://calendar.google.com/calendar/embed?src=adfiuiokq9jtac8t9keomc00b0%40group.calendar.google.com&ctz=Europe)

**Comment by ghost** [comment]
## Errors
USD amount not specified in summary section
BSQ amount not specified in summary section
No compensation lineitems found.

**Comment by MwithM** [comment]
Reminder: tomorrow is the last day to submit compensation requests.

**Comment by MwithM** [comment]
Closed for the end of Cycle.
