### ISSUE TITLE
For Cycle 46

### ISSUE THREAD

**Issue by DrColver** [bisq-network/compensation#1271]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[595.24]`** 
- USD requested: [500] 
- BSQ rate: [0.84] USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| Linux notifications, jpackage | dev | | https://github.com/bisq-network/bisq2/pull/678 | |
| Linux notifications | dev | | https://github.com/bisq-network/bisq2/pull/687 | |
| Parse currency type | dev | | https://github.com/bisq-network/bisq2/pull/688 | |
| Stop previous electrum | dev | | https://github.com/bisq-network/bisq2/pull/689 | |
| Left submenu expand/collapse | dev | | https://github.com/bisq-network/bisq2/pull/691 | |
| Chat channel change handling | dev | | https://github.com/bisq-network/bisq2/pull/693 | |
|  Improve offer process | dev | | https://github.com/bisq-network/bisq2/pull/695 | |
|  Fix empty market combobox | dev | | https://github.com/bisq-network/bisq2/pull/697 | |
|  Fix top pane userprofile combobox | dev | | https://github.com/bisq-network/bisq2/pull/698 | |
|  Fix userprofile selection on unfocus | dev | | https://github.com/bisq-network/bisq2/pull/699 | |
|  Send unused bitcoin address | dev | | https://github.com/bisq-network/bisq2/pull/700 | This was an unsolicited feature |
|  Prevent multiple instances | dev | | https://github.com/bisq-network/bisq2/pull/703 | |
|   | dev | 500 | | Total for items above. |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by ripcurlx** [comment]
@alvasw @HenrikJannsen Could you please ACK this CR as I wasn't involved in the contributions. Thanks!

**Comment by HenrikJannsen** [comment]
ACK

**Comment by ripcurlx** [comment]
Based on https://github.com/bisq-network/compensation/issues/1271#issuecomment-1510042975 I approve this compensation request for Dev. Please submit your CR to the DAO for voting and post the transaction ID here afterwards! Thanks and welcome!

**Comment by MwithM** [comment]
Closed as not submitted.

**Comment by DrColver** [comment]
@MwithM  I was unable to submit the request in time, sorry for the inconvenience.
