### ISSUE TITLE
For Cycle 46

### ISSUE THREAD

**Issue by gabernard** [bisq-network/compensation#1274]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`207.14`** 
- USD requested: 174 
- BSQ rate: 0.84 USD per BSQ 

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| GitHub Admin | ops* | 25 |  https://github.com/bisq-network/roles/issues/16#issuecomment-1501364615 | Cycle 41 |
| GitHub Admin | ops* | 25 | https://github.com/bisq-network/roles/issues/16#issuecomment-1501364967 | Cycle 42 |
| GitHub Admin | ops* | 25 | https://github.com/bisq-network/roles/issues/16#issuecomment-1501365109 | Cycle 43 |
| GitHub Admin | ops* | 33 | https://github.com/bisq-network/roles/issues/16#issuecomment-1501365250 | Cycle 44 |
| GitHub Admin | ops* | 33 | https://github.com/bisq-network/roles/issues/16#issuecomment-1501365367 | Cycle 45 |
| GitHub Admin | ops* | 33 | https://github.com/bisq-network/roles/issues/16#issuecomment-1501366224 | Cycle 46 |

**Comment by Emzy** [comment]
As ops team lead I approve this compensation request for ops.

**Comment by gabernard** [comment]
470504702d4dedeba4bbb91b92b0a7092709f39d598ba6c9eb08a8e185d606f7

**Comment by MwithM** [comment]
Closed as accepted.
