### ISSUE TITLE
For Cycle 47

### ISSUE THREAD

**Issue by DrColver** [bisq-network/compensation#1292]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[930.23]`** 
- USD requested: [800] 
- BSQ rate: [0.86] USD per BSQ 
- Previous compensation request (if applicable): #1271  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

I failed to submit the request last cycle, https://github.com/bisq-network/compensation/issues/1271. All old items are listed here with a comment that they are from the previous cycle.

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| Linux notifications, jpackage | dev | | https://github.com/bisq-network/bisq2/pull/678 | Cycle 46 |
| Linux notifications | dev | | https://github.com/bisq-network/bisq2/pull/687 |Cycle 46 |
| Parse currency type | dev | | https://github.com/bisq-network/bisq2/pull/688 |Cycle 46 |
| Stop previous electrum | dev | | https://github.com/bisq-network/bisq2/pull/689 |Cycle 46|
| Left submenu expand/collapse | dev | | https://github.com/bisq-network/bisq2/pull/691 |Cycle 46 |
| Chat channel change handling | dev | | https://github.com/bisq-network/bisq2/pull/693 |Cycle 46 |
|  Improve offer process | dev | | https://github.com/bisq-network/bisq2/pull/695 |Cycle 46 |
|  Fix empty market combobox | dev | | https://github.com/bisq-network/bisq2/pull/697 |Cycle 46 |
|  Fix top pane userprofile combobox | dev | | https://github.com/bisq-network/bisq2/pull/698 |Cycle 46 |
|  Fix userprofile selection on unfocus | dev | | https://github.com/bisq-network/bisq2/pull/699 |Cycle 46 |
|  Send unused bitcoin address | dev | | https://github.com/bisq-network/bisq2/pull/700 |Cycle 46 |
|  Prevent multiple instances | dev | | https://github.com/bisq-network/bisq2/pull/703 |Cycle 46 |
|   | dev | 500 | | Total for items above. |
| Graceful leave channel | dev | | https://github.com/bisq-network/bisq2/pull/742 |Cycle 47 |
| Improve trade buttons | dev | | https://github.com/bisq-network/bisq2/pull/743 |Cycle 47 |
| Refactor leave channel method | dev | | https://github.com/bisq-network/bisq2/pull/778 |Cycle 47 |
| Fix expand icon bug | dev | | https://github.com/bisq-network/bisq2/pull/823 |Cycle 47 |
| Optimize chat view | dev | | https://github.com/bisq-network/bisq2/pull/826 |Cycle 47 |
| Improve user profile selection | dev | | https://github.com/bisq-network/bisq2/pull/834 |Cycle 47 |
|   | dev | 300 | | Total for items above. |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by alvasw** [comment]
ACK

**Comment by HenrikJannsen** [comment]
ACK

**Comment by DrColver** [comment]
957591b16163e1b917e465d7b3fef56cb3cd40965fba4815dcdba673221a1f96

**Comment by ripcurlx** [comment]
Sorry about my absence this cycle and not reviewing all dev CRs. As dev team lead I approve this CR for dev.

**Comment by MwithM** [comment]
Closed as accepted.
