### ISSUE TITLE
For Cycle 51

### ISSUE THREAD

**Issue by aspire2dev** [bisq-network/compensation#1378]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[2000.00]`** 
- USD requested: [1560.00] 
- BSQ rate: [0.78] USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| bisq2 - Ensure protobuf enum have no name conflicts and a UNSPECIFIED default value | dev | | https://github.com/bisq-network/bisq2/pull/1159 | |
| bisq2 - Replace BisqText with Text or Label | dev | | https://github.com/bisq-network/bisq2/pull/1178 | |
| bisq2 - Fiat icons appear out of center in create offer screen | dev | | https://github.com/bisq-network/bisq2/pull/1199 | |
| bisq2 - Layout bug with TextList component | dev | | https://github.com/bisq-network/bisq2/issues/1177 | |
|  | dev | 1560.00 | | Total for items above |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by HenrikJannsen** [comment]
ACK

**Comment by HenrikJannsen** [comment]
Its better to have the USD amount assigned at each task line.

**Comment by aspire2dev** [comment]
Proposal Tx. ID: `a1fb1e2982018b349d1221e0e1b38f0327f7a705c9e5fa1040ae4d063ddd6df9`

**Comment by ripcurlx** [comment]
I approve this compensation request for dev based on https://github.com/bisq-network/compensation/issues/1378#issuecomment-1727817115

**Comment by MwithM** [comment]
Closed as accepted.
