### ISSUE TITLE
For Cycle 52

### ISSUE THREAD

**Issue by aspire2dev** [bisq-network/compensation#1398]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`4094.59`** 
- USD requested: 3030.00 
- BSQ rate: 0.74 USD per BSQ 
- Previous compensation request (if applicable): # https://github.com/bisq-network/compensation/issues/1378

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
|Ordered list on reputation screen|dev|120|https://github.com/bisq-network/bisq2/pull/1203||
|Close button to new profile creation|dev|240|https://github.com/bisq-network/bisq2/pull/1204||
|Expand / Collapse navigation|dev|240|https://github.com/bisq-network/bisq2/pull/1212||
|Dashboard button misalignment|dev|600|https://github.com/bisq-network/bisq2/pull/1219||
|Learn screen, adaptation of Dashboard and Bisq Easy views |dev|480|https://github.com/bisq-network/bisq2/pull/1234||
|Trade apps screen |dev|480|https://github.com/bisq-network/bisq2/pull/1244||
|TabView wrapping |dev|120|https://github.com/bisq-network/bisq2/pull/1247||
|Visual issues when animations are off|dev|180|https://github.com/bisq-network/bisq2/pull/1251||
|Chat rules layout and text review |dev|210|https://github.com/bisq-network/bisq2/pull/1248||
|Network info screen|dev|360|https://github.com/bisq-network/bisq2/pull/1254||

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by aspire2dev** [comment]
Tx. ID: 4a20845f55fdf9551eaa86d3d7283b504d9d46a9f57b7df3ba633beb08434479

**Comment by HenrikJannsen** [comment]
ACK

**Comment by ripcurlx** [comment]
I approve this compensation request for dev based on https://github.com/bisq-network/compensation/issues/1398#issuecomment-1776151016. Sorry for my late response! I'm available from now on on a more regular basis again - finally 😅

**Comment by MwithM** [comment]
Closed as accepted.
