### ISSUE TITLE
Kick Start day bounty

### ISSUE THREAD

**Issue by kwcareer** [bisq-network/compensation#142]
## Summary

 - BSQ requested: 10
 - BSQ address:  B1EoZ4gaFK3Wj7bbN7uypZ6TXcrnniiHpDz

## Contributions delivered

Participated in Market Kick-start day 20th September 2018.
Placed offers for ZEC, DCR and MAID and traded GRC on the day.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
