### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by Technohacker** [bisq-network/compensation#143]
## Summary

 - BSQ requested: 30
 - BSQ address: B1Q9Gg1DxURa1xBvvXmWcJVEDMiwUNWCyad

## Contributions delivered

(Partial) CryptoNote address validator ([pull request](https://github.com/bisq-network/bisq/pull/1683)) - 30

## Contributions in progress

CryptoNote address validator (with checksum validation)

## Roles performed

None

**Comment by ManfredKarrer** [comment]
@Technohacker I think 15 BSQ is very humble. Feel free to ask for more.

**Comment by Technohacker** [comment]
@ManfredKarrer  Well, I don't feel very justified taking too much :P
Updated to take 30 BSQ :)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
