### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#144]
## Summary

 - BSQ requested: 650
 - BSQ address: B1PFD3uscJqFQfLNAS6bWQtr1PUahrWNvC7

Since I missed the [September 2018 compensation](https://github.com/bisq-network/compensation/issues/140) voting round, I am resubmitting some of the contributions in the October 2018 round. 

I retracted some of the compensation requests (crossed out below) after feedback from Manfred. 

### Spreading the word about Bisq (600BSQ)
* Promoted Bisq at the Scaling Bitcoin conference in Japan by talking to around 10 people extensively for two full evenings.  
* Went to local meetups and promoted Bisq.
~* Studied various concepts related to Bisq like public key cryptography, hash functions, proof of work, P2P networks, git, pull requests, etc.~
~* Made some F2F trades to learn how Bisq works. I noticed many of the issues below when doing this.~

### Pull requests (50BSQ)

* https://github.com/bisq-network/bisq/pull/1674: Improved grammar of seed info 
* https://github.com/bisq-network/bisq/pull/1684: Improved grammar of Welcome text 

~### Reported issues (350BSQ)~

~I am only including the issues that I have reported and that have been closed by merging some changes to master.~

~* https://github.com/bisq-network/bisq/issues/1704: Window "Trading wallet is sufficiently funded" appears for too short a time~

~* https://github.com/bisq-network/bisq/issues/1707: An offer maker's contact information is not easily seen in an F2F trade~

~* https://github.com/bisq-network/bisq/issues/1703: Same onion address appearing as multiple peers~

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
