### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#145]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 190
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

All work contributed is on the DAO, to be requested at a later date.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Helping out with review and final touches to get the DAO out in testnet.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bitcoin node maintainer - https://github.com/bisq-network/roles/issues/66#issuecomment-433837468 `(50)`
Bitcoin node operator - https://github.com/bisq-network/roles/issues/67#issuecomment-432191694 `(100)`
Tor relay operator - https://github.com/bisq-network/roles/issues/72#issuecomment-433838114 `(40)`

Total requested for roles, BSQ 190

**Comment by ManfredKarrer** [comment]
Please add also something for your review work. Past DAO work/review work can be added once DAO is on testnet.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
