### ISSUE TITLE
[WIP] For Cycle 56

### ISSUE THREAD

**Issue by salokiam** [bisq-network/compensation#1456]
## Summary

- **BSQ requested**: **``** 
- USD requested: 3000 
- BSQ rate:  USD per BSQ 
- Previous compensation request (if applicable): #[1393](https://github.com/bisq-network/compensation/issues/1393)   

## Contributions delivered

| Title                           | Team |  USD | Link                                                                                                        | Notes |
|---------------------------------|-----|-----:|-------------------------------------------------------------------------------------------------------------| --- |
| Upgrade to java17               | dev |      | https://github.com/bisq-network/bisq2-web-ui/pull/6                                                         |  |
| Update to latest bisq2          | dev |      | https://github.com/bisq-network/bisq2-web-ui/pull/7                                                         |  |
| change submodule url and branch | dev |      | https://github.com/bisq-network/bisq2-web-ui/pull/8 and https://github.com/bisq-network/bisq2-web-ui/pull/9 |  |
| Update to vaadin24              | dev |      | https://github.com/bisq-network/bisq2-web-ui/pull/10 and https://github.com/bisq-network/bisq2-web-ui/pull/11                                                   |  |
| Total                           |  dev  | 3000 |                                                  |  |

Note: Alle commits are related to the bisq2-web-ui project. This constitutes 'Milestone Update' from the [Milestone plan](https://github.com/bisq-network/bisq2/discussions/1312). I estimated $6500 USD for these tasks, but it turned out to be much less work than anticipated. Upgrading to major version did include quite some research and trial.

**Comment by salokiam** [comment]
I guess I missed deadline for cycle 54, so I will resubmit for cycle 55, when its time for submission.

**Comment by MwithM** [comment]
It's better to leave this as not submitted with the original title and open a new one For Cycle 55. There you could copy this post, but update the  [rates](https://github.com/bisq-network/compensation/issues/1459) for that Cycle.
