### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by flix1** [bisq-network/compensation#146]
## Summary

 - BSQ requested: 500
 - BSQ address: B18pxrZRFJ7Q1PsND9xqayk1uQbtZiH39MC

## Contributions delivered

 - Hosting Weekly Growth Calls:
https://github.com/bisq-network/growth/issues/75

- Ambassador/interviews
Coindesk
https://www.coindesk.com/bitcoin-decentralized-exchange-dex-crypto-bisq-dao-monero/
BitcoinNews
https://bitcoinnews.com/exclusive-interview-with-the-founder-of-bisq-a-decentralized-crypto-exchange/
Reddit 100+ posts 
https://www.reddit.com/r/Bitcoin/comments/9glgfq/bisq_the_decentralized_exchange/
https://www.reddit.com/r/Bitcoin/comments/9qxx3e/exclusive_interview_with_the_founder_of_bisq_dex/

## Roles performed

 - Bitcointalk moderator:
bisq-network/roles#37

**Comment by ripcurlx** [comment]
@flix1 Just to be sure: Did you use a new Bisq address by intent? Before you used always `B1Pdq17bL5GiitCsNybi3Fc3V8qa7btYnPe`

**Comment by flix1** [comment]
@ripcurlx actually I wanted to ask about that... _B1Pdq17bL5GiitCsNybi3Fc3V8qa7btYnPe_ was my previous BSQ address. However if I hit Ctr+D now and go to the DAO section I see this new address _B18pxrZRFJ7Q1PsND9xqayk1uQbtZiH39MC_. This happened since the update to v. 0.8.0. 

I'm hoping that my recovery seed will allow me to still have access to the old address... can you please confirm that?

![image](https://user-images.githubusercontent.com/4233784/47774599-c4af9000-dced-11e8-9096-24d25f35c7dd.png)

**Comment by ripcurlx** [comment]
@flix1 I think atm I could just change your old address to match the new one you have access to as long as we are not on Mainnet. @ManfredKarrer Or do I miss something?

**Comment by flix1** [comment]
Thanks!

**Comment by ManfredKarrer** [comment]
The current address is not important and many have lost their old wallet. So i will request before mainnet anyway an new address from all... so no its just an ID.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
