### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/compensation#147]
## Summary

 - BSQ requested: <s>390</s> 1650 BSQ (updated requested amount as per comments)
 - BSQ address: B1N7BFqBX2MUmbZ4KGNKujooPaWBxTyVx6H

## Contributions delivered

This is my first official compensation request and I am uncertain on the requested amounts. Any feedback/suggestions would be appreciated.

- Provided updated content for the wiki page describing how to use regtest (see https://github.com/bisq-network/bisq/issues/1833). The wiki has been updated with this content: https://github.com/bisq-network/bisq/wiki/4.2.1.-How-to-use-Bisq-with-regtest-(advanced). This content has a relatively small audience as it is intended for developers and technical users only for the purpose of testing Bisq, but should hopefully help new developers/testers get up to speed quicker with less confusion.
[`100 BSQ`]

- CI builds were failing for several days as a result of Oracle JDK10 no longer available for download as it is now end of life, so switched to use OpenJDK10 (https://github.com/bisq-network/bisq/pull/1794). I consider this is a relatively high value added contribution since it was preventing any pull requests from running CI tests.
[`500 BSQ`]

- Updated the unix install script (https://github.com/bisq-network/bisq/pull/1817). I am not sure the significance of this script or how widely it is used, but it has been updated to work with OpenJDK10. Therefore I am considering it a relatively low value added contribution.
[`100 BSQ`]

- Fixed the last request timestamp in price feed service (https://github.com/bisq-network/bisq/pull/1730). Just a minor bug fix with low severity so a relatively low value added contribution.
[`50 BSQ`]

- Show cancel button in wallet password prompt when opening the application (https://github.com/bisq-network/bisq/pull/1765). This seems like a common use case and desired feature for a user to be able to cancel/close the application at the password prompt so may be considered a decent value-added contribution.
[`200 BSQ`]

- Fix text being truncated at certain display scaling levels in Windows 10 (https://github.com/bisq-network/bisq/pull/1767). Since display scaling is commonly enabled by default in Windows 10 laptops, this is likely to affect a decent share of the user base, and since it has the potential for the user to not see the entire message in a popup which may contain critical information, I am considering it a decent value-added contribution.
[`250 BSQ`]

- Fix arbitrator language selection fields (https://github.com/bisq-network/bisq/pull/1771). Just a minor bug fix when using arrow keys to make a selection, so a relatively low value added contribution.
[`50 BSQ`]

- Fix preferences view combobox selection (https://github.com/bisq-network/bisq/pull/1774). Just a minor bug fix when using arrow keys to make a selection, so a relatively low value added contribution.
[`50 BSQ`]

- Implemented a fix that will properly wait for the offer availability check to complete before showing the fund trade options (https://github.com/bisq-network/bisq/pull/1775). When taking an offer that does not specify an amount range, it was not waiting until the offer had been confirmed to be available before showing the fund trade options. This could potentially lead to a user funding his wallet if the offer is no longer available (before the offer availability check is successfully completed). As a result, I consider this a relatively high value added contribution.
[`350 BSQ`]

## Contributions in progress

- Cleanup the gradle config (https://github.com/bisq-network/bisq/pull/1808)

- Identify/resolve warnings encountered in gradle build (https://github.com/bisq-network/bisq/issues/1815)

- Switch to Java 11
https://github.com/bisq-network/bisq/issues/1787
https://github.com/bisq-network/bisq/pull/1810

**Comment by ripcurlx** [comment]
@devinbileck I personally think that the value added is higher than the amount requested compared to other contributions. Feel free to update it, leave a comment below and I'll update it in the voting spreadsheet.

**Comment by devinbileck** [comment]
Thanks @ripcurlx. I will browse past compensation requests and try to adjust accordingly.

**Comment by ManfredKarrer** [comment]
Yes I agree with @ripcurlx that your contributions have added more value as the 390 BSQ. Feel free to update! Your contributions have been all high quality with basically no required help from other devs.

**Comment by devinbileck** [comment]
@ripcurlx @ManfredKarrer I have updated my requested amount. Please take a look and let me know if that looks more reasonable to you.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
