### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#148]
## Summary

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested:`3805`
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

I'll again delay the compensation for the java 10 port which is also already merged into master until the 0.9.0 release, as it is still in progress and might cause additional efforts during release phase.

**Reviews of PRs**
I monitor PR reviews separately from the responsibilities of the Bisq Desktop Maintainer role.

_Reviewed PRs:_
- https://github.com/bisq-network/bisq/pull/1819
- https://github.com/bisq-network/bisq/pull/1822
- https://github.com/bisq-network/bisq/pull/1807
- https://github.com/bisq-network/bisq/pull/1795
- https://github.com/bisq-network/bisq/pull/1794
- https://github.com/bisq-network/bisq/pull/1775
- https://github.com/bisq-network/bisq/pull/1777

**BSQ amount requested:** `900`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I'm currently working on the redesign of the Bisq client which was merged a couple of days ago into the [release branch for 0.9.0](https://github.com/bisq-network/bisq/tree/release-candidate-0.9.0)

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

To make it more transparent and give people an idea how much effort which role means, I'll try to split up the overall number for each role.

- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63#issuecomment-434226553 `(960 BSQ)`
- Growth: https://github.com/bisq-network/roles/issues/42#issuecomment-434231591 `(860 BSQ)`
- Analytics: https://github.com/bisq-network/roles/issues/40#issuecomment-434232105 `(480 BSQ)`
- YouTube Admin:https://github.com/bisq-network/roles/issues/56#issuecomment-434236453 `(25 BSQ)`
- Bitcoin Fullnode Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-434251546 `(50 BSQ)`
- Transifex Admin: https://github.com/bisq-network/roles/issues/20#issuecomment-434241268 `(25 BSQ)`
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31#issuecomment-434241767 `(480 BSQ)`
- Bisq Design Maintainer: https://github.com/bisq-network/roles/issues/75#issuecomment-434241934 `(25 BSQ)`

**BSQ amount requested for all these roles (see detailed amount for each role): 2905**

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- Bisq Events Maintainer: https://github.com/bisq-network/roles/issues/65

## Notes to self
<details>

My PR reviews this month were created by reviewing the results of this GitHub Issues search query: 
[is:pr reviewed-by:ripcurlx updated:2018-10-01..2018-10-31 sort:updated-desc](https://github.com/bisq-network/bisq-desktop/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Aripcurlx+updated%3A2018-10-01..2018-10-31+sort%3Aupdated-desc+)

**Comment by ManfredKarrer** [comment]
Feels a bit too low from my point of view...

**Comment by ripcurlx** [comment]
@ManfredKarrer Just in general or for a certain role?

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
