### ISSUE TITLE
For October 2018 

### ISSUE THREAD

**Issue by joachimneumann** [bisq-network/compensation#150]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 200
 - BSQ address: B1HjazHawa5LD3j8o4gStJYyZFSnZqx8R7H

## Contributions delivered

- Bugfixes Android App:
   Back Button closes App (version 1.0.1 -> 1.0.2)
   Correct order of notifications  (version 1.0.0 -> 1.0.1)
   Table returns to previous scroll position
   update of Kotlin / gradle
   commits: https://github.com/joachimneumann/bisqremote_Android/commits/master

## Contributions in progress
- The update for the new design (Logo and colors) is prepared, but not yet launched. I will request compensation for this when it is launched

## Roles performed

- helping with the Apps in slack / bisq-mobile and giving feedback on bugs

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
