### ISSUE TITLE
For October 2018 and before

### ISSUE THREAD

**Issue by cypherspace86** [bisq-network/compensation#151]
## Summary

Primary coding DAO Parameter validations and tests for these. Secondary promoting Bisq at misc conferences during the year.

 - BSQ requested: 500
    Divided as:
         -3 x Helping promoting Bisq at conferences: 150
         -Participation in review and brainstorming: 50
         -Java code: 300

 - BSQ address: B1L9b6PkGMPBmvscxkPdLkVhN5HZUEkknzj

## Contributions delivered

I have been promoting Bisq during networking sessions at various events over the last year. (34c3, BH18, HCPP18)

Minor participations in review and brainstorming processes over the last year.

## Contributions in progress 

 I'm primarely seeking compensation for my work on [1769](https://github.com/bisq-network/bisq/issues/1769) which was taken of the planning board due to new refactoring plans for the DAO params. I did not know about these plans and could not hinder working for no reason.
So PR [1824](https://github.com/bisq-network/bisq/pull/1824) solves issue [1769](https://github.com/bisq-network/bisq/issues/1769), but won't get released.
I understand that it may conflict with the principles of [proposal 19](https://github.com/bisq-network/proposals/issues/19), but I was encouraged, by @ManfredKarrer to seek compensation anyways due to the situation. 

## Roles performed

- Developer
- Promoter
- Reviewer

**Comment by ManfredKarrer** [comment]
I can confirm that it was my fault that he worked on a bounty task where later I did bigger changes so that his PR did not made sense to get merged anymore.

**Comment by ManfredKarrer** [comment]
@ cypherspace86 Could you split up the 650 BSQ which part is for the code task and the what for the promotion?

**Comment by cypherspace86** [comment]
Well I basically added the promotion part for free to at least have some delivered content in the compensation request now that the code is not released.
So it would be Java code: 650, promotion: 0 bsq

**Comment by cypherspace86** [comment]
Thanks @ManfredKarrer, I still figuring out the right way to write feasible compensation requests.
I have lowered the requested amount a bit and adjusted the proportions.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
