### ISSUE TITLE
For cycle 57

### ISSUE THREAD

**Issue by brokenmoney** [bisq-network/compensation#1513]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`85`** 
- USD requested: 180 
- BSQ rate: 2.12 USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| bisq 2 moderator | support | 180 | supporting new users |  |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by leo816** [comment]
My [Team Lead](https://bisq.wiki/Compensation#Team_Lead) review is complete and I approve this request. Please submit your DAO proposal and paste the transaction ID here as a comment when complete, thanks.

**Comment by brokenmoney** [comment]
82f58400c6c2e4e65d84ed0257d75099973a30c356dfdd58e6c14ae728e708c6

**Comment by MwithM** [comment]
Closed as accepted.
