### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by KanoczTomas** [bisq-network/compensation#152]
## Summary

 - BSQ requested: 313
 - BSQ address: B17TT6PsriwSLoKDnybE4LoDazkffQxtx3G

## Contributions delivered

 - Working on closing delayed reimbursement issues ([support repo](https://github.com/bisq-network/support)):
[#102](https://github.com/bisq-network/support/issues/102) [#103](https://github.com/bisq-network/support/issues/103) [#104](https://github.com/bisq-network/support/issues/104) [#105](https://github.com/bisq-network/support/issues/105) [#106](https://github.com/bisq-network/support/issues/106) [#107](https://github.com/bisq-network/support/issues/107) [#108](https://github.com/bisq-network/support/issues/108) [#109](https://github.com/bisq-network/support/issues/109) [#110](https://github.com/bisq-network/support/issues/110) [#111](https://github.com/bisq-network/support/issues/111) [#113](https://github.com/bisq-network/support/issues/113) [#114](https://github.com/bisq-network/support/issues/114) [#115](https://github.com/bisq-network/support/issues/115) [#116](https://github.com/bisq-network/support/issues/116) [#118](https://github.com/bisq-network/support/issues/118) [#119](https://github.com/bisq-network/support/issues/119) [#120](https://github.com/bisq-network/support/issues/120) [#121](https://github.com/bisq-network/support/issues/121) [#122](https://github.com/bisq-network/support/issues/122) [#123](https://github.com/bisq-network/support/issues/123) [#124](https://github.com/bisq-network/support/issues/124) [#125](https://github.com/bisq-network/support/issues/125) [#126](https://github.com/bisq-network/support/issues/126) [#127](https://github.com/bisq-network/support/issues/127) [#128](https://github.com/bisq-network/support/issues/128) [#129](https://github.com/bisq-network/support/issues/129) [#130](https://github.com/bisq-network/support/issues/130) [#131](https://github.com/bisq-network/support/issues/131) [#132](https://github.com/bisq-network/support/issues/132) [#133](https://github.com/bisq-network/support/issues/133) [#134](https://github.com/bisq-network/support/issues/134) [#135](https://github.com/bisq-network/support/issues/135) [#136](https://github.com/bisq-network/support/issues/136) [#137](https://github.com/bisq-network/support/issues/137) [#138](https://github.com/bisq-network/support/issues/138) [#139](https://github.com/bisq-network/support/issues/139) [#140](https://github.com/bisq-network/support/issues/140) [#142](https://github.com/bisq-network/support/issues/142) [#143](https://github.com/bisq-network/support/issues/143) [#144](https://github.com/bisq-network/support/issues/144) [#145](https://github.com/bisq-network/support/issues/145) [#82](https://github.com/bisq-network/support/issues/82) - all belong to [#101](https://github.com/bisq-network/support/issues/101).

- Documenting above process so Bisq can stay more decentralized and any new member could do refunds monthly as planned. PR [#146](https://github.com/bisq-network/support/pull/146) has been merget to the support repo. A brief [readme](https://github.com/bisq-network/support/blob/master/README.md) pointing to the doc was added to the [support repo](https://github.com/bisq-network/support) and the documentation can be viewed [here](https://github.com/bisq-network/support/blob/master/reimbursement-process.md).

- Took a role to update batch reimbursement as soon as possible so Bisq has no more issues with long backlogs as the last one. Already worked on [#148](https://github.com/bisq-network/support/issues/148) [#150](https://github.com/bisq-network/support/issues/150) [#151](https://github.com/bisq-network/support/issues/151) [#152](https://github.com/bisq-network/support/issues/152). These issue are staged and processed, will be closed automatically after batch reimbursement happens. - all belong to [#147](https://github.com/bisq-network/support/issues/147).

## Roles performed

I have a gut feeling this could be a new role, but not sure. Asking for guidance on this topic. I spoke to @cbeams that I will take the role of a person who monitors the support repo and processes reimbursement claims with a target of reimbursement batches once per month in mind.

**Comment by ManfredKarrer** [comment]
Great thanks! I leave details how to proceed to @cbeams

**Comment by cbeams** [comment]
> I have a gut feeling this could be a new role, but not sure.

Thanks, @KanoczTomas, we actually have an existing 'Support Maintainer' role that covers this well. See my comments at https://github.com/bisq-network/roles/issues/76#issuecomment-434836367 regarding handover to you.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
