### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#153]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**
## Roles performed
- Support Staff | https://github.com/bisq-network/roles/issues/64#issuecomment-434349640 | 2700 BSQ
- Forum operator | https://github.com/bisq-network/roles/issues/19#issuecomment-434358721 | 250 BSQ
- Reddit moderator | https://github.com/bisq-network/roles/issues/25#issuecomment-434344739 | 50 BSQ

**Comment by cbeams** [comment]
@alexej996, thanks for following the reporting formatting instructions I originally laid out at https://docs.bisq.network/roles.html#reporting. In practice, though, most of us (including myself) have been using a different, and I think more natural / readable format. I've updated the doc accordingly, please have a look at https://github.com/bisq-network/bisq-docs/pull/91 to see the changes.

**Comment by alexej996** [comment]
I will have a look, thanks :)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
