### ISSUE TITLE
New to Bitcoin 

### ISSUE THREAD

**Issue by Ih8udomuch** [bisq-network/compensation#1545]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[BSQ amount]`** 
- USD requested: [USD amount] 
- BSQ rate: [rate] USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| your | first | item | goes | here |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by MwithM** [comment]
Closed as invalid.

Please read the compensation guidelines at https://bisq.wiki/Compensation and ask me anything you might need at bisq.chat
