### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#155]
## Basic information

 - BSQ amount requested: **16275**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

### Development work:
Much of my work was focussed on the DAO but also many other areas as well as reviews and merging PRs. As we are close to the testnet release and as it is hard to separate DAO work with non DAO work I will request in total my dev efforts.
Requested BSQ: 12000 BSQ

### Interviews
I did several interviews that months:
Requested BSQ: 1000 BSQ

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1
- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8 `(100)`
- Seed node maintainer: https://github.com/bisq-network/roles/issues/6 `(25)`
- Statsnode Maintainer: https://github.com/bisq-network/roles/issues/7 `(25)`
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14 `(25)`
- Events Maintainer: https://github.com/bisq-network/roles/issues/65 `(25)`
- Markets Website+API Maintainer: https://github.com/bisq-network/roles/issues/9 `(25)`

Sum: 225 BSQ

Operator roles:
- Markets Website+API Operator: https://github.com/bisq-network/roles/issues/9 `(50)`
- Seed node operator: https://github.com/bisq-network/roles/issues/15 `(6 nodes: 300)`
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10 `(50)`
- Price node Operator `(2 nodes: 100)`
- Relay node (mobile notifications) Operator `(50)`
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67 `(2 nodes: 100)`
- BSQ explorer node `(50)`
- Testnet DAO seed node `(50)`

Sum: 750 BSQ

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

Major roles:
- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63 `(2000)`
- GitHub Admin: https://github.com/bisq-network/roles/issues/16 `(200)`
- Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12 `(50)`
- Slack Admin: https://github.com/bisq-network/roles/issues/23 `(50)`

Sum: 2300 BSQ

Minor roles:
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Freenode Admin: https://github.com/bisq-network/roles/issues/22
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31
- Transifex Admin: https://github.com/bisq-network/roles/issues/20
- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Support Staff: https://github.com/bisq-network/roles/issues/64

Requested for all the listed roles: 3275 BSQ

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
