### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by freimair** [bisq-network/compensation#156]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 1000
 - BSQ address: B1JJUQWUHEoUwng4uGGWsT4hnTMc6dXtj9K

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- I have provided consulting on the topic of cryptography in the past months
- I took over Arch AUR package maintenance
  - https://aur.archlinux.org/packages/bisq/
  - https://aur.archlinux.org/packages/bisq-bin/
  - https://aur.archlinux.org/packages/bisq-git/

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

https://github.com/bisq-network/bisq/issues/1761
https://github.com/bisq-network/bisq/issues/1241
https://github.com/bisq-network/bisq/issues/965
https://github.com/bisq-network/bisq/issues/829
https://github.com/bisq-network/bisq/issues/413

furthermore, I am running final test on an updated netlayer https://github.com/JesusMcCloud/netlayer

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by ManfredKarrer** [comment]
I just added a role for AUR maintainer.
https://github.com/bisq-network/roles/issues/78

@freimair Is the AUR updated? In the comments it seems that there are issues...

**Comment by cbeams** [comment]
@freimair, regarding the new role, please familiarize yourself with https://docs.bisq.network/roles.html.

**Comment by cbeams** [comment]
It's not obvious to me that the contributions delivered are worth the requested 1000 BSQ. I'm not suggesting they aren't, just that there wasn't enough context in the description or information available via the links provided for me to judge either way.

**Comment by ripcurlx** [comment]
Same here - I had to delegate the vote (I guess to @ManfredKarrer who is aware of all the consulting taken place), because of the lack of information.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.

**Comment by freimair** [comment]
> @freimair Is the AUR updated? In the comments it seems that there are issues...

yes it seems like that, I , however, have been able to build any of the three versions without issues. I will of course have an eye out...
