### ISSUE TITLE
For Cycle 61

### ISSUE THREAD

**Issue by helixx87** [bisq-network/compensation#1587]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`333.33`** 
- USD requested: 670
- BSQ rate: 2.01 USD per BSQ 
- Previous compensation request (if applicable): None - it's my first compensation request

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| Refactor "remove radio" logic in JFXRadioButtonSkinBisqStyle | dev | 50 | https://github.com/bisq-network/bisq/pull/6708
| API: gettransactions method | dev | 300 | https://github.com/bisq-network/bisq/pull/6680
| Support "all" attribute in getoffers API method | dev | 200 | https://github.com/bisq-network/bisq/pull/6680
| Fix close button behaviour on successful offer creation popup | dev | 20 | https://github.com/bisq-network/bisq/pull/6641
| Tests for OfferUtil | dev | 100 | https://github.com/bisq-network/bisq/pull/6608

**Comment by MwithM** [comment]
You did not send the compensation request to the DAO.
You can send it for the next cycle, opening a new issue called "For cycle 62" and updating the BSQ rate for that new cycle.

**Comment by helixx87** [comment]
Thanks for the info, I thought I need to wait for approval in the github and then send request to the DAO.

**Comment by MwithM** [comment]
You are technically correct, but lately on dev team there is no explicit approval.
