### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#160]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `2057`
 - BSQ address: B1HGxmhfWJwwvvDgTRrWpZ1QsEZn7rMEaVE

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

None.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

None.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

### Substantive reports

 - Arbitrator: https://github.com/bisq-network/roles/issues/13#issuecomment-434772915 `(NA)`
 - Bisq Docs Maintainer: https://github.com/bisq-network/roles/issues/29#issuecomment-434776274 `(25 BSQ)`
 - Bisq Pricenode Maintainer: https://github.com/bisq-network/roles/issues/5#issuecomment-434795161 `(25 BSQ)`
 - Bisq Pricenode Operator: https://github.com/bisq-network/roles/issues/14#issuecomment-434795656 `(32 BSQ)`
 - Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12#issuecomment-434796853 `(25 BSQ)`
 - Founder: https://github.com/bisq-network/roles/issues/1#issuecomment-434865124 `(NA)`
 - Proposals Maintainer: https://github.com/bisq-network/roles/issues/30#issuecomment-434800266 `(25 BSQ)`
 - Slack Admin: https://github.com/bisq-network/roles/issues/23#issuecomment-434845744 `(25 BSQ)`
 - Support Maintainer: https://github.com/bisq-network/roles/issues/76#issuecomment-434836367 `(25 BSQ)`
 - Twitter Admin:  https://github.com/bisq-network/roles/issues/21#issuecomment-434851087 `(1800 BSQ)`

### Nothing to report

 - DNS Admin: https://github.com/bisq-network/roles/issues/18#issuecomment-434797619 `(25 BSQ)`
 - GitHub Admin: https://github.com/bisq-network/roles/issues/16#issuecomment-434798855 `(25 BSQ)`
 - Roles Maintainer: https://github.com/bisq-network/roles/issues/28#issuecomment-434837713 `(25 BSQ)`

## Notes to self
<details>

My contributions this month were created by reviewing the results of this GitHub Issues search query: [org:bisq-network involves:cbeams updated:2018-10-01..2018-10-31 sort:updated-desc](https://github.com/issues?utf8=%E2%9C%93&q=org%3Abisq-network+involves%3Acbeams+updated%3A2018-10-01..2018-10-31+sort%3Aupdated-desc+)

The list of roles above was generated by the following `ghi` command run within my clone of the bisq-network/roles repository:

```
ghi list --assignee=cbeams --no-labels \
| grep -v '^#' \
| cut -b7- | rev | cut -d' ' -f3- | rev | sort \
| xargs -Irole echo " - role: "
```

Also useful to opening all of these issues is the following command:
```
for role in $(\
ghi list --mine \
  | grep -v '^#' \
  | cut -d'[' -f1 \
  | sed 's/^ *//' | sed 's/  /:/' \
  | awk -F':' '{print $2 ":" $1}' \
  | sort | cut -d':' -f2\
); do ghi show --web $role; done;
```
</details>

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
