### ISSUE TITLE
For January-October 2018

### ISSUE THREAD

**Issue by eyalron33** [bisq-network/compensation#164]
## Summary
This compensation request regards a variety of contributions made to Bisq during the first 10 months of 2018.

- BSQ amount requested: 4000 (2000 for January-October + 2000 for November 2018)
- BSQ address: B1PU7DoYDHWi2impz86Fvu3ZgsREaBnGJBW

## Contributions delivered

20 hours of contribution to during January-October 2018 to:
- the design, analysis and auditing of the Bisq DAO and systems which are relevant to that. ,
- Bisq weekly call about the BISQ DAO,
- involvement in the design of a few other systems, such of the trading protocol, Bisq (potential) stable coin, off chain trading protocol etc.

All of that was done in collaboration with other Bisq members, for example, Manfred Karrer.

**Addition, 30th November 2018**: 20 hours of working on [Trading protocol v2 without arbitrators](https://github.com/bisq-network/proposals/issues/52). The work is in collaboration with Craig Sailor and Manfred Karrer, the github fork [is here](https://github.com/craigsailor/bisq).

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
