### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by freimair** [bisq-network/compensation#166]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 9600
 - BSQ address: B1JJUQWUHEoUwng4uGGWsT4hnTMc6dXtj9K

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

#### all the things Tor.

I have been busy with fixing and enhancing the Tor base of Bisq.
- A long requested feature has been a somewhat editable torrc file (bisq-network/bisq#965, bisq-network/bisq#829 and thus, bisq-network/bisq#413, bisq-network/bisq#483). Addressed by bisq-network/bisq1893 and later enhanced by bisq-network/bisq#1903
- Unfortunately, as I did my work on Netlayer, a bug in Netlayer showed up. Worked on in bisq-network/bisq#1914. The majority of work had to be done in [Netlayer](https://github.com/JesusMcCloud/netlayer) as a new [release](https://github.com/JesusMcCloud/netlayer/releases/tag/0.4.7.1)  was due. The fix has been introduced to Bisq in bisq-network/bisq#1917.
- The [Tor Browser Bundle](https://www.torproject.org/) got updated and with it, the tor binary version. Again, a new [Netlayer release](https://github.com/JesusMcCloud/netlayer/releases/tag/0.4.7.1.1) was due which was introduced to Bisq in bisq-network/bisq#1928.
- Another long requested feature has been the option to use a Tor service provided by the system (bisq-network/bisq#1761, bisq-network/bisq#811, bisq-network/bisq#492, bisq-network/bisq#1887). As Netlayer had only marginal support for using "external" Tor (https://github.com/JesusMcCloud/netlayer/issues/7#issuecomment-369331181), fresh Netlayer releases ([0.6](https://github.com/JesusMcCloud/netlayer/releases/tag/0.6), [0.6.1](https://github.com/JesusMcCloud/netlayer/releases/tag/0.6.1)) has been due. However, a good portion of the implementation work had to be done in the jtorctl dependency which made fresh [jtorctl releases ([v1](https://github.com/JesusMcCloud/jtorctl/releases/tag/1), [v1.1](https://github.com/JesusMcCloud/jtorctl/releases/tag/1)) due as well. The feature set has been integrated into Bisq in bisq-network/bisq#1935, bisq-network/bisq#1966, and bisq-network/bisq#2009.
- Aside from direct features for Bisq, the tor-binary dependency has been worked on to clean and ease up future use in applications (such as Bisq). Hence, an fresh tor-binary release has been created and integrated with Netlayer in its [0.6.1 release](https://github.com/JesusMcCloud/netlayer/releases/tag/0.6.1).

(note that due to jitpack/jitpack.io#3572, the releases Netlayer 0.6.1 and jtorctl 1.1 are not being build correctly and thus, things break at the moment (bisq-network/bisq#2009, bisq-network/bisq#2010). I am working to get jitpack up to speed. However, I decided to this very compensation request as is, as it does fit well and the work itself is already done.)

#### other
- Last but not least, while fixing the AUR bisq package, I stumbled over a minor hickup fixed in bisq-network/bisq#1979.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- battle jitpack
- The requested feature list for Bisq's Tor base only leaves a few issues open, where I am going to focus on bisq-network/bisq#731.
- Tor network issues (such as bisq-network/bisq#791, bisq-network/bisq#1172, bisq-network/bisq#1241, bisq-network/bisq#1299) want to be taken down which I keep in the back of my head.
- A fresh monitoring tool (bisq-network/bisq#1361) might just be the right tool for tackling the Tor network issues. I am going to work on the monitoring tool after completing the Tor feature request stated above.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- Arch Linux AUR maintainer: https://github.com/bisq-network/roles/issues/78#issuecomment-442436032 (100 BSQ)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
