### ISSUE TITLE
For Cycle 65

### ISSUE THREAD

**Issue by makhni-dev** [bisq-network/compensation#1668]
## Summary

- **BSQ requested**: **`352.94`** 
- USD requested: 600 
- BSQ rate: 1.7 USD per BSQ 

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | ---: | --- | --- |
| Create Bisq Easy trade details pop up | dev* | 600 | https://github.com/bisq-network/bisq2/pull/2957 |  |

**Comment by makhni-dev** [comment]
txid: df21af3a427f6205937046af5efc120a38501cae0b631cba9373a48c7087a29b

**Comment by HenrikJannsen** [comment]
I consider that requested amount as too high for the delivered work, which required lot of back and forth changes in the review and another follow-up PR by another dev. Sorry that I did not review the request before the voting. Feel free to make another request in next voting cycle with an adjusted amount in case it would get rejected.

**Comment by MwithM** [comment]
Closed as rejected.
You can resubmit this at next cycle, using new BSQ rates.

**Comment by HenrikJannsen** [comment]
If you re-submit please consider to adjust the requested amount, as this amount I cannot support. My vote got invalid as I missed the vote reveal phase, but I would have down-voted the request and will do again in the next request if not adjusted accordingly.
