### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by joachimneumann** [bisq-network/compensation#168]
## Summary
 - BSQ requested: 250
 - BSQ address: B1HjazHawa5LD3j8o4gStJYyZFSnZqx8R7H

## Contributions delivered
Detailed [instruction](https://github.com/joachimneumann/bisqremote) in the README which successfully enabled slack user kopite77 to install the Bisq Mobile App and the bisqremote java app locally and to send notifications using his own firebase certificates. Based on this, he wants to help debugging the mobile app.

## Contributions in progress
I am [learning](https://www.coursera.org/learn/crypto) about cryptography in order to improve the security of the Bisq notifications. Also, the new design is ready to be uploaded to the App stores.

## Roles performed
Managing bisq-mobile on slack

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
