### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by chirhonul** [bisq-network/compensation#169]
## Summary

 - BSQ requested: 1850
 - BSQ address: B197ZcX369usMDHCF6iD2h1CMbntkovDqoe

## Contributions delivered

I am requesting 1400 BSQ for the operational and technical work setting up bisq.space, and another 50 BSQ for the domain name and server hosting costs. There's also a request for 400 BSQ for work on the monorepo merge some time back.

### Creating bisq.space as replacement for bisq.slack.com

See comments starting at https://github.com/bisq-network/proposals/issues/54#issuecomment-440560170 for progress so far.

Draft operational notes are at https://github.com/chirhonul/bisq.space and the service is usable at [bisq.space](https://bisq.space) currently, although I would be happy in requesting compensation for the work at a later time if that would be preferable.

I'm requesting 1400 BSQ for the technical work setting up bisq.space, documenting and planning operational aspects, looking into operational issues etc.

### Operational costs for bisq.space

See above. I'm requesting 50 BSQ for paying for the domain name and the server hosting costs.

### Assist with monorepo merge

I'm requesting compensation of 400 BSQ for the historical work of assisting with the monorepo merge. This was merged to `master` but not included in the most recent v0.8.1 release as per [this comment](https://github.com/bisq-network/proposals/issues/38#issuecomment-425028818) saying that this is acceptable. Let me know if I misunderstood something.

My commits were included in this PR:

* https://github.com/bisq-network/bisq/pull/1650

## Roles performed

None so far.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
