### ISSUE TITLE
 For November 2017 

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#17]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 6000
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### Development work

- Test release v0.6.0 https://docs.google.com/spreadsheets/d/18n6wV0g5MPTs9Xni0cFji8U34xV3O1IRPDEYZrluBuU/edit#gid=1386834576
- Code review of Bisq wallet and bitcoinj regarding Bip 44 implementation and bloom filter usage

It's a bit hard to evaluate how much to ask for the review parts. There is a lot of time spent on review but not much to show for it apart from a silent ack that it looks ok and a minor UI bug that I didn't even fix properly https://github.com/bisq-network/exchange/pull/1025. I still think it has value to have more eyes on the code, but I ask @ManfredKarrer to opine if it looks outrageous.

**Comment by ManfredKarrer** [comment]
@sqrrm Looks good for me. I have seen in past reviews that you actually find bugs ;-) and provide valuable improvements. If you have not found anything serious with BIP 44 I hope there are no serious issues ;-).
Also the investigation of bloomfilters and the longest chain attack problem (B2X) is hard to estimate but I trust your time based estimation.
