### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#170]
## Summary

 - BSQ requested: 150
 - BSQ address: B1PFD3uscJqFQfLNAS6bWQtr1PUahrWNvC7

### Spreading the word about Bisq (100BSQ)

* Went to Zurich Bitcoin meetups (Decentralized Identity, Hardware Wallets) and promoted Bisq.

### Pull requests (50BSQ)

 - https://github.com/bisq-network/bisq/pull/1829: Improve grammar of background info

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
