### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by aejontargaryen** [bisq-network/compensation#171]
## Summary

 - BSQ requested: 30
 - BSQ address: B1AweC1bYPY6SzkWTanwX2JWpBhVRxL72he

## Contributions delivered
Monero account popup updated. https://github.com/bisq-network/bisq/pull/1902  |  30

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
