### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#173]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 35190
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

This is a request for compensation work on the DAO for April - November. I have worked with Manfred on getting the DAO to a ready state. In total I estimate I have contributed about 2.5 months worth of work to the project during this period. As the details are now a bit muddled due to time passing and a lot of the work is in the form of design and discussions I will try to describe the process.

### Planning

Most of the work has been in design and conceptual discussion. Although the general concept of the DAO was quite clear from the beginning the details were lacking. At first the plan was to go live with a basic
version without many of the features now implemented but as we went on it became obvious that it would add extra work and possibly several hard forks or other issues with the DAO to not have a more or less complete technical understanding of where we were going. Each of the concepts, such as phases, compensation requests, voting, bonding and confiscation has been discussed as it was clear they were needed but not how they would affect the handling of BSQ.

Another big part of the discussions has been finding attack vectors, both from a social and technical point of view and verifying that the code is correct according to those measures.

### Code

I implemented the main parts of the bonding and confiscation and I've reviewed all the DAO code throughout the process, including continuous testing and feedback to Manfred.

For details see https://github.com/sqrrm as there is a muddled history with work done directly against Manfred's repo and the great repo reunification.

Amount requested: BSQ 35000

Footnote: I think this is a bad way to do compensation for longer running projects, as has been mentioned elsewhere. We need to find a way to handle bigger projects and get continuous feedback to the contributors.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Currently working on the DAO explorer.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bitcoin node maintainer - https://github.com/bisq-network/roles/issues/66#issuecomment-442941479 `(50)`
Bitcoin node operator - https://github.com/bisq-network/roles/issues/67#issuecomment-442941947 `(100)`
Tor relay operator - https://github.com/bisq-network/roles/issues/72#issuecomment-442942812 `(40)`

Total requested for roles, BSQ 190

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
