### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/compensation#174]
## Summary

 - BSQ requested: 1860
 - BSQ address: B1N7BFqBX2MUmbZ4KGNKujooPaWBxTyVx6H

## Contributions delivered

- Initiated work on cleaning up and reorganizing the gradle config (https://github.com/bisq-network/bisq/pull/1808) which was superseded by https://github.com/bisq-network/bisq/pull/1862
[`200 BSQ`]

- Identifying and resolving warnings encountered in gradle build
[`300 BSQ`]
    - Using our recently forked [gradle-witness](https://github.com/bisq-network/gradle-witness) repo, I updated the gradle build to ensure reproducible builds and generate an MD5 hash which can be verified against (https://github.com/bisq-network/gradle-witness/pull/1)
    - Added a new gradle-witness.jar based on above mentioned fork (https://github.com/bisq-network/bisq/pull/1901) in order to resolve deprecated method prior to moving to Gradle 5 (see https://github.com/bisq-network/bisq/issues/1897)
    - Updated to latest shadow plugin version 4.0.2 to resolve a deprecated method prior to moving to Gradle 5 (https://github.com/bisq-network/bisq/pull/1922)

- Fixed pricenode gradle build which was failing on Windows (https://github.com/bisq-network/bisq/pull/1890)
[`50 BSQ`]

- Added a gitattributes file to ensure line endings are normalized in all text files (https://github.com/bisq-network/bisq/pull/1927)
[`50 BSQ`]

- Limited initial window size on application launch for displays with a usable resolution smaller than the initial window size (https://github.com/bisq-network/bisq/pull/1945)
[`100 BSQ`]

- Resolved BisqHelpFormatterTest failure on Windows (https://github.com/bisq-network/bisq/pull/1963)
[`50 BSQ`]

- Removed *nix scripts on Windows (https://github.com/bisq-network/bisq/pull/1964)
[`10 BSQ`]

- Implemented a more organized and structured approach to release testing
[`1000 BSQ`]
    - Setup [TestQuality](https://bisq.testquality.com) as our new test management tool and ported test cases from the old [spreadsheet](https://docs.google.com/spreadsheets/d/18n6wV0g5MPTs9Xni0cFji8U34xV3O1IRPDEYZrluBuU/edit#gid=1386834576)
    - Added testing guide (https://github.com/bisq-network/bisq/pull/1987)

- Reviewed pull requests
[`100 BSQ`]
    - https://github.com/bisq-network/bisq/pull/1924
    - https://github.com/bisq-network/bisq/pull/1852

## Contributions in progress

- Testing v0.9.0 release

- Adding more test cases in TestQuality to increase test coverage

- Identifying and resolving warnings encountered in gradle build. There are still a few warnings that need to be resolved before updating to gradle 5.

- Switch to Java 11
https://github.com/bisq-network/bisq/issues/1787
https://github.com/bisq-network/bisq/pull/1810

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
