### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#176]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**
## Roles performed
- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-443028079 (2700 BSQ)
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-443037293 (250 BSQ)
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-443020800 (50 BSQ)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
