### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#178]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 100
 - BSQ address: B1FGfKZQrpbLN9UNMogyJAVTR5PJNRkGPXJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**Revise DAO Technical Specification doc**
Improved various parts of the doc to help newcomers interested in understanding the DAO at a deeper level. Edits focused on clarifying the message, not typos or aesthetics. See [this pull request](https://github.com/bisq-network/bisq-docs/pull/93#event-1989782540).

**BSQ amount requested:** `100`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Much of what I've been doing lately hasn't been very visible but will be released for feedback and merging in December. That work includes writings and other items to implement [this proposal](https://github.com/bisq-network/proposals/issues/56), implementing various items on the redesigned website, implementing the docs redesign, and migrating Slack to Rocket.

I expect to take on the roles of Rocket.chat admin in December and email list admin in January.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

N/A.

**Comment by ManfredKarrer** [comment]
Your requested amount seems very low to me even if most of your work has not been released.

**Comment by chirhonul** [comment]
I agree with @ManfredKarrer. It is clear that you are doing a huge amount of work and have many efforts underway, and that the value to the bisq community is much greater than the requested amount. I would also encourage increasing the amount you request significantly.

**Comment by m52go** [comment]
@ManfredKarrer @chirhonul I appreciate your feedback but I'm not sure how I can request more without anything to show for it at the moment. I fully expect to request compensation for the value I'm creating, just pushed forward a bit.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
