### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#179]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 5457
 - BSQ address: `B1HGxmhfWJwwvvDgTRrWpZ1QsEZn7rMEaVE`

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

 - Refactored Gradle build: bisq-network/bisq#1862
 - Redesigned CLI help output: bisq-network/bisq#1961
 - Reworked dev docs: bisq-network/bisq#1924
 - Introduced convenient start scripts for Bisq executables in root dir of main repo: bisq-network/bisq#1956
 - Delisted untraded assets: bisq-network/bisq#1861
 - Added CODEOWNERS file to help streamline PR review assignments: bisq-network/bisq#1860
 - Various smaller PRs
 - Reviewed a number of PRs

BSQ Requested: `5000`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

None.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

 - Arbitrator: https://github.com/bisq-network/roles/issues/13#issuecomment-443315583 `(NA)`
 - Bisq Docs Maintainer: https://github.com/bisq-network/roles/issues/29#issuecomment-443325840 `(25 BSQ)`
 - ~Bisq Pricenode Maintainer:~ https://github.com/bisq-network/roles/issues/5 (issue now closed)
 - Bisq Pricenode Operator: https://github.com/bisq-network/roles/issues/14#issuecomment-443332323 `(32 BSQ)`
 - Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12#issuecomment-443333865 `(25 BSQ)`
 - DNS Admin: https://github.com/bisq-network/roles/issues/18#issuecomment-443334231 `(25 BSQ)`
 - Founder: https://github.com/bisq-network/roles/issues/1#issuecomment-443346246 `(NA)`
 - GitHub Admin: https://github.com/bisq-network/roles/issues/16#issuecomment-443334945 `(25 BSQ)`
 - Proposals Maintainer: https://github.com/bisq-network/roles/issues/30#issuecomment-443335518 `(0 BSQ)`
 - Roles Maintainer: https://github.com/bisq-network/roles/issues/28#issuecomment-443337382 `(25 BSQ)`
 - Slack Admin: https://github.com/bisq-network/roles/issues/23#issuecomment-443338290 `(25 BSQ)`
 - Support Maintainer: https://github.com/bisq-network/roles/issues/76#issuecomment-443339094 `(25 BSQ)`
 - Twitter Admin: https://github.com/bisq-network/roles/issues/21#issuecomment-443343112 `(250 BSQ)`

## Notes to self
<details>

My contributions this month were created by reviewing the results of this GitHub Issues search query: [org:bisq-network involves:cbeams updated:2018-11-01..2018-11-30 sort:updated-desc](https://github.com/issues?page=5&q=org%3Abisq-network+involves%3Acbeams+updated%3A2018-11-01..2018-11-30+sort%3Aupdated-desc&utf8=%E2%9C%93)

The list of roles above was generated by the following `ghi` command run within my clone of the bisq-network/roles repository:

```
ghi list --assignee=cbeams --no-labels \
| grep -v '^#' \
| cut -b7- | rev | cut -d' ' -f3- | rev | sort \
| xargs -Irole echo " - role: "
```

Also useful to opening all of these issues is the following command:
```
for role in $(\
ghi list --mine \
  | grep -v '^#' \
  | cut -d'[' -f1 \
  | sed 's/^ *//' | sed 's/  /:/' \
  | awk -F':' '{print $2 ":" $1}' \
  | sort | cut -d':' -f2\
); do ghi show --web $role; done;
```
</details>

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/165#issuecomment-444496356.
