### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#184]
## Summary

- BSQ requested: 2500BSQ
- BSQ address: B1PFD3uscJqFQfLNAS6bWQtr1PUahrWNvC7

### Educational videos on Bisq DAO (2000BSQ)
- Created five videos for the Bisq DAO Basics series by interviewing Manfred Karrer:  
  - Bitcoin Transactions: https://www.youtube.com/watch?v=mOSYPrgLKWw
  - Colored Coins: https://www.youtube.com/watch?v=68_DU1c0Cac
  - BSQ Tokens - Technical: https://www.youtube.com/watch?v=GfD5XaR_oLs
  - BSQ Tokens - Economic: https://www.youtube.com/watch?v=hsAfja6uB8w
  - Compensation Requests and Voting: https://www.youtube.com/watch?v=OdoXsSqinQM
 - @m52go reviewed, edited and uploaded the videos on YouTube.

### Transifex Translations and Reviews (450BSQ)
- https://www.transifex.com/user/profile/arunasurya/: translated two strings of ~350 words each into Russian, and reviewed ~650 strings

### Pull Requests (50BSQ)
- https://github.com/bisq-network/bisq/pull/2138: correct minor grammatical mistakes in the User Agreement, Bisq Testnet

**Comment by ripcurlx** [comment]
> BSQ requested: 2500BSQ
No need to add the unit (BSQ) again. Without it is easier for me to copy&paste it over to the voting spreadsheet 😉

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
