### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by freimair** [bisq-network/compensation#185]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 14050
 - BSQ address: B1JJUQWUHEoUwng4uGGWsT4hnTMc6dXtj9K

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- Tor Stream isolation is available with https://github.com/bisq-network/bisq/pull/2081 (as requested by https://github.com/bisq-network/bisq/issues/731)
- The 0.9.0 release introduced some configuration issues where I assisted in finding (https://github.com/bisq-network/bisq/issues/2048#issuecomment-444149682) and fixing them (https://github.com/bisq-network/bisq/pull/2090)
- https://github.com/bisq-network/bisq/pull/2009: during work on the monitoring stuff a fresh release of Netlayer ([0.6.2](https://github.com/JesusMcCloud/netlayer/releases/tag/0.6.2)) was due, as there have been some hidden bugs
  - whenever only one single hidden service is active (in native tor mode), one cannot unpublish that very service
  - attempting to shut down tor within the ready-listener resulted in a deadlock (tackled by using ephemeral hidden services in native tor mode as well) (using ephemeral HS might even make some difference for https://github.com/bisq-network/bisq/issues/1943)
  - native Tor got killed by the JVM and therefore, no graceful shutdown has been possible. Now, the shutdown-hook is configurable.
- Tor 0.3.9 (from [Torbrowser 8.0.4](https://github.com/JesusMcCloud/tor-binary/releases/tag/8.0.4-jitpack)) (via https://github.com/bisq-network/bisq/pull/2009 as well)
- streamlined the [tor-binary](https://github.com/JesusMcCloud/tor-binary) dependency so that it builds on jitpack.io. The big advantage for Bisq is that there is no separate source repo line necessary for fetching the tor-binary dependency from (as this has lead to a nasty bug https://github.com/bisq-network/bisq/pull/1917 already) (via https://github.com/bisq-network/bisq/pull/2009 as well)
- creating and refining the [Monitoring Proposal](https://github.com/bisq-network/proposals/issues/62)
- Monitoring Release **Babysteps** (https://github.com/bisq-network/proposals/issues/62#issuecomment-450391634, https://github.com/bisq-network/bisq/pull/2181, https://monitor.bisq.network)

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- Monitoring Release **Showing Off**
- eventually, Windows startup issues - as it has to do with Tor...

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- [Arch Linux AUR maintainer](https://github.com/bisq-network/roles/issues/78#issuecomment-450404562) 50 BSQ

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
