### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by CaveSpectre11** [bisq-network/compensation#186]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 100 
 - BSQ address: B1M4i1X6oq3i8YaA6C9tgYUF86EZ8r6MdZC

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

https://github.com/bisq-network/bisq/pull/2025 as reported in https://github.com/bisq-network/bisq/issues/2021
20 BSQ. Corrected faulty regex in 13 coins, Reworked testInvalidAddresses() for said coins.
https://github.com/bisq-network/bisq/pull/2162 
80 BSQ. Fixed a few typos in displayStrings; and reworked a few things

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
