### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/compensation#187]
## Summary

 - BSQ requested: 3500
 - BSQ address: B1N7BFqBX2MUmbZ4KGNKujooPaWBxTyVx6H

## Contributions delivered

- Testing [v0.9.0 release](https://github.com/bisq-network/bisq/releases/tag/v0.9.0) on Windows. This was a major release and required thorough testing. I did not find any major issues, but identified a few minor cosmetic, content, and validation issues.
Executed the following tests in [TestQuality](https://bisq.testquality.com):
[v0.9.0 Account Setup [Windows]](https://bisq.testquality.com/project/4883/plan/8684/run/67924/result/829110)
[v0.9.0 Arbitration/Support Process [Windows]](https://bisq.testquality.com/project/4883/plan/8685/run/67921/result/829080)
[v0.9.0 Funds/Wallet Management [Windows]](https://bisq.testquality.com/project/4883/plan/8686/run/67918/result/829068)
[v0.9.0 Trading Process [Windows]](https://bisq.testquality.com/project/4883/plan/8683/run/67885/result/828582)
Entered the following issues:
https://github.com/bisq-network/bisq/issues/1996
https://github.com/bisq-network/bisq/issues/1997
https://github.com/bisq-network/bisq/issues/1998
https://github.com/bisq-network/bisq/issues/1999
https://github.com/bisq-network/bisq/issues/2033
https://github.com/bisq-network/bisq/issues/2041
https://github.com/bisq-network/bisq/issues/2042
https://github.com/bisq-network/bisq/issues/2043
https://github.com/bisq-network/bisq/issues/2044
https://github.com/bisq-network/bisq/issues/2045
https://github.com/bisq-network/bisq/issues/2046
https://github.com/bisq-network/bisq/issues/2047
https://github.com/bisq-network/bisq/issues/2058
https://github.com/bisq-network/bisq/issues/2059
https://github.com/bisq-network/bisq/issues/2065

- Testing the DAO on testnet. Not following any formal test cases, but performing exploratory style testing based on knowledge about the DAO I have gained from documentation and from YouTube videos. I did not find any major issues, but identified primarily usability issues.
Entered the following issues:
https://github.com/bisq-network/bisq/issues/2082
https://github.com/bisq-network/bisq/issues/2086
https://github.com/bisq-network/bisq/issues/2087
https://github.com/bisq-network/bisq/issues/2091
https://github.com/bisq-network/bisq/issues/2092
https://github.com/bisq-network/bisq/issues/2114
https://github.com/bisq-network/bisq/issues/2124
https://github.com/bisq-network/bisq/issues/2139
https://github.com/bisq-network/bisq/issues/2140
https://github.com/bisq-network/bisq/issues/2141

- Resolved a few issues regarding line endings, one that was specifically causing BisqHelpFormatterTest to fail on Windows.
https://github.com/bisq-network/bisq/pull/2031
https://github.com/bisq-network/bisq/pull/2032

- Implemented a script that installs and configures the necessary JDK on Windows, and made a few refinements along the way. This should make the setup process for new Windows devs quick and easy, as well as ensure they are using the proper JDK.
https://github.com/bisq-network/bisq/pull/2039
https://github.com/bisq-network/bisq/pull/2085
https://github.com/bisq-network/bisq/pull/2131
https://github.com/bisq-network/bisq/pull/2165

- Added the install_java.sh script (which had been removed as part of restructuring done in https://github.com/bisq-network/bisq/pull/1924), and updated it to work on a variety of Linux distributions. This should make the setup process for new Linux devs quick and easy, as well as ensure they are using the proper JDK.
https://github.com/bisq-network/bisq/pull/2003
https://github.com/bisq-network/bisq/pull/2055

## Contributions in progress

- Continuing to test the DAO on testnet. More exploratory style testing.

- Update Windows install experience. Key features include abort the installer if the application is running prior to install or uninstall, and added German, French, and Spanish translations.
https://github.com/bisq-network/bisq/pull/2164

- Update Windows packaging process so that it is capable of performing the complete packaging
process. This will allow anyone running Windows to easily generate their own Bisq installer if they so chose, rather than downloading it.
https://github.com/bisq-network/bisq/pull/2163

- Update Linux packaging process so that it is capable of performing the complete packaging
process. This will allow anyone running Linux to easily generate their own Bisq installer if they so chose, rather than downloading it.

- Scan files using VirusTotal as part of release process in order to ensure that they are not being flagged as false positives.
https://github.com/bisq-network/bisq/issues/2177

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
