### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by rex4539** [bisq-network/compensation#188]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 40
 - BSQ address: B153NNHXQxnH5v6AXv8F5zdhPsdjkQfxB7v

## Contributions delivered

Requesting missing BSQ from older compensation request.

See https://github.com/bisq-network/compensation/issues/165#issuecomment-443485915 and https://github.com/bisq-network/compensation/issues/165#issuecomment-443486556

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
