### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#189]
## Basic information

 - BSQ amount requested: **13575**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

### Development work:
- Development work [1]
- Preparation and testing for v0.9.0 release
- Preparation and testing for v0.9.1 release
- Code review
- Onboarding/coordination with new developers. 

Requested: 9000 BSQ

### DAO educational videos:
Interviews with @arunasurya about DAO topics:

- Bitcoin Transactions: https://www.youtube.com/watch?v=mOSYPrgLKWw
- Colored Coins: https://www.youtube.com/watch?v=68_DU1c0Cac
- BSQ Tokens - Technical: https://www.youtube.com/watch?v=GfD5XaR_oLs
- BSQ Tokens - Economic: https://www.youtube.com/watch?v=hsAfja6uB8w
- Compensation Requests and Voting: https://www.youtube.com/watch?v=OdoXsSqinQM

Requested: 1000 BSQ

[1] https://github.com/ManfredKarrer

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1
- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8 `(25)`
- Seed node maintainer: https://github.com/bisq-network/roles/issues/6 `(25)`
- Statsnode Maintainer: https://github.com/bisq-network/roles/issues/7 `(225)`
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14 `(100)`
- Events Maintainer: https://github.com/bisq-network/roles/issues/65 `(25)`
- Markets Website+API Maintainer: https://github.com/bisq-network/roles/issues/9 `(25)`

Sum: 425 BSQ

Operator roles:
- Markets Website+API Operator: https://github.com/bisq-network/roles/issues/9 `(50)`
- Seed node operator: https://github.com/bisq-network/roles/issues/15 `(8 nodes: 400)`
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10 `(50)`
- Price node Operator `(2 nodes: 100)`
- Relay node (mobile notifications) Operator `(50)`
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67 `(2 nodes: 100)`
- BSQ explorer node `(50)`
- Testnet DAO seed node `(50)`

Sum: 850 BSQ

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

Major roles:
- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63 `(2000)`
- GitHub Admin: https://github.com/bisq-network/roles/issues/16 `(200)`
- Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12 `(50)`
- Slack Admin: https://github.com/bisq-network/roles/issues/23 `(50)`

Sum: 2300 BSQ

Minor roles:
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Freenode Admin: https://github.com/bisq-network/roles/issues/22
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31
- Transifex Admin: https://github.com/bisq-network/roles/issues/20
- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Support Staff: https://github.com/bisq-network/roles/issues/64

Requested for all the listed roles: 3575 BSQ

**Comment by ripcurlx** [comment]
@ManfredKarrer Isn't your compensation request a little bit low this month with all the efforts that also went into releasing 0.9.0?

**Comment by ManfredKarrer** [comment]
Ah I forgot that 0.9 was released in December.... Will add the release preparation and testing efforts. Thanks.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
