### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#190]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `3790`
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

### Reviews of PR
https://github.com/bisq-network/bisq/pull/2056
https://github.com/bisq-network/btcd-cli4j/pull/3
https://github.com/bisq-network/bisq/pull/2109
https://github.com/bisq-network/bisq/pull/2117
https://github.com/bisq-network/bitcoinj/pull/16

**BSQ requested** `600`

### DAO Explorer
I made the DAO explorer usable and setup a server to host it. It would be good to move the current explorer at explorer.bisq.network to a new server and the one I'm running at explorer.sqrrm.net seems better.

https://github.com/bisq-network/bisq-explorer/pull/1
https://github.com/bisq-network/bisq-explorer/pull/2

**BSQ requested**
Setup server: `100`
Work on explorer: `2400`

### Bisq client work
Minor work on the client with a focus on DAO related issues.
https://github.com/bisq-network/bisq/pull/2074
https://github.com/bisq-network/bisq/pull/2094
https://github.com/bisq-network/bisq/pull/2172

**BSQ requested** `400`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

More work on DAO related issues of more serious nature is being reviewed and more work is needed. These to PRs are about spending pending BSQ and keeping the BTC and BSQ wallet states healthy. There is also more work needed on the BSQ accounting in the dashboard overview but that's more of a cosmetic issue.

https://github.com/bisq-network/bisq/pull/2171
https://github.com/bisq-network/bitcoinj/pull/18

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bitcoin node maintainer - https://github.com/bisq-network/roles/issues/66#issuecomment-449849236 `50`
Bitcoin node operator - https://github.com/bisq-network/roles/issues/67#issuecomment-450498407 `100`
Tor relay operator - https://github.com/bisq-network/roles/issues/72#issuecomment-447636785 `140`

The tor relays were some trouble this month.

Total requested for roles, BSQ 290

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
