### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by BravoIndia** [bisq-network/compensation#192]
## Summary

 - BSQ requested: 800 BSQ
 - BSQ address: B1RsBHsUuEBTLUgf7KeFs4KnT9jwMWi7Xt

## Contributions delivered

- Thai language delivered with [v0.9.0 release](https://github.com/bisq-network/bisq/releases/tag/v0.9.0).

  - Translation: 4963 words translated throughout November and December.

Requested: 120 BSQ

  - Review: 1677 words edited, 4643 words reviewed throughout November and December.

Requested: 120 BSQ

- Testing the DAO on testnet and [v0.9.0 release](https://github.com/bisq-network/bisq/releases/tag/v0.9.0). Including helping to identify the BisqHelpFormatterTest failing on Windows https://github.com/bisq-network/bisq/pull/2032, clarifying build.md https://github.com/bisq-network/bisq/pull/2008, making suggestions for UI https://github.com/bisq-network/bisq/issues/2071 and spending unconfirmed BSQ https://github.com/bisq-network/bisq/issues/2107 (addressed with https://github.com/bisq-network/bisq/pull/2099 and https://github.com/bisq-network/bisq/pull/2171 respectively).

  - Identifying a DAO voting critical UI bug https://github.com/bisq-network/bisq/issues/2072 (addressed with https://github.com/bisq-network/bisq/pull/2094) eligible for a [bounty](https://bisq.community/t/how-to-explore-the-dao-on-testnet/6692) of 100 - 1000 BSQ.

Requested: 560 BSQ

## Contributions in progress

- Hebrew translation.

**Comment by ManfredKarrer** [comment]
@BravoIndia Feel free to request more. Your contribution in testing was highly appreciated and high qualitity!

**Comment by BravoIndia** [comment]
Thank you @ManfredKarrer and @ripcurlx, your appreciation is very heartwarming. The pleasure is sincerely all mine.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
