### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by joachimneumann** [bisq-network/compensation#194]
## Summary
BSQ requested: 2600
BSQ address: B1HjazHawa5LD3j8o4gStJYyZFSnZqx8R7H

## Contributions delivered
Adaptation of the Android and the iOS App to the new graphical design, colors and icon. This work was done in October 2018, but I wanted to wait with the compensation request until the Apps with the new design are in the app store.

## Roles performed
Managing bisq-mobile on slack
Bugfixes

**Comment by ripcurlx** [comment]
@joachimneumann It would be great if you could link the PR's of bug fixes/work you did in your repository to make it easier to evaluate your contribution.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
