### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#196]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**
## Roles performed
- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-450576897 (2500 BSQ)
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-450578172 (350 BSQ)
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-450576397 (150 BSQ)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
