### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/compensation#197]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `2400`
 - BSQ address: B19yxYCRTVaDfRfucrH6aEzeZpoVTv8Je8S

This compensation request :
- follows the https://docs.bisq.network/roles.html#compensation recommandations
- applies the 1BSQ=1USD rule
- takes into account the time spent for the roles
- is quite a copy/paste of october & november compensation requests (for the roles)

### Substantive reports

- Support | https://github.com/bisq-network/roles/issues/64#issuecomment-450633835 | (BSQ  requested = 2000)
Evaluation is based and intended in line with : previous compensation requests, https://github.com/bisq-network/compensation/issues/24 , and other support compensation requests.

- Fees and connectivity monitoring | see the weekly reports in https://github.com/bisq-network/roles/issues/10 | (BSQ requested = 200)
TL;DR: there was zero catch this month (nodes are running well).

- Prices monitoring | https://github.com/bisq-network/roles/issues/10#issuecomment-450620481 | (BSQ requested = 200)
TL;DR: There were no noticeable divergences between pricenodes this month.

## Other points (BSQ requested = 0)
- Clearnet Bisq webpages monitoring : 0 alert this month

## Contributions in progress
- I'll try to provide realtime monitoring/reporting in january. Should be on an onion at first.
- I'm working on a support documentation (compilation of main support issues)
- It's just a beginning, but I'm putting a bit the hands in the bisq java code

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
