### ISSUE TITLE
For November 2018 - February 2019

### ISSUE THREAD

**Issue by oscarguindzberg** [bisq-network/compensation#198]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 40650
 - BSQ address: B1LiYyuKpAZQHuyzRiFy8uBYNC71S8nEXQJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

I have focused on several bitcoinj related stuff. 

These items describe my contributions from Nov 2018 to Feb 2019:

- "Feasibility for replacing Bitcoinj" research
  -  https://github.com/bisq-network/bisq/issues/1062#issuecomment-446755367 
- "Review BIP 44 Implementation" code audit
  - https://github.com/bisq-network/bisq/issues/1853#issuecomment-447598673
- Write bugfix "When date of the seed is not specified use bisq 0.5 release date" (committed by Manfred)
  - https://github.com/bisq-network/bisq/commit/717f5fb9b2c55ccb69c26454b228d20079470eb0 
- Several code cleanup PRs
  - Code cleanup - https://github.com/bisq-network/bisq/pull/2137
  - Remove Networks and AbstractBitcoinNetParams since they are not used - https://github.com/bisq-network/bisq/pull/2182
  - Fix getActiveKeyChain() typo - https://github.com/bisq-network/bisq/pull/2151 
- "Bisq disconnected from local btc node" issue investigation
  - https://github.com/bisq-network/bisq/issues/1823#issuecomment-447605289   
  - Issue closed because a workaround was implemented, a new related issue should be created for the still unsolved problem.
- “Accepted offer failed to execute, went through anyway but never happened” issue investigation
  - https://github.com/bisq-network/bisq/issues/2112#issuecomment-449741123
- Fix bug "TX considered non-standard due to unknown version number 2"
  - Issue: https://github.com/bisq-network/bisq/issues/1832 
  - PR1: https://github.com/bisq-network/bisq/pull/2127
  - PR2: https://github.com/bisq-network/bitcoinj/pull/16 
- jdk8 vs jdk 10
  - Found out bitcoinj has to be built using jdk8 and bisq has to be built using jdk10
  - Documented how to have both jdk8 and jdk10 on the same computer and wrote a script to switch between them.
  - Evaluate the risks of building with jdk8 and running with jdk10.
  - try to build bitcoinj using jdk10 and found lots of issues, documented the problems I had.
  - See details on https://github.com/bisq-network/bitcoinj/issues/17
- "Restore from seed" does not works on windows  
  - Research
    - Found and documented the bug https://github.com/bisq-network/bisq/issues/2402
    - Part of the research is documented on jdk8 vs jdk10 issue https://github.com/bisq-network/bitcoinj/issues/17
    - Discuss on related (maybe duplicate) bug https://github.com/bisq-network/bisq/issues/2323
    - Investigate "block store deletion problem on windows". 
    - Write unit test that exposes the bug https://github.com/oscarguindzberg/bitcoinj/commit/7bd0d3672ca772fa9ec1bd04eca742cfa57fcbef 
    - Understand why WindowsMMapHack was necessary. Read:
      - https://github.com/bitcoinj/bitcoinj/blob/v0.14.7/core/src/main/java/org/bitcoinj/store/WindowsMMapHack.java
      - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4715154
      - http://www.mapdb.org/blog/mmap_files_alloc_and_jvm_crash/
      - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4724038
      - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6359560
    - Evaluate different approaches to solve the problem: 
      - include sun.* classes
      - use LevelDBBlockStore
      - Remove usage of MappedByteBuffer in SPVBlockStore by using FileChannel or RandomAccessFile directly
  - Implement a solution that removes mmap usage 
    - PR on bisq https://github.com/bisq-network/bisq/pull/2403 
    - PR on bitcoinj upstream https://github.com/bitcoinj/bitcoinj/pull/1695
    - Test performance of the PR: SPVBlockStoreTest.performanceTest() fails on a mac, on a windows box on aws and travis-ci (Had to fix bitcoinj upstream to print test log on travis-ci https://github.com/bitcoinj/bitcoinj/pull/1699)   
  - Implement alternative solution with SPVBlockStore.clear() 
    - PR on bisq https://github.com/bisq-network/bisq/pull/2438 
    - PR on bitcoinj upstream https://github.com/bitcoinj/bitcoinj/pull/1702
  - Test restore from seed on wallet-template bitcoinj project 
    - Create issue upstream because it fails https://github.com/bitcoinj/bitcoinj/issues/1704       
- Rebuild  commit history of bisq’s bitcoinj
  - "Merge" has been used instead of "rebase" for years to add code and to bring new changes from bitcoinj upstream. In that context some tasks are very hard and risky to do: Understanding what (and why) has changed compared to the original bitcoinj, deciding whether a change makes sense or not, using "git blame", incorporating changes from upstream, doing more changes to the code.   
  - I rebuilt the commit history from scratch. Now every commit makes sense on its own, has a descriptive commit message and a link to the original commit.
  - New commit history: https://github.com/oscarguindzberg/bitcoinj/commits/bisq_0.14.4.1-rebase2
  - Old commit history: https://github.com/bisq-network/bitcoinj/commits/bisq_0.14.4.1
- Rebase bisq’s bitcoinj from v0.14.7 upstream 
  - See https://github.com/oscarguindzberg/bitcoinj/tree/bisq_0.14.7-original 
  - Run unit tests and make sure no more test fail compared to the ones that already fail on bisq’s bitcoinj 0.14.4.1 branch
  - Review upstream bitcoinj commits from v0.14.4 to v0.14.7
    - Remove bloq’s dns seed https://github.com/oscarguindzberg/bitcoinj/commit/b3b3b6457458f513766aeb0d70ead8237686fe87
- Fix failing tests on bisq's bitcoinj branch
  - https://github.com/bisq-network/bitcoinj/issues/19 
- Update harcoded seed nodes 
  - https://github.com/bisq-network/bitcoinj/commit/b8541e1fde92a59444d4404f6ce488fe987bde37
- Prevent DoS attacks to bitcoinj. 
  - https://github.com/bisq-network/bitcoinj/commit/a4abdb6b2b4093f6e715dee7a0cdd483d0288392
  - https://github.com/bisq-network/bitcoinj/commit/66c5bd46cbabfab57e3cdcc6379e21c81d989ae1
- Code review of bisq's bitcoinj
  - Review the changes done by bisq to bitcoinj (tor/hidden services, fee calculation and connection handling changes still have to be reviewed)
  - Implement changes on https://github.com/bisq-network/bitcoinj/tree/bisq_0.14.7
  - See details in https://github.com/bisq-network/bitcoinj/issues/20
- Use bitcoinj 0.14.7 in bisq
  - https://github.com/bisq-network/bisq/pull/2478
- Review “Clone transaction before adding to wallet” PR
  - https://github.com/bisq-network/bitcoinj/pull/18
- Review “Transaction can serialize and deserialize according to Segwit”
  - https://github.com/bisq-network/bitcoinj/issues/13#issuecomment-460394501
- Bisq dev session presentation: bitcoinj
- Remove "pricenode" direct dependency on "assets"
  - https://github.com/bisq-network/bisq/pull/2197
- Be able to upgrade bitcoinj without upgrading libdohj
  - https://github.com/bisq-network/bisq/pull/2198
- Remove libdohj dependency from bisq
  - https://github.com/bisq-network/bisq/pull/2368
  - Revert Dash specific change on bitcoinj: https://github.com/oscarguindzberg/bitcoinj/commit/5b35c8412d547b2e2dbd0e77b22c75081875b0ff 

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- Investigate moving to bitcoinj upstream master
  - https://groups.google.com/forum/#!topic/bitcoinj/M05pt8Hwnw0
  - https://groups.google.com/forum/#!topic/bitcoinj/qjxgcpKak3s
  - Participate in https://github.com/bisq-network/bisq/issues/1139 
  - https://groups.google.com/forum/#!topic/bitcoinj/kE6hO3Cj8-Q 
  - Review bitcoinj master source code
  - Review https://github.com/bitcoinj/bitcoinj/pull/1563 (see my comments)
  - Send email asking for 0.15 release notes - https://groups.google.com/forum/#!topic/bitcoinj/kE6hO3Cj8-Q
  - Investigate segwit bip144 support in bitcoinj https://groups.google.com/forum/#!topic/bitcoinj/qjxgcpKak3s

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by ManfredKarrer** [comment]
@oscarguindzberg You can find the BSQ address in the mainnet Bisq app when you click cmd+d then the DAO menu item becomes visible where you find a single screen with a BSQ address.

**Comment by ManfredKarrer** [comment]
Please remove the WIP once the request is final.

**Comment by ManfredKarrer** [comment]
You can add merged code to completed work. We changed policy a while back to that merged PRs are considered delivered work.

**Comment by ripcurlx** [comment]
@oscarguindzberg I didn't transfer your compensation request for voting because it was marked with [WIP]. Feel free to submit it for next month's voting cycle.

**Comment by ManfredKarrer** [comment]
Thanks @oscarguindzberg for the detailed overview!

**Comment by ManfredKarrer** [comment]
Regaring https://github.com/bisq-network/bisq/pull/2478 : I did not had time today to review and test it but it will be done soon. So lets make an exception here and consider it as merged ;-) (there is no doubt that it gets merged).

**Comment by m52go** [comment]
Hello @oscarguindzberg would you mind making a corresponding compensation request in the testnet Bisq DAO, if you haven't already? Would really help us with testing this round.

The proposal phase for this round ends sometime tonight.

https://docs.bisq.network/getting-started-dao.html

**Comment by ManfredKarrer** [comment]
@ripcurlx Seems you added it still to the spreadsheet. Could you edit/strike your above comment?

**Comment by ripcurlx** [comment]
> @ripcurlx Seems you added it still to the spreadsheet. Could you edit/strike your above comment?

Done.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
