### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#199]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `7925`
 - BSQ address: B1FGfKZQrpbLN9UNMogyJAVTR5PJNRkGPXJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**Website**
I hadn't worked on the site until the redesign was merged, so I didn't thoroughly review it beforehand, assuming others had it under control. However, there were a series of issues discovered afterward that I spent considerable time fixing.
- Fix markets page (bisq-network/bisq-website/pull/103)
- Fix download link issues (various issues across mobile, chrome/firefox browsers, operating systems), add analytics, etc (bisq-network/bisq-website/pull/102, bisq-network/bisq-website/pull/97, bisq-network/bisq-website/pull/99)

BSQ requested: `4400`

**Copy**
Major initiative was within the Bisq program. I went through most of the `displayStrings.properties` file and reworded and refined over 40 strings.
- Program copy (https://github.com/bisq-network/bisq/pull/2104) 
- Website copy (https://github.com/bisq-network/bisq-website/pull/104)

BSQ requested: `650`

**Video**
I lightly edited and posted videos for @arunasurya and @MaxHillebrand. Did 9 videos total (6 from Aruna and from Max). Pricing at 50 BSQ per video.

BSQ requested: `450`

**Email**
Set up a basic instance of Mautic to use for email campaigns, to use in conjunction with Amazon SES. Setup is ready to opt old email subscribers in to the new system. Should enable us to start sending emails to the new list in mid to late January (need to allow users sufficient time to opt in).

BSQ requested: `800`

**Miscellaneous/overlooked from before**
- ICO note (https://github.com/bisq-network/bisq-docs/pull/94)
- BofA warning (https://github.com/bisq-network/bisq/issues/1814)

BSQ requested: `50`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- DAO docs ([done](https://github.com/m52go/bisq-docs/tree/user-dao-intro), PR coming, figured it would be better to release after holidays)
- DAO tweetstorms ([1 is done](https://gist.github.com/m52go/e1126270b6089d377c58983ea7864bce), going out soon)
- DAO simulation for the website (will be based on [this graphic](https://i.imgur.com/C0xfyqH.png))
- Testnet DAO article for Bitcoin Magazine (to be published any day now, I'm told...)
- Talk for February conference
- Two blog posts for January: topics TBD
- Docs for backup and recovery, trading rules, and support. My docs output for December was disappointing.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- Twitter Admin: [bisq-network/roles/issues/21 (comment)](https://github.com/bisq-network/roles/issues/21#issuecomment-450703687) `1500 BSQ`
- Roles Admin: [bisq-network/roles/issues/28 (comment)](https://github.com/bisq-network/roles/issues/28#issuecomment-450703917) `25 BSQ`
- Docs Maintainer [bisq-network/roles/issues/29 (comment)](https://github.com/bisq-network/roles/issues/29#issuecomment-450703982) `25 BSQ`
- Slack Admin [bisq-network/roles/issues/23 (comment)](https://github.com/bisq-network/roles/issues/23#issuecomment-450704080) `25 BSQ`

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
