### ISSUE TITLE
 For October 2017 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#2]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: **14000**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value. **Please include only completed work!**_

### Development work:
- Implement "Payment account age based trade amount limits" (Merged PR: https://github.com/bisq-network/exchange/pull/984)
- Many smaller commits for UI improvements (based on Christoph's feedback), merge altcoins, merge other PR from other developers, bug fixes,... 
See complete Github activity at: https://github.com/ManfredKarrer

### Proposal:

Payment account age based trade amount limits:
https://github.com/ManfredKarrer/proposals/blob/limits-by-account-age/payment-account-age-witness.adoc
https://github.com/bisq-network/proposals/pull/2

### Documents:
https://github.com/bisq-network/docs/blob/master/exchange/howto/run-seednode.adoc
https://github.com/bisq-network/docs/blob/master/exchange/howto/run-price-relay-node.adoc
https://github.com/bisq-network/docs/blob/master/exchange/howto/add-alternative-base-currency.adoc
https://github.com/bisq-network/docs/blob/master/exchange/howto/add-new-country.adoc
https://github.com/bisq-network/docs/blob/master/exchange/howto/list-token.adoc

### Other:
- Communication with contributors
- Feedback to phase zero doc
- Feedback and discussions regarding UI improvements

**Comment by cbeams** [comment]
I've entered this compensation request into the [stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=0).

**Comment by cbeams** [comment]
I've entered this request in the [stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=0) at 14000 BSQ for address B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#8
