### ISSUE TITLE
For December 2017

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#20]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 6250
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### API

regtest fix:
https://github.com/mrosseel/bisq-api/issues/2
https://github.com/bisq-network/exchange/pull/1103

added dockerfile on request:
https://github.com/mrosseel/bisq-api/commit/5fe51e3a57f65e28c3cefbeb013f01f4745dfe0b

### Monitoring 

Monitoring fixes:
https://github.com/mrosseel/bisq-monitoring/commits/master

### Various

Pricenode data feed troubleshooting:
https://github.com/bisq-network/exchange/issues/1088
https://github.com/bisq-network/exchange/pull/1089

### Hosting
Monthly costs nodes: 50 / node * 5: 250 BQS

Running:
1 Price node + bitcoinaverage subscription
1 Seed node
2 Bitcoin full nodes
1 Monitoring node + 1 messaging sync node (on one server)
  
### Roles

https://github.com/bisq-network/roles/issues/22#issuecomment-355343121

**Comment by cbeams** [comment]
Hi @mrosseel, I just noticed this is still in draft mode and that there's no BSQ amount / address yet. I'll be filling out the voting spreadsheet between now and EOD. Could you get those values in there by then?

**Comment by mrosseel** [comment]
hey @cbeams yes should be complete now

**Comment by cbeams** [comment]
Thanks. This request has been entered into the [2017.12 tab](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=548599266) of the BSQ stake and voting spreadsheet and is ready to be voted on.

**Comment by csacher** [comment]
@mrosseel  the role spec is missing at: https://github.com/bisq-network/roles
Please follow "How to Create a New Role" (point 1 and 2 are already settled, follow 3,4,5).
Thanks.

**Comment by cbeams** [comment]
bisq-network/exchange#1103 and bisq-network/exchange#1088 have not been merged. This seems to violate the principle of requesting compensation for _completed_ work only. Perhaps I'm missing something, so I've voted `0` for this request in the meantime. Happy to change my vote to `1` tomorrow morning if there is further feedback.

**Comment by mrosseel** [comment]
Agreed for #1103 (I did a workaround to help out the api user since this route would take too long).
For #1088 it seems this is merged in PR #1089

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#26.
