### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by freimair** [bisq-network/compensation#200]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 7000
 - BSQ address: B1JJUQWUHEoUwng4uGGWsT4hnTMc6dXtj9K

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- Sins commited in a previous year got a hold of me. Fixed in https://github.com/bisq-network/bisq/pull/2194.
- Monitor release: Showing off (https://github.com/bisq-network/bisq/pull/2348)
- Presentation of Monitor progress: https://www.youtube.com/watch?v=M4cusbcI_j8

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- Monitor release: Settled, see task list https://github.com/bisq-network/proposals/issues/62
- eventually, take over a seed node and do some optimization stuff and maybe tackle one of these issues
  - https://github.com/bisq-network/bisq/issues/2258
  - https://github.com/bisq-network/bisq/issues/2256
  - https://github.com/bisq-network/bisq/issues/1241
  - https://github.com/bisq-network/bisq/issues/1172
  - ...

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- [Arch Linux AUR Maintainer](https://github.com/bisq-network/roles/issues/78#issuecomment-452638986)

**Comment by ripcurlx** [comment]
@freimair That's a first, that a compensation request is prepared already in the beginning of the month :+1:

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
