### ISSUE TITLE
For November 2018 - January 2019

### ISSUE THREAD

**Issue by KanoczTomas** [bisq-network/compensation#201]
## Summary
 - BSQ requested: 305
 - BSQ address: B17TT6PsriwSLoKDnybE4LoDazkffQxtx3G

### November 2018
- wrote update instructions for Monero transaction proof text [#1885](https://github.com/bisq-network/bisq/issues/1885) - **requesting bounty `30` BSQ**
- processed reimbursement issues for November 2018, [#155](https://github.com/bisq-network/support/issues/155), [#156](https://github.com/bisq-network/support/issues/156), [#157](https://github.com/bisq-network/support/issues/157), [#158](https://github.com/bisq-network/support/issues/158), [#159](https://github.com/bisq-network/support/issues/159), [#160](https://github.com/bisq-network/support/issues/160), [#161](https://github.com/bisq-network/support/issues/161), [#162](https://github.com/bisq-network/support/issues/162), [#163](https://github.com/bisq-network/support/issues/163), [#164](https://github.com/bisq-network/support/issues/164), [#165](https://github.com/bisq-network/support/issues/165), [#166](https://github.com/bisq-network/support/issues/166), [#167](https://github.com/bisq-network/support/issues/167), [#168](https://github.com/bisq-network/support/issues/168), [#169](https://github.com/bisq-network/support/issues/169), [#170](https://github.com/bisq-network/support/issues/170), [#171](https://github.com/bisq-network/support/issues/171), [#172](https://github.com/bisq-network/support/issues/172) - batch payment issue: [#147](https://github.com/bisq-network/support/issues/147) - **requesting `25` BSQ**

### January 2019
- created and documented a helper script to process reimbursements - inspired by my laziness and a huge batch reimbursement that needed automatization (commit [526f4b0...](https://github.com/bisq-network/support/commit/526f4b028f9753aa9afea12e2c5c2e9b9196eb8b)) - **requesting `200` BSQ**

### December 2018
* Support Maintainer: https://github.com/bisq-network/roles/issues/76#issuecomment-451463905 - **requesting `25` BSQ**
### January 2019
* Support Maintainer: https://github.com/bisq-network/roles/issues/76#issuecomment-458343177 - **requesting `25` BSQ**

**Comment by ripcurlx** [comment]
To me your compensation request feels a little bit low compared to what you contributed.

**Comment by KanoczTomas** [comment]
@ripcurlx thanks, I reconsidered the amount requesting the automation script. From the stakeholders perspective it is much more then 5 BSQ value added. I strugle to find my contribution value so thanks for the feedback. I valued it to 200 BSQ, please share your thoughts if it is too much or the oposite. Also for the role I am doing for reimbursements 25 BSQ might be a bit low, but that is I thought a fixed price, maybe we should reconsider it. On the other hand adding the automation script reduces the job to do significantly and 25 BSQ got realistic with that work added.

**Comment by ripcurlx** [comment]
There is no fixed value on a role. 25 BSQ is used by lots of contributors as a base value for roles you're holding and reporting when there is hardly any contribution involved in a month. So your updated amount looks now more realistic to me 👍

**Comment by KanoczTomas** [comment]
@ripcurlx ah good to know. I had a gut feeling that the role amount is fixed :) Makes more sense now, thanks for clarifying.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
