### ISSUE TITLE
For November 2018

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/compensation#202]
## Summary

- BSQ requested: 200
- BSQ address: B16kMZonmnNXrZvSqGuXVjpWWTZnSVG3xJb
 
## Contributions delivered
 
- [Payment Methods Slack](https://bisq.slack.com/messages/C89R6FQS3/)
- [Payment Methods Community](https://bisq.community/c/payment-methods)
- [Payment Methods Tracking and Report](https://docs.google.com/spreadsheets/d/1AeWAz5w_IzIQ3-QS9yEzZBOTH_83DT503IhLg_PQD10/edit?usp=sharing)
- [PM Evaluation](https://github.com/bisq-network/payment-methods/issues/19)
 
## Contributions in progress
 
- [Payment Methods Knowledge Base: Cash Deposit](https://github.com/bisq-network/bisq-docs/pull/52)
- [Payment Methods Knowledge Base: Revolut](https://github.com/bisq-network/bisq-docs/pull/51)
- [Adding Payeer] (https://github.com/bisq-network/payment-methods/issues/14)
- [Adding Serve] (https://github.com/bisq-network/payment-methods/issues/7)
- [Adding Qiwi](https://github.com/bisq-network/payment-methods/issues/15)
- [Adding Advanced Cash](https://github.com/bisq-network/payment-methods/issues/17)
 
## Roles performed
 
- Payment Methods Maintainter. Report for May: https://github.com/bisq-network/roles/issues/38#issuecomment-451907197

**Comment by ripcurlx** [comment]
@alfsbs In your two CR you are referencing the wrong report. It is always your report from last May.

**Comment by KanoczTomas** [comment]
https://github.com/bisq-network/payment-methods/issues/19 is not working! (PM evaluation)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
