### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#205]
## Basic information

 - BSQ amount requested: **15600**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

### Development work:
- Development work [1]
- Preparation and testing for v0.9.2 release
- Hotfix for v0.9.3 release
- Code review

### Others:
- Onboarding/coordination with new developers
- Created 2 new branches and PRs for API and new trade protocol
- Add DAO monitor node (http://104.248.88.175/)
- Investigated stability issues with seed nodes at mainnet as well as DAO nodes
- Dev sessions
- Proposals [2, 3]

Requested: 12000 BSQ

[1] https://github.com/ManfredKarrer
[2] https://github.com/bisq-network/proposals/issues/67
[3] https://github.com/bisq-network/proposals/issues/68

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1
- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8 `(25)`
- Seed node maintainer: https://github.com/bisq-network/roles/issues/6 `(25)`
- Statsnode Maintainer: https://github.com/bisq-network/roles/issues/7 `(25)`
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14 `(25)`
- Events Maintainer: https://github.com/bisq-network/roles/issues/65 `(25)`
- Markets Website+API Maintainer: https://github.com/bisq-network/roles/issues/9 `(25)`

Sum: 150 BSQ

Operator roles:
- Markets Website+API Operator: https://github.com/bisq-network/roles/issues/9 `(50)`
- Seed node operator: https://github.com/bisq-network/roles/issues/15 `(6 mainnet + 4 testnet nodes: 500)`
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10 `(1 Mainnet + 1 Testnet (DAO): 100)`
- Price node Operator `(2 nodes: 100)`
- Relay node (mobile notifications) Operator `(50)`
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67 `(2 nodes: 100)`
- BSQ explorer node `(50)`

Sum: 950 BSQ

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

Major roles:
- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63 `(2000)`
- GitHub Admin: https://github.com/bisq-network/roles/issues/16 `(200)`
- Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12 `(250)`
- Slack Admin: https://github.com/bisq-network/roles/issues/23 `(50)`

Sum: 2500 BSQ

Minor roles:
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Freenode Admin: https://github.com/bisq-network/roles/issues/22
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31
- Transifex Admin: https://github.com/bisq-network/roles/issues/20
- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Support Staff: https://github.com/bisq-network/roles/issues/64

Requested for all the listed roles: 3600 BSQ

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
