### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#206]
## Summary

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested:`10405`
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**Reviews of PRs**
I monitor PR reviews separately from the responsibilities of the Bisq Desktop Maintainer role.

_Reviewed PRs:_
- https://github.com/bisq-network/bisq/pull/2198 
- https://github.com/bisq-network/bisq/pull/2165
- https://github.com/bisq-network/bisq/pull/2164
- https://github.com/bisq-network/bisq/pull/2191
- https://github.com/bisq-network/bisq/pull/2205
- https://github.com/bisq-network/bisq/pull/2187
- https://github.com/bisq-network/bisq/pull/2190
- https://github.com/bisq-network/bisq/pull/2163
- https://github.com/bisq-network/bisq/pull/2078
- https://github.com/bisq-network/bisq/pull/2218
- https://github.com/bisq-network/bisq/pull/2217
- https://github.com/bisq-network/bisq/pull/2224
- https://github.com/bisq-network/bisq/pull/2220
- https://github.com/bisq-network/bisq/pull/2213
- https://github.com/bisq-network/bisq/pull/2212
- https://github.com/bisq-network/bisq/pull/2219
- https://github.com/bisq-network/bisq/pull/2207
- https://github.com/bisq-network/bisq/pull/2248
- https://github.com/bisq-network/bisq/pull/2264
- https://github.com/bisq-network/bisq/pull/2200
- https://github.com/bisq-network/bisq/pull/2252
- https://github.com/bisq-network/bisq/pull/2250
- https://github.com/bisq-network/bisq/pull/2275
- https://github.com/bisq-network/bisq/pull/2314
- https://github.com/bisq-network/bisq/pull/2313
- https://github.com/bisq-network/bisq/pull/2312
- https://github.com/bisq-network/bisq/pull/2315
- https://github.com/bisq-network/bisq/pull/2104
- https://github.com/bisq-network/bisq/pull/2251
- https://github.com/bisq-network/bisq/pull/2330
- https://github.com/bisq-network/bisq/pull/2329

**BSQ amount requested:** `2200`

I was working mainly on the two releases v0.9.2 and v0.9.3 this month and following PRs were merged and released. Testing and release efforts are part of the Desktop Maintainer role.

**PRs merged into master**
- https://github.com/bisq-network/bisq/pull/2148
- https://github.com/bisq-network/bisq/pull/2215
- https://github.com/bisq-network/bisq/pull/2237

**BSQ amount requested:** `500`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I'm working on v0.9.4 which should be released some time in February.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

To make it more transparent and give people an idea how much effort which role means, I'll try to split up the overall number for each role.

- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63#issuecomment-458894533 `(4700 BSQ)`
- Growth: https://github.com/bisq-network/roles/issues/42#issuecomment-458900672 `(1200 BSQ)`
- Analytics: https://github.com/bisq-network/roles/issues/40#issuecomment-458902421 `(1000 BSQ)`
- Bitcoin Fullnode Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-458905253 `(50 BSQ)`
- Transifex Admin: https://github.com/bisq-network/roles/issues/20#issuecomment-458906504 `(150 BSQ)`
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31#issuecomment-458906970 `(580 BSQ)`
- Bisq Design Maintainer: https://github.com/bisq-network/roles/issues/75#issuecomment-458908305 `(25 BSQ)`

**BSQ amount requested for all these roles (see detailed amount for each role):** `7705`

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bisq Events Maintainer: https://github.com/bisq-network/roles/issues/65

## Notes to self
<details>

My PR reviews this month were created by reviewing the results of this GitHub Issues search query: 
[is:pr reviewed-by:ripcurlx updated:2019-01-01..2019-01-31 sort:updated-desc](https://github.com/bisq-network/bisq-desktop/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Aripcurlx+updated%3A2019-01-01..2019-01-31+sort%3Aupdated-desc+)

**Comment by ManfredKarrer** [comment]
@ripcurlx Your requested amount feels too low to me.

**Comment by ripcurlx** [comment]
@ManfredKarrer I haven't added my work on the 0.9.4 of this month in this compensation request. But still I've also forgot to add the contributions of the last two days to the compensation request. Just updated the amount.

**Comment by ManfredKarrer** [comment]
All what it merged can be included (even if its not released)....

**Comment by ripcurlx** [comment]
@ManfredKarrer I know, but for me it's easier in that regard to have it in the CR when it is released, as otherwise I would need to separate merge ornot merged to master contributions as well.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
