### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/compensation#207]
## Summary

 - BSQ requested: 3000
 - BSQ address: B18BA37KaiSHLMhyjs7FMPAJMfcVcVzJPCm

## Contributions delivered

Start a bisq instagram account to organically establish presence on the bitcoin circles ahead of a potential bull market in the next coming years. 

Start generating compelling and animated visual content to drive users to the client and signal to potential contributors that bisq is still developing despite the bear market.

Account: https://www.instagram.com/bisqnetwork/
Post 1: Animation In and Out green background
Post 2: Animation In and Out white background
Post 3: UI screenshots

## Contributions in progress

Template creation to display small pull quotes, data on volume and price performance.

## Roles performed

Design

![screen shot 2019-01-29 at 6 59 32 pm](https://user-images.githubusercontent.com/807505/51948822-0b4d7d00-23f8-11e9-9dd6-3b8bfae81b0f.png)

**Comment by KanoczTomas** [comment]
@ripcurlx instagram is fine for small actions that were done, like mile stones with added graphics. I think putting the monghtly trades amount (with nice graphics) or new listings/delistings would be fine on it.

**Comment by pedromvpg** [comment]
Here are some graphics I've been working on for potential future posts.

![screen shot 2019-02-02 at 11 01 39 am](https://user-images.githubusercontent.com/807505/52166342-00d20280-26da-11e9-9b40-24b24bec0ada.png)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
