### ISSUE TITLE
[WIP] For January 2019

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/compensation#208]
## Summary

 - BSQ requested: 1000
 - BSQ address: B18BA37KaiSHLMhyjs7FMPAJMfcVcVzJPCm

## Contributions delivered

First working prototype to code implementation of the monthly reporting tool within the website environment. 

Objective: to simplify and automate the issuing of reports and embedded them on the website blog to enrich the content and provide more information in one single location with seamless image export to share on other platforms.

## Contributions in progress

1. Pull relevant data from APIs: slack users, twitter followers, github contributors/pull requests/commits, etc.
2. Layout information in a legible but engaging way.
3. Develop the system so its backwards compatible so the template works with current and future reporting requirements.

https://pedromvpg.github.io/bisq-website/blog/report-february-2019/

## Roles performed

Web-development and Visual Design

![screen shot 2019-01-29 at 7 10 57 pm](https://user-images.githubusercontent.com/807505/51949231-bb6fb580-23f9-11e9-8cd7-fd406cb12d00.png)

**Comment by ManfredKarrer** [comment]
@pedromvpg  Is that request compete now as it is still marked WIP? This months will be the last requests on the spreadsheet...

**Comment by pedromvpg** [comment]
I'm going to close this one out as it relates to 
https://github.com/bisq-network/bisq-website/pull/156

I'll come back to this in the future once its more developed.
