### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/compensation#209]
## Summary

 - BSQ requested: 50
 - BSQ address: B18BA37KaiSHLMhyjs7FMPAJMfcVcVzJPCm

## Contributions delivered

QA website:
1. Navigation active state issue
2. Markets page pair selection issue

## Roles performed

Designer

**Comment by HarryMacfinned** [comment]
@pedromvpg ,
The usual usage for compensation request is to open only one issue per month, and to group everything inside.

**Comment by ripcurlx** [comment]
@pedromvpg As @HarryMacfinned mentioned it would be great if you could merge CR of the same month into one issue next time. If the work is spread over multiple months, splitting it up is fine.

**Comment by KanoczTomas** [comment]
To be honest I lack what was done in this CR, as I am fairly new could not really guess what was the work delivered - just giving feedback :)

**Comment by devinbileck** [comment]
I agree that a more detailed description with links to GH issues would be very beneficial for those not following every single issue/PR to be able to make a decision when voting.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
