### ISSUE TITLE
For December 2017

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#21]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 12500
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### Development/UX
Finally I was able to start working more and more on the Bisq app itself and am committing UI-improvements and small bug fixes at the moment which will be released soon. General moderation of `#ux` channel.

[1] https://github.com/bisq-network/exchange/pull/1065
[2] https://github.com/bisq-network/exchange/pull/1091
[3] https://github.com/bisq-network/exchange/pull/1097
[4] https://github.com/bisq-network/exchange/pull/1112
[5] https://github.com/bisq-network/exchange/pull/1113

### Testing
Testing for release [v0.6.2](https://docs.google.com/spreadsheets/d/18n6wV0g5MPTs9Xni0cFji8U34xV3O1IRPDEYZrluBuU/edit?usp=sharing)

### Growth
https://github.com/bisq-network/roles/issues/42

### Analytics
https://github.com/bisq-network/roles/issues/40

### Bitcoin Fullnode Operator
Maintenance of full core node btc.christophatteneder.com:8333 and adding of hidden tor service.

### Other
Communication with contributors

**Comment by cbeams** [comment]
This request has been entered into the [2017.12 tab](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=548599266) of the BSQ stake and voting spreadsheet and is ready to be voted on.

**Comment by cbeams** [comment]
I've voted +1 for this compensation request, but want to mention / ask about bisq-network/exchange#1091 bisq-network/exchange#1097, which have been merged to the `UI-improvements` but (so far as I understand) have not been merged to `master`. What do you think, @ripcurlx and @ManfredKarrer about how this fits with the idea of filing compensation requests only for _completed_ work? If it's not in `master`, I'd say it's not complete, i.e. it may never make it in front of users.

**Comment by ManfredKarrer** [comment]
The downside with applying that is that there is more pressure to merge things to master (both time wise and risk wise) as the requester is waiting for getting compensated. No strong/clear opinion on that...

**Comment by ripcurlx** [comment]
Yes, I guess it depends how we want to have the workflow in the end. If we’ll have a development branch that has stuff in it that needs to be more tested before merged into master I think we could also include pull requests that are not merged into master yet. If we only want to have a master branch and everything that is committed into it has to be release ready than we might not include  pull requests that are not merged into master in compensation requests.

**Comment by sqrrm** [comment]
I think the requirement of only compensating for merges to master might be too strict. For now I'll be voting yes for reasonable looking contributions. Could be that adds too much of a requirement to check the compensation requests though, the ones merged to master are guaranteed to be reviewed and accepted as good contributions.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#26.
