### ISSUE TITLE
For December 2018 and January 2019

### ISSUE THREAD

**Issue by eyalron33** [bisq-network/compensation#210]
This compensation request regards a variety of contributions made to Bisq during December 2018 and January 2019.

    BSQ amount requested: 5000 (3000 for December 2018 + 2000 for January 2019)
    BSQ address: B1PU7DoYDHWi2impz86Fvu3ZgsREaBnGJBW

### Development:

- Collaborating with Craig Sailor on the Bisq new trade protocol ([github repository](https://github.com/craigsailor/bisq)).
- Collaborating with Manfred Karrer for planning of the [Bisq new trade protocol](https://github.com/bisq-network/proposals/issues/52) and its [roadmap](https://docs.google.com/document/d/160-74pYDowU4ok3czx-hG6QZYiH0tpNdUN-J4xIdVgI/edit).

###  Lectures

- Preparation and conducting The DAO of Bisq lecture in [Warsaw Ethereum developers meetup](https://www.youtube.com/watch?v=AjX2OGbp8xw).

- Preparation for The DAO of Bisq in the blockchain track in [FOSDEM 2019](https://fosdem.org/2019/schedule/event/the_dao_of_bisq/).

### Various other contributions

- [Hosting Bisq weekly call](https://www.youtube.com/watch?v=cZtg2sjXli0) about the BISQ new trade protocol.
- Participation in a variety of Bisq calls and meetings, including various developers discussions about Bisq.

All of that was done in collaboration with other Bisq members, for example, Manfred Karrer or Craig Sailor.

**Comment by ripcurlx** [comment]
@eyalron33 It would be great if you could split up your contributions in the descriptions between the different contributions, so it is easier to evaluate. Also if people do similar tasks in the future they would have a reference they could use for their valuation of contribution.

**Comment by eyalron33** [comment]
@ripcurlx Good idea, I didn't think about it. Is it ok if I'll do it for the next time though? Because for this time I was just marking the hours for myself, without writing which task was done on each hour.

Sorry about that.

I added the amount of hours there for clarification.

**Comment by ripcurlx** [comment]
I think we shouldn't add hours of work as we don't want to compensate time spent, but more work contributed. But yes, it would be great if you could split up for next month how the total sum you are requesting is made of.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
