### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#211]
## Summary

- BSQ requested: 350
- BSQ address: B1PFD3uscJqFQfLNAS6bWQtr1PUahrWNvC7

### Reviews and feedback: 100BSQ
Reviewed and provided feedback to @m52go on [the Introduction to Bisq DAO](https://docs.bisq.network/user-dao-intro.html). 

### Transifex Reviews and Glossary Additions for Russian: 250BSQ
- https://www.transifex.com/user/profile/arunasurya/: reviewed over 80 strings and added 35+ terms to the Russian glossary.

**Comment by ripcurlx** [comment]
@arunasurya As you started to work more and more in Transifex, do you think you would be up for taking over the Transifex maintainer role? I'm doing the updating of the translations within the client before every release with a script, so it is not much effort for me to continue to do it myself. But it would be great if someone could have an eye on comments and feedback within Transifex and to push it more pro-active. What do you think?

**Comment by KanoczTomas** [comment]
@arunasurya is there a way to view the transifex aditions without having transifex account?
https://www.transifex.com/user/profile/arunasurya/ says profile for me. I am too lazy now to create an account, just maybe you could state it needs an account to verify, or maybe find out how it can be easily viewed by anyone. Of maybe copying it here would help as well, or linking a file.

**Comment by arunasurya** [comment]
@ripcurlx , sure I can take over the role. Maybe we can have a brief call to discuss how to transition smoothly? Let me know on slack!

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
