### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#213]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `1660`
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

### Reviews

https://github.com/bisq-network/bisq/pull/2191
https://github.com/bisq-network/bisq/pull/2195

**BSQ requested** `230`

### DAO Explorer at https://explorer.bisq.network/ and https://explorer.sqrrm.net/
We had some trouble with the seed nodes this month due to memory config. After Manfred figured how to set it we've been stable. Added better handling of new blocks.

**BSQ requested**
Work: `1200`
Server: `40`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Working on spending unconfirmed BSQ and related issues found during this work.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bitcoin node maintainer - https://github.com/bisq-network/roles/issues/66#issuecomment-459144403 `50`
Bitcoin node operator - https://github.com/bisq-network/roles/issues/67#issuecomment-459144623 `100`
Tor relay operator - https://github.com/bisq-network/roles/issues/72#issuecomment-459145157 `40`

Total requested for roles, BSQ `190`

**Comment by ManfredKarrer** [comment]
@sqrrm  Your requested amount feels too low to me.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
