### ISSUE TITLE
For January

### ISSUE THREAD

**Issue by CaveSpectre11** [bisq-network/compensation#214]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 50
 - BSQ address: B1M4i1X6oq3i8YaA6C9tgYUF86EZ8r6MdZC

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

https://github.com/bisq-network/bisq/pull/2187 as reported in https://github.com/bisq-network/bisq/issues/2134
50 BSQ.  Fixed color saturation on buttons when hovering or selected.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

(I have been busy with my day job 14 hour days and have not been able to participate lately)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
