### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/compensation#215]
## Summary

 - BSQ requested: 4000
 - BSQ address: B1N7BFqBX2MUmbZ4KGNKujooPaWBxTyVx6H

## Contributions delivered

- Updated Windows install experience. Key features include abort the installer if the application is running prior to install or uninstall (e.g. to prevent file in use conflicts), and added German, French, and Spanish translations (all text content shown within the installer dialogs should be translated).
PR: https://github.com/bisq-network/bisq/pull/2164
Included in v0.9.3: https://github.com/bisq-network/bisq/releases/tag/v0.9.3

- Updated Windows packaging process so that it is capable of performing the complete packaging
process. This will allow anyone running Windows to easily generate their own Bisq installer if they so choose, rather than downloading it.
PR: https://github.com/bisq-network/bisq/pull/2163
Included in v0.9.3: https://github.com/bisq-network/bisq/releases/tag/v0.9.3

- Updated Linux packaging process so that it is capable of performing the complete packaging
process. This will allow anyone running Linux to easily generate their own Bisq installer if they so choose, rather than downloading it.
PR: https://github.com/bisq-network/bisq/pull/2190
Included in v0.9.3: https://github.com/bisq-network/bisq/releases/tag/v0.9.3

- Testing the DAO (exploratory style). Refer to issues discovered/entered:
https://github.com/bisq-network/bisq/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Adevinbileck+created%3A2019-01-01..2019-01-31

- Updated dao setup doc with instructions for Windows users. This is targeted towards developers/testers testing the DAO on regtest.
https://github.com/bisq-network/bisq/pull/2271

- Misc bug fixes and improvements.
https://github.com/bisq-network/bisq/pull/2314
https://github.com/bisq-network/bisq/pull/2313
https://github.com/bisq-network/bisq/pull/2277
https://github.com/bisq-network/bisq/pull/2264
https://github.com/bisq-network/bisq/pull/2248
https://github.com/bisq-network/bisq/pull/2247
https://github.com/bisq-network/bisq/pull/2211
https://github.com/bisq-network/bisq/pull/2165

## Contributions in progress

- Generate an RPM package as part of Linux packaging process. We can now provide an installation package for redhat-based Linux distributions which should help with adoption from more users.
PR: https://github.com/bisq-network/bisq/pull/2200
Although this has been merged to master, we do not have a release yet that includes an RPM package, so I am not requesting compensation for this until we do so I can properly gauge the value of this contribution.

- Added the ability to specify a remote regtest host using the bitcoinRegtestHost command line parameter, as well as supporting a tor connection to the regtest host. This allows for being able to simulate a somewhat realistic environment for testing purposes by deploying remote nodes/clients all communicating via tor (which has inherit delays) while still being able to take advantage of the benefits of testing in regtest mode (e.g. generating blocks on demand). This capability is targeted towards a very small audience (i.e. developers/testers), but it should allow for testing and debugging using an environment that more closely mimics the mainnet network.
https://github.com/bisq-network/bisq/pull/2312
https://github.com/bisq-network/bisq/pull/2346

- Continuing to test the DAO. More exploratory style testing.

- Investigating automating the deployment of a large scale regtest network with multiple remote nodes and clients for testing purposes.

- Scan files using VirusTotal as part of release process in order to ensure that they are not being flagged as false positives.
https://github.com/bisq-network/bisq/issues/2177

**Comment by ripcurlx** [comment]
Thanks for all your work and testing @devinbileck!

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
