### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#216]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**
## Roles performed
- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-459353230 (2600 BSQ)
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-459362187 (250 BSQ)
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-459357024 (150 BSQ)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
