### ISSUE TITLE
For January 2019

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#219]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `8150`
 - BSQ address: B1FGfKZQrpbLN9UNMogyJAVTR5PJNRkGPXJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**Documentation**
- DAO Introduction ([PR](https://github.com/bisq-network/bisq-docs/pull/96))
- DAO Getting Started ([PR](https://github.com/bisq-network/bisq-docs/pull/96))
- Backup/Recovery ([PR](https://github.com/bisq-network/bisq-docs/pull/95))
- Update old screenshots with new GUI ([PR](https://github.com/bisq-network/bisq-docs/pull/97))
- Modify rules for new assets + add new GitHub issue template ([PR](https://github.com/bisq-network/bisq-docs/pull/99) and [PR](https://github.com/bisq-network/bisq/pull/2320))

BSQ Requested: `5000`

**YouTube**
- Optimize YouTube profile for engagement: cleaned up and organized playlists, rearranged home page to feature best videos, and configured end screens for most-watched videos.

BSQ Requested: `500`

**Journalists**
- Corresponded with journalists throughout December and January for articles published in January: Bitcoin Magazine, Dash News, Cointelegraph.

BSQ Requested: `400`

**Website**
- Fixed minor bugs on the website ([PR](https://github.com/bisq-network/bisq-website/pull/116))

BSQ Requested: `150`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- Had been working on a web page for the DAO but the PR was not well-received. Lesson learned...I will seek feedback early for significant contributions that are not well-defined in advance.
- Speaking: just spoke at a local meetup today (Thursday night), and have conference speaking events scheduled next week (10 February) and next month (10 March).

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Twitter Admin: https://github.com/bisq-network/roles/issues/21#issuecomment-459628462 `2000`
Roles Admin: https://github.com/bisq-network/roles/issues/28#issuecomment-459628493 `25`
Docs Maintainer https://github.com/bisq-network/roles/issues/29#issuecomment-459628508 `25`
Slack Admin https://github.com/bisq-network/roles/issues/23#issuecomment-459628482 `25`
YouTube Admin https://github.com/bisq-network/roles/issues/56#issuecomment-459628534 `25`

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/204#issuecomment-460541588.
