### ISSUE TITLE
For December 2017

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#22]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 700
 - BSQ address: B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

Running of 3 Bitcoin Fullnodes. 
3 onion address 
3 clearnet address
3 VPS servers and one dedicated server.
See: https://github.com/bisq-network/roles/issues/39

Running one Pricenode and one Seednode server.
Paying for a $12 USD / Mounth bitcoinaverage.com Subscription (for the Pricenode)

Running the bisq-contrib mailinglist server

## Compensation calculation:

no Setup

Monthly costs nodes: 5* VPS (50 / node) -> 250
Monthly costs dedicated node 100
Monthly costs mailinglist server: 50
=400

Extra efforts caused by problems with seednode and bitcoin nodes.
=300

Total
=700

**Comment by ManfredKarrer** [comment]
Feel free to add the extra efforts caused in that month with trying to get the issues with the nodes stable. I think the 50 BSQ does not cover the real effort.

**Comment by Emzy** [comment]
OK. For the extra efforts caused in this month I would add en extra of 75% for all nodes.
=700

**Comment by cbeams** [comment]
This request has been entered into the [2017.12 tab](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=548599266) of the BSQ stake and voting spreadsheet and is ready to be voted on.

**Comment by csacher** [comment]
@Emzy the role spec is missing at: https://github.com/bisq-network/roles
Please follow "How to Create a New Role" (point 1 and 2 are already settled, follow 3,4,5).

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#26.
