### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by KanoczTomas** [bisq-network/compensation#221]
## Summary

 - BSQ requested: 4320
 - BSQ address:  B17TT6PsriwSLoKDnybE4LoDazkffQxtx3G

## Contributions delivered

 * created scripts to automate regtest setup for DAO local testing. The script is prompting the user for Alice's and Bob's address and creates the genesis TX for them, spins up a regtest bitcoind and mines blocks accordingly. There are scripts to spin up bitcoind, seed node, alice and bob. See https://github.com/bisq-network/bisq/pull/2405 - **requesting `563` BSQ**
* helped edit the source code for https://explorer.bisq.network/testnet/ to run on DAO testnet after bitcoin testnet became unusable - **requesting `25` BSQ**
* set up a block explorer for bisq DAO testnet chain reachable at http://bisq.info. Created an easy to deploy docker image for the dao with branding so it is not confused with other block explorer. Detailed documentation at: https://github.com/KanoczTomas/esplora/blob/dao-testnet/DAO.md - **requesting `3582` BSQ**
* hosting the DAO testnet block explorer at http://bisq.info - **requesting `50` BSQ**

## Contributions in progress
Notes for self:

* https://github.com/bisq-network/proposals/issues/73 - zeroMQ proposal - *check status*
* create new proposal for archiving see https://github.com/bisq-network/proposals/issues/72, we diverted from the topic, so I was asked to create a new proposal - *todo*
* create best practice for running a bitcoin full node with hardening guides - *todo*

## Roles performed

 * Support Maintainer: [bisq-network/roles#76 (comment)](https://github.com/bisq-network/roles/issues/76#issuecomment-468276156) - **requesting `50` BSQ**
  * Bitcoin Fullnode Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-468280097 - **requesting `50` BSQ**

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
