### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/compensation#223]
## Summary

 - BSQ requested: `3550`
 - BSQ address: `B1N7BFqBX2MUmbZ4KGNKujooPaWBxTyVx6H`

## Contributions delivered

My notable contributions include the following:

- **Generate RPM package as part of Linux packaging process.** We can now provide an installation package for RedHat-based Linux distributions which should help with adoption from more users.
PR: https://github.com/bisq-network/bisq/pull/2200
Our recent release (v0.9.4) was the first release to include an RPM package and it has been downloaded 42 times within the first week - as per http://www.somsubhra.com/github-release-stats/?username=bisq-network&repository=bisq.

- **Allow remote regtest host to be specified using bitcoinRegtestHost command line parameter**. Added the ability to specify a remote regtest host using the bitcoinRegtestHost command line parameter, as well as supporting a Tor connection to the regtest host. This allows for being able to simulate a somewhat realistic environment for testing purposes by deploying remote nodes/clients all communicating via Tor (which has inherit delays) while still being able to take advantage of the benefits of testing in regtest mode (e.g. generating blocks on demand). This capability is targeted towards a very small audience (i.e. developers/testers), but it should allow for testing and debugging using an environment that more closely mimics the mainnet network.
https://github.com/bisq-network/bisq/pull/2312
https://github.com/bisq-network/bisq/pull/2346

- **Add URL redirects to GitHub content**. See https://github.com/bisq-network/bisq/issues/2429 for more details.
https://github.com/bisq-network/bisq-website/pull/122
https://github.com/bisq-network/bisq/pull/2444

- **Testing (exploratory style).** Refer to issues discovered/entered:
https://github.com/bisq-network/bisq/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Adevinbileck+created%3A2019-02-01..2019-02-28

- **Misc bug fixes and improvements.** To desktop client, website, and docs:
https://github.com/bisq-network/bisq/pulls?q=is%3Apr+is%3Amerged+author%3Adevinbileck+updated%3A2019-02-01..2019-02-28
https://github.com/bisq-network/bisq-website/pulls?q=is%3Apr+is%3Amerged+author%3Adevinbileck+updated%3A2019-02-01..2019-02-28
https://github.com/bisq-network/bisq-docs/pulls?q=is%3Apr+is%3Amerged+author%3Adevinbileck+updated%3A2019-02-01..2019-02-28

- **Reviewed PRs:**
https://github.com/bisq-network/bisq/pull/2462
https://github.com/bisq-network/bisq/pull/2447
https://github.com/bisq-network/bisq/pull/2428
https://github.com/bisq-network/bisq/pull/2427
https://github.com/bisq-network/bisq/pull/2424
https://github.com/bisq-network/bisq/pull/2423
https://github.com/bisq-network/bisq/pull/2420

**BSQ amount requested:** `3500`

## Contributions in progress

- Creating tests in new testing tool https://bisq.ontestpad.com.

- Ongoing testing.

## Roles performed

- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-467195324 `(50 BSQ)`

**BSQ amount requested:** `50`

## Notes to self

<details>
  <summary>Details</summary>
My PR reviews this month were created by reviewing the results of this GitHub Issues search query:
https://github.com/bisq-network/bisq/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Adevinbileck+updated%3A2019-02-01..2019-02-28+sort%3Aupdated-desc
</details>

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
