### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#224]
## Summary

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested:`16180`
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**Reviews of PRs**
I monitor PR reviews separately from the responsibilities of the Bisq Desktop Maintainer role.

_Reviewed PRs:_
- https://github.com/bisq-network/bisq/pull/2436
- https://github.com/bisq-network/bisq/pull/2434
- https://github.com/bisq-network/bisq/pull/2455
- https://github.com/bisq-network/bisq/pull/2456
- https://github.com/bisq-network/bisq/pull/2428
- https://github.com/bisq-network/bisq/pull/2453
- https://github.com/bisq-network/bisq/pull/2431
- https://github.com/bisq-network/bisq/pull/2423
- https://github.com/bisq-network/bisq/pull/2426
- https://github.com/bisq-network/bisq/pull/2424
- https://github.com/bisq-network/bisq/pull/2403
- https://github.com/bisq-network/bisq/pull/2413
- https://github.com/bisq-network/bisq/pull/2405
- https://github.com/bisq-network/bisq/pull/2417
- https://github.com/bisq-network/bisq/pull/2376
- https://github.com/bisq-network/bisq/pull/2371
- https://github.com/bisq-network/bisq/pull/2377
- https://github.com/bisq-network/bisq/pull/2412
- https://github.com/bisq-network/bisq/pull/2409
- https://github.com/bisq-network/bisq/pull/2388
- https://github.com/bisq-network/bisq/pull/2379
- https://github.com/bisq-network/bisq/pull/2384
- https://github.com/bisq-network/bisq/pull/2198
- https://github.com/bisq-network/bisq/pull/2137
- https://github.com/bisq-network/bisq/pull/2368
- https://github.com/bisq-network/bisq/pull/2221
- https://github.com/bisq-network/bisq/pull/2345
- https://github.com/bisq-network/bisq/pull/2372
- https://github.com/bisq-network/bisq/pull/2348

**BSQ amount requested:** `2900`

I was working mainly on v0.9.4 this month and following PRs were merged and released. Testing and release efforts are part of the Desktop Maintainer role.

**PRs released in v0.9.4**
- https://github.com/bisq-network/bisq/pull/2237
- https://github.com/bisq-network/bisq/pull/2246
- https://github.com/bisq-network/bisq/pull/2265
- https://github.com/bisq-network/bisq/pull/2280
- https://github.com/bisq-network/bisq/pull/2283
- https://github.com/bisq-network/bisq/pull/2306
- https://github.com/bisq-network/bisq/pull/2310
- https://github.com/bisq-network/bisq/pull/2315
- https://github.com/bisq-network/bisq/pull/2316
- https://github.com/bisq-network/bisq/pull/2317
- https://github.com/bisq-network/bisq/pull/2318
- https://github.com/bisq-network/bisq/pull/2370
- https://github.com/bisq-network/bisq/pull/2372
- https://github.com/bisq-network/bisq/pull/2379
- https://github.com/bisq-network/bisq/pull/2384
- https://github.com/bisq-network/bisq/pull/2386
- https://github.com/bisq-network/bisq/pull/2388
- https://github.com/bisq-network/bisq/pull/2389
- https://github.com/bisq-network/bisq/pull/2394
- https://github.com/bisq-network/bisq/pull/2395
- https://github.com/bisq-network/bisq/pull/2409
- https://github.com/bisq-network/bisq/pull/2410
- https://github.com/bisq-network/bisq/pull/2411
- https://github.com/bisq-network/bisq/pull/2417
- https://github.com/bisq-network/bisq/pull/2419
- https://github.com/bisq-network/bisq/pull/2421
- https://github.com/bisq-network/bisq/pull/2435
- https://github.com/bisq-network/bisq/pull/2440
- https://github.com/bisq-network/bisq/pull/2442
- https://github.com/bisq-network/bisq/pull/2451
- https://github.com/bisq-network/bisq/pull/2453

**BSQ amount requested:** `6000`

Besides my work on the bisq repository I started to do some improvements on the website this month as well. As I'm going to watch the Google search console status of https://bisq.network more closely from now on, I'll continue to improve our page speed and the SEO optimization step by step for our DAO release on Mainnet. 

**PRs merged into website**
- https://github.com/bisq-network/bisq-website/pull/127
- https://github.com/bisq-network/bisq-website/pull/128
- https://github.com/bisq-network/bisq-website/pull/129
- https://github.com/bisq-network/bisq-website/pull/130
- https://github.com/bisq-network/bisq-website/pull/134

**BSQ amount requested:** `600`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I'm working on v0.9.5 which should be released some time in March.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

To make it more transparent and give people an idea how much effort which role means, I'll try to split up the overall number for each role.

- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63#issuecomment-467506115 `(4800 BSQ)`
- Growth: https://github.com/bisq-network/roles/issues/42#issuecomment-467824565 `(600 BSQ)`
- Analytics: https://github.com/bisq-network/roles/issues/40#issuecomment-467825119 `(600 BSQ)`
- Bitcoin Fullnode Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-467825995 `(50 BSQ)`
- Transifex Admin: https://github.com/bisq-network/roles/issues/20#issuecomment-467826738 `(25 BSQ)`
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31#issuecomment-467827184 `(580 BSQ)`
- Bisq Design Maintainer: https://github.com/bisq-network/roles/issues/75#issuecomment-467827338 `(25 BSQ)`

**BSQ amount requested for all these roles (see detailed amount for each role):** `6680`

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bisq Events Maintainer: https://github.com/bisq-network/roles/issues/65

## Notes to self
<details>

My PR reviews this month were created by reviewing the results of this GitHub Issues search query: 
[is:pr reviewed-by:ripcurlx updated:2019-02-01..2019-02-28 sort:updated-desc](https://github.com/bisq-network/bisq-desktop/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Aripcurlx+updated%3A2019-02-01..2019-02-28+sort%3Aupdated-desc+)

**Comment by KanoczTomas** [comment]
@ripcurlx could you please add the year as well to the issue? It will make the header unique.

**Comment by ripcurlx** [comment]
> @ripcurlx could you please add the year as well to the issue? It will make the header unique.

Sure - Yes, time flies 😄

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
