### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by freimair** [bisq-network/compensation#226]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 12400
 - BSQ address: B1JJUQWUHEoUwng4uGGWsT4hnTMc6dXtj9K

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- Monitor release **Settled** (via https://github.com/bisq-network/bisq/pull/2432)  (8500 BSQ)
  - see https://github.com/bisq-network/proposals/issues/62 for a list of new features and or course the git log for all the fixes along the way
  - enjoy the [Readme](https://github.com/bisq-network/bisq/blob/fb5c9834e0e49ba2d4f697133f089c2a6e0718ae/monitor/README.md)
  - **Settled** is the last release for a while. Feast your eyes on the [live service](https://monitor.bisq.network)
  - thanks for the help in the Price Node monitoring approach, @HarryMacfinned
  - all in all, I believe that we can finally close https://github.com/bisq-network/bisq/issues/1361
- fixed https://github.com/bisq-network/bisq/issues/599 via https://github.com/bisq-network/bisq/pull/2475
Although I am not completely sure that every little issue leading to https://github.com/bisq-network/bisq/issues/599 is resolved, I am quite sure I managed to find and resolve the biggest one. Therefore I am going to claim the bounty. Following @ManfredKarrer:  "[7:12 PM] propably one of the most valuable lines in the code base" I am going to request a bounty of 1500 BSQ considering that the bounty has been out for almost 1,5 years. also closes bisq-network/bisq#2258
- drafted a proposal for an upcoming testing framework decision https://github.com/bisq-network/proposals/issues/74 (600 BSQ)
- refactoring https://github.com/bisq-network/bisq/pull/2464 and https://github.com/bisq-network/bisq/pull/2476 (800 BSQ)
- took over two seednodes from @ManfredKarrer. Took some time setting the servers up and the servers are 5$ a month. (600 BSQ)
- update Arch user repo packages [here](https://aur.archlinux.org/packages/bisq) and [here](https://aur.archlinux.org/packages/bisq-bin) (50 BSQ)
- reviewed a couple of pull requests (350 BSQ)
  - https://github.com/bisq-network/bisq/pull/2344
  - https://github.com/bisq-network/bisq/pull/2399
  - https://github.com/bisq-network/bisq/pull/2403
  - https://github.com/bisq-network/bisq/pull/2470

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- ongoing massive refactoring https://github.com/bisq-network/bisq/pull/2469
- get a DAO_TESTNET monitoring up and running (currently waiting for in put on what is to be monitored...)
- all the things tor and netlayer
  - https://github.com/bisq-network/bisq/issues/1299
  - https://github.com/bisq-network/bisq/issues/1943
  - https://github.com/bisq-network/bisq/issues/2396
  - https://github.com/bisq-network/bisq/issues/2398
  - https://bisq.community/t/stuck-on-3-4-hidden-service-published-v9-3/6908/23
  - https://github.com/bisq-network/bisq/issues/2465
  - https://github.com/bisq-network/bisq/issues/2472
  - https://github.com/bisq-network/bisq/issues/2474 (https://github.com/bisq-network/bisq/issues/2327)
  - update tor binaries
  - add features to netlayer

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- [Arch Linux AUR Maintainer](https://github.com/bisq-network/roles/issues/78#issuecomment-468289035)
- definitely taking over the [Seed Node Operator](https://github.com/bisq-network/roles/issues/15) role
- most probably taking over the [Seed Node Maintainer](https://github.com/bisq-network/roles/issues/6) role as suggested by https://github.com/bisq-network/roles/issues/6#issuecomment-468139978
- it seems that I am also owner of the [Monitoring Operator/Maintainer](https://github.com/bisq-network/roles/issues/10) role as suggested by https://github.com/bisq-network/roles/issues/10#issuecomment-468140719

**Comment by m52go** [comment]
Hello @freimair would you mind making a corresponding compensation request in the testnet Bisq DAO, if you haven't already? Would really help us with testing this round.

The proposal phase for this round ends sometime tonight.

https://docs.bisq.network/getting-started-dao.html

**Comment by freimair** [comment]
@m52go oh my, totally forgot about that. Damn work-live-balance stuff. Next time, for sure!

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
