### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#228]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `5230`
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

### Development
This is a collection of DAO code review and improvement over the last three months, some of which has been more on the general safety of BSQ parsing and some more specific.
https://github.com/bisq-network/bisq/pull/2171
https://github.com/bisq-network/bitcoinj/pull/18
https://github.com/bisq-network/bisq/pull/2242
https://github.com/bisq-network/bisq/pull/2244
https://github.com/bisq-network/bisq/pull/2366
https://github.com/ManfredKarrer/bisq/pull/2
**BSQ requested** `3900`

### Reviews
https://github.com/bisq-network/bisq/pull/2336
https://github.com/bisq-network/bisq/pull/2360
https://github.com/bisq-network/bisq/pull/2361
https://github.com/bisq-network/bisq/pull/2363
https://github.com/bisq-network/bisq/pull/2357
https://github.com/bisq-network/bisq/pull/2355
https://github.com/bisq-network/bisq/pull/2365
https://github.com/bisq-network/bisq/pull/2371
https://github.com/bisq-network/bisq/pull/2377
https://github.com/bisq-network/bisq/pull/2379
https://github.com/bisq-network/bisq/pull/2384
https://github.com/bisq-network/bisq/pull/2386
https://github.com/bisq-network/bisq/pull/2388
https://github.com/bisq-network/bisq/pull/2394
**BSQ requested** `1100`

### DAO explorer
Running a server at explorer.sqrrm.net
**BSQ requested** `40`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I currently can't do much work, hope to be back soon

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._
> __

Bitcoin node maintainer - https://github.com/bisq-network/roles/issues/66#issuecomment-468215956 `50`
Bitcoin node operator - https://github.com/bisq-network/roles/issues/67#issuecomment-468216327 `100`
Tor relay operator - https://github.com/bisq-network/roles/issues/72#issuecomment-468216909 `40`

**BSQ requested** `190`

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
