### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by eyalron33** [bisq-network/compensation#229]
## Basic information

 - BSQ requested: 1400
 - BSQ address: B1PU7DoYDHWi2impz86Fvu3ZgsREaBnGJBW

## Contributions delivered
- Gave a lecture [The DAO of Bisq](https://fosdem.org/2019/schedule/event/the_dao_of_bisq/) in Fosdem 2019. I paid from my own pocket for traveling and accommodation in this event.

Requested: 300 BSQ

- Gave a lecture The DAO of Bisq in [Amsterdam Bitcoin Wednesday workshop](https://www.bitcoinwednesday.com/speakers/eyal-ron-core-developer-bitsquare-dao/). I paid from my own pocket for traveling and accommodation in this event.

Requested: 300 BSQ

## Contributions in progress

Writing specifications for [Mixed arbitrator/mediator trade protocol](https://docs.google.com/document/d/1fWN9uvcPltQurqQQ2Xg-NgPaGhtaRGYtCTL-163cugY/). The document is in revision state.

Requested: 800 BSQ

**Comment by ManfredKarrer** [comment]
Are you shure 1400 BSQW covers your efforts? I felt it was more...

**Comment by arunasurya** [comment]
@eyalron33, I would agree with @ManfredKarrer, considering that your presentation was fantastic and substantial, how many people you have reached, preparation, travel time, etc...

**Comment by eyalron33** [comment]
Thank you both for this though:-)

It's too late to change now, but I'll consider "adjusting" the presentations costs in next month request.

**Comment by m52go** [comment]
Hi @eyalron33, would you mind making a corresponding compensation request in the testnet Bisq DAO, if you haven't already? Would really help us with testing this round.

The proposal phase for this round ends sometime tonight.

https://docs.bisq.network/getting-started-dao.html

**Comment by eyalron33** [comment]
@m52go Done.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
