### ISSUE TITLE
For December 2017 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#23]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: **15900**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value. **Please include only completed work!**_

### Development work:
- Work on Bisq DAO [1]
- Release 0.6.2 [2]
- Monitor for seed nodes and Bitcoin nodes [3]
- Investigate issues with network instability
- Investigate issues with failed trade transactions
- Manage distribution of nodes infrastructure
- Setup of 2 new seed nodes, 3 Bitcoin nodes, 1 new relay node (6 * 200 BSQ for setup of new nodes)
- Maintain 6 seed nodes, 3 Bitcoin nodes, 3 relay nodes, market server and BSQ explorer (14 * 50 BSQ)

See complete Github activity at: https://github.com/ManfredKarrer

[1] https://github.com/bisq-network/exchange/tree/dao
[2] https://github.com/bisq-network/exchange/releases/tag/v0.6.2
[3] http://seedmonitor.0-2-1.net:8080/

### Other:
- Communication with contributors and node operators
- Attend CCC conference in Leipzig

**Comment by cbeams** [comment]
This request has been entered into the [2017.12 tab](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=548599266) of the BSQ stake and voting spreadsheet and is ready to be voted on.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#26.
