### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#230]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**
## Roles performed
- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-468261912 (2600 BSQ)
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-468266962 (250 BSQ)
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-468258437 (150 BSQ)

**Comment by m52go** [comment]
Hello @alexej996 would you mind making a corresponding compensation request in the testnet Bisq DAO, if you haven't already? Would really help us with testing this round.

The proposal phase for this round ends sometime tonight.

https://docs.bisq.network/getting-started-dao.html

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
