### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by xiphon** [bisq-network/compensation#231]
## Summary

 - BSQ requested: 100
 - BSQ address: B1EnBmUPBggfHogLy3DidFob1vvd2YfB4Yb

## Contributions delivered

 - Implemented Monero and Cryptonote address validator https://github.com/bisq-network/bisq/pull/2422

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
