### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/compensation#232]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `2900`
 - BSQ address: B19yxYCRTVaDfRfucrH6aEzeZpoVTv8Je8S

This compensation request :
- follows the https://docs.bisq.network/roles.html#compensation recommandations
- applies the 1BSQ=1USD rule

### Substantive reports

- Support | https://github.com/bisq-network/roles/issues/64#issuecomment-468344806 | (BSQ requested = 2500)
Evaluation is based and intended in line with : previous compensation requests, and other support compensation requests.
The time needed actually to assume the support role increased (significantly) compared to july 2018.
As anticipated in january compensation request, I have hence updated my request (from 2000 to 2500). [Activity numbers (trades) : 2018Q3/2700 trades, 2018Q4/6800 trades, 2019Q1/4000 trades].

- Fees and connectivity monitoring | see the weekly reports in https://github.com/bisq-network/roles/issues/10 | (BSQ requested = 200)
Concerned monitored data files : https://github.com/HarryMacfinned/bisq-monitor
TL;DR: there was zero catch this month (nodes are running well).

- Prices monitoring | https://github.com/bisq-network/roles/issues/10#issuecomment-468364440 | (BSQ requested = 200)
TL;DR: There were no noticeable divergences between pricenodes this month.
(18 strictly punctual alerts, ie false alarms)

## Other points (BSQ requested = 0)
- Clearnet Bisq webpages monitoring : some alerts this month, only on back-office, reported in the #bisq-monitor channel
- approved proposal https://github.com/bisq-network/proposals/issues/71 (update Bisq's fiat trade limits)
- participation in DAO testing
- participation in evaluating https://github.com/bisq-network/bisq/issues/568 (snap package)

## Contributions in progress
Per @freimair request related to his work on monitoring :
- I uploaded the exchange fee history online. It's actually available here :  https://github.com/HarryMacfinned/bisq-monitor
I can upload it on a more official place if wanted. (BSQ requested = 0, since it's already paid job)
- also, I transmitted the python code I wrote for monitoring for reuse in
https://github.com/freimair/bisq/blob/monitor/monitor/src/main/java/bisq/monitor/metric/PriceNodeStats.java
I intent to upload this code as a first official version next month.
I wrote v0.0.1 of this code in july 2018 and continuously improve it since.
I will fill a compensation request for this code when I officially upload it.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
