### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#233]
## Summary

 - BSQ requested: 1000
 - BSQ address: B1PFD3uscJqFQfLNAS6bWQtr1PUahrWNvC7

### Blog post initiative: 600BSQ
 - Coordinated the blog post initiative: recruiting writers, reviews/edits, setting up a smooth blog writing process, keeping the Bisq community informed, etc.
- Worked closely with @m52go on reviews/edits, publication and other processes.

### A blog post: 400BSQ
 - Published a blog post on Medium: https://medium.com/bisq-network/an-overview-of-the-bisq-network-d66e1fdea21b

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
