### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#234]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `9450`
 - BSQ address: B1FGfKZQrpbLN9UNMogyJAVTR5PJNRkGPXJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**Video**
- Bisq DAO in Brief ([link](https://www.youtube.com/playlist?list=PLFH5SztL5cYPAXWFz-IMB4dBZ0MEZEG_e))
  - Comprehensive but _concise_ 7-part video series covering:
    - the why, what, and how of the Bisq DAO
    - walk-through of BSQ issuance
    - practical takeaways for traders and contributors
    - a technical overview
  - Final product is result of planning structure of series, writing (scripting for maximum impact + naturalness), designing (producing graphics, etc), video recording, and video editing.
  - Longest video is 6 minutes; most are between 3-5 minutes. As with writing, shorter is harder and vastly more time-consuming, but it's also vastly more effective.

BSQ Requested: `4900`

**Website**
- DAO landing page ([pull request](https://github.com/bisq-network/bisq-website/pull/121))
  - Propose, edit, and refine final site copy (along with others; was collaborative effort) ([issue](https://github.com/bisq-network/growth/issues/99)); also handle launch (e.g., [bugs](https://github.com/bisq-network/bisq-website/pull/126))

BSQ Requested: `800`

**Blog**
- Bisq DAO for Maximalists ([link](https://github.com/bisq-network/bisq-website/pull/118))
  - Early indications are that it's highly effective for [those who bother reading it](https://twitter.com/Coinosphere/status/1100969078343254016).

BSQ Requested: `500`

**Documentation**
- Add doc for compensation requests and voting ([pull request](https://github.com/bisq-network/bisq-docs/pull/104))
- Add doc to collect all DAO resources ([pull request](https://github.com/bisq-network/bisq-docs/pull/107))
- Add 'quick links' buttons to help users find high-priority docs quicker ([pull request](https://github.com/bisq-network/bisq-docs/pull/108) and [pull request](https://github.com/bisq-network/bisq-docs/pull/111))

BSQ Requested: `1200`

**Events**
- TABConf Atlanta (8-10 February) ([link](https://tabconf.com/))
  - Just requesting travel expenses.
  - [Organizers](https://www.youtube.com/channel/UCBwksHClcQDU7j9HVnYD7zg/videos) still haven't posted video...

BSQ Requested: `450`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Write more and record more. People have already started talking, and we need to lead the narrative.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Twitter Admin: https://github.com/bisq-network/roles/issues/21#issuecomment-468477806 `1500`
Roles Admin: https://github.com/bisq-network/roles/issues/28#issuecomment-468477742 `25`
Docs Maintainer https://github.com/bisq-network/roles/issues/29#issuecomment-468477767 `25`
Slack Admin https://github.com/bisq-network/roles/issues/23#issuecomment-468477786 `25`
YouTube Admin https://github.com/bisq-network/roles/issues/56#issuecomment-468477723 `25`

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/222#issuecomment-470107704.
