### ISSUE TITLE
For February 2019

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/compensation#235]
## Summary

 - BSQ requested: 5000
 - BSQ address: B18BA37KaiSHLMhyjs7FMPAJMfcVcVzJPCm

## Contributions delivered

**DAO webpage design**
BSQ Requested: 2000

**DAO webpage implementation**
BSQ Requested: 1000

**DAO descriptive illustrations and diagrams**
BSQ Requested: 1500

**Client DAO screen**
BSQ Requested: 500

![bisq-dao-page_design](https://user-images.githubusercontent.com/807505/53685990-e21e5600-3cef-11e9-864f-1bb8e2429eed.png)

![bisq-dao-page_screencapture](https://user-images.githubusercontent.com/807505/53685991-e21e5600-3cef-11e9-9505-b849ca17c0c5.png)

![dao_benefits](https://user-images.githubusercontent.com/807505/53685992-e21e5600-3cef-11e9-94dd-e2aa00a7ea30.png)

![dao_how](https://user-images.githubusercontent.com/807505/53685993-e21e5600-3cef-11e9-95ff-520b3d6ad761.png)

![dao_intro](https://user-images.githubusercontent.com/807505/53685994-e21e5600-3cef-11e9-8285-2e11df233064.png)

![dao_what](https://user-images.githubusercontent.com/807505/53685996-e2b6ec80-3cef-11e9-8e3c-187c7697ec87.png)

![dao_why](https://user-images.githubusercontent.com/807505/53685997-e2b6ec80-3cef-11e9-88e9-33be4590ebba.png)

![screen shot 2019-03-02 at 1 31 00 pm](https://user-images.githubusercontent.com/807505/53686001-ef3b4500-3cef-11e9-8fbd-28715bcd45a5.png)

**Comment by ManfredKarrer** [comment]
I fear that request came too late. But no worry just add it again for March.

**Comment by ripcurlx** [comment]
@pedromvpg Yes, unfortunately your compensation request was filed too late for this month's voting round. Feel free to re-submit it next month.

**Comment by pedromvpg** [comment]
Created a new one for march
https://github.com/bisq-network/compensation/issues/258

Can we close this one?
