### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by freimair** [bisq-network/compensation#236]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 14200
 - BSQ address: B1JJUQWUHEoUwng4uGGWsT4hnTMc6dXtj9K

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- as I encountered the openjdk with Wayland coredumps now during development I finally had a reproducible testing source and found a solution: closes https://github.com/bisq-network/bisq/issues/2279 (300 BSQ)
- Netlayer, jtorctl, tor-binary via https://github.com/bisq-network/bisq/pull/2499, https://github.com/bisq-network/bisq/pull/2508 (2200 BSQ)
  - [tor](https://github.com/JesusMcCloud/tor-binary/releases/tag/8.0.6) got updated to [0.3.5.7](https://blog.torproject.org/new-releases-tor-0357-03410-and-03311) (included in tor browser 8.0.5 and 8.0.6)
  - [jtorctl](https://github.com/JesusMcCloud/jtorctl/releases/tag/1.3) now does report errors instead of discarding them
  - [netlayer](https://github.com/JesusMcCloud/netlayer/releases/tag/0.6.4b2) received some refactoring
    - netlayer allows attaching a readyListener even when no java socket is attached
    - a take on solving some windows issues where tor cannot be started because it is still running
- seed node optimizations (https://github.com/bisq-network/bisq/pull/2501) (3300 BSQ)
  - streamline the memory footprint of DoS countermeasure
  - get rid of the `--myAddress` command line parameter only quite used by seed nodes
  - issue a fresh UpdateDataRequest periodically
- monitor fixes, tweaks and a [new metric](https://monitor.bisq.network/d/SzHBCGjmz/playground?orgId=1) via https://github.com/bisq-network/bisq/pull/2507 (1600 BSQ)
- massive refactoring https://github.com/bisq-network/bisq/pull/2469 and https://github.com/bisq-network/bisq/pull/2476 and https://github.com/bisq-network/bisq/pull/2552 (5400 BSQ)
- another update of Netlayer and tor-binary via https://github.com/bisq-network/bisq/pull/2581
  - [tor](https://github.com/JesusMcCloud/tor-binary/releases/tag/8.0.8) got updated to [0.3.5.8](https://blog.torproject.org/new-releases-tor-0402-alpha-0358-03411-and-03312) (included in tor browser 8.0.7 and 8.0.8) (300 BSQ)
  - [netlayer](https://github.com/JesusMcCloud/netlayer/releases/tag/0.6.5) received a longer cookie timeout as indicated by (https://github.com/bisq-network/bisq/issues/2398 and probably https://github.com/bisq-network/bisq/issues/2574)
- reviewed PRs (300 BSQ)
  - https://github.com/bisq-network/bisq/pull/2583
  - https://github.com/bisq-network/bisq/pull/2538
  - https://github.com/bisq-network/bisq/pull/2523
  - https://github.com/bisq-network/bisq/pull/2494
  - https://github.com/bisq-network/bisq/pull/2470

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- DAO monitoring

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- [Arch Linux AUR maintainer](https://github.com/bisq-network/roles/issues/78#issuecomment-469010385) (50 BSQ)
- [Netlayer Maintainer](https://github.com/bisq-network/roles/issues/81#issuecomment-478328739) (50 BSQ)
- [Seednode Maintainer](https://github.com/bisq-network/roles/issues/6#issuecomment-478328923) (150 BSQ)
- [Seednode Operator](https://github.com/bisq-network/roles/issues/15#issuecomment-478328977) (100 BSQ)
- [Monitoring Operator/Maintainer](https://github.com/bisq-network/roles/issues/10#issuecomment-478329321) (450 BSQ)

**Comment by devinbileck** [comment]
I noticed https://github.com/bisq-network/bisq/pull/2501 is not yet merged. So should not be considered delivered yet.
As seednode operator, you have 2 seednodes? Typically 50 BSQ is requested per node. So should it be 100 not 150? But based on your total requested, I believe you calculated it as 100 so maybe that was just a typo?

**Comment by freimair** [comment]
Ah damn, that one is indeed not merged. Well, hm. @ripcurlx I guess there is not much we can do now can we?

ad Seednode Operator: yes, typo.

**Comment by ripcurlx** [comment]
> Ah damn, that one is indeed not merged. Well, hm. @ripcurlx I guess there is not much we can do now can we? I guess then every additional change required to get that one into master is free of charge (at least if I get that one granted)...
> 
> ad Seednode Operator: yes, typo.

As everything is already copied over to the spreadsheet for voting, I can't update the amount anymore. If your CR gets accepted, please try to get your PR merged to master as soon as possible after the DAO launch.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
