### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by KanoczTomas** [bisq-network/compensation#237]
## Summary

 - BSQ requested: 2825
 - BSQ address:  B17TT6PsriwSLoKDnybE4LoDazkffQxtx3G

## Contributions delivered

 * created an issue template as I had to ask for aditional details from people requesting reimbursement. The template gathers bisq version as well. The template worked fine as I did not have to ask for additional info anymore, making processing on my side easier and quicker -  https://github.com/bisq-network/support/commit/401b87c145089f0b647b04c0c2c27f82a5bcb2f5 - **requesting `400` BSQ**
* wrote a blog post (first in the series) about setting up a regtest environment - https://bisq.network/blog/how-to-set-up-bitcoin-regtest/  **requeting `200` BSQ** - big thanks for @arunasurya and @m52go for rewievs
* hosting the DAO testnet block explorer at http://bisq.info - **requesting `50` BSQ**
* participating in testing the DAO on Bisq testnet - **requesting `1500` BSQ**

## Contributions in progress

Notes for self:

* https://github.com/bisq-network/proposals/issues/73 - zeroMQ proposal - *check status*
* create new proposal for archiving see https://github.com/bisq-network/proposals/issues/72, we diverted from the topic, so I was asked to create a new proposal - *todo*
* create best practice for running a bitcoin full node with hardening guides - *todo*
* after DAO: https://github.com/bisq-network/proposals/issues/54
* after DAO: extend esplora to understand BSQ tokens and make it the new explorer https://github.com/bisq-network/roles/issues/11#issuecomment-477141474

## Roles performed

 * Support Maintainer: https://github.com/bisq-network/roles/issues/76#issuecomment-478371976 - **requesting `600` BSQ**
  * Bitcoin Fullnode Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-478372193 - **requesting `50` BSQ**
 * Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66#issuecomment-478373267 **requesting `25` BSQ**

**Comment by KanoczTomas** [comment]
@ripcurlx please note values were altered for the blogpost on my side. I made a mistake of relatively comparing the post with other requests, when did a reseach about how much they pay on the market it was way over shot :) Please update it in the spreadsheet. The amounts especially in the support part are reflecting the feedback I did ask too litle in the past for that work. This was captured in a comment under support maintainer role as well, I want to highlight it here. So there is no false impression that the amount seen here is overshot.

Of course I hope if anyone has a rightful feeling of prices being too high, please by all means vote against the proposal. And leave feedback. We have to learn how to use this powerful control mechanism. There were not many votes against in the past according to the spreadsheet, we need to learn how to do that :)

**Comment by devinbileck** [comment]
Regarding **_participating in testing the DAO on Bisq testnet_**, do you have any additional details such as a report detailing the test coverage or the issues you encountered/entered.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
