### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by michaltakac** [bisq-network/compensation#238]
## Summary

>_Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

- BSQ requested: 20
- BSQ address: B18x61QoqJetyBs4eGNtKr4D5aAdwref2o6

## Contributions delivered

>_Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Participated in quick survey about my experience with the bisq dao (on testnet).

**Comment by ripcurlx** [comment]
@michaltakac Could you please share your feedback here as well, as I guess there is no link available that documents your testing efforts and survey input?

**Comment by m52go** [comment]
I chatted directly with @michaltakac on Slack before and after he submitted feedback. I know it's not customary to acknowledge work without some kind of proof, but I think it is reasonable in this case.

**Comment by ripcurlx** [comment]
> I chatted directly with @michaltakac on Slack before and after he submitted feedback. I know it's not customary to acknowledge work without some kind of proof, but I think it is reasonable in this case.

Works for me this time, but I do think it's important to be as transparent as possible in CRs, otherwise they won't be voted for in future voting rounds.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
