### ISSUE TITLE
For March - testing 0.9.5

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/compensation#239]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 20
 - BSQ address: B1LpTRDi1tLqX74u23F5ZdnjXV7bhxwaxX8

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

helped testing the DAO voting mechanism and answered a survey

**Comment by ripcurlx** [comment]
@FKrauss Could you please share your feedback here as well, as I guess there is no link available that documents your testing efforts and survey input?

**Comment by m52go** [comment]
I chatted directly with @FKrauss on Slack before and after he submitted feedback. I know it's not customary to acknowledge work without some kind of proof, but I think it is reasonable in this case.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
