### ISSUE TITLE
For December 2017

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#24]
## Basic information

 - BSQ amount requested: **2000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**

### Forum operator:
- Setup of the forum, including redirecting from the old domain over HTTP and HTTPS
- Maintaining the forum, including backups, updates and responding to forum outages
(forum operator https://github.com/bisq-network/roles/issues/19)

### Support:
- Providing support for users on forum, reddit, bitcointalk, Slack (chat-bridge channel)
(forum profile https://bisq.community/u/alexej996/summary)

### Moderation:
- Moderating Bisq forum and subreddit (reddit moderator https://github.com/bisq-network/roles/issues/25)

**Comment by alexej996** [comment]
PS: I quite obviously made up the BSQ amount for this compensation request, I had no idea what to put.
Initially I was just going to make the request for being a forum operator as I do the support work completely on a voluntary basis, but Manfred has been really supportive and encouraging about it that I added it.

**Comment by ManfredKarrer** [comment]
@alexej996 You are doing a fantastic job and I am sure you spend quite a lot of time for answering to so many questions and threads. I would suggest you to add up roughly the hours and multiply it with an hourly rate for such activity. Sure both is difficult as well but you should get compensated like in a professional work relationship not based on altruism.

**Comment by cbeams** [comment]
Yeah, I think the way we have to estimate compensation—in all cases, really—is what is it worth to _Bisq_ to have this work getting done? What is the value to the Bisq network and all its users and contributors that people who ask questions on the Bisq forum get a timely, friendly and well-informed response?

I'd say that's worth at least 2000 BSQ per month. Or, to put it another way, I certainly wouldn't want to be spending _less_ than 2000 BSQ per month making sure that this is happening.

And that's just the _moderation_ work you're doing. When you add in _operating_ and _administering_ the forum as well—these are all at least potentially separate roles that you are playing, @alexej996, I think it's worth more than 2,000 BSQ.

So I think it's fine to try to land on a number by adding up your hours and multiplying it by your hourly rate like @ManfredKarrer suggests, but the final test should be to ask whether that amount is what the services you provide are _worth_ to the Bisq DAO.

I don't know precisely what that worth is better than anyone else here, but I'm confident that if we all think this way about the problems, and improve on this kind of thinking as we go, that we'll discover the right values for compensation over time.

**Comment by alexej996** [comment]
Thank you for your thoughts on this. I will consider this for the next month's comp. request. :+1:

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#26.
