### ISSUE TITLE
For March 2019 - Translation RU/Localization

### ISSUE THREAD

**Issue by y3v63n** [bisq-network/compensation#240]
## Summary

 - BSQ requested: 305
 - BSQ address: B17jdeefV4g5PuL4CgisJeR32JAbAF7ztfD

## Contributions delivered

Requested (105 BSQ):
1,503 words translated into Russian (at the rate of 0.07USD). 

Requested (200 BSQ):
Helped @arunasurya with identifying localization workflows and processes, suggested glossary and style guide creation for each language and provided template for them. Helped to extract high-frequency terms from the current source strings and add them to the glossary. Time spent: 10 hours.

## Contributions in progress

- Translation of new strings into Russian.
- Review of previous translations.
- Helping address translation questions on #Transifex channel in Slack.
- Creation of RU Style Guide for Bisq that can be used as a template for other languages.

**Comment by arunasurya** [comment]
Thank you for all your contributions this month, @y3v63n! I look forward to continuing working with you!

**Comment by devinbileck** [comment]
Just curious, is it possible to provide links or a report of translations contributed? And any record of discussions regarding your second contribution?
Otherwise without that information, the majority of stake holders will be unable to make an informed vote and will (should) either defer or reject it.

**Comment by y3v63n** [comment]
> Just curious, is it possible to provide links or a report of translations contributed? And any record of discussions regarding your second contribution?
> Otherwise without that information, the majority of stake holders will be unable to make an informed vote and will (should) either defer or reject it.

I checked several recent compensation requests for translation jobs and none of them contained any reports, so that was the reason I didn't provide any either.

Anyone with Transifex account can verify the word counts I indicated above here: https://www.transifex.com/bisq/bisq-desktop/translate/#ru/displaystringsproperties/166392802?q=translator%3Ay3v63n+translated_after%3A2019-03-01

Not sure if our current Transifex subscription allows this but if so, someone with admin rights should also be able  to generate monthly word count reports for all languages.

Regarding the second contribution, the list of terms suggested by me can be found here: https://docs.google.com/spreadsheets/d/102l37lcmLn7FZmbZ8F9PJF376iHv8hN7ucTYPoqoIZo/edit#gid=0

I'm also in discussion with @arunasurya on a daily basis in Slack via DMs and in the #Transifex channel.

Hope this helps.

**Comment by devinbileck** [comment]
Thanks @y3v63n , that helps!
Sorry, I wasn't trying to single you out. I like to evaluate and make an informed vote on as many proposals that I can, which requires sufficient details within the proposal.
That link to transifex should be sufficient to evaluate your contribution.

**Comment by huey735** [comment]
@y3v63n you can get your statistics on Transifex by going to the Bisq Dashboard and on the top right of the graph you can select "all" or "mine". Selecting mine, it'll show only your contributions. That's where I got my numbers.

**Comment by y3v63n** [comment]
@huey735 Thanks! For some reason, word counts in the dashboard are slightly higher than those when I use filters.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
