### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by huey735** [bisq-network/compensation#241]
## Summary

 - BSQ requested: 740
 - BSQ address: B1NBcexfGapodHZzFyoeTzJnqqdSkZbNVQQ

## Contributions delivered
**Request: 20 BSQ**
Participated in quick survey about my experience with the bisq dao (on the testnet).
This value was suggested by the bounty.

**Request: 280 BSQ**
Translated the "Bisq DAO in Brief" playlist created by @m52go to Portuguese
https://www.youtube.com/playlist?list=PLFH5SztL5cYPAXWFz-IMB4dBZ0MEZEG_e
Time spent: at a rhythm of 15min/min of audio it averaged to around 7hrs
I initially calculated it at 10 BSQ/hr which gave me 70 BSQ, but from the suggestion of others I'll raise it to 280 BSQ.

**Request: 440 BSQ**
Translation and review of Bisq software to Portuguese (pt)  - https://github.com/bisq-network/bisq/commit/8b2396e7e29e50a42321f7c9100f4540c63e2d15
Translation of Bisq software to Portuguese (Brazil) (pt_BR)
Word count:
12 765 Reviewed
12 640 Edited
9 280 Translated

I looked at previous compensation requests for similar work that were accepted for reference and found [this one](https://github.com/bisq-network/compensation/issues/192) by @BravoIndia.
So I decide to value each word at 0.02 BSQ. I separated the work into two groups:

- Translation - 9280 * 0.02 = 185.6 
- Edits and Reviews - (12 765 + 12 640) / 2 * 0.02 = 254.05
Total = 439.65

![transifex-translation-1903](https://user-images.githubusercontent.com/44140017/55291286-dbf5c500-53d4-11e9-8776-d5f070f3aa5f.png)

## Contributions in progress
Translation and review of Bisq software to Portuguese (pt)
Translation of Bisq software to Portuguese (Brazil) (pt_BR)

**Comment by ripcurlx** [comment]
@huey735 Could you please share your feedback here as well, as I guess there is no link available that documents your testing efforts and survey input?

**Comment by huey735** [comment]
Yeah I was wondering about that. Well, my feedback was focused on the UX/UI.
* During the Vote Phase, the button to actually vote was semi-hidden which caused me to not cast the vote. Admittedly, it was mostly due to my lack of attention.
* I didn't fully understand what to do on the Vote Reveal Phase from its description. However, I think it was more me complicating things rather than the text being ambiguous. I didn't really have to do anything other than launch the Bisq client so that the network could "see" my vote.

The first issue is more critical because one isn't aware that they've left the program without casting the vote. And voters mistakes are something to be weary of. The second is trivial because even in case of doubt just by virtue of being online during the Vote Reveal Phase the software would still execute what was intended.

Fortunately, I was able to correct this and properly vote on the second round.

**Comment by m52go** [comment]
@huey735 your request of 70 BSQ for translating the _whole series_ seems very low to me.

**Comment by huey735** [comment]
I guess. I figured 10 BSQ/hr of work would suffice. I wouldn't know any other way to measure its worth to be honest. I'll look at other contributors providing similar work in the future for reference.

**Comment by m52go** [comment]
It's not too late to change your request.

Freelance pricing is notoriously hard. Better to charge for the value of the project to Bisq, instead of hourly, relative to other contributions, I think. The production of these videos was accepted at 4900 BSQ, and your translations will make them available to a whole new _relevant_ market. We've been getting lots of interest from Brazil lately. That's why I was so interested in you doing the translation in the first place. An offer to translate to Korean, for example, wouldn't have been so interesting.

Based on this, I would easily accept something 5-6x your request. That's just my opinion.

But I see your confusion. There was no way for you to know all this ahead of time. We need to figure out how to communicate this stuff beforehand.

**Comment by huey735** [comment]
@ripcurlx I took advantage of the vote delay to make some edits to my request and include the translation work you merged to the Bisq software.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.

**Comment by ManfredKarrer** [comment]
@huey735 
Please send me in slacl or the forum a btc address for refunding you for the donation for the dao genesis tx: see https://bisq.community/t/refund-bsq-genesis-donations/7776
