### ISSUE TITLE
For March 2019 - Blogpost

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/compensation#242]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 420
 - BSQ address: B1BUqX5aYPyXMzCfGNX6UjTyNQd1t6qpyRK

## Blogpost: 400 BSQ

Completed a blog titled "How to Earn BSQ by Contributing to Bisq" which was published on Bisq's medium blog.

https://bisq.network/blog/how-to-earn-bsq/

## Feedback Survey: 20 BSQ
Provided feedback via a survey about testing the Bisq DAO

## Contributions in progress

> New blog post scheduled for April 1st publication titled "How to Submit a Compensation Request to Bisq and What to Expect"

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by arunasurya** [comment]
Great job! Looking forward to your future posts!

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
