### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/compensation#244]
## Summary

 - BSQ requested: `6550`
 - BSQ address: `B1N7BFqBX2MUmbZ4KGNKujooPaWBxTyVx6H`

## Contributions delivered

- **Testing (exploratory style).** Primarily focused on DAO related functionality. I mainly encountered/entered UI issues or improvements, but did uncover a more serious issue when submitting proposals with manipulated DAO parameters, leading to https://github.com/bisq-network/bisq/pull/2587. [`3000 BSQ`]

  - [Show BTC amount required for issuance in compensation/reimbursement request confirmation prompt](https://github.com/bisq-network/bisq/issues/2594)
  - [Add visual indicator that a pending vote reveal transaction needs to be published in upcoming reveal phase](https://github.com/bisq-network/bisq/issues/2484)
  - [Remove salt for account age verification field when adding altcoin account](https://github.com/bisq-network/bisq/issues/2537)
  - [System tray icon on Linux does not use transparent background](https://github.com/bisq-network/bisq/issues/2572)
  - [Retain window size/location upon restarting application](https://github.com/bisq-network/bisq/issues/2580)
  - [Show the security deposit in the available offers view](https://github.com/bisq-network/bisq/issues/2586)
  - [UI improvements when DAO state in conflict](https://github.com/bisq-network/bisq/issues/2588)

- **Testing wallet restore functionality (after several reported issues).** Identified issue [Wallet shows 0 balance after restore seed words](https://github.com/bisq-network/bisq/issues/2516) [`1000 BSQ`]

- **Debugging the [auth cookie not created](https://github.com/bisq-network/bisq/issues/2398) issue on Windows**. And provided a solution which lead to a [fix](https://github.com/bisq-network/bisq/pull/2581) being merged. [`1000 BSQ`]

- **Implemented misc bug fixes and improvements.** To desktop client. [`1000 BSQ`]

  - [Show valuation in BTC balance tooltips](https://github.com/bisq-network/bisq/pull/2481)
  - [Update bond lockup prompt](https://github.com/bisq-network/bisq/pull/2487)
  - [Fix exception handling during Tor setup](https://github.com/bisq-network/bisq/pull/2538)
  - [Fix typos/grammar in account.seed.restore.info](https://github.com/bisq-network/bisq/pull/2565)
  - [Fix BTC status incorrectly hidden on splash screen](https://github.com/bisq-network/bisq/pull/2567)
  - [Suppress popup at shutdown when open offers are disabled](https://github.com/bisq-network/bisq/pull/2569)
  - [Update change param validator error messages](https://github.com/bisq-network/bisq/pull/2579)
  - [Show close button when creating offer without required account](https://github.com/bisq-network/bisq/pull/2590)

- **Reviewed PRs.** [`500 BSQ`]

  - [Add MacOS support in install_java.sh script](https://github.com/bisq-network/bisq/pull/2483)
  - [Fix incorrect available balance for voting](https://github.com/bisq-network/bisq/pull/2462)
  - [Add removed deprecated payment methods again as it would break trade history](https://github.com/bisq-network/bisq/pull/2505)
  - [Fix missing balance at restore from seed words](https://github.com/bisq-network/bisq/pull/2517)
  - [Add dao betatest network](https://github.com/bisq-network/bisq/pull/2546)
  - [Improve data structure, validation and performance](https://github.com/bisq-network/bisq/pull/2556)
  - [Fix get all bonds not returning not active bonds](https://github.com/bisq-network/bisq/pull/2576)
  - [Set max buyer's security deposit to 20% instead of 10%](https://github.com/bisq-network/bisq/pull/2575)

**BSQ amount requested:** `6500`

## Contributions in progress

- **Expanding manual test coverage.** I am creating test cases in our new testing tool https://bisq.ontestpad.com. I have a basic structure implemented with test scenarios for various components of the Bisq desktop application. However, some scenarios are just placeholders and require additional details added, and there are several components that will need scenarios to be implemented. I am currently implementing the test scenarios using a BDD-style syntax (given/when/then). I will need user feedback if that is the best approach, given that not everyone that will be executing them has a testing/development background.

- **Ongoing testing.** Primarily focused on DAO related functionality in anticipation of the DAO launch.

- **Deploying additional nodes.** A relay node and price node.

## Roles performed

- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-476844190 `[50 BSQ]`

**BSQ amount requested:** `50`

## Notes to self

<details>
  <summary>Details</summary>

- My contributions were determined by reviewing the results of this GitHub search query:
https://github.com/bisq-network/bisq/pulls?q=is%3Apr+is%3Amerged+author%3Adevinbileck+updated%3A2019-03-01..2019-03-31

- My PR reviews this month were determined by reviewing the results of this GitHub search query:
https://github.com/bisq-network/bisq/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Adevinbileck+updated%3A2019-03-01..2019-03-31+sort%3Aupdated-desc

- My issues discovered/entered were determined by reviewing the results of this GitHub search query:
https://github.com/bisq-network/bisq/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Adevinbileck+created%3A2019-03-01..2019-03-31

</details>

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
