### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by flix1** [bisq-network/compensation#245]
## Summary

> 
 - BSQ requested: 15000
 - BSQ address: **B18pxrZRFJ7Q1PsND9xqayk1uQbtZiH39MC** (spreadsheet address)

## Contributions delivered

 For past contributions including:
200 https://github.com/bisq-network/compensation/issues/34
20 https://github.com/bisq-network/compensation/issues/46
20 https://github.com/bisq-network/compensation/issues/62
800 https://github.com/bisq-network/compensation/issues/124
500 https://github.com/bisq-network/compensation/issues/146

**Comment by ManfredKarrer** [comment]
@flix1 Please request an appropriate amount. You provided a huge contribution with your help and strategies to bring liquidity to another level! Hard to estimate that value but I would not feel comfortable if you did not get at least about 20 000 BSQ for all that. You never requested much in the past for your contributions so I think we owe you something.

**Comment by flix1** [comment]
I am extremely thankful @ManfredKarrer. I hope to be able to contribute more to Bisq in the future. 

I will correct my request.

**Comment by flix1** [comment]
I have used the spreadsheet BSQ address as I understand that we will migrate to the new DAO genesis BSQ addresses at a later date.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
