### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#249]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**
## Roles performed
- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-477975538 (2600 BSQ)
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-477980192 (250 BSQ)
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-477976627 (150 BSQ)

**Comment by alexej996** [comment]
I will be creating a compensation request in Bisq DAO on testnet very soon.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
