### ISSUE TITLE
For December 2017

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#25]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 250
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

Run one full node all month, partial month of seednode jhgcy2won7xnslrb.onion, pricenode rb2l2qale2pqzjyo.onion including full month of bitcoinaverage sub at $12 (was easy to downgrade) and another partial month of full node i3a5xtzfm4xwtybd.onion

- Full node 185.25.48.184 / 3r44ddzjitznyahw.onion

Quite a bit of trouble with the services this month.

**Comment by cbeams** [comment]
This request has been entered into the [2017.12 tab](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=548599266) of the BSQ stake and voting spreadsheet and is ready to be voted on.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#26.
