### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by oscarguindzberg** [bisq-network/compensation#250]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 12300
 - BSQ address: B1LiYyuKpAZQHuyzRiFy8uBYNC71S8nEXQJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Audits:

- Bisq's bitcoinj "addr" message support audit (2300 BSQ)
  - Audit report: https://github.com/bisq-network/bitcoinj/issues/28
  - Bugfix: https://github.com/bisq-network/bisq/pull/2591
  - Add link to this report on the source code: https://github.com/bisq-network/bitcoinj/pull/29 
- bisq’s bitcoinj fee calculation changes audit (2200 BSQ)
  - Commit to audit: https://github.com/oscarguindzberg/bitcoinj/commit/7dd1bfd9c3028266a5f8d1954cbf259ee3907e9b 
  - Fix: https://github.com/bisq-network/bitcoinj/pull/27
- Bisq’s bitcoinj tor support audit (2300 BSQ)
  - Audit report: https://github.com/bisq-network/bitcoinj/issues/25    
  - Improvements: https://github.com/bisq-network/bitcoinj/pull/24 
  - Created a couple of PR on bitcoinj upstream
    - https://github.com/bitcoinj/bitcoinj/pull/1741
    - https://github.com/bitcoinj/bitcoinj/pull/1742
- TxBroadcaster audit (2000 BSQ)
  - Audit report: https://github.com/oscarguindzberg/bisq/commit/82ef7921b944f9ede3817d0cca031e16ff957416 
  - Improvements PR https://github.com/bisq-network/bisq/pull/2536

Other improvements:

- Compile bitcoinj with openjdk10 (700 BSQ) 
  - https://github.com/bisq-network/bitcoinj/pull/23
  - https://github.com/bisq-network/bisq/pull/2564 
- Move clear blockstore feature to bitcoinj (300 BSQ)
  - https://github.com/bisq-network/bitcoinj/pull/22 
  - https://github.com/bisq-network/bisq/pull/2563 
- Investigate: Error at BitcoinJ deserializing message https://github.com/bisq-network/bisq/issues/2557  (200 BSQ)
- Update testnet dns seeds https://github.com/bisq-network/bitcoinj/pull/26 (100 BSQ)
- "Restore from seed"
  - Fix missing balance at restore from seed words https://github.com/bisq-network/bisq/pull/2517  (100 BSQ)
    - Code review
  - Improve restore wallet from seed process https://github.com/bisq-network/bisq/pull/2524 (400 BSQ)
    - I wrote the source code (https://github.com/oscarguindzberg/bisq/commit/d307fa8179e26c15250ded8cc8bde0c17d2d00f4)
    - Manfred created the PR.
    - I did code review and testing.
  - Stress on the label that Bisq will be shutdown after restore https://github.com/bisq-network/bisq/pull/2530 (100 BSQ)
  - "Restore from seed" test on bisq. Some bugs were reported but I could not reproduce any bugs. (200 BSQ)
  - Retest bitcoinj upstream bug https://github.com/bitcoinj/bitcoinj/issues/1704 because I was told it was solved. Report what is working and what is not. I had to update to java 11 because the wallet template bitcoinj subproject now requires that. It's important for us that have a benchmark wallet to know how restore from seed should work on bitcoinj. (200 BSQ)
  - Complete “Restore from seed using blockstore.clear() fix” upstream PR https://github.com/bitcoinj/bitcoinj/pull/1702 (not merged upstream yet) (300 BSQ)

Research/exploratory tasks:
- Signet network research (400 BSQ)
  - It is a “stable testnet” with proof of authority.
  - Read email thread on bitcoin core mailing list https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-March/016734.html
  - Start bitcoinj signet implementation https://github.com/oscarguindzberg/bitcoinj/tree/signet 
- Rebroadcasting research (400 BSQ)
  - Discuss on bitcoinj mailing list https://groups.google.com/forum/#!topic/bitcoinj/lkK9N3NhoPY 
  - Read thread about “reject” msg removal in bitcoin core mailing list https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2019-March/016701.html 

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- Bisq’s bitcoinj connection handling changes audit
  - https://github.com/bisq-network/bitcoinj/issues/30 

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8#issuecomment-478048635 (100 BSQ)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
