### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by ben-kaufman** [bisq-network/compensation#251]
## Summary

 - BSQ requested: 1800
 - BSQ address: BmkZMETyptYNqoXj5mnQVqDGA9XprxwpR4V

## Contributions delivered

My PRs:
https://github.com/bisq-network/bisq/pull/2483 - 200 BSQ
https://github.com/bisq-network/bisq/pull/2492 - 10 BSQ
https://github.com/bisq-network/bisq/pull/2504 - 1000 BSQ (as specified in issue bisq-network/bisq#2477)
https://github.com/bisq-network/bisq/pull/2519 - 100 BSQ
https://github.com/bisq-network/bisq/pull/2521 - 250 BSQ
https://github.com/bisq-network/bisq/pull/2528 - 200 BSQ

Those 2 were started by me and completed by @ManfredKarrer 
https://github.com/bisq-network/bisq/pull/2526 - 20 BSQ
https://github.com/bisq-network/bisq/pull/2541 - 20 BSQ

Reviewed PRs:
https://github.com/bisq-network/bisq/pull/2515
https://github.com/bisq-network/bisq/pull/2577

This is my first compensation request :) if you think I should change something here please let me know.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
