### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#252]
## Basic information

 - BSQ amount requested: **16775**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

### Development work:
- Development work [1]
- Preparation and testing for v0.9.5 release
- DAO testing
- Setup for new DAO testnets (testnet, mainnet)

### Others:
- Dev sessions

Requested: 13000 BSQ (the relative high amount reflects a very intense month with in average 6 days a week / 12 hours a day. Also the specific DAO work was quite challenging, no "walk in the park"...) 

[1] https://github.com/ManfredKarrer

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14 `(25)`
- Events Maintainer: https://github.com/bisq-network/roles/issues/65 `(25)`
- Markets Website+API Maintainer: https://github.com/bisq-network/roles/issues/9 `(25)`

Sum: 75 BSQ

Operator roles:
- Markets Website+API Operator: https://github.com/bisq-network/roles/issues/9 `(50)`
- Seed node operator: https://github.com/bisq-network/roles/issues/15 `(4 mainnet + 9 DAO testnet nodes: 650)`
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10 `(1 Mainnet + 1 Testnet (DAO): 100)`
- Price node Operator `(2 nodes: 100)`
- Relay node (mobile notifications) Operator `(50)`
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67 `(2 nodes: 100)`
- BSQ explorer node `(50)`
- BSQ DAO regtest master nodes `(2 nodes: 100)`

Sum: 1200 BSQ

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

Major roles:
- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63 `(2000)`
- GitHub Admin: https://github.com/bisq-network/roles/issues/16 `(200)`
- Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12 `(250)`
- Slack Admin: https://github.com/bisq-network/roles/issues/23 `(50)`

Sum: 2500 BSQ

Minor roles:
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Freenode Admin: https://github.com/bisq-network/roles/issues/22
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31
- Transifex Admin: https://github.com/bisq-network/roles/issues/20
- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Support Staff: https://github.com/bisq-network/roles/issues/64

Requested for all the listed roles: 3775 BSQ

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
