### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#253]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `22040`
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

### DAO Design
As the launch of the DAO is closing in I'm also adding a request for work done on DAO design, security and other work that is now reflected in the code. Most of this work has been in direct discussions and planning with @ManfredKarrer over the last 18 months, some in code that was rejected but later improved on and some in documentation.

BSQ requested `20000`

### Reviews
https://github.com/bisq-network/bisq/pull/2532
https://github.com/bisq-network/bisq/pull/2556
https://github.com/bisq-network/bisq/pull/2584
https://github.com/bisq-network/bisq/pull/2587

BSQ requested `1500`

### Explorer
Setup explorer for betanet, this requires a full node with txindex. Taking on the explorer operator/maintainer role. 

BSQ requested `300`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bitcoin node maintainer - https://github.com/bisq-network/roles/issues/66#issuecomment-478256663 `50`
Bitcoin node operator - https://github.com/bisq-network/roles/issues/67#issuecomment-478256758 `100`
Tor relay operator - https://github.com/bisq-network/roles/issues/72#issuecomment-478256981 `40`
Explorer maintainer/operator - https://github.com/bisq-network/roles/issues/11#issuecomment-478256552 `50`

BSQ requested `240`

**Comment by Wimking1987** [comment]
BSQ requested:350
BSQ address: B14Cictu1JaHoR3wCF4uq9D3LxcxZvk4FYs

https://github.com/Wimking1987/bisq-design/commit/5773112cba134015db5bfb685ee8799261581f1f

**Comment by ManfredKarrer** [comment]
@Wimking1987 You need to create a new issue for your compensation request. This is the request of @sqrrm

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
