### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by eyalron33** [bisq-network/compensation#255]
## Basic information

 - BSQ requested: 600
 - BSQ address: B1PU7DoYDHWi2impz86Fvu3ZgsREaBnGJBW

## Contributions delivered
- Additional compensation for Bisq lectures given in February 2019, see discussion [here](https://github.com/bisq-network/compensation/issues/229).

Requested: 500 BSQ

- Proof reading [Aruna Surya](https://github.com/arunasurya)'s Bisq documentation.

Requested: 100 BSQ

**Comment by devinbileck** [comment]
Just curious, any record of your proof reading activities?

**Comment by eyalron33** [comment]
It was done on a private email exchange with @arunasurya. You can also see [Aruna's compensation request](https://github.com/bisq-network/compensation/issues/259) where my help was mentioned.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
