### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/compensation#256]
march 2019
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `2900`
 - BSQ address: B19yxYCRTVaDfRfucrH6aEzeZpoVTv8Je8S

This compensation request :
- follows the https://docs.bisq.network/roles.html#compensation recommandations
- applies the 1BSQ=1USD rule

### Substantive reports

- Support | https://github.com/bisq-network/roles/issues/64#issuecomment-478323513 | (BSQ requested = 2500)
Evaluation is based and intended in line with : previous compensation requests, and other support compensation requests.
(Activity numbers : 2018Q3/2700 trades, 2018Q4/6800 trades, 2019Q1/5400 trades).

- Fees and connectivity monitoring | see the weekly reports in https://github.com/bisq-network/roles/issues/10 | (BSQ requested = 200)
Concerned monitored data files : https://github.com/HarryMacfinned/bisq-monitor
TL;DR: there was zero catch this month (nodes are running well).

- Prices monitoring | https://github.com/bisq-network/roles/issues/10#issuecomment-478260255 | (BSQ requested = 200)
TL;DR: One pricenode stucked end of march.

(NB : The monitoring role includes also manual sorting of false alarms, ie monitoring several Bisq specific pages + following of Tor metrics page + maillist)

## Other points (BSQ requested = 0)
- Clearnet Bisq webpages monitoring : 2 alerts this month, only back-office, reported in the #bisq-monitor channel
- participation in DAO testing
- participation in proposal https://github.com/bisq-network/proposals/issues/75 (removing money orders)
- bisq-network github activity : 3 issues

## Contributions in progress
- I'm participating to v0.9.6 tests right now. Will be in next month's CR
- looking to (maybe) add stalled node detection to the monitor
- investigating for anonymous Tor relay operating [WIP]
- onion website(s) handling [WIP]

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
