### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#257]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `8325`
 - BSQ address: B1FGfKZQrpbLN9UNMogyJAVTR5PJNRkGPXJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**Blog**
- Write post/essay _Benefits of the Bisq DAO, Part I: Funding FLOSS & Avoiding Surveillance Capitalism_ ([link](https://github.com/bisq-network/bisq-website/pull/149))
  - I requested a bit more than usual here because this post was a longer and required more time to think and formulate than others. It also got several positive reactions on Twitter, both through the post itself and the [resulting tweetstorm](https://twitter.com/bisq_network/status/1107713696502083585).

BSQ Requested: `750`

**Blog Operations**
- Review, edit, and publish 3 other posts for the month in coordination with arunasurya

BSQ Requested: `1000`

**Website**
- Overhaul FAQs page ([PR](https://github.com/bisq-network/bisq-website/pull/151))

BSQ Requested: `1500`

**Docs**
- Speed improvements ([PR](https://github.com/bisq-network/bisq-docs/pull/115) and [PR](https://github.com/bisq-network/bisq-docs/pull/116)). 
  - [Google PageSpeed rating](https://developers.google.com/speed/pagespeed/insights/?url=docs.bisq.network) is now perfect 100 for desktop and 94 for mobile. As explained [here](https://github.com/bisq-network/roles/issues/21#issuecomment-478378744), I don't see any reasonable way to improve the mobile rating.
- Minor updates to help contributors specify their mainnet BSQ addresses ([PR](https://github.com/bisq-network/bisq-docs/pull/120)) and encourage DAO testing and feedback ([PR](https://github.com/bisq-network/bisq-docs/pull/117)).

BSQ Requested: `800`

**Video**
- Test the Bisq DAO in 90 Seconds ([link](https://www.youtube.com/watch?v=L8wyrONcJfA))
  - Under-valuing here since the ultimate "shelf-life" was short (video will no longer be useful after April), but a good number of users who helped test the DAO watched it, so I think it was a good effort.

BSQ Requested: `250`

**Events/Communications**
- Panel at MIT Bitcoin Expo (9-10 March) ([link](https://www.youtube.com/watch?v=UgE0PIJ08Zw))
  - Fly to Boston for 3 days/2 nights
- Interview with Ricardo Martinez ([link](https://medium.com/@rickytheghost1981/the-bisq-dao-an-interview-with-steve-jain-891941315b7a))
  * Also posted on the World Crypto Network with an intro from Max Hillebrand ([link](https://www.youtube.com/watch?v=0j0sHyeCBbw))

BSQ Requested: `600`

**Other Operations**
- Push for DAO testing participation and feedback
  - Across Slack, GitHub, email, and personal 1-on-1 contact as appropriate

BSQ Requested: `925`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Partly because I was late in submitting my PRs, and partly because some PRs are tied to the actual DAO launch, a chunk of my work this month hasn't been merged yet. It will just come through in next month's request.

- DAO docs preparation - PR pending
- DAO faqs ([PR](https://github.com/bisq-network/bisq-website/pull/152))
- DAO website tweaks ([PR](https://github.com/bisq-network/bisq-website/pull/153))
- Stats page on website ([PR](https://github.com/bisq-network/bisq-website/pull/156))

On the communications front, 2 items are coming up.

- Appearance on Peter McCormack's _What Bitcoin Did_ podcast, probably happening sometime in May
- Interview with Vlad Costea of Crypto Insider

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Twitter Admin: https://github.com/bisq-network/roles/issues/21#issuecomment-478378744 `2500` 
Roles Admin: https://github.com/bisq-network/roles/issues/28#issuecomment-478378420 `25`
Docs Maintainer: https://github.com/bisq-network/roles/issues/29#issuecomment-478378542 `25`
Slack Admin: https://github.com/bisq-network/roles/issues/23#issuecomment-478378616 `25`
YouTube Admin: https://github.com/bisq-network/roles/issues/56#issuecomment-478378660 `25`

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
