### ISSUE TITLE
ACTION REQUIRED: All Contributors Since October 2017

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#260]
We need a final mainnet BSQ address from each of you before the DAO launches.

All of you have already specified addresses in your compensation requests, but you may want to generate a fresh one if:

* you no longer have access to the wallet
* the wallet is old (e.g., 1.5-year-old wallets _should_ work, but there have been several significant changes over time, and compatibility hasn't been tested)
* you just want to generate a new one for any other reason

**No matter what you choose to do, please reply to this thread _before the end of this week_:**
- To change your address...
  - _Preferred_: reply here with your new address AND old address
  - _Otherwise_: email genesis@bitsquare.io with new and old addresses AND reply here stating you've done so
- To keep your address...
  - Reply here confirming your existing BSQ address is the one that should be used

If you've already confirmed your address in the past few days through other means, please still reply here to acknowledge you've seen this message.

It is critical that we get this right for everyone. I'll cross names of this list as people reply. 

~~- @sqrrm~~

~~- @ripcurlx~~

~~- @Emzy~~

- @JesusMcCloud

~~- @mrosseel~~

- @Nolaan

~~- @neiman30~~

~~- @alexej996~~

- @maskoficarus

- @leomcy

~~- @flix1~~

- @stevenkain

~~- @jdonmoyer~~

- @ghubstan

- @alfsbs

~~- @blabno~~

~~- @tomatopeel~~

~~- @rex4539~~

- @AndersBTC

- @m52go

~~- @HarryMacfinned~~

- @initCCG

~~- @BravoIndia~~

~~- @chirhonul~~

- @bugrasan

- @joachimneumann

- @pfergi42

~~- @clearwater-trust~~

~~- @fedegrc~~

~~- @kopite77~~

~~- @dgyg~~

~~- @devinbileck~~

- @princeofeth

~~- @ArthurCideron~~

~~- @arunasurya~~

~~- @kwcareer~~

~~- @Technohacker~~

- @cyphersphinx86

- @KanoczTomas

~~- @freimair~~

~~- @leshik~~

- @fotispap

~~- @j3ko~~

~~- @eyalron33~~

~~- @aejontargaryen~~

~~- @pedromvpg~~

~~- @CaveSpectre11~~

- @moneroproblem

**Comment by m52go** [comment]
[continued; can't tag more than 50 people in a single post]

- @oscarguindzberg

- @xiphon

- @michaltakac

- @FKrauss

- @y3v63n

- @huey735

- @Mycelial1

- @Stam57

- @ben-kaufman

- @Wimking1987

**Comment by alexej996** [comment]
My old BSQ address is: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**
The new one is: **B1Bq9yRRvjbSb9VJYt59farky9MUUYmxZR5**

**Comment by y3v63n** [comment]
Hi, the address I specified is a new one and should be fine.

**Comment by michaltakac** [comment]
Confirming my existing BSQ address **B18x61QoqJetyBs4eGNtKr4D5aAdwref2o6** is the one that should be used

**Comment by mrosseel** [comment]
Hi,

Already mailed to genesis@ with the new address for @mrosseel

regards,
Mike

**Comment by Technohacker** [comment]
Confirming I have access to the wallet with address **B1Q9Gg1DxURa1xBvvXmWcJVEDMiwUNWCyad**

(Checked with version v0.9.1. In case I need to update please let me know)

**Comment by oscarguindzberg** [comment]
I confirm my current address B1LiYyuKpAZQHuyzRiFy8uBYNC71S8nEXQJ

**Comment by dgyg** [comment]
Confirming my BSQ address B1DMw2kmC2Dfj7Ncq6kUdwfFJ7dPQDy7dwr

**Comment by ripcurlx** [comment]
Confirming that my current address is **B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS**

**Comment by jdonmoyer** [comment]
Confirming that my current address is: B1G3RTdM2tSwkSB5tgno3aETHDdR3Cc2r92

Jason Donmoyer
*Threddies <https://threddies.com/> Co-Founder*

Check out our Retail Store & Showroom:
510 W. Walnut St.
Perkasie, PA 18944

215-257-4100

**Comment by CaveSpectre11** [comment]
Mine is fairly new (November 2018) so I presume it's confirm-able: B1M4i1X6oq3i8YaA6C9tgYUF86EZ8r6MdZC

**Comment by rex4539** [comment]
I confirm that my address is B153NNHXQxnH5v6AXv8F5zdhPsdjkQfxB7v

**Comment by FKrauss** [comment]
confirming, same address:
B1LpTRDi1tLqX74u23F5ZdnjXV7bhxwaxX8

**Comment by j3ko** [comment]
confirming my address has not changed:
B1PP58rq6TnKifRitzHgU8gJemL1dcNtKNV

**Comment by huey735** [comment]
Confirming address
B1NBcexfGapodHZzFyoeTzJnqqdSkZbNVQQ

**Comment by flix1** [comment]
New address:  **B1KnLU3Ff1SLwW1HrkoYMFrx8VEuTVPfyvD**

(Old address: B18pxrZRFJ7Q1PsND9xqayk1uQbtZiH39MC)

**Comment by Emzy** [comment]
Confirming address:
B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE

**Comment by Stam57** [comment]
My old BSQ address is:
B1Ke6nE58wDpLa8StA3Ls3nRNSrtheKSG2V

My new BSQ address is:
B1CPX2HuSeW4Kzfs3sjuuPPxteLzZUNb66D

**Comment by arunasurya** [comment]
Confirming the address: B1PFD3uscJqFQfLNAS6bWQtr1PUahrWNvC7

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by m52go** [comment]
Wimking1987
B14Cictu1JaHoR3wCF4uq9D3LxcxZvk4FYs

**Comment by Mycelial1** [comment]
Confirming my BSQ address 
B1BUqX5aYPyXMzCfGNX6UjTyNQd1t6qpyRK

**Comment by leshik** [comment]
Confirming that my current address is **B1CK6i6P4cGc73sRTtovNaRUC9QrjhzUJxd**

**Comment by tomatopeel** [comment]
please use my old address

**Comment by eyalron33** [comment]
*for both eyalron33 and neiman30*:

Confirming address: B1PU7DoYDHWi2impz86Fvu3ZgsREaBnGJBW

**Comment by ben-kaufman** [comment]
My old BSQ address is: BmkZMETyptYNqoXj5mnQVqDGA9XprxwpR4V
My new address is: B112ZP1RHmVyxGknTtDR8bvRKyQuhVNc1Xo

**Comment by clearwater-trust** [comment]
Confirming address: **B15VTptnSAUURnacM9MV736yjUmF4Qta6E2**

Thanks!

**Comment by ArthurCideron** [comment]
Let me add to the notification storm.

Confirming:
B1CuNXH7DfFLdti8TMFnaYTVBs7umXH8d2A

**Comment by blabno** [comment]
This is @blabno
My BSQ mainnet address is: B1ARsZ9kk1wANuuw9EDFnWF9ERwa1x5N2Rm

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BravoIndia** [comment]
Confirming: B1RsBHsUuEBTLUgf7KeFs4KnT9jwMWi7Xt

Thank you!

**Comment by HarryMacfinned** [comment]
Hello @m52go ,
I just sent a mail to the address you mentioned.
Thank you.

**Comment by sqrrm** [comment]
Old: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ
New: B13ydR5AbXUMDs4444SrMcvaxcUqH8t2s2G

**Comment by kwcareer** [comment]
I replied by email, but unlike others I have not appeared in the reply list. This is what I sent:

Confirming my existing address is:  B1EoZ4gaFK3Wj7bbN7uypZ6TXcrnniiHpDz

**Comment by m52go** [comment]
@kwcareer how is that you have a spot on the voting spreadsheet, but don't have an issue in this repository?

I had assumed all contributors would have opened issues in this repository...now I'm wondering if there are other contributors like you.

**Comment by kwcareer** [comment]
@m52go 
> @kwcareer how is it that you have a spot on the voting spreadsheet, but don't have an issue in this repository?

I do not know, did I omit to take some action somewhere perhaps? I found this if it is of any help: https://github.com/bisq-network/compensation/issues/142

**Comment by m52go** [comment]
Oh...you are in the list after all. Not sure where the confusion is.

I used an API call to get a list of all users who have opened an issue here, so the chances of an error were slim to none.

**Comment by chirhonul** [comment]
Confirming that my address `B197ZcX369usMDHCF6iD2h1CMbntkovDqoe` is correct.

**Comment by freimair** [comment]
old: B1JJUQWUHEoUwng4uGGWsT4hnTMc6dXtj9K
new: B15co2SV4cZr5ytscwHejuQWiZHYJN5imxg

**Comment by fedegrc** [comment]
Confirming address B1961fVVFMnQunrKVtWVsBsReLvL6q6VT3R

**Comment by pedromvpg** [comment]
still the same: B18BA37KaiSHLMhyjs7FMPAJMfcVcVzJPCm

**Comment by kopite77** [comment]
confirming my BSQ address: B1KMMTchfJAyNDGQwUW2qdJKLxvUupnfKZZ

**Comment by aejontargaryen** [comment]
confirming BSQ address : B1AweC1bYPY6SzkWTanwX2JWpBhVRxL72he

**Comment by KanoczTomas** [comment]
communicated my new address, you should have it now @m52go

**Comment by pfergi42** [comment]
**New address:** B1JDugJeHYuzX7biJ7Nw6KSABVy21d5rqWo

Old address: B1D3KUonHEcCg9tuvYXVRbWivdGfCHtnA8n

**Comment by cbeams** [comment]
Confirming that I've sent my new addresses to @ManfredKarrer as requested.

**Comment by criptonauta** [comment]
> 
> 
> We need a final mainnet BSQ address from each of you before the DAO launches.
> 
> All of you have already specified addresses in your compensation requests, but you may want to generate a fresh one if:
> 
>     * you no longer have access to the wallet
> 
>     * the wallet is old (e.g., 1.5-year-old wallets _should_ work, but there have been several significant changes over time, and compatibility hasn't been tested)
> 
>     * you just want to generate a new one for any other reason
> 
> 
> **No matter what you choose to do, please reply to this thread _before the end of this week_:**
> 
>     * To change your address...
>       
>       * _Preferred_: reply here with your new address AND old address
>       * _Otherwise_: email [genesis@bitsquare.io](mailto:genesis@bitsquare.io) with new and old addresses AND reply here stating you've done so
> 
>     * To keep your address...
>       
>       * Reply here confirming your existing BSQ address is the one that should be used
> 
> 
> If you've already confirmed your address in the past few days through other means, please still reply here to acknowledge you've seen this message.
> 
> It is critical that we get this right for everyone. I'll cross names of this list as people reply.
> 
> ~- @sqrrm~
> 
> ~- @ripcurlx~
> 
> ~- @Emzy~
> 
>     * @JesusMcCloud
> 
> 
> ~- @mrosseel~
> 
>     * @Nolaan
> 
> 
> ~- @neiman30~
> 
> ~- @alexej996~
> 
>     * @maskoficarus
> 
>     * @leomcy
> 
> 
> ~- @flix1~
> 
>     * @stevenkain
> 
> 
> ~- @jdonmoyer~
> 
>     * @ghubstan
> 
>     * @alfsbs
> 
> 
> ~- @blabno~
> 
> ~- @tomatopeel~
> 
> ~- @rex4539~
> 
>     * @AndersBTC
> 
>     * @m52go
> 
> 
> ~- @HarryMacfinned~
> 
>     * @initCCG
> 
> 
> ~- @BravoIndia~
> 
> ~- @chirhonul~
> 
>     * @bugrasan
> 
>     * @joachimneumann
> 
>     * @pfergi42
> 
> 
> ~- @clearwater-trust~
> 
> ~- @fedegrc~
> 
> ~- @kopite77~
> 
> ~- @dgyg~
> 
> ~- @devinbileck~
> 
>     * @princeofeth
> 
> 
> ~- @ArthurCideron~
> 
> ~- @arunasurya~
> 
> ~- @kwcareer~
> 
> ~- @Technohacker~
> 
>     * @cyphersphinx86
> 
> 
> ~- @KanoczTomas~
> 
> ~- @freimair~
> 
> ~- @leshik~
> 
>     * @fotispap
> 
> 
> ~- @j3ko~
> 
> ~- @eyalron33~
> 
> ~- @aejontargaryen~
> 
> ~- @pedromvpg~
> 
> ~- @CaveSpectre11~
> 
>     * @moneroproblem
@m52go 

I contributed but my name is not on the list

A lot of translations in Transifex since 2 years ago.

**Comment by m52go** [comment]
@criptonauta have you ever made a compensation request for your work? It doesn't seem like you've ever opened an issue in this repository.

**Comment by criptonauta** [comment]
> 
> 
> @criptonauta have you ever made a compensation request for your work? It doesn't seem like you've ever opened an issue in this repository.

@m52go not yet. Just knew about it some days ago. I will finish the current revision since it's close to a new release and make a request prior to May 5th.

**Comment by m52go** [comment]
The convention has been to make a compensation request on a monthly basis for any work you've done in the past month.

But you're still free to make a compensation request for all your contributions from the past, as long as you can provide documentation/proof of them so stakeholders can make an informed decision.
