### ISSUE TITLE
Bisq DAO Testing Feedback

### ISSUE THREAD

**Issue by JohnResh** [bisq-network/compensation#262]
Claim of feedback reward + bug report.

 - BSQ requested: 30
 - BSQ address: B1FcVZn2xXfTNS5Fib8yZDQMrRL87GPR6YG

## Contributions delivered
https://github.com/bisq-network/bisq/issues/2596

Also:
Bisq DAO Testing Feedback: done
Got it. Thank you!

**Comment by ripcurlx** [comment]
@JohnResh You need to file your compensation request here https://github.com/bisq-network/compensation/issues. To be able to evaluate your compensation request please add your feedback to the issue as well. Thanks for testing the DAO!

**Comment by ripcurlx** [comment]
@JohnResh My mistake 😬 - I had multiple repositories mixed up in my ZenHub view.

**Comment by ripcurlx** [comment]
But as mentioned above, please add your testing feedback here in the issue as well.

**Comment by JohnResh** [comment]
I did not save my testing feedback, but I remember suggesting adding tooltips to the governance terms, especially "confiscating a bond" which I found quite confusing. 
Hope this is enough. If not, you can reduce the reward to +10 just for the bug report.

**Comment by ManfredKarrer** [comment]
Please make sure you make the request in the Bisq app in the DAO section!
The BSQ address field above can be removed as it is now irrelevant.

**Comment by m52go** [comment]
I found 1 response that reflected @JohnResh's feedback from above. I, for one, would recommend including the feedback survey in your compensation request when you file it in the DAO.

![Screenshot from 2019-05-04 10-24-49](https://user-images.githubusercontent.com/735155/57180532-66f43000-6e57-11e9-88b9-0df2d43c6018.png)

**Comment by MwithM** [comment]
`Closing old issue`
