### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by itsN1X** [bisq-network/compensation#264]
## Summary

 - BSQ requested: 666
 - BSQ address: B1NpPA7nh3gPe2FRozYuuJVBWF5Pm5rT8q1

## Contributions delivered

-  Surveys
-  Testing DAO (regtest)
-  Bug Report & Feedback
-  Governance
-  Testnet Peers (regtest)

<details><summary>

## Contributions in progress

</summary>

- [x] Testing DAO 
- [x] Platform compatibility (Soft)
-  Governance
- [ ] Proposing (regtest)
- [x] Proposal analysing (regtest)
- [ ] Voting proposed (regtest)

## Roles performed

__Testing__
__Feedback__
__Promotion__

<details><summary>
## Notes
</summary>

###### Joint : 
Request for `Oct 2018-Mar 2019`.
 
<details><summary>

**Thank You**

</summary>

###### Amount :
Please approximate, I've no idea of its valuation. Assume it to be a placeholder for updating (#263 ) my mainnet address.</details></details></details>

**Comment by m52go** [comment]
Hi @itsN1X, I believe we spoke on Slack. Have you actually done these tasks, or are they items you plan to do in the future?

Compensation can only be requested for delivered work ([link](https://github.com/bisq-network/proposals/issues/19)).

If you're wondering where to start, I recommend [checking out this checklist](https://docs.bisq.network/contributor-checklist.html), hanging out on our Slack and/or forum, and getting started with smaller tasks in collaboration with others.

**Comment by itsN1X** [comment]
Oh, my bad! That was such a `¬<pre>` message løl

_And I am not an active_ contributor, but have been w\ the project since a while🖤

----

- [ ] Survey

###### `20`**BSQ**

- [ ] Reporting

 bugs in `regtestdao`
###### `X`**BSQ**

- [ ] Testing the new 9.7, > on multiple OSes.
    :- TAILS ☑ :  `Clean Install`
    :- Ubuntu ☑ :  `Clean Install`
    :- MINT ☑ :  `Clean Install`
    :- Kubuntu ☑ :  `Clean Install`
    :- Lubuntu ☑ :  `Clean Install`
    :- arch64/armv8 ⚠ :  `Error in:Installation`
*(So as to draw my own conclusions apropos system-resources' efficiency/stability/minimum(s).)*
######  `Y`**BSQ**

- [ ] Added nodes
###### `Z`**BSQ**

- [ ] Governance
*I only (+\o\\-1)voted for the proposals I deemed legitimate.*
$I also reviewed each  proposal rigorously to ensure meaningful feedback.

Many of these tasks also stay W-I-P as mentioned in the `<details>` in #264, under the **Contributions in progress** sub-heading. 

<pre>+Generic *word-of-mouth* _promotion_ among my dear/near folk.</pre>
###### `¶`**BSQ**

----
----

# Summary


 - BSQ requested: 6̶6̶6̵ `20`+( **X**+**Y**+**Z**+¶) $`BSQ`
 - BSQ address: B1NpPA7nh3gPe2FRozYuuJVBWF5Pm5rT8q1

**Comment by ManfredKarrer** [comment]
Please make sure you make the request in the Bisq app in the DAO section!
The BSQ address field above can be removed as it is now irrelevant.

**Comment by MwithM** [comment]
`Closing old issue`

**Comment by itsN1X** [comment]
cc @33o1—

- [ ] append to pending (#bAckLog)
