### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by agb19** [bisq-network/compensation#265]
## Summary

Hi everyone, this is my first compensation request, please be gentle and apologies for any mistakes. 

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 500

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Identified, documented and tested two issues affecting Bisq functionality on slow networks. My contribution includes:
- discussing the problem on the bisq.community forum with other affected users
- studying the problem in real and simulated network environments
- submitting two issues to the Github project: 
  - https://github.com/bisq-network/bisq/issues/2547 (ref'd in @ManfredKarrer's PR2583) and 
  - https://github.com/bisq-network/bisq/issues/2549
- providing reproducible test methods, suggestions and feedback to assist with solving the problem

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

As a Bisq user with a slow network connection in real life (and, more recently, a Github account), I will keep testing and ~~complaining~~ giving feedback about the software performance in poor network conditions, with a view to helping other users in similar situations and increasing adoption. 

Thank you.

**Comment by ManfredKarrer** [comment]
Please make sure you make the request in the Bisq app in the DAO section!
The BSQ address field above can be removed as it is now irrelevant.

**Comment by agb19** [comment]
Done, thanks!

**Comment by MwithM** [comment]
`Closing old issue`
