### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by rhcastilhos** [bisq-network/compensation#266]
## Summary

 - BSQ requested: 118.98 BSQ

## Contributions delivered

**Request: 118.98 BSQ**

Translation of Bisq software to Portuguese (Brazil) (pt_BR) (from dec/18 to apr/19)
Word count:
- 5,949 Translated

As previous requests of translators, I'm asking for each word 0.02 BSQ:
- Translation - 5,949 words * 0.02 BSQ = 118.98 BSQ

![image](https://user-images.githubusercontent.com/10789865/57184889-bf144c00-6ec2-11e9-9f09-dd9dd3c7133d.png)

## Contributions in progress
I'm still active translating Bisq software to Portuguese (Brazil) whenever new strings are added.

**Comment by arunasurya** [comment]
You may find the following documentation useful for your comp. request: https://github.com/arunasurya/bisqtransifex/blob/master/translatordocumentation.md.

**Comment by ManfredKarrer** [comment]
Please make sure you make the request in the Bisq app in the DAO section!
The BSQ address field above can be removed as it is now irrelevant.

**Comment by rhcastilhos** [comment]
I don't have 2 BSQ to open the request.
The minimum amount available in bisq is 120 BSQ for 0.03 BTC, which is too much for me. It would be nice to have offers with smaller amounts of BSQ.

**Comment by ManfredKarrer** [comment]
Make your own offer ;-)

**Comment by MwithM** [comment]
`Closing old issue`
