### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#267]
## Summary

 - BSQ requested: 2704
 - BSQ address: B16cXeZAQyQ7Dmnkcjr4GdkifJexn6FJ5aA

### Bisq blog project (700BSQ)
- Wrote a blog post: https://bisq.network/blog/why-aruna-surya/ (400BSQ).
- Reviewed and suggested edits for two blog posts (https://bisq.network/blog/dao-launch-third-anniversary/; https://bisq.network/blog/ricardo-janine-rogue-bitcoin-interview/), provided input for a new blog maintainer role proposal (https://github.com/bisq-network/proposals/issues/81) (300BSQ).

Collaborators: @m52go (reviews, publishing posts, blog maintainer role proposal input), @Mycelial1 (blog maintainer role proposal input).

### Transifex reviews (4BSQ)
Reviewed 20 strings (107 words) in Russian. At a rate of 0.035BSQ per word, this amount to 3.745 or 4BSQ.

![Transifex comp request: reviewer April 2019](https://user-images.githubusercontent.com/43150241/56968728-365c7f80-6b53-11e9-84ef-a8ca509f7f45.png)
![Transifex comp req 2 April 2019 ](https://user-images.githubusercontent.com/43150241/56968741-3c526080-6b53-11e9-8fdb-4a69de10dbc6.png)
![Transifex comp req 3 April 2019](https://user-images.githubusercontent.com/43150241/56968753-42484180-6b53-11e9-860e-5c8cb4bc0d89.png)
![Total number of reviewed strings](https://user-images.githubusercontent.com/43150241/56969188-2b561f00-6b54-11e9-95e3-dc6a9108ba2d.png)

### Transifex Admin (2000BSQ)
- Moderated several communication channels (#transifex Slack channel, Announcements and Team discussions on Transifex).
- Created [a monthly report](https://github.com/bisq-network/roles/issues/20).
- Had calls with translators from the Spanish and Portuguese teams, email conversations with the translators from the French, Russian, Vietnamese, Portuguese, Greek, Thai and Persian teams.
- Created documentation for translators and reviewers based on these calls/conversations, and discussions with @ripcurlx and @y3v63n: https://github.com/arunasurya/bisqtransifex.
- Started an issue to make website translatable (https://github.com/bisq-network/bisq-website/issues/173).
- Collaborators: @ripcurlx (updating the translations for each release, advice, weekly calls, etc), @y3v63n (glossary initiative, input in the translator documentation: LGA, compensation requests, difficult terms and queries, etc).

**Comment by MwithM** [comment]
`Closing old issue`
