### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by y3v63n** [bisq-network/compensation#268]
## Summary

- BSQ requested: 580.63

### Transifex translations (140.63 BSQ)

- Translated 2,009 words into Russian (at the rate of 0.07 BSQ per source word). Ensured that at the time of the release on 15  April, Russian was 100% translated. See the screenshot with the stats bellow. The report can also be accessed here: https://www.transifex.com/bisq/bisq-desktop/translate/#ru/$/110522281?q=translator%3Ay3v63n+translated_after%3A2019-04-01+translated_before%3A2019-04-30

![Opera Снимок_2019-05-03_091649_www transifex com](https://user-images.githubusercontent.com/39760876/57122112-3e4f3600-6d84-11e9-9524-9e143520a602.png)

### Other tasks (22 hours at the rate of 20 BSQ/h) (440 BSQ)

- Offered the idea and created [Bisq Query Tracker](https://docs.google.com/spreadsheets/d/1P4JMLrcRtSWkxfh9jG7AXkfdgdkEYwgttGgly-ercXc/edit#gid=0) to help all translators leave/discuss questions/queries arising in the process of translation.
- Started reviewing the existing Russian translations. The translations have been done by 12 people. As a result, the current version has numerous inconsistencies in terminology as well as various linguistic and functional errors. All the changes are being logged into the follwoing [Review Report](https://docs.google.com/spreadsheets/d/1P4JMLrcRtSWkxfh9jG7AXkfdgdkEYwgttGgly-ercXc/edit#gid=0) that has also been offered as a model for the rest of the languages, but the idea is still in discussion due to possible complexity/additional workload concerns for other translators.
- Spearheaded the Glossary Initiative: based on the high frequency terms identified last month (around 100), added them to the [Transifex Glossary](https://www.transifex.com/bisq/bisq-desktop/glossary/ru/?page=1) and provided translations for some of them.
- Communicated news regarding the Glossary Initiative and Bisq Query Tracker through several communication channels (#transifex Slack channel and Team discussions on Transifex).
- Had two calls with @arunasurya to discuss matters related to Transifex translations and related initiatives.
- [Contributed](https://github.com/arunasurya/bisqtransifex/commits?author=y3v63n) to the documentation for translators and reviewers created by @arunasurya: https://github.com/arunasurya/bisqtransifex

## Contributions in progress

- Revieweing existing Russian translations.
- Working on the Translation Style Guide.

**Comment by ManfredKarrer** [comment]
Please make sure you make the request in the Bisq app in the DAO section!
The BSQ address field above can be removed as it is now irrelevant.

**Comment by huey735** [comment]
@ManfredKarrer how will you know what BSQ address to send the funds to?

**Comment by sqrrm** [comment]
@huey735 The request should be done within the app which will automatically handle the addresses.

When you make the compensation request the app will create a transaction with some BSQ and BTC  txoutputs that can be spent by an address you control. One of the BTC outputs will later be treated as a BSQ txoutput if enough people vote in favor of your compensation request. You never have to bother with the actual addresses used, you will only see the compensation request in the UI and later see the available BSQ.

If you're interested you can see more about the individual transactions on under the BSQ WALLET > TRANSACTIONS tab.

**Comment by ripcurlx** [comment]
> Other tasks (22 hours at the rate of 20 BSQ/h) (440 BSQ)

@y3v63n Please don't add add any hourly rates in your compensation requests as we are not compensating by hour, but by delivered work. So just posting 440 BSQ is in your case sufficient.
