### ISSUE TITLE
Cycle 5

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#269]
## Summary

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested:`29880`

This is a compound compensation request for contributions delivered from April 2019 until now. I'll tried to split up all contributions as detailed as possible. I wasn't very active from May until August because of paternity leave  -> !😴.

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**Reviews of PRs**
I monitor PR reviews separately from the responsibilities of the Bisq Desktop Maintainer role.

_Reviewed PRs:_
### April 2019
- https://github.com/bisq-network/bisq/pull/2616
- https://github.com/bisq-network/bisq/pull/2614
- https://github.com/bisq-network/bisq/pull/2652
- https://github.com/bisq-network/bisq/pull/2656
- https://github.com/bisq-network/bisq/pull/2655
- https://github.com/bisq-network/bisq/pull/2670
- https://github.com/bisq-network/bisq/pull/2669
- https://github.com/bisq-network/bisq/pull/2665
- https://github.com/bisq-network/bisq/pull/2667
- https://github.com/bisq-network/bisq/pull/2680
- https://github.com/bisq-network/bisq/pull/2699
- https://github.com/bisq-network/bisq/pull/2707
- https://github.com/bisq-network/bisq/pull/2648
- https://github.com/bisq-network/bisq/pull/2719
- https://github.com/bisq-network/bisq/pull/2722
- https://github.com/bisq-network/bisq/pull/2733
- https://github.com/bisq-network/bisq/pull/2701
- https://github.com/bisq-network/bisq/pull/2742
- https://github.com/bisq-network/bisq/pull/2736
- https://github.com/bisq-network/bisq/pull/2737
- https://github.com/bisq-network/bisq/pull/2763
- https://github.com/bisq-network/bisq/pull/2753
- https://github.com/bisq-network/bisq/pull/2752

**BSQ amount requested:** `2720`

### Since May 2019
- https://github.com/bisq-network/bisq/pull/2787
- https://github.com/bisq-network/bisq/pull/2801
- https://github.com/bisq-network/bisq/pull/2813
- https://github.com/bisq-network/bisq/pull/2854
- https://github.com/bisq-network/bisq/pull/2864
- https://github.com/bisq-network/bisq/pull/2870
- https://github.com/bisq-network/bisq/pull/2884
- https://github.com/bisq-network/bisq/pull/2890
- https://github.com/bisq-network/bisq/pull/2903
- https://github.com/bisq-network/bisq/pull/2905
- https://github.com/bisq-network/bisq/pull/2930
- https://github.com/bisq-network/bisq/pull/2937
- https://github.com/bisq-network/bisq/pull/2943
- https://github.com/bisq-network/bisq/pull/2945
- https://github.com/bisq-network/bisq/pull/2947
- https://github.com/bisq-network/bisq/pull/2952
- https://github.com/bisq-network/bisq/pull/2953
- https://github.com/bisq-network/bisq/pull/2954
- https://github.com/bisq-network/bisq/pull/2963
- https://github.com/bisq-network/bisq/pull/2964
- https://github.com/bisq-network/bisq/pull/2968
- https://github.com/bisq-network/bisq/pull/2976
- https://github.com/bisq-network/bisq/pull/2981
- https://github.com/bisq-network/bisq/pull/2983
- https://github.com/bisq-network/bisq/pull/3063
- https://github.com/bisq-network/bisq/pull/3064
- https://github.com/bisq-network/bisq/pull/3103
- https://github.com/bisq-network/bisq/pull/3107
- https://github.com/bisq-network/bisq/pull/3113
- https://github.com/bisq-network/bisq/pull/3118
- https://github.com/bisq-network/bisq/pull/3119
- https://github.com/bisq-network/bisq/pull/3124
- https://github.com/bisq-network/bisq/pull/3127
- https://github.com/bisq-network/bisq/pull/3131
- https://github.com/bisq-network/bisq/pull/3134
- https://github.com/bisq-network/bisq/pull/3139
- https://github.com/bisq-network/bisq/pull/3142
- https://github.com/bisq-network/bisq/pull/3148
- https://github.com/bisq-network/bisq/pull/3149
- https://github.com/bisq-network/bisq/pull/3152
- https://github.com/bisq-network/bisq/pull/3153
- https://github.com/bisq-network/bisq/pull/3154
- https://github.com/bisq-network/bisq/pull/3156
- https://github.com/bisq-network/bisq/pull/3164
- https://github.com/bisq-network/bisq/pull/3165
- https://github.com/bisq-network/bisq/pull/3166
- https://github.com/bisq-network/bisq/pull/3168
- https://github.com/bisq-network/bisq/pull/3172
- https://github.com/bisq-network/bisq/pull/3176
- https://github.com/bisq-network/bisq/pull/3177
- https://github.com/bisq-network/bisq/pull/3179
- https://github.com/bisq-network/bisq/pull/3181
- https://github.com/bisq-network/bisq/pull/3184
- https://github.com/bisq-network/bisq/pull/3188
- https://github.com/bisq-network/bisq/pull/3189
- https://github.com/bisq-network/bisq/pull/3192
- https://github.com/bisq-network/bisq/pull/3193
- https://github.com/bisq-network/bisq/pull/3196
- https://github.com/bisq-network/bisq/pull/3199

**BSQ amount requested:** `5860`

### April 2019
I was working mainly on v1.0.0, v1.0.1 and 1.1.0 this month and following PRs were merged to master.
Testing and release efforts are part of the Desktop Maintainer role.

**PRs merged to master**
- https://github.com/bisq-network/bisq/pull/2723
- https://github.com/bisq-network/bisq/pull/2724
- https://github.com/bisq-network/bisq/pull/2725
- https://github.com/bisq-network/bisq/pull/2734
- https://github.com/bisq-network/bisq/pull/2740
- https://github.com/bisq-network/bisq/pull/2742
- https://github.com/bisq-network/bisq/pull/2746

**BSQ amount requested:** `5032`

Besides my work on the Bisq repository I did some improvements on the website in April again. 

**PRs merged into website**
- https://github.com/bisq-network/bisq-website/pull/168
- https://github.com/bisq-network/bisq-website/pull/169

**BSQ amount requested:** `100`

### Since May 2019

I was working mainly on v1.1.1, v1.1.2, v1.1.3, v1.1.4 and 1.1.5 in that time and following PRs were merged to master.
Testing and release efforts are part of the Desktop Maintainer role.

**PRs merged to master**
- https://github.com/bisq-network/bisq/pull/3157
- https://github.com/bisq-network/bisq/pull/3180

**BSQ amount requested:** `200`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I'm working mainly on the new protection tools that will be released in 1.2.0.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

To make it more transparent and give people an idea how much effort which role means, I'll try to split up the overall number for each role.

- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63#issuecomment-489085542 `(5220 BSQ for April + 900 BSQ for May + 660 BSQ for June + 2220 BSQ for July + 1854 BSQ for August + 1300 BSQ until end of Cycle 5) -> `**`(12154 BSQ)`**
- Growth: https://github.com/bisq-network/roles/issues/42#issuecomment-489090821 (only for April as @m52go took over the primary role) **`(800 BSQ)`**
- Analytics: https://github.com/bisq-network/roles/issues/40#issuecomment-489092178 `(180 BSQ for April + 54 BSQ for May + 150 BSQ for June + 300 BSQ for July + 360 BSQ for August + 360 BSQ until end of Cycle 5) -> `**`(1044 BSQ)`**
- Bitcoin Fullnode Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-489098822 `(50 BSQ * 5) -> `**`(250 BSQ)`**
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31#issuecomment-489099441 (Only for April as role is not necessary anymore with the DAO live) **`(580 BSQ)`**
- Bisq Design Maintainer: https://github.com/bisq-network/roles/issues/75#issuecomment-489099596 `(25 BSQ * 5) -> `**`(125 BSQ)`**
- GitHub Admin:  https://github.com/bisq-network/roles/issues/16#issuecomment-523029125 `(30 BSQ for June + 270 BSQ for July + 40 BSQ for August + 25 BSQ until end of Cycle 5) -> `**`(365 BSQ)`**
- Transifex Admin (secondary): https://github.com/bisq-network/roles/issues/20 `(500 BSQ for April + 150 BSQ for May after that @y3v63n took over primary role completely) -> `**`(650 BSQ)`**

**BSQ amount requested for all these roles (see detailed amount for each role):** `15968`

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bisq Events Maintainer: https://github.com/bisq-network/roles/issues/65

**Comment by ripcurlx** [comment]
I'll delay all compensation requests until August 2019 (roughly cycle 4), because of taxation and insurance reasons in my home country.

**Comment by ripcurlx** [comment]
I continue to delay request for compensation until cycle 5.

**Comment by MwithM** [comment]
Closed as accepted
