### ISSUE TITLE
For January 2018

### ISSUE THREAD

**Issue by maskoficarus** [bisq-network/compensation#27]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: **100**
 - BSQ address: **B14Kx2iNpmUg1ZefDFinwcwx1oSzLh5abGo**

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

**Development work:**

- Implement "Support a 'CMD+Enter' keyboard shortcut for sending arbitration chat message" (Merged PR: https://github.com/bisq-network/exchange/pull/1160)

**Comment by cbeams** [comment]
Great to see that you submitted this, @maskoficarus!

I have been appreciating using `CMD+Enter` every day since you implemented this. Thanks again.

**Comment by cbeams** [comment]
This request is staged for voting at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1018906710.

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
