### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by blabno** [bisq-network/compensation#274]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 200
 - BSQ address: B1PuuhNN2CnLAS4wiSTkdXEBqqTx4UMF4Nn

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

New asset review.

**Comment by Mycelial1** [comment]
I would vote on this if you provided some details :)

**Comment by MwithM** [comment]
`Closing old issue`
