### ISSUE TITLE
Before April 2019

### ISSUE THREAD

**Issue by criptonauta** [bisq-network/compensation#275]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 304.75
 - BSQ address: B1NT4jRKVNTVQ746y11Vy9jBECApJxQgKUW

## Contributions delivered

> I've started with some translation / localization service for Bisq app 2 years ago. Only recently I found out about the compensation system. After being more active, I thought it's worth to request compensation for that work.

To sort what was done prior to April 2019, I used the following filters on Transifex:

**For Translation:**

`translator:criptonauta translated_before:2019-03-31`

Also selected all strings

![image](https://user-images.githubusercontent.com/6478038/57196115-af7b1e80-6f27-11e9-8174-d08e6346104f.png)

_It returned 161 Strings with 415 words_
415 words * 0.1USD per word = 41.5

**For Revision:**

`reviewer:criptonauta translated_before:2019-03-31`

Also selected all strings
![image](https://user-images.githubusercontent.com/6478038/57196180-3fb96380-6f28-11e9-9578-b0d85ab78372.png)

_It  returned 852 strings with 5265 words_
5265 words * 0.05 = 263.25

**Comment by MwithM** [comment]
`Closing old issue`
