### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by criptonauta** [bisq-network/compensation#276]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 111,65
 - BSQ address: B1NT4jRKVNTVQ746y11Vy9jBECApJxQgKUW

## Contributions delivered

> Translation (pt_BR)
To sort what was done during April 2019, I used the following filters on Transifex:

**For Translation:**

`translator:criptonauta translated_before:2019-04-30 translated_after:2019-04-01`

Also selected all strings

![image](https://user-images.githubusercontent.com/6478038/57196606-72fdf180-6f2c-11e9-8255-5949d3260eeb.png)

_It returned 29 Strings with 472 words_
472 words * 0.1USD per word = 47.2

**For Revision:**

`reviewer:criptonauta translated_before:2019-04-30 translated_after:2019-04-01`

Also selected all strings
![image](https://user-images.githubusercontent.com/6478038/57196635-ae002500-6f2c-11e9-885d-8fb4cbb26910.png)

_It  returned 188 strings with 1289 words_
1289 words * 0.05 = 64,45

## Contributions in progress

> _Still concluding the revision for pt_BR language so it can be added back to Bisq app on next release_

**Comment by MwithM** [comment]
`Closing old issue`
