### ISSUE TITLE
For April 2019, Cycle 1

### ISSUE THREAD

**Issue by lyyva** [bisq-network/compensation#278]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 420
 - BSQ address: B1GCDozS2rf8AhKszR9Bbpu3pa769jCfL5a

## Contributions delivered
 
- completed testing of trading process

- completed testing of altcoin trading accounts
- started testing DAO governance, but was unable to complete this time.
Outside of the fixed testing processes, i also participated in most DAO testing rounds on testnet and tested trades on mainnet. 

Testing results can be seen on bisq.ontestpad.com.

Bugreports:
- https://github.com/bisq-network/bisq/issues/2714
- https://github.com/bisq-network/bisq-docs/issues/128
- https://github.com/bisq-network/bisq/issues/2708

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress]

- I would like to keep going with any required testing.

- I keep an ongoing spreadsheet with UI/UX problems and feedback and will hopefully be able to integrate some of that in future releases.
- Going forward, i would like to start a knowledge base/troubleshooting helper integrated in the app.
If anyone is up for this, ping me!

This compensation request is based on hours, since it required setting up the testing environment etc. Further testing will hopefully be less time-intense.

**Comment by ripcurlx** [comment]
> Testing results can be seen on bisq.ontestpad.com.

@lyyva which version did you test on testpad, so I can export the report of your tests.

**Comment by ripcurlx** [comment]
I didn't find your name on any of the reports - did you use another name? Do you still have the invitation link sent via email?

**Comment by devinbileck** [comment]
@lyyva I believe your username on slack/testpad is bisquit?
I have already generated these reports:
https://bisq.ontestpad.com/script/35/report/ACE?auth=99cd2e6ebd1190565c2ba744f16d424b
https://bisq.ontestpad.com/script/31/report/ACE?auth=68660bf7fe39e4dc490920d4a8c48d87

**Comment by lyyva** [comment]
@ripcurlx yep, bisquit - i tried typing in both usernames in the dao proposal, but seems to have gotten lost! Thanks @devinbileck - those are the ones.

**Comment by MwithM** [comment]
`Closing old issue`
