### ISSUE TITLE
For January 2018

### ISSUE THREAD

**Issue by leomcy** [bisq-network/compensation#28]
## **Basic information**

> Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:

BSQ amount requested: 200
BSQ address: B1NEAhGPQveHjsvvetFQSdmpLvnyAdeMiV6

## **Details**

>Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value.

Youtube tutorial bounty.

Produce a "How to buy bitcoin with Euros using Bisq" video #1
https://github.com/bisq-network/youtube/issues/1

**Comment by cbeams** [comment]
This request is staged for voting at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1018906710

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
