### ISSUE TITLE
Cycle 1

### ISSUE THREAD

**Issue by oscarguindzberg** [bisq-network/compensation#283]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `22950`
 - BSQ address: `B17rrWD5BVbx2R8DVxRGkN3FqkppB2mKrjQ`

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- bisq’s bitcoinj 0.14.7 connection handling changes audit (2300 BSQ)
  - Audit: https://github.com/bisq-network/bitcoinj/issues/30
  - Fixes: https://github.com/bisq-network/bitcoinj/pull/31
- Migrate to bitcoinj 0.15 (12400 BSQ)
  - Review bitcoinj 0.15 release release notes https://bitcoinj.github.io/release-notes
  - Use bisq's bitcoinj 0.15 in bisq
    - https://github.com/bisq-network/bisq/pull/2772
  - Rebase bisq’s bitcoinj from bitcoinj 0.15.1
    - https://github.com/bisq-network/bitcoinj/commits/bisq_0.15.1  
    - All commits added by me have a description linking to the commit on the 0.14.7 branch that originated it.
    - Many commits were combined.
    - Many commits were already included on upstream bitcoinj 0.15.1
- Broadcasting DAO proposal txs / bitcoinj "deprecated" confidence problem (3000 BSQ)
    - Report and investigate bug: https://github.com/bisq-network/bisq/issues/2639
    - Create Fix PR (need more analysis) https://github.com/bisq-network/bitcoinj/pull/32
    - Create upstream issue: https://github.com/bitcoinj/bitcoinj/issues/1769 
    - Tests to prove the problem: https://github.com/oscarguindzberg/bitcoinj/commits/tx-confidence-cache
- distributed reputation system (1200 BSQ)
  - Contribute to implement proposal https://github.com/bisq-network/proposals/issues/78
  - Complete implementation of SignedWitnessService.
  - Write SignedWitnessServiceTest
  - See https://github.com/oscarguindzberg/bisq/tree/add-protection-tools-improvements (I added just 1 commit with all the changes. Oscar’s commit is not the latest one because Manfred have a commit dated june 13th (in the future). This is Oscar’s commit: https://github.com/oscarguindzberg/bisq/commit/172d9f658e42d56d192727dae54b6744de6e76e8)
- spy utxos (500 BSQ)
  - Discuss spy utxos with manfred
    - https://github.com/bisq-network/bisq/issues/2604#issuecomment-479273545
  - Ignore dust utxo PR review 
    - https://github.com/bisq-network/bisq/pull/2621
- Misc (1250 BSQ)
  - Bugfix for bitcoinRegtestHost=none mode 
    - https://github.com/bisq-network/bisq/pull/2646
  - Typo 
    - https://github.com/bisq-network/bisq/pull/2647
  - Wallet.findKeyFromPubKeyHash(): Fix ScriptType, use P2PKH.
    - https://github.com/bitcoinj/bitcoinj/pull/1782 
  - Doichain: set p2shHeader
    - https://github.com/bisq-network/bisq/pull/2728
  - Report "Selling BSQ shows weird fee"
    - https://github.com/bisq-network/bisq/issues/2727
  - Help testing the DAO.
- user support (2200 BSQ)
  - https://github.com/bisq-network/bisq/issues/2797
  - https://github.com/bisq-network/bisq/issues/2778
  - https://github.com/bisq-network/bisq/issues/2640
  - https://github.com/bisq-network/bisq/issues/2702
  - https://github.com/bisq-network/bisq/issues/2729#issuecomment-484090604
  - https://github.com/bisq-network/bisq/issues/2758#issuecomment-485445220
  - https://github.com/bisq-network/bisq/issues/2773
  - https://github.com/bisq-network/bisq/issues/2754

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- Proposal for user support improvements
  - https://github.com/bisq-network/proposals/issues/82

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8#issuecomment-490628545 (100 BSQ)

**Comment by MwithM** [comment]
`Closing old issue`
