### ISSUE TITLE
Cycle 1

### ISSUE THREAD

**Issue by lyyva** [bisq-network/compensation#284]
## Summary

 - BSQ requested: 20
 - BSQ address: B196TC3zLzsKAZzQRXzhc8pWjCmJqxXAyR3

## Contributions delivered
filled out the DAO testing survey back before the v1 release. Unfortunately did not take a screenshot, didn´t know back then that i had to, but m52go would be able to confirm.

## Contributions in progress
continously testing, see the other request.

**Comment by MwithM** [comment]
`Closing old issue`
