### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#285]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B122i2L3e1bRmye1r5zZmYh2mCLSsqZuAhY**
## Roles performed
- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-494037683 (2600 BSQ)
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-494052117 (250 BSQ)
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-494031122 (150 BSQ)

Note: Unfortunately I wasn't at my PC to make reports and a compensation request at the beginning of the month. I can publish this one in the DAO at this cycle. I hope it is not too much trouble :)

**Comment by MwithM** [comment]
`Closing old issue`
