### ISSUE TITLE
For Cycle 2 #287

### ISSUE THREAD

**Issue by ArnaudFR86** [bisq-network/compensation#287]
## Summary

 - BSQ requested: 1773
 - BSQ address: B1N9DAjde1BwxeYPNKSwwNN44onubKQzyGH

## Contributions: French translation & Review

Transifex nickname: arnaudFR86

•	Translated:
14944 words from bisq-desktop 14944 * 0,08=1195

•	Reviewed:
16539 words from bisq-desktop 16539 * 0.035=578

![reviewingfrench](https://user-images.githubusercontent.com/50170753/58873976-dc0d8c00-86c7-11e9-9a30-99f02cd760cf.jpg)
![translationtofrench](https://user-images.githubusercontent.com/50170753/58873978-dc0d8c00-86c7-11e9-9af9-af2c785b67ed.jpg)

I have done a big part of the French translation and ask 0.08 per word as it is the price I have been paid before for a similar work. 

I've called another translator to review my work but he did not showed up, so I had to review my own work but I've done it 2 weeks after I've completed the translation, time needed to get a clear mind and a fresh view. 

Also during that time I've been reading Bisq tutorials, used Bisq, checking others translators work, and looked for specific terms. I ask the lower price for the reviewing part 0.035

 I edited le tittle, and amount on 09/06/2019 to not include the part of the translation that have not been yet delivered/uploaded to users.

**Comment by m52go** [comment]
@ArnaudFR86 one suggestion -- would you mind changing the title of this issue to indicate the DAO cycle, e.g., "For Cycle 2"? You can specify the specific time frame within the request, if you need to.

https://docs.bisq.network/compensation.html#create-the-issue

**Comment by huey735** [comment]
@ArnaudFR86 the translation for the website hasn't yet been delivered according to this [standard](https://github.com/bisq-network/proposals/issues/19).

**Comment by ArnaudFR86** [comment]
@huey735 "work in question has been made available to users. "  The French one have been uploaded in 1.1.2 and is avaibable for users, but you are right for the 809 words part.

**Comment by ArnaudFR86** [comment]
Edit: 09/06/2019: The total have been edited according to @huey735 remark, and to follow correct process.

**Comment by MwithM** [comment]
There's 2 compensation requests pointing to the same issue. One was open at 4th june and another on 9th.

**Comment by sqrrm** [comment]
Since there are two compensation requests pointing to this one github issue I will be voting against them both to avoid both getting approved. This is not a vote against the work done, just making sure the process works as intended. A new request for this same work can be created for the next cycle so the work will still be compensated, just that compensation will come later.

I suspect this double request is due to some confusion on how the compensation requests work in the client vs the github issues. @ArnaudFR86 if you have ideas on how to improve on UI, documentation or anything else please voice them.

**Comment by ArnaudFR86** [comment]
quote from the chat yesterday: 

ArnaudFR86 [8 h 18]

Hi guys, one question too, yesterday I have edited my compensation request to change the amount, then I withdrawn my proposal in dao to change the amount and re-submitted to match the new amount, but now I can see that my proposal #287 appear two times in the compensation list, (  with the same good updated amount) it is an issue ? Thanks

Homard [8 h 23]

@ArnaudFR86 I had a similar issue. Without touching anything.

Restarting the application and now it's fine again.

ArnaudFR86 [8 h 30]

@Homard Thanks for you reply, but I rebooted the a few times since yesterday and tried on another computer and it remain two times in the list.. (modifié) 

ArnaudFR86 [8 h 36]

( I restarted the application yesterday thinking it may solve the issue, it had, I mean I saw only one proposal for a certain duration, but then the second one showed again

11/06, so I should close this one  and recreate a new one ? 
why the frist proposal still showing whereas I've delete it before submitting the new one ? I think this can be an issue with the sofware may be to fix.

Thanks for your help.

**Comment by ManfredKarrer** [comment]
Seems the deletion was not well propagated.

**Comment by ArnaudFR86** [comment]
@sqrrm Understood, I will create a new proposal for the next cycle. the initial confusion come from me that included in my proposal some work that have not been yet delivered. one part of the work have been uploaded, but not the website part, I should had made the distinction initialy, Documentation is fine.

@ManfredKarrer after canceling my initial proposal and submitting the second, I kept the computer and the software on for a long time .

Please refuse both proposals and I will re-submit a new one that included the website part if delivered for cycle 3.

Thanks.

**Comment by ManfredKarrer** [comment]
I voted already on the other one. Once the voting starts you should not change or close open proposals.

**Comment by ArnaudFR86** [comment]
Iam sorry, understood, it will not happen again.

**Comment by sqrrm** [comment]
As the first proposal of the two got accepted there should be no need to ask for compensation again.

@ManfredKarrer This case would be a typical reason for having the extra time between proposal submission and voting (BREAK1). It's currently set at 1 day (149 blocks) which was perhaps not enough to conclude this discussion before voting started. I don't see a need to change it, just pointing out why it's there and that perhaps we'll need to change it in the future.
