### ISSUE TITLE
For January 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#29]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: **15550**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value. **Please include only completed work!**_

### Development work:
- Investigate remaining problems with failed transactions, network instability and reported bugs.
- Monitor infrastructure nodes
- Release 0.6.3 [2]
- Release 0.6.4 [3]
- Prepare release 0.6.5 (might get released very soon)
- Work on Bisq DAO [1]
- Setup of 1 new price relay node (200 BSQ for setup)
- Move 2 seed nodes to a dedicated server (2 * 200 BSQ for setup)
- Maintain 6 BTC seed nodes, 2 LTC seed nodes and 2 Dash seed nodes , 3 Bitcoin nodes, 4 price relay nodes, market server and BSQ explorer (19 * 50 BSQ)

See complete Github activity at: https://github.com/ManfredKarrer

[1] https://github.com/bisq-network/exchange/tree/dao
[2] https://github.com/bisq-network/exchange/releases/tag/v0.6.3
[3] https://github.com/bisq-network/exchange/releases/tag/v0.6.4

### Other:
- Communication with contributors and node operators
- On-boarding of new contributors

**Comment by cbeams** [comment]
This request is staged for voting at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1018906710

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
