### ISSUE TITLE
For cycle 2: May 1 - June 6

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#292]
## Summary

 - BSQ requested: 2200
 - BSQ address: B1N4MqESeLjN6PQg2ZsfTEnhsnqQk8J6V16

## Roles performed: Transifex Admin
- Set up and moderated [the first translator call](https://www.youtube.com/watch?v=nAE0EdojliQ&list=PLFH5SztL5cYPPMIBM22SbqrJ01AXTeVY_).
- Updated [the Bisq Translation documentation](https://github.com/arunasurya/bisqtransifex).
- Had phone calls with several translators.
- Did Transifex-specific work (updated settings, teams, dealt with issues, etc).
- Coordinated the new project, bisq-website (calls/discussions with @huey735 , @y3v63n ; creating the bisq-website project on Transifex, etc).
- Reviewed the homepage, vision, Bisq DAO, FAQ, Getting Started and other pages in preparation for file transfer to Transifex, made [suggestions for edits](https://docs.google.com/spreadsheets/d/1P4JMLrcRtSWkxfh9jG7AXkfdgdkEYwgttGgly-ercXc/edit#gid=1623394417).
- Created [the monthly report](https://github.com/bisq-network/roles/issues/20).

Collaborators:
- @y3v63n:  Bisq glossary, query tracker, pull requests for issues, weekly calls, etc.
- @huey735: Bisq website - uploading files, documenting steps, working on the website design to accommodate several languages, etc.
- @m52go: pull requests for edits for the Bisq pages.

**Comment by m52go** [comment]
@arunasurya would you mind changing the title of this issue to indicate the DAO cycle, e.g., "For Cycle 2"? You can specify the specific time frame within the request, if you need to.

**Comment by MwithM** [comment]
`Closed as already voted`
