### ISSUE TITLE
Cycle 2

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/compensation#296]
## Summary
BSQ requested:  30.8
BSQ address: B1LRkpmQrCMcrdC55jdU6nJN5eoQmT9Vowq

## Contributions delivered
Spanish Translator

**Translated** 440 words into Spanish from bisq-website homepage_content and bisq-desktop 
BSQ requested = 30.8 (0.07 x 440)

![1](https://user-images.githubusercontent.com/34950746/59129731-a375e880-893b-11e9-96ef-e38002cc4051.jpg)
![2](https://user-images.githubusercontent.com/34950746/59129732-a40e7f00-893b-11e9-8299-4326930e1813.jpg)

## Contributions in progress

[WIP]
Blog Post: "How Bisq can help Venezuelans buy Bitcoin" https://github.com/bisq-network/bisq-website/issues/180

Collaborators:
@MwithM
@m52go

**Comment by m52go** [comment]
169 BSQ for editing a blog post? That sounds high to me.

Also -- this post would need to be merged over the weekend in order for it to be eligible for compensation before voting begins. I will try to get it done this time, but in the future, know that work [must be merged](https://docs.bisq.network/compensation.html#value-your-work) before it can be compensated.

**Comment by Mycelial1** [comment]
Sure.
I wanted an even number that represented my coordination with writers, editing, and keeping the blog moving forward.

Because the blog role isn't technically defined yet, I will reduce the requested amount and make a separate compensation request to see how the stakeholders respond to it. 

I believe communications like the blog are important to maintain but I am fully prepared for the stakeholders to deny the request if that's how they feel.

**Comment by ArnaudFR86** [comment]
As you said keeping the blog moving forward, I think for the next one,  you should only include the work that have been already delivered as stated here:  "for non-code contributions that means already delivered. "

**Comment by huey735** [comment]
@Mycelial1 Amy work for the translation of the website hasn't been delivered yet according to this [standard](https://github.com/bisq-network/proposals/issues/19).

**Comment by Mycelial1** [comment]
OK. I will hold off until next cycle.
