### ISSUE TITLE
Cycle 2

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#297]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B122i2L3e1bRmye1r5zZmYh2mCLSsqZuAhY**
## Roles performed
- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-500067820 (2600 BSQ)
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-500069605 (300 BSQ)
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-500064245 (100 BSQ)

**Comment by MwithM** [comment]
`Closed as already voted`
