### ISSUE TITLE
For October 2017

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#3]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 1500
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### Development work:
Getting started with Bisq development and community. First real PR merged. Took a long time to write due to inexperience with Bisq and java. Probably should only be a few days work rather than the 10 spent. As mentioned in https://github.com/bisq-network/compensation/issues/1#issuecomment-340487067 it only makes sense to request for the work delivered, not the effort spent.

https://github.com/bisq-network/exchange/pull/986

### Other:
* Feedback on phase zero doc
* Review of account age code
* Compiling Bisq with jdk9 - can be done with effort. Will help gui scaling issues for HDPI screens.

**Comment by cbeams** [comment]
Thanks, @sqrrm. I've entered this in the voting spreadsheet.

**Comment by cbeams** [comment]
I've entered this request in the [stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=0) at 1500 BSQ for address B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#8
