### ISSUE TITLE
For January 2018

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#30]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 400
 - BSQ address: B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

Running of 3 Bitcoin Fullnodes. 
3 onion address 
3 clearnet address
3 VPS servers and one dedicated server.
See: https://github.com/bisq-network/roles/issues/39

Running one Pricenode and one Seednode server.
Paying for a $12 USD / Mounth bitcoinaverage.com Subscription (for the Pricenode)

Running the bisq-contrib mailinglist server

## Compensation calculation:

no Setup

Monthly costs nodes: 5* VPS (50 / node) -> 250
Monthly costs dedicated node 100
Monthly costs mailinglist server: 50
=400

**Comment by cbeams** [comment]
This request is staged for voting at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1018906710

**Comment by cbeams** [comment]
@Emzy, note for future compensation requests that the new Bitcoin Node Operator issue is bisq-network/roles#67 (which superseded bisq-network/roles#39).

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
