### ISSUE TITLE
Cycle 3

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#301]
## Summary

 - BSQ requested: 625
 - BSQ address: B1AV2e3cizdiyraqDXfXGBMBiHikpRfwqjt

## Roles performed: Transifex Admin
- Set up and moderated [the second translator call](https://www.youtube.com/watch?v=K1TG-_ISj2w&list=PLFH5SztL5cYPPMIBM22SbqrJ01AXTeVY_&index=2).
- Successfully transferred the role of the Transifex Admin to @y3v63n (had several calls, online discussions, etc).
- Made minor changes to [the Bisq translator documentation](https://github.com/arunasurya/bisqtransifex/blob/master/translatordocumentation.md).

**Comment by MwithM** [comment]
`Closed as voted already`
