### ISSUE TITLE
Cycle 3

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/compensation#302]
## Summary
 - BSQ requested: 200
 - BSQ address: B1FALz8qtjBSrAJDG8YRNE4yk8RVN3bB6qo

## Contributions delivered
Bug reports:
[bisq-network/bisq/issues/2938](https://github.com/bisq-network/bisq/issues/2938) includes an analysis about the source of the problem.
[bisq-network/support/issues/260](https://github.com/bisq-network/support/issues/260)

## Contributions in progress (not asking for compensation in this cycle)
**Translation**
Translation to Hebrew: #Bisq-desktop
As the photo below shows, 280 strings (3500 words) were translated.

![translate1](https://user-images.githubusercontent.com/52383635/60460723-34936300-9c4d-11e9-9e2c-6bb986aa160c.PNG)

**Comment by MwithM** [comment]
Hi Drazen.
Thanks for translation to Hebrew. At the moment Bisq is not compensating for translations to this language: https://github.com/arunasurya/bisqtransifex/blob/master/translatordocumentation.md#core-languages
Anyway, thanks again for all your have done and I encourage you to keep translating as maybe in the future it could be compensated. When I started translating to Spanish I did it just to learn some English and help to spread this amazing project. It was amazing the first time I saw Bisq client translated to Spanish.

**Comment by y3v63n** [comment]
Hi Drazen,

As MwithM rightly pointed out, Hebrew is not a core languge for Bisq right now, and therefore, translations into it are not compensated. 

We really appreciate your help, but this is how it is right now. If we expand the scope of core languages in future, you can definitely submit your compensation request then.

**Comment by Drazen-V** [comment]
I edited my request.
What should I do about the Reimbursement request on the Bisq app?
Is there a way to edit it? Should I submit a new request?

**Comment by m52go** [comment]
@Drazen-V during the proposal phase, you can delete your proposal and submit a new one. After the proposal phase is over, proposals are locked in.

FYI you will lose the 2 BSQ fee you paid to make the original proposal, and you will need to pay another 2 BSQ to make the new proposal.

**Comment by ManfredKarrer** [comment]
@Drazen-V Reimbursement requests are intended for the new trade protocol (not in place yet). Please use a normal compensation request!

**Comment by Drazen-V** [comment]
I removed the original request, it got removed from the "Proposals for current cycle" window in the app. I placed a new Compensation request, as suggested above.
For some reason I see now the 2 proposals at the same window in the app.

Any idea why the removed proposal shows now (meanwhile we got advanced from the Proposal phase to the Blind vote phase)? Is this a bug?

**Comment by m52go** [comment]
[Something similar](https://github.com/bisq-network/compensation/issues/287#issuecomment-500790282) happened in the last cycle...seems like it might be a bug after all.

**Comment by ManfredKarrer** [comment]
It seems the network and seed nodes have stability issues atm and the remove message was not well propagated. People should down-vote the old proposal....

**Comment by MwithM** [comment]
Closed as old.
