### ISSUE TITLE
Cycle 3

### ISSUE THREAD

**Issue by torachan3** [bisq-network/compensation#305]
## Summary

 - BSQ requested: 20
 - BSQ address: B1G1zmn4WMKd7FJEMRwYCCb4GnsoVj421Ej

## Contributions delivered

I claim the JPY Liquidity Party bounty posted at [bisq-network/growth#140](https://github.com/bisq-network/growth/issues/140)

- Although I did not create an offer on the day of the liquidity party (per bounty requirements), I have created 1 BUY and 1 SELL order that I plan to keep online as a result of learning about Bisq through the Liquidity Party held at the Tokyo Bitcoin Hackers meetup on June 19th.
- Left feedback on my experience of using Bisq for the first time and setting up first orders.

## Contributions in progress

- I plan to keep at least 1 BUY and 1 SELL order online.

![screen](https://user-images.githubusercontent.com/52248779/60768840-7a47a400-a103-11e9-9ac3-589306b93889.png)

**Comment by MwithM** [comment]
`Closed as voted already`
