### ISSUE TITLE
For January 2018

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#31]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 11000
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### Development/UX
https://github.com/bisq-network/roles/issues/63

After merging back the UI-Improvement branch into Development there were a couple of fixes necessary that came up while testing. Also fixed small bugs not related to the ui refactoring. Created issues for every UX suggestion that came up in the click-prototypes and Slack discussions. Prioritization and communication on all issues. Started to work on a mockup for a new onboarding and trading experience. General moderation of `#ux` channel.

[1] https://github.com/bisq-network/exchange/pull/1272
[2] https://github.com/bisq-network/exchange/pull/1276
[3] https://github.com/bisq-network/exchange/pull/1197

### Growth
https://github.com/bisq-network/roles/issues/42

### Analytics
https://github.com/bisq-network/roles/issues/40

### Bitcoin Fullnode Operator
Maintenance of full core node btc.christophatteneder.com:8333. Resizing to 250 GB and patching of instance for spectre/meltdown vulnerability. 

### Other
Communication with contributors

**Comment by cbeams** [comment]
This request is staged for voting at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1018906710

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
