### ISSUE TITLE
Cycle 3

### ISSUE THREAD

**Issue by agb19** [bisq-network/compensation#314]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 300

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Identified, documented and fixed an interop issue on Tails OS, related to an incompatible use of IPv6 in localhost Tor connections: 

- issue: https://github.com/bisq-network/bisq/issues/2840 
- fixed by: https://github.com/bisq-network/bisq/pull/2862

**Comment by MwithM** [comment]
`Closed as voted already`
