### ISSUE TITLE
For January 2018

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#32]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 2650
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### API

This month I've been mostly working on citkane's issues, since he's the first real user of the API ( https://github.com/citkane/bisq-front ) he runs into bugs and regressions and consistently logs them. Two issues remain which I hope to solve this week.

https://github.com/mrosseel/bisq-api/issues/5
https://github.com/mrosseel/bisq-api/issues/6
https://github.com/mrosseel/bisq-api/issues/7
https://github.com/mrosseel/bisq-api/issues/8
https://github.com/mrosseel/bisq-api/issues/9
https://github.com/mrosseel/bisq-api/issues/12
https://github.com/mrosseel/bisq-api/issues/15
https://github.com/mrosseel/bisq-api/issues/16
https://github.com/mrosseel/bisq-api/issues/17

### Hosting
Monthly costs nodes: 50 / node * 5: 250 BSQ

Running:
1 Price node + bitcoinaverage subscription
1 Seed node
2 Bitcoin full nodes
1 Monitoring node + 1 messaging sync node (on one server)
  
### Roles

https://github.com/bisq-network/roles/issues/22#issuecomment-355343121

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
