### ISSUE TITLE
For May - June 2019

### ISSUE THREAD

**Issue by blabno** [bisq-network/compensation#321]
## Summary

> _Specify the total amount of BSQ you are requesting:_

- BSQ requested: 400
- BSQ address: B1ERWi6jd9v1WfJVk6uDgA7L4ohjfj2mcj5

## Contributions delivered

New asset review.

**Comment by freimair** [comment]
which one?

**Comment by blabno** [comment]
BurntBlackCoin, ZeroClassic have been merged in.
Reviewed but not merged: GENIX, bzedge, CMBT, CAT.

**Comment by MwithM** [comment]
Closed as accepted.
