### ISSUE TITLE
For July 2019

### ISSUE THREAD

**Issue by blabno** [bisq-network/compensation#322]
## Summary

> _Specify the total amount of BSQ you are requesting:_

- BSQ requested: 150
- BSQ address: B1ERWi6jd9v1WfJVk6uDgA7L4ohjfj2mcj5

## Contributions delivered

New asset review.

**Comment by freimair** [comment]
which one?

**Comment by blabno** [comment]
Following assets have been merged and there are few others that required review and communication but whose developers remain silent: Particl, Genesis, Myce, Kore, Vertcoin, DarkPay, PENG, Emercoin, SixEleven

**Comment by MwithM** [comment]
Closed as accepted.
