### ISSUE TITLE
Cycle 4

### ISSUE THREAD

**Issue by y3v63n** [bisq-network/compensation#328]
## Summary

- BSQ requested: 920
 
 ## Roles performed: Transifex Admin

- Set up and moderated the [third translator call](https://github.com/bisq-network/growth/issues/153).
- Did Transifex-specific work (updated settings, added new team members, communicated with translators, dealt with issues, etc).
- Sent out invitations to join the Bisq translation team to Chinese, Vietnamese and Thai (our core languages translations into which had stalled) members of Tor and Bitcoin translation teams. Two Chinese translators joined the team as a result and completed software and website translations.
- Moderated the #Transifex channel in Slack.
- Created and launched the first translation [bounty to translate Bisq into Japanese](https://github.com/bisq-network/proposals/issues/104).
- Created the [monthly report](https://github.com/bisq-network/roles/issues/20#issuecomment-517141003).

**Comment by MwithM** [comment]
Great to hear that your translators to Chinese request were this successful.
And of course, Japanese bounty.
