### ISSUE TITLE
For January 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#33]
## Basic information

 - BSQ amount requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**

### Forum operator:
- Maintaining the forum, including backups and updates
(forum operator https://github.com/bisq-network/roles/issues/19)

### Support:
- Providing support for users on forum, reddit, bitcointalk, Slack (chat-bridge channel)
(forum profile https://bisq.community/u/alexej996/summary)

### Moderation:
- Moderating Bisq forum and subreddit (reddit moderator https://github.com/bisq-network/roles/issues/25)

**Comment by cbeams** [comment]
This request is staged for voting at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1018906710

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
