### ISSUE TITLE
Cycle 4

### ISSUE THREAD

**Issue by niyid** [bisq-network/compensation#335]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested:
 1270 BSQ
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

https://github.com/bisq-network/bisq/issues/1896    500 BSQ (updated to reflect critical nature of solution)
https://github.com/bisq-network/bisq/issues/2106    500 BSQ (updated to reflect critical nature of solution)
https://github.com/bisq-network/bisq/issues/2741       20 BSQ
https://github.com/bisq-network/bisq/issues/2944    150 BSQ
https://github.com/bisq-network/bisq/issues/2955    100 BSQ

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

N/A

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

N/A

**Comment by HarryMacfinned** [comment]
@niyid Thank you for coming helping with dev.
Hope you will continue.
(and also hope you could do something with the issues/proposals concerning XMR ;-) )

**Comment by HarryMacfinned** [comment]
My understanding is that, while it may be more reassuring to be assigned, it is not technically githubally necessary in order to work on the task.
(I stand to be corrected if I'm wrong).
And btw, in case you didn't see them, @ManfredKarrer had 2 other open proposals (86 + 87) also concerning XMR/monero.

**Comment by niyid** [comment]
@HarryMacfinned 

Yes, I am aware that it is not necessary to be assigned which is why I have continued to work anyway. Thanks for bringing the other proposals to my attention.

Regards.

**Comment by MwithM** [comment]
Closed as accepted (Cycle 5)
