### ISSUE TITLE
For Cycle 5

### ISSUE THREAD

**Issue by BLOCKCHAINSMOKER** [bisq-network/compensation#337]
## Summary
Hello Everyone, 

I have translated the entire website into farsi on transifex. 

I have provided screenshots of the 100% completion for the website on transifex. 

I have also provided screen shots for the number of words that I have translated. 

I have calculated my BSQ using the fixed rate for all languages which is 0.08 BSQ per source word. 4,966 words (see screenshot for July) x 0.08= 397.28 and 833 words (see screenshot for August )x 0.08= 66.64  66.64+397.28=463.92

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 463.92
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

## Contributions in progress

Any updates will be promptly translated. 

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed
I have not been assigned any specific roles but I would love to get further involved and would be willing to post a bond.

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Please see screenshots.

<img width="1379" alt="Screen Shot 2019-08-27 at 2 55 44 PM" src="https://user-images.githubusercontent.com/52120793/64063988-42477380-cc11-11e9-804e-8545d4c0b2bc.png">
<img width="1028" alt="Screen Shot 2019-08-28 at 3 42 52 PM" src="https://user-images.githubusercontent.com/52120793/64063989-42e00a00-cc11-11e9-9b9a-26ea751a19d3.png">
<img width="1057" alt="Screen Shot 2019-08-28 at 3 43 10 PM" src="https://user-images.githubusercontent.com/52120793/64063990-42e00a00-cc11-11e9-817b-e83b25d5939f.png">

**Comment by huey735** [comment]
The website translation hasn't been delivered yet according to this standard:

>Provide links to contributions you have delivered, the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value.

Hopefully we can deliver it before the end of the cycle and you can go ahead.

**Comment by BLOCKCHAINSMOKER** [comment]
Yes I agree according to the <a href="https://github.com/bisq-network/proposals/issues/19"> "delivered"</a> standard it is not delivered until the work is delivered to the end user. Thanks @huey735!

**Comment by y3v63n** [comment]
Also, the rate we use 0.07BSQ per source word. Sorry for the confusion, I believe it was me who misinformed you.

**Comment by MwithM** [comment]
Closed as not delivered.
Please ask for reopen or send a new compensation request.
