### ISSUE TITLE
For Cycle 5

### ISSUE THREAD

**Issue by KISBITCOIN** [bisq-network/compensation#339]
## Summary

 - BSQ requested: 1500

## Contributions delivered

Created video tutorial guides with step by step demonstration on downloading,verifying,installing,setting up, backing up and trading on Bisq. A new user can have their hand held through the entire process, acclimating them with Bisq.

Part 1 : https://www.youtube.com/watch?v=tIEDEbXN4YE
Part 2 : https://www.youtube.com/watch?v=_Q9MC7-KbXM

**Comment by ArnaudFR86** [comment]
$100-200/ per hour sounds like a lot to me in comparaison with what translators got and time spent. Based on the current views, it makes $2.56$ per view.

**Comment by chimp1984** [comment]
Please remove the hourly rate as it is just for your own estimation important and it would give a wrong signal. $100-$200 per hour is a lot compared to senior Java developers who earn about 80-120 USD. But also here if a developer finds a critical bug in 1 hour he can charge much more than his hourly rate. The value added to Bisq is what counts.

I think the videos have been very good and added a lot of value to Bisq, so I am not shocked by the cost of 1500 for 2 videos. Just the hourly rate gives a wrong signal. Seems you are very professional to be able to deliver high quality work in short time. Good for you!

**Comment by ifarnung** [comment]
I was just introduced to BISQ this month, and I find it a very promising project, and I have been contributing as a market maker. So in studying the DAO, I'm going over all the compensation requests to better understand how BSQ is distributed.
Anyway, I agree with ArnaudFR86 that this compensation request amount seems very high.
The videos are high quality and it must have taken skill to create them to this level, but 1500 BSQ?

**Comment by MwithM** [comment]
Closed as accepted.
