### ISSUE TITLE
For January 2018

### ISSUE THREAD

**Issue by flix1** [bisq-network/compensation#34]
## Basic information

 - BSQ amount requested: 200
 - BSQ address:  B1Pdq17bL5GiitCsNybi3Fc3V8qa7btYnPe 

## Details

Produce a "How to buy bitcoin with INR using Bisq" video
https://github.com/bisq-network/youtube/issues/9

**Comment by ManfredKarrer** [comment]
@flix1 Please add also something for all your efforts on growing Bisq!

**Comment by cbeams** [comment]
This request is staged for voting at https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1018906710

**Comment by cbeams** [comment]
Thanks, @flix1. I agree with Manfred it would be good if (in future requests) you included the other work you complete. It's much appreciated, and ideally we don't want any completed work to go uncompensated.

**Comment by cbeams** [comment]
Closing as complete. See https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
