### ISSUE TITLE
For Cycle 5

### ISSUE THREAD

**Issue by ArnaudFR86** [bisq-network/compensation#341]
## Summary

BSQ requested: 305
BSQ address: B1MuGmtxStddTevSi8DRoXF8XUy4zzWJWpY
 
## Contributions delivered

-Website French Translation (Transifex nickname: arnaudFR86)

![B6](https://user-images.githubusercontent.com/50170753/64163190-17dbfd00-ce41-11e9-8a86-9a14856cd79a.JPG)
![b](https://user-images.githubusercontent.com/50170753/64163191-18749380-ce41-11e9-90a8-d636d4b3205a.JPG)
![B2](https://user-images.githubusercontent.com/50170753/64163192-18749380-ce41-11e9-98b8-368d8421977b.JPG)
![B3](https://user-images.githubusercontent.com/50170753/64163194-18749380-ce41-11e9-887c-50955341f255.JPG)
![B4](https://user-images.githubusercontent.com/50170753/64163196-18749380-ce41-11e9-873b-7a9589a15076.JPG)
![B5](https://user-images.githubusercontent.com/50170753/64163198-19a5c080-ce41-11e9-9966-0d66887d1a50.JPG)

Total 4083x0.07= 285 BSQ
Words from bisq/bisq-website: 197+405+31+18+3884+357= 4892 words
I deduce the 809 words already paid in cycle 2 (see proposal #287) 4892-809= 4083 Words.
Price per word: 0.07 

Reviewing: done by Huey and Steeve, Thank you.

## Roles performed #37 Bitcointalk Moderator

https://github.com/bisq-network/roles/issues/37

BSQ requested: 20 BSQ

Posted 3 messages on the main topic that reach today 6158 views ( it was 2083 when I started), and created a topic about the needs for Devs, and got 196 views and a few comments from users, and provided replies to it.

https://bitcointalk.org/index.php?topic=4509053.msg51359592#msg51359592
https://bitcointalk.org/index.php?topic=5175007.msg52145713#msg52145713

Marketing Help:
-Helped KIS Bitcoin for the French Subtitles of the 2 Videos.
-Posted with @BisqF on Twitter.

**Comment by huey735** [comment]
@ArnaudFR86 you can search all resources of bisq-website at once
![trresources](https://user-images.githubusercontent.com/44140017/64493152-57a54900-d274-11e9-9e75-ae198f7681c0.png)

**Comment by ArnaudFR86** [comment]
@huey735 Hello, If was looking at your comments on my github compensation request, Using the method you showed to me, I have a total of 3874 words, whereas I submitted a request for 4083 words. the difference is due that i prepared the compensation request times ago, and my calculation probably included some identicals translated terms, or updated ones. I tried to get a feedback on my compensation request a few days ago, but now if I modifie it, I will face the same issue as the first one I submited on cycle 2... :/

**Comment by huey735** [comment]
@ArnaudFR86, yeah that's an unfortunate aspect of the way we're counting translated strings right now. What we are looking at is of the number of translated strings what amount did X translate. But in a cycle strings come and ago and you've certainly translated more than those 4083 words as the strings have been updated multiple times since you started translating the bisq-website resource. Maybe we should discuss it over at the #transifex channel on Slack

**Comment by MwithM** [comment]
Closed as accepted.
