### ISSUE TITLE
For cycle 5

### ISSUE THREAD

**Issue by acrual** [bisq-network/compensation#346]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested:
 130
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- I've been testing wallet protection and wallet recovery of version 1.1.6. Results can be viewed in the bisq's team version of testpad (bisq.ontestpad.com, project Bisq116).

- I've also been testing the DAO in the same version 1.1.6 and found a bug that I've reported both in the testpad and here in github https://github.com/bisq-network/bisq/issues/3227 although apparently according to Wiz, it had already been reported and fixed in a PR

Testpad info is available at https://bisq.ontestpad.com/project/1/folder/f36/report/?auth=2a5f15335ce2966d8595e93145d26112

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I have just landed so to say and I'm still figuring out the entire app, the code, the DAO, etc... so nothing yet.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

I'm not responsible for any roles

**Comment by ripcurlx** [comment]
Here is the live guest link for the Testpad report: https://bisq.ontestpad.com/project/1/folder/f36/report/?auth=2a5f15335ce2966d8595e93145d26112

**Comment by acrual** [comment]
> Here is the live guest link for the Testpad report: https://bisq.ontestpad.com/project/1/folder/f36/report/?auth=2a5f15335ce2966d8595e93145d26112

Awesome thanks. Actually I'm going to do a second round of tests with the new version Christophe has just published in slack. Should I edit the compensation request when I'm done or should I simply add another compensation request?

**Comment by ripcurlx** [comment]
Actually that shouldn't be necessary in your case as the changes don't touch the area you're testing. But thanks for the testing so far 👍

**Comment by acrual** [comment]
> Actually that shouldn't be necessary in your case as the changes don't touch the area you're testing. But thanks for the testing so far 👍

Ok understood, many thanks! :)

**Comment by ripcurlx** [comment]
But you could help out @wiz testing the DAO governance which hasn't been tested thoroughly so far. In that case, you don't need to create another compensation request, just add it to this one.

**Comment by acrual** [comment]
> But you could help out @wiz testing the DAO governance which hasn't been tested thoroughly so far. In that case, you don't need to create another compensation request, just add it to this one.

Ok, thanks, perfect, downloading the jar files as I write :)

**Comment by MwithM** [comment]
Closed as accepted.
