### ISSUE TITLE
cycle5

### ISSUE THREAD

**Issue by christophsturm** [bisq-network/compensation#357]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 12000
 
 

## Contributions delivered

guice fixes:
https://github.com/bisq-network/bisq/pull/3043
https://github.com/bisq-network/bisq/pull/3058
https://github.com/bisq-network/bisq/pull/3061
https://github.com/bisq-network/bisq/pull/3086

fix tests and build for jdk 11 and 12
https://github.com/bisq-network/bisq/pull/3081
https://github.com/bisq-network/bisq/pull/3091
https://github.com/bisq-network/bisq/pull/3113

experiment with kotlin for the test suite
https://github.com/bisq-network/bisq/pull/3115

signed witness
https://github.com/bisq-network/bisq/pull/3120

profiling, bug and performance fixes
https://github.com/bisq-network/bisq/pull/3182
https://github.com/bisq-network/bisq/pull/3186
https://github.com/bisq-network/bisq/pull/3213
https://github.com/bisq-network/bisq/pull/3216
https://github.com/bisq-network/bisq/pull/3218
https://github.com/bisq-network/bisq/pull/3214

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by MwithM** [comment]
Closed as accepted.
