### ISSUE TITLE
For Cycle 5

### ISSUE THREAD

**Issue by erciccione** [bisq-network/compensation#358]
## Summary

> _Specify the total amount of BSQ you are requesting:_ 

 - BSQ requested: `800`
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Refactored way to translate *Statistics* page of the website: bisq-network/bisq-website#221
Improved contributor's workflow to make git history clearer: bisq-network/bisq#3217

### Reviews
bisq-network/bisq-website#233
bisq-network/bisq-website#226
bisq-network/bisq-docs#159
bisq-network/bisq-website#211
bisq-network/bisq-website#220
bisq-network/bisq-docs#157
bisq-network/bisq-website#190

**Comment by erciccione** [comment]
This is my first request, any feedback would be very appreciated :)

**Comment by erciccione** [comment]
I gave a look at some other proposals and i had the feeling i was asking to less, i changed the amount in the OP from `500` to `800` BSQ. Please let me know if this rate is fair.

**Comment by wiz** [comment]
Can you delete the 500 BSQ request? I see two requests

**Comment by erciccione** [comment]
@wiz i'm sure i've deleted it right before opening a new one, not sure why it's still showing up. Anyway, i don't seem able to remove it anymore, should i just reject it?

**Comment by sqrrm** [comment]
The remove proposal feature has some issues causing proposals to not get removed even though they should be. We will just have to reject the 500 BSQ request.

**Comment by MwithM** [comment]
Closed as rejected.

**Comment by erciccione** [comment]
Just for the records @MwithM the proposal was accepted. There were 2 opened because for some bug the DAO didn't remove the old one, which was correctly rejected. The correct one was approved.
