### ISSUE TITLE
For cycle 5

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/compensation#359]
## Summary

 - BSQ requested: 140
 
## Contributions delivered

 I've tested the trading process for version 1.1.6. Link to the test report is https://bisq.ontestpad.com/script/98/report  Results can be viewed in the bisq's team version of testpad (bisq.ontestpad.com, project Bisq116).  I minor bug was found regarding the trading chat for traders (issue [3210](https://github.com/bisq-network/bisq/issues/3210))

**Comment by chimp1984** [comment]
Requested amount sounds very low to me....

**Comment by mpolavieja** [comment]
It is really difficult to assess the value of this kind of things.  Moreover I was not assigned to perform the full test but only the critical issues.   How much do you think I should ask?

**Comment by MwithM** [comment]
Closed as accepted.
