### ISSUE TITLE
For January and February 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#36]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 3000
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

I've been refactoring and writing tests for the DAO code. Due to this not being urgent most of the changes are not yet merged and as such I can't claim compensation for them yet. Last month I forgot to lodge a compensation request in time so this request is for both January and February.
- Running 1 bitcoin fullnode for January and February, bisq-network/roles#67
- Work on DAO code, 

Costs:
Monthly cost for dedicated server for bitcoin node: 50
Bitcoinaverage subscription: 12

**Comment by cbeams** [comment]
> Bitcoinaverage subscription: 12

Are you actually operating a pricenode, @sqrrm? You're not listed as an operator in `ProvidersRepository`.

**Comment by sqrrm** [comment]
Manfred took it over in December but it's still on my subscription I believe. I would consider running it again myself but I'm not sure the issues we saw in December were due to my setup or due to the other stuff going on back then.

**Comment by ManfredKarrer** [comment]
@sqrrm Yes would be good if you could take it back if you are sure your setup is stable (it does not have much requirement regarding RAM, CPU). It was probably mainly Tor issues back then. You can start setting it up again and once u have it running let me know then I will kill my instance. If you start yours your HS will be taken anyway.

**Comment by sqrrm** [comment]
@ManfredKarrer Yeah, I can get that back up next week then. Should I get the seednode back up as well? I've, changed the bad service to something that seems a lot better, which is also where I'm running the tor relay node and another bitcoin node which I plan on perhaps also taking back from you or just adding a new one?

**Comment by ManfredKarrer** [comment]
Yes seed node would be good again. I am running atm the majority pf nodes again which should be mitigated. the monitor tool now give much better control so we are better equipped as earlier.
Bitcoin node would be good as well. Take mine back first. We have currently enough.

**Comment by cbeams** [comment]
This request has been staged in the [BSQ stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1285577275)

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
