### ISSUE TITLE
BSQ rate for Cycle 6 is 1.00 USD per 1 BSQ

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/compensation#364]
Proposal https://github.com/bisq-network/proposals/issues/114 got accepted in DAO voting.
At block 595151 (cycle 6 started at 595147) the 90 days average price of 1 BSQ is 1.00 USD.

So it does not change anything from our 1 USD rate used so far, but is it now based on real market price. Expect next cycle to not be the same ;-).

<img width="1017" alt="Screen Shot 2019-09-16 at 16 44 12" src="https://user-images.githubusercontent.com/54558767/64967749-5d68e300-d8a1-11e9-8bad-65b56956243d.png">

**Comment by erciccione** [comment]
I think this is a step forward compared to $1 = 1 BSQ, but that carries potentially big issues. The biggest problem i see in hardcoding a value at the beginning of the cycle is: will people actually use it?

Right now the 90-day average is about 0.96$ and looking at the market is probably going more down, at least in the near future. If the value of 1 BSQ keep decreasing during this cycle, a contributor will have to submit a compensation proposal using $1 = 1 BSQ, but knowing they will receive, for example, $0.80 = 1 BSQ (many contributors tend to submit their proposal near the end of a cycle, which makes sense). This will put the contributor in an ankward situation where they 1) correctly use the average accorded here, devaluating their contribution and therefore losing money, or 2) Ignore the rate decided here and use the average at the moment they submit their proposal, which would lead to disproportional proposals.

I understand this is a very complicate matter that is hard to avoid when you have volatility involved and i don't have a solution, just wanted to give some food for thoughts :)

**Comment by chimp1984** [comment]
@erciccione Agree there is no easy and perfect solution. But using a long term average brings some stability into the price which is overall a good property for the DAO. That the 1 USD price was quite stable over the past months is because most contributors did not want to sell below 1 USD when this was the "promised" price at request time.

**Comment by huey735** [comment]
My disagreement isn't well thought out yet, but I still have reservation regarding abandoning 1 BSQ = 1 USD. So I'm just voicing my position.

**Comment by MwithM** [comment]
Closed as Cycle 6 has finalised.

@chimp1984 Rate for Cycle 7 should be 0.79USD per 1 BSQ?

![imagen](https://user-images.githubusercontent.com/50149324/67125060-41d05f80-f1f4-11e9-8be1-9fc63a331ef7.png)
Stats at block 599.976

**Comment by chimp1984** [comment]
@MwithM Could you post the new BSQ rate for that cycle?
