### ISSUE TITLE
For Cycle 6

### ISSUE THREAD

**Issue by Oscar65** [bisq-network/compensation#365]
## Summary

 - BSQ requested: 51

## Contributions delivered

739 words translated/fixed typos in transifex Spanish (MnM gave me permissions).

## Contributions in progress

I'm starting to learn how bisq-desktop works and trying to fix minor issues.

## Roles performed

Spanish translator. But I want to be also a developer.

**Comment by MwithM** [comment]
Also reviewed typos like missing opening question marks "¿" and also substitued "/n" and "\n", which was used to start a new line, for the now allowed "intro" character.
Compensation is only requested for the easy part to value, which is the translation. He made changes to 115 strings.
![imagen](https://user-images.githubusercontent.com/50149324/65127434-af238180-d9f7-11e9-8320-b1d4bc805bdd.png)

@Oscar65 Remember to add some images in Compensation Requests to provide proof of delivered work.

**Comment by Oscar65** [comment]
I wrote what MnM told me to ask for compensation.

**Comment by Oscar65** [comment]
Sorry, I forgot. This is my first compensation request. I will do in next compensation requests. Thanks.

**Comment by MwithM** [comment]
Closed as accepted.
