### ISSUE TITLE
Cycle 6

### ISSUE THREAD

**Issue by rafaelpac** [bisq-network/compensation#367]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 100
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

I have ordered 200 stickers for spreading the use of Bisq in my city (Brazil).
I have put some of them around our main university walls and bus stops.
I gave some out for friends to spread the message at bars and street food vendors.
https://photos.app.goo.gl/t14T3yubH5chwRdw5

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I still have a few to distribute.
My plan is to organize a few sessions with people interested to help them setup the software and get their first sats for the first transaction fees and deposit.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Not applicable, I guess.

**Comment by wiz** [comment]
Can you post the sticker image data on GitHub somewhere? I want to make Bisq stickers too!

**Comment by rafaelpac** [comment]
I don't have the vector image, only a regular one... I created the design with the simple interface of the website where I bought it, and it was not allowed to download the vector image.

![bisq sticker](https://user-images.githubusercontent.com/6444444/65746418-31d1ce00-e0d5-11e9-8456-b9a51b3d5b32.png)

![image](https://user-images.githubusercontent.com/6444444/65746452-48782500-e0d5-11e9-9118-52aeac9c002a.png)

**Comment by ifarnung** [comment]
This is very cool! Nice work.

**Comment by MwithM** [comment]
@rafaelpac Please change proposal title to "cycle 6" or "for cycle 6".

**Comment by FKrauss** [comment]
that's pretty cool!

**Comment by ripcurlx** [comment]
@rafaelpac Please use for the next request the same GitHub handle for your compensation request in the Bisq DAO to prevent confusions. ATM you used pac instead of rafaelpac.

**Comment by MwithM** [comment]
Closed as accepted.
