### ISSUE TITLE
For Cycle 6

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#368]
## Basic information

- BSQ amount requested: **340**

### Roles:

Operator roles:
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67 `(2 nodes: 2 x 80= 160)`
- 1 Monitor node: `(50)` 
- 1 Markets server: `50` 
- BSQ explorer backup: `80` (Dao full node)

Sum: 340 BSQ

**Comment by MwithM** [comment]
Closed as accepted.
