### ISSUE TITLE
For February 2018 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#37]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: **7900**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value. **Please include only completed work!**_

### Development work:
- Maintaining Bisq exchange repo (merging PRs to master branch)
- Release 0.6.5 [1]
- Release 0.6.6 [2]
- Maintain 6 BTC seed nodes, 2 LTC seed nodes and 2 Dash seed nodes , 3 Bitcoin nodes, 3 price relay nodes, market server and BSQ explorer (18 * 50 BSQ)

Was not working full time that month because of bronchitis.

See complete Github activity at: https://github.com/ManfredKarrer

[1] https://github.com/bisq-network/exchange/releases/tag/v0.6.5
[2] https://github.com/bisq-network/exchange/releases/tag/v0.6.6

**Comment by cbeams** [comment]
This request has been staged in the [BSQ stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1285577275)

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
