### ISSUE TITLE
Cycle 6

### ISSUE THREAD

**Issue by erciccione** [bisq-network/compensation#374]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - Total BSQ requested: `1050 BSQ`
 
 

## Contributions delivered
 BSQ requested: `800 BSQ`	

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

bisq-network/bisq-website/pull/256  
*This PR is in preparation for a new system that will make the bisq-website repository scalable and easier to maintain. See bisq-network/bisq-website/issues/244*.

bisq-network/bisq-docs/pull/161
bisq-network/bisq/pull/3278

## Reviews
BSQ requested: `250 BSQ`	

bisq-network/bisq-website/pull/238
https://github.com/bisq-network/bisq-website/pull/248
bisq-network/bisq-docs/pull/163
bisq-network/bisq-website/pull/253
bisq-network/bisq-website/pull/263
bisq-network/bisq-docs/pull/165
https://github.com/bisq-network/bisq-docs/pull/166

## Proposed features (relevant opened issue) 
BSQ requested: `0 BSQ`

bisq-network/bisq/issues/3303
https://github.com/bisq-network/bisq-website/issues/261
bisq-network/bisq/issues/3352

Edit: Sorry, i used a lower price rate than intended. Total amount is now 1050 BSQ.

Edit2: 2 proposals are showing in the DAO again. Please reject the older one, since it's should have been removed.

**Comment by MwithM** [comment]
Closed as accepted.
