### ISSUE TITLE
For cycles 5 and 6

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/compensation#377]
For cycles 5 and 6
## Summary

> _Specify the total amount of BSQ you are requesting_

 - BSQ requested: `800`

This compensation request :
- follows the https://docs.bisq.network/roles.html#compensation recommandations
- uses 1BSQ=1USD as basis
- is for cycle 5 and for cycle 6. (I didn't make a CR for cycle 5 previously).

### Substantive reports

- Fees and connectivity monitoring | (BSQ requested = `200 (per cycle)`)
Concerned monitored data files : https://github.com/HarryMacfinned/bisq-monitor
TL;DR: NTR, nodes were delivering coherent fees. 1 exceptions alert transmitted for cycle 6.

- Prices monitoring | (BSQ requested = `200 (per cycle)`)
TL;DR: NTR, nodes were delivering coherent prices, except 1 price alert transmitted for cycle 5. 

See the weekly reports in https://github.com/bisq-network/roles/issues/10 

NB1 : The monitoring role includes also manual sorting of false alarms, ie monitoring several Bisq specific pages + following of Tor metrics page + maillist
NB2 : All the alerts are given on the slack #bisq-monitor and #bisq-pricenode channels

**Comment by MwithM** [comment]
Closed as accepted.
