### ISSUE TITLE
Cycle 6

### ISSUE THREAD

**Issue by doitsu232** [bisq-network/compensation#381]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 306.04
 
## Contributions delivered
Translation English to German of the following strings:

**#bisq-desktop**
displayStrings.properties - 650 words
![screenshot-www transifex com-2019 10 10-18_03_01](https://user-images.githubusercontent.com/7280760/66560949-09dd7280-eb8b-11e9-8706-fd3cb535b581.png)

**bisq-website**
community - 213 words
![screenshot-www transifex com-2019 10 10-18_05_11](https://user-images.githubusercontent.com/7280760/66561264-ba4b7680-eb8b-11e9-977a-97987dc0f970.png)
dao_content.yml - 303 words
![screenshot-www transifex com-2019 10 10-18_08_05](https://user-images.githubusercontent.com/7280760/66561311-d3ecbe00-eb8b-11e9-92f8-cb691ef3da32.png)
images.yml - 29 words
![screenshot-www transifex com-2019 10 10-18_09_28](https://user-images.githubusercontent.com/7280760/66561323-da7b3580-eb8b-11e9-83a2-0c4a65e97d47.png)
main_nav.yml - 18 words
![screenshot-www transifex com-2019 10 10-18_10_08](https://user-images.githubusercontent.com/7280760/66561334-dfd88000-eb8b-11e9-8bea-773969f84067.png)
strings.yml - 2798 words
![screenshot-www transifex com-2019 10 10-18_12_02](https://user-images.githubusercontent.com/7280760/66561353-e7982480-eb8b-11e9-85a7-b2c9fd00079f.png)
vision.md - 361 words
![screenshot-www transifex com-2019 10 10-18_13_38](https://user-images.githubusercontent.com/7280760/66561372-ee269c00-eb8b-11e9-96f9-b80f253cd9a6.png)

website total: 3722 x 0.07 = 260.54 BSQ

**translated words total:** 4372 words x 0.07 = 306.04 BSQ

## Contributions in progress
89 strings untranslated (3966 words)
![screenshot-www transifex com-2019 10 10-18_02_00](https://user-images.githubusercontent.com/7280760/66560810-bc610580-eb8a-11e9-82e6-184494448e75.png)

## Roles performed
Translator

**Comment by ripcurlx** [comment]
@doitsu232 Thanks for the translations. I just went through the not reviewed translations of #bisq-desktop on Transifex and accepted them and/or made some changes. I think we need to look through the German translation to be consistent with the translation of Mediator and Arbitrator. E.g. for Mediator both "Vermittler" and "Mediator" is used in the translation. As "Vermittler" is used already for Arbitrator I think we should use "Mediator" as translations for Mediator.

**Comment by doitsu232** [comment]
i agree on that, let's use "mediator" in all translations. it was actually a bit tricky to find the right translation for that term because it is basically "vermittler" but a slightly different function. thanks for clarifying! :)

**Comment by MwithM** [comment]
Closed as accepted.
