### ISSUE TITLE
Cycle 6

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/compensation#382]
## Summary

 - BSQ requested: 662 BSQ

## Contributions delivered

Localization (Pt-br) - APP - review 215 strings -> 2573 words * 0.0375 BSQ per word  == **96 BSQ**
Localization (pt-br) - Website - translation 112 strings ->  3553 words * 0.075 BSQ per word = **266 BSQ**
[Presentation](https://www.meetup.com/bitcoinsaopaulo/events/264278690/) to Local São Paulo community - **100 BSQ** 
[Tutorial](https://www.meetup.com/Bitcoin-Copenhagen/events/264684618/) with Local Community Copenhagen, Denmark - [presentation](https://docs.google.com/presentation/d/1SXlgJb92x2qPOr1thCbYm5KL1mCmMzu0NW1bnvm_-E4/edit?usp=sharing) - **100 BSQ**
Local Support over telegram (https://t.me/bisqbrasil): **100 BSQ**

## Contributions in progress

- Payment methods research BR (no link yet)
- Porting the PT-BR language to the website -> in progress, was waiting for the new language system to be merged
- Local BR support telegram channel - https://t.me/bisq_brasil

## Roles performed

- Analytics admin - [Sept report](https://github.com/bisq-network/roles/issues/91)

Translations details:
transifex user: **fkrauss**

App strings review
<img width="1116" alt="app reviews" src="https://user-images.githubusercontent.com/4820683/66568436-b60e6180-eb69-11e9-875c-2f085f9154b1.png">

Website translation
<img width="1192" alt="site translations" src="https://user-images.githubusercontent.com/4820683/66568504-df2ef200-eb69-11e9-9be2-105b871d89bf.png">

**Comment by MwithM** [comment]
Closed as accepted.

**Comment by MwithM** [comment]
Closed as accepted.
