### ISSUE TITLE
For Cycle 7

### ISSUE THREAD

**Issue by KamilPredecki** [bisq-network/compensation#388]
- BSQ requested: 1800
 
## Contributions delivered

All three videos below are in Polish.

How works decentralized exchanges based on BISQ exchange:
Part 1: https://www.youtube.com/watch?v=dhPaI4Tb8qo

Fully trade on BISQ exchange:
Part 2: https://www.youtube.com/watch?v=d3wc51tjTnw

Interview with Developer (Bernard) about BISQ DAO, Bonding, Future of BISQ exchange, Creating account on BISQ, Creating Compensation
Part 3: https://www.youtube.com/watch?v=_8J0beJ99-A&t

**Comment by MwithM** [comment]
Closed as accepted.
