### ISSUE TITLE
For February 2018

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#39]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 2650
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### API

This month was mostly filled with discussions with @blabno and testing of his integration tests, also discussions and testing with citkane on his bisq-engine and bisq-front efforts

Issues solved in api:
https://github.com/mrosseel/bisq-api/issues/19
https://github.com/mrosseel/bisq-api/issues/20

PR's reviewed:
https://github.com/mrosseel/bisq-api/pull/23

### Hosting
Monthly costs nodes: 50 / node * 5: 250 BSQ

Running:
1 Price node + bitcoinaverage subscription
1 Seed node
2 Bitcoin full nodes
1 Monitoring node + 1 messaging sync node (on one server)
  
### Roles

https://github.com/bisq-network/roles/issues/22#issuecomment-355343121

**Comment by cbeams** [comment]
This request has been staged in the [BSQ stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1285577275).

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
