### ISSUE TITLE
For Cycle 7

### ISSUE THREAD

**Issue by blabno** [bisq-network/compensation#393]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 1050
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

* Assets review: YANG, Ergo, VFC, VARIUS, MSR, XSL, XND, BitcoinV, ZOD, CTSC, Faircoin, uPlexa, XND, ANI (200 BSQ)
* meetups:
  - Present Bisq at Krakow-Bitcoin-Meetup https://www.meetup.com/pl-PL/Krakow-Bitcoin-Meetup/events/264497027 (250 BSQ)
  - Present Bisq at Wroclaw Blockchain Meetup https://www.meetup.com/pl-PL/Wroclaw-Blockchain-Meetup/events/265145693/ (500 BSQ)
* podcast: (100 BSQ)
  - Fully trade on BISQ exchange: https://www.youtube.com/watch?v=d3wc51tjTnw
  - Interview with Developer (Bernard) about BISQ DAO, Bonding, Future of BISQ exchange, Creating account on BISQ, Creating Compensation: https://www.youtube.com/watch?v=_8J0beJ99-A&t

**Comment by ripcurlx** [comment]
@blabno Could you please paste your transaction ID as a comment in your compensation requests as it might be confusing to stakeholders that you have two compensation requests with the same name.

**Comment by blabno** [comment]
@ripcurlx I thought that each request inside Bisq app has a link pointing to individual github issues, not?

**Comment by MwithM** [comment]
Closed as accepted.
