### ISSUE TITLE
For Cycle 7

### ISSUE THREAD

**Issue by blabno** [bisq-network/compensation#394]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 10000
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

* Minimal API https://github.com/bisq-network/incubator-bisq-api/pull/2
* Add Docker support https://github.com/bisq-network/incubator-bisq-api/pull/12

**Comment by MwithM** [comment]
Closed as rejected (duplicity).
