### ISSUE TITLE
For Cycle 7

### ISSUE THREAD

**Issue by Oscar65** [bisq-network/compensation#396]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 374.85
 
### Bisq desktop in Spanish

3701 words translated

![201910112218 WordsTranslated](https://user-images.githubusercontent.com/26004574/68527644-71512400-02e9-11ea-978d-ce6592a643b4.png)

1059 words reviewed

![Captura de pantalla de 2019-10-24 07-17-11](https://user-images.githubusercontent.com/26004574/68527638-68605280-02e9-11ea-9985-3116877d3c0c.png)

## Translation work summary ( BSQ)

Spanish is one of the [core languages](https://github.com/arunasurya/bisqtransifex/blob/master/translatordocumentation.md#core-languages).
Its translation work uses the [compensation rate](https://github.com/arunasurya/bisqtransifex/blob/master/translatordocumentation.md#compensation-requests) as followed:

Translated: 3701 x 0.07 = 259.07 USD
Edited & Reviewed: 1059 x 0.035 = 37.065 USD

BSQ amount: 296.135 / 0.79 = 374.85 BSQ

## Roles performed

Translator

**Comment by MwithM** [comment]
Why are translations since september 25th?

**Comment by Oscar65** [comment]
You sent me this screenshot on slack.com after my translation to add it to CR because after your fixes, transifex.com will show you as translator.

**Comment by MwithM** [comment]
Ok it's true, you didn't ask a CR for translation on last cycle.

**Comment by MwithM** [comment]
Closed as accepted.
