### ISSUE TITLE
For October 2017

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#4]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 6000
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### General notes
As I'm in my first few weeks supporting bisq, working mainly on the user-facing side of the client, I had lots of set-up tasks to do to get everything up and running and to understand and simulate all use-cases within the client locally. Still, as we will focus on output and contribution to bisq that is finished, I'll stick to that.

### Bisq Monitoring Sheet
https://docs.google.com/spreadsheets/d/1o-I5fAx7DJRVqYjW8fPbo0ztlGIhIZ1EM2iLc5aEHnA/edit?usp=sharing
Before changing anything in the client it is necessary to be able to draw a line in the sand and to think about how we measure improvements within the client. The bisq monitoring sheet is the first step to get an up-to-date picture of our platform and our current progress. I started using exported data from the client in the beginning, but switched using the bisq-api to get live data into the sheet. At the moment you can use the sheets to see our current revenue growth rate and predictions for the current month (predictions will get more realistic after the first couple of days). Also there are a couple of fields to simulate platform and value growth of the bisq token itself. It should give everyone a feeling if bisq  would be a regular business, how long it would take to be cashflow positive. Starting from here, I think it is important that we'll define together our KPIs (Key Performance Indicators) which will give us actionable insights to see if changes in different versions of a client where successful or not. This is necessary, as the market is changing so quickly and external influences make it not possible to make assumptions just looking on total number of trades or volume.

### Bisq Click Prototypes for Gathering User Feedback
The ones who know best, what would help us to grow our customer base, are our customers. Because of that, I created two click prototypes of the two most important tasks users can do on our platform. Sell & Buy Bitcoins (or other Cryptocurrencies). People can have a look at the status quo (development branch) of bisq and leave comments and engage within discussions while interacting with the prototype. I'll continue to engage the bisq community to click through our current client and think about what always bothered them and would make their lives easier to complete their tasks.

Bob wants to sell BTC (Create Offer): https://invis.io/D6E67JWFH
Alice wants to buy BTC (Take Offer): https://invis.io/46E67NTQR

Starting from the gathered feedback, I'll then suggest changes within the client simulating changed behavior with click-prototypes to prevent building stuff that might only seem to be an improvement from my side. I'll only do this for the bigger and more critical changes as they might need a couple of iterations before finding a rough consensus. Smaller changes and improvements will be done directly within the current codebase, where discussions can be handled within the pull request itself, if necessary.

Although I've had my first cherry pick commit pull request experience this month, I'm looking forward to make my first proper pull requests this month. Feel free to ask me anything in more detail either here or within slack (dm, #ux or #general).

**Comment by cbeams** [comment]
@ripcurlx, regarding this being your first request, and not yet having a BSQ address, you can generate one by opening your Bisq client, clicking `CMD-d` and clicking the "DAO" icon that appears in the upper right corner. From that screen, you'll see a BSQ address in the "Receive" tab. You can then paste that address into the description above, and I'll add it to the stake and voting spreadsheet for you. Thanks!

**Comment by ripcurlx** [comment]
@cbeams: Thanks! I've just updated my request.

**Comment by cbeams** [comment]
I've entered this request in the [stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=0) at 6000 BSQ for address B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#8
