### ISSUE TITLE
Cycle 7

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/compensation#405]
## Summary

 - Total BSQ requested: **303 BSQ**
 
## Contributions delivered

I´ve tested the batch / bootstrapping signing process introduced for version 1.2.0 in order to have enough signing seeds so the day to day singing process runs properly once version 1.2.0 was deployed. BSQ requested for this task: **126 BSQ**.  

I've tested the trading process for version 1.2.0. Link to the testpad report is https://bisq.ontestpad.com/script/111/report.  BSQ requested for this task : **177 BSQ**

## Contributions in progress

I have submitted a proposal to make an improvement on the signing process.  https://github.com/bisq-network/proposals/issues/133

**Comment by chimp1984** [comment]
It feels very low from what I have seen from your valuable contributions.

**Comment by MwithM** [comment]
Closed as accepted.
