### ISSUE TITLE
For Cycle 7 (Deferred)

### ISSUE THREAD

**Issue by niyid** [bisq-network/compensation#409]
<strike>
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested:
 
 
## Contributions delivered
> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- https://github.com/bisq-network/bisq/issues/3292 / https://github.com/bisq-network/bisq/issues/3303 / https://github.com/bisq-network/bisq/issues/3352 **`1000 BSQ`**
- https://github.com/bisq-network/bisq/issues/3510 **`1000 BSQ`** (This was reviewed up both because there was an initial error in including a contribution that has been removed and the opinion that it was initially under estimated in the first place. This issue was a showstopper and was also discovered, the expected outcome defined and fixed).

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- https://github.com/bisq-network/proposals/issues/110

1. Migrated [The XMR Integration Incubator](https://github.com/bisq-network/incubator-bisq-xmr-integration) to Protocol v1.2. This had an impact on the trading views as expected and of course the expected timelines.
2. Created a diverged replica of the previously existing trade views for XMR. These will later converge in areas where there are commonalities.

- https://github.com/bisq-network/bisq/issues/3229
- https://github.com/bisq-network/bisq/issues/3231
- https://github.com/bisq-network/bisq/issues/3328
- https://github.com/bisq-network/bisq/issues/3338
- https://github.com/bisq-network/bisq/issues/3408

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

N/A
</strike>

**Comment by ripcurlx** [comment]
> * [bisq-network/bisq#3292](https://github.com/bisq-network/bisq/issues/3292) / [bisq-network/bisq#3303](https://github.com/bisq-network/bisq/issues/3303) / [bisq-network/bisq#3352](https://github.com/bisq-network/bisq/issues/3352) **`1000 BSQ`**
> * [bisq-network/bisq#3317](https://github.com/bisq-network/bisq/issues/3317) **`400 BSQ`**
Is this work already delivered? Merged in master? I think both were in an open PR I reviewed yesterday.

> * [bisq-network/bisq#3510](https://github.com/bisq-network/bisq/issues/3510) **`600 BSQ`**
This work is delivered and merged into master.

**Comment by niyid** [comment]
[From this comment](https://github.com/bisq-network/bisq/pull/3366#pullrequestreview-314907582)
> utACK
> 
> Still need ack from @ManfredKarrer for changes in DAO code to be able to merge

I was under the impression that merging was a foregone conclusion.

**Comment by chimp1984** [comment]
> Still need ack from @ManfredKarrer for changes in DAO code to be able to merge

This only applies to code in the dao package in core not in Desktop.

**Comment by chimp1984** [comment]
@niyid I don't see the merged PRs only the issues. Feel free to make your compensation request again next months with listing merged PRs only. I support your contribution but that request seems to not follow our rules.

**Comment by niyid** [comment]
Thanks for the support.

There had been many confusing comments concerning code reviews and
acknowledgement over the past few days mostly stemming from the reviewers
who has earlier been busy with v1.2 launch switching to pending PR reviews
while I was also busy trying to keep abreast of impact of the switch on XMR
Integration Incubator. One of such is the comment on DAO code and needing
acknowledgement from Manfred (which I thought was not necessary).

I am fine with waiting till actual PR merge and filing next cycle.

Regards.

**Comment by chimp1984** [comment]
Thanks for your understanding!
