### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/compensation#413]
## Summary

> _Specify the total amount of BSQ you are requesting:_

- Total USD: `$27,200`
- BSQ requested: `$27,200` / $[0.81](https://github.com/bisq-network/compensation/issues/414) = `33580`
- Proposal transaction ID: `30e4147c5bb9c8c271fce803ec65cac95d719d6b2eeb11ec79694f9f0a996a7a` 

 

The worked delivered below is the result of around 230 hours of full-time development work that began at the end of Cycle 7. The large focus was on making the P2P layer more robust (fixing bugs), testable (added ~250 test cases), and making it easier to change in the future (comments, javadocs, cleaner design). It concluded with the v1.2.4 testing the ensured it was stable upon release.

I spent the remaining time split between compensated work (triaging incoming bugs/code reviews) and non-compensated work (keybase questions, new dev onboarding, dev process feedback, writing proposals). 

Overall, it has been a positive experience contributing to Bisq and I hope the community agrees that my work has been valuable to the project. Don't hesitate to get in touch if you have questions or comments.

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

## Testing Efforts (v1.2.4) `$2,000`
[Bugs Filed](https://github.com/bisq-network/bisq/issues/created_by/julianknutsen)
[TestPad Report](https://bisq.ontestpad.com/project/1/folder/f44/report/?auth=c0db84c85870e4e8cecc6340d20bbaa7)

As this was the first time through the manual testing release cycle, I was able to identify a few nice-to-haves for future testing, validate known customer pain points, and reproduce some user-submitted bugs so that the fixes could make it into the release.

## Development Efforts `$25,200`

The development work focused on the P2P layer. It started with full unit testing of the `P2PDataStorage` code that identified numerous edge case bugs and performance issues that were *delivered* in this cycle. The work was very incremental so it should be easy to parse for anyone interested in how or why I made the changes.

Overall, I am very happy with the end state of the code. I believe that the next dev who needs to work with it can do so in a much safer environment and get better feedback about their changes.

#### Feature Development [$5000]
- [Phase 1](https://github.com/bisq-network/proposals/issues/140#phase1) of [Compensation Request Proposals not deleted as expected](https://github.com/bisq-network/proposals/issues/140)

This work involved full testing of the P2P synchronization path (even between multiple instances of `P2PDataStorage`) that identified multiple bugs and performance issues that were *delivered* as part of the cycle.

#### Bug Fixes [$9750]
Full `bug dump` after my review and testing of `P2PDataStorage` can be found [here](https://docs.google.com/document/d/1pxFin3Sw8xK0USdlayWS3iU8crPtGGXX0GYXx1GTrNo/edit?usp=sharing). It lays out what I found, which Pull Requests addressed the various issues, and which items are still outstanding.

P2PDataStorage Audit Fixes [$6000]
- [Misuse of remove() instead of removeMailboxData in P2PService](https://github.com/bisq-network/bisq/pull/3556)
- [Remove messages with non-increasing sequence numbers are accepted](https://github.com/bisq-network/bisq/pull/3558)
- [Add messages with non-increasing sequence numbers are accepted](https://github.com/bisq-network/bisq/pull/3558)
- [addProtectedStorageEntry() returns true when no state is changed](https://github.com/bisq-network/bisq/pull/3558)
- [onDisconnect path not correctly removing PersistablePayloads](https://github.com/bisq-network/bisq/pull/3608)
- [Invalid ProtectedStorageEntry (bad receiversPubKey) isn't validated](https://github.com/bisq-network/bisq/pull/3609)
- [Remove messages seen before Adds were not handled correctly](https://github.com/bisq-network/bisq/pull/3638)
- [TempProposal objects not properly persisted](https://github.com/bisq-network/bisq/pull/3640)

Incorrect Key Usage Bugs [$3000]
- [Duplicate map Entrys due to incorrect 20 vs. 32-byte keys](https://github.com/bisq-network/bisq/pull/3636)
- [Client node receiving duplicate Payloads on GetUpdatedDataRequest](https://github.com/bisq-network/bisq/pull/3636)

Other Individual Bugs [$750]
- ($750) [FileManager audit and delay bug](https://github.com/bisq-network/bisq/pull/3690)

#### Performance Work [$1500]
- [Remove onBatch interfaces in P2PDataStore](https://github.com/bisq-network/bisq/pull/3621) | bisq-network/bisq#3143

#### Code Quality [$8000]
Unit testing of `P2PDataStorage` and associated objects that increased code coverage dramatically and added over 250 tests. This was required to ensure the bug fixes had regression tests and that all changes were done safely. All future changes to this code will be much easier due to the additional safety net these tests now provide.

**v1.2.3**
![v1 2 3-coverage](https://user-images.githubusercontent.com/8082291/70676151-10966d80-1c40-11ea-95cf-0c2c7cc114d7.JPG)

![v1 2 3-tests](https://user-images.githubusercontent.com/8082291/70676289-87336b00-1c40-11ea-9d3d-7c4b8c618fa5.JPG)

**master 12-11-19**
![12-11-master-coverage](https://user-images.githubusercontent.com/8082291/70676147-0e341380-1c40-11ea-8802-7b066d01de61.JPG)

![12-11-master-tests](https://user-images.githubusercontent.com/8082291/70676350-c2359e80-1c40-11ea-8107-cb712e7f6ff2.JPG)

- bisq-network/bisq/pull/3554
- bisq-network/bisq/pull/3557
- bisq-network/bisq/pull/3568
- bisq-network/bisq/pull/3582
- bisq-network/bisq/pull/3583
- bisq-network/bisq/pull/3584
- bisq-network/bisq/pull/3587

### Code Reviews [$600]
- ($100) bisq-network/bisq#3572 | bisq-network/bisq#3461
- ($125) bisq-network/bisq#3734
- ($125) bisq-network/bisq#3718
- ($250) bisq-network/bisq#3773

### Bug Triage [$350]
- ($100) bisq-network/bisq/issues/3672
  - Manual bisection of bug to identify bad commits
- ($250) bisq-network/bisq/issues/3752
  - Only includes the initial work to verify it was not a regression and non-critical. All work related to the fix would go into the cycle where the fix was delivered.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

#### Feature Development
- [Compensation Request Proposals not deleted as expected](https://github.com/bisq-network/proposals/issues/140)

## Roles performed
N/A
> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by MwithM** [comment]
Closed as accepted
