### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by rafaelpac** [bisq-network/compensation#415]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: `459 BSQ`
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

**BUG FIX**
https://github.com/bisq-network/bisq/pull/3625 `350 BSQ`
This bug was preventing offers to be accepted in markets considered risky (where trade limits are imposed to non-signed accounts). It would only happen when there was a range min-max for the offer. Although it was a very small fix, it was a big issue, since the trades were not allowed to complete.
It was affecting lots of users as seen on issues [3601](https://github.com/bisq-network/bisq/issues/3601), [3540](https://github.com/bisq-network/bisq/issues/3540), [3537](https://github.com/bisq-network/bisq/issues/3537), [3663](https://github.com/bisq-network/bisq/issues/3663), [3720](https://github.com/bisq-network/bisq/issues/3720) and [3750](https://github.com/bisq-network/bisq/issues/3750).

**Cosmetic fix** of a tooltip.
https://github.com/bisq-network/bisq/pull/3624 `50 BSQ`

**TRANSLATIONS** `59 BSQ`
My Transifex username is rafaelalvespereira (not possible to change it, but I think I will create a new one there after this cycle).

- Translations to pt-br (646 words = `45.22 BSQ`)
![image](https://user-images.githubusercontent.com/6444444/70846772-831f6d00-1e3b-11ea-863f-8e764fb81297.png)

- Review of translations to pt-br (318 words = `11,13 BSQ`)
![image](https://user-images.githubusercontent.com/6444444/70846882-d645ef80-1e3c-11ea-9ca0-86cbf314d7c7.png)

- Translations to pt (30 words = `2,1 BSQ`)
![image](https://user-images.githubusercontent.com/6444444/70846933-40f72b00-1e3d-11ea-83b9-6e7976143244.png)

- Review of translations to pt (25 words = `0,875 BSQ`)
![image](https://user-images.githubusercontent.com/6444444/70846919-258c2000-1e3d-11ea-884c-50ccff429f1f.png)

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by MwithM** [comment]
Closed as accepted
