### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by lusarz** [bisq-network/compensation#418]
## Summary

 - BSQ requested: 1800
 
## Contributions delivered
This is my first compensation pull request. Some of work was delivered before Cycle 8 (October - November 2019).

**Code contribution (merged pull requests):**
- [Refactor BisqEnvironment](https://github.com/bisq-network/bisq/pull/3362)
BSQ requested: 250

- [Remove not used private methods from BisqEnvironment](https://github.com/bisq-network/bisq/pull/3363)
BSQ requested: 50

- [Refactor FilterWindow](https://github.com/bisq-network/bisq/pull/3364)
BSQ requested: 100

- [Refactor BisqApp - update scene size calculation](https://github.com/bisq-network/bisq/pull/3380)
BSQ requested: 50

- [Refactor BisqApp - update error popup message build](https://github.com/bisq-network/bisq/pull/3381)
BSQ requested: 50

- [Refactor BisqApp - move icon load into ImageUtil ](https://github.com/bisq-network/bisq/pull/3382)
BSQ requested: 50

- [Remove unused stuff from Utilities](https://github.com/bisq-network/bisq/pull/3383)
BSQ requested: 100

- [Refactor BisqEnvironment - create getListProperty](https://github.com/bisq-network/bisq/pull/3432)
BSQ requested: 100

- [Refactor BisqEnvironment - use @Getter annotation for appDataDir ](https://github.com/bisq-network/bisq/pull/3433)
BSQ requested: 50

- [Refactor BisqEnvironment - change type of ignoreLocalBtcNode to boolean](https://github.com/bisq-network/bisq/pull/3434)
BSQ requested: 50

- [Refactor of FilterWindow - eliminate duplicates](https://github.com/bisq-network/bisq/pull/3616)
BSQ requested: 150

- [Remove redundant interfaces from FilterWindow and SendAlertMessageWindow](https://github.com/bisq-network/bisq/pull/3617)
BSQ requested: 150

- [Remove redundant interfaces from SendPrivateNotificationWindow ](https://github.com/bisq-network/bisq/pull/3653)
BSQ requested: 150

- [Use dependency injection in FilterWindow and SendAlertMessageWindow ](https://github.com/bisq-network/bisq/pull/3654)
BSQ requested: 100

- [Refactor OfferView constructor ](https://github.com/bisq-network/bisq/pull/3655)
BSQ requested: 50

- [Split EmptyWalletWindow into BsqEmptyWalletWindow and BtcEmptyWalletWindow](https://github.com/bisq-network/bisq/pull/3660)
BSQ requested: 250

**Code reviews**
- https://github.com/bisq-network/bisq/pull/3658
BSQ requested: 50

- https://github.com/bisq-network/bisq/pull/3661
BSQ requested: 50

## Contributions in progress

- https://github.com/bisq-network/bisq/pull/3586 - code review
- https://github.com/bisq-network/incubator-bisq-api/pull/14 - code review

**Comment by MwithM** [comment]
Hello, please change title to "Cycle 8" or "For Cycle 8"

**Comment by lusarz** [comment]
@MwithM It's my first compensation request, and some of contribution were done before Cycle 8. It's why I set this title. But if it doesn't matter I'll change this title. Just want to be sure

**Comment by MwithM** [comment]
Yeah change the title then at the start of your request you can explain the time of the tasks you're asking for compensation.

**Comment by MwithM** [comment]
Closed as accepted
