### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by PortfelKowalskiego** [bisq-network/compensation#419]
## Summary

 - BSQ requested: 1300
 
 

Film and article in Polish

BISQ - A real decentralized exchange:
YouTube: https://youtu.be/NZzOBUcTI6E

Bisq - decentralized P2P exchange
Article: https://bitcoinpl.org/bisq-zdecentralizowana-gielda-p2p/

**Comment by MwithM** [comment]
Closed as accepted

**Comment by chimp1984** [comment]
@MwithM As far I see there was no compensation request filed, so it was not accepted.
