### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by sundaywar** [bisq-network/compensation#426]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 218
 
## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

2,521 words * $0.07/word = $176.47 / $0.81 BISQ/$ = 218 BISQ

Bisq Translations by sundaywar:
#bisq-desktop / displayStrings.properties / 6 strings:
string 757 - 17 words
string 859 - 253 words
string 861 - 204 words
string 967 - 4 words
string 1528 - 2 words
string 1676 - 6 words

#bisq-website / community / 2 strings:
string 2 - 9 words
string 13 - 152 words

#bisq-website / strings.yml / 25 strings:
string 34 - 1 word
string 39 - 25 words 
string 51 - 56 words
string 59 - 3 words
string 114 - 153 words
string 116 - 206 words 
string 118 - 76 words
string 121 - 228 words
string 123 - 112 words
string 125 - 128 words
string 129 - 255 words
string 137 - 5 words
string 138 - 99 words
string 139 - 9 words
string 140 - 80 words
string 142 - 143 words
string 143 - 12 words
string 144 - 40 words
string 145 - 7 words
string 146 - 32 words
string 148 - 25 words
string 164 - 62 words
string 170 - 14 words
string 181 - 3 words
string 185 - 2 words

#bisq-website / vision.md / 11 strings:
string 2 - 9 words
string 5 - 1 word
string 7 - 1 word
string 8 - 2 words
string 9 - 39 words
string 10 - 6 words
string 12 - 3 words
string 13 - 9 words
string 14 - 10 words
string 15 - 10 words
string 16 - 8 words

![image](https://user-images.githubusercontent.com/50192212/70595929-74199000-1b99-11ea-99c2-a23d99d6a4ed.png)

![image](https://user-images.githubusercontent.com/50192212/70596000-ab883c80-1b99-11ea-80fc-6d9484121cf2.png)

## Contributions in progress

None, I'm done with all of the Spanish translations.

## Roles performed

Translator (Spanish)

**Comment by MwithM** [comment]
Strings related to abandoned altcoins (856 UPX, 859 MSR, etc) were left untranslated on purpose. Anyways, as the work has quality and this wasn't noticed to you before or is written somewhere, I think you should get all the compensation, thanks.

**Comment by sundaywar** [comment]
Ah! I didn't notice that, thank you for the heads up. Will double check next time.

**Comment by sundaywar** [comment]
wallet address: B185tQNrLaaM41kp9j2qn5UCr1DBSb7depL

**Comment by MwithM** [comment]
Closed as accepted

**Comment by MwithM** [comment]
> wallet address: B1******

There's no need for this, it's all done by the DAO when you create a compensation request on Bisq Client. I suggest you to remove-edit this message.
