### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by dlnd1986** [bisq-network/compensation#429]
## Summary

 - BSQ requested: 630 BSQ

## Contributions delivered

Translations from English to German 
Reviewing of German translations

translation rate: $0.07 USD / word
reviewing rate: $0.035 USD / word

**#bisq-desktop**
displayStrings.properties

translated: 15 strings (990 words) $69.30 USD
![screenshot-www transifex com-2019 12 (4)](https://user-images.githubusercontent.com/57072303/70685818-c9919200-1caa-11ea-88ef-dd006d36902c.png)

reviewed: 185 strings (5816 words) $203.56 USD
![screenshot-www transifex com-2019 12 (5)](https://user-images.githubusercontent.com/57072303/70685819-ca2a2880-1caa-11ea-9198-cbe3a4028e9d.png)

**#bisq-website**

community
reviewed: 13 strings (198 words) $6.93 USD
![screenshot-www transifex com-2019 12 (6)](https://user-images.githubusercontent.com/57072303/70685820-cac2bf00-1caa-11ea-9ac2-f0e302061212.png)

dao_content.yml
translated: 6 strings (102 words) $7.14 USD
![screenshot-www transifex com-2019 12 (7)](https://user-images.githubusercontent.com/57072303/70685821-cb5b5580-1caa-11ea-8125-758da85cbae2.png)

reviewed: 37 strings (405 words) $14.175 USD
![screenshot-www transifex com-2019 12 (8)](https://user-images.githubusercontent.com/57072303/70685822-cb5b5580-1caa-11ea-81ac-49fed2a84be4.png)

images.yml
translated: 1 string (2 words) $0.14 USD
![screenshot-www transifex com-2019 12 (10)](https://user-images.githubusercontent.com/57072303/70685824-cbf3ec00-1caa-11ea-85ca-b0e5c2dd7be5.png)

reviewed: 18 strings (31 words) $1.085 USD
![screenshot-www transifex com-2019 12 (9)](https://user-images.githubusercontent.com/57072303/70685823-cb5b5580-1caa-11ea-86c2-ceb28e55f9a4.png)

main_nav.yml
reviewed: 17 strings (18 words) $0.63 USD
![screenshot-www transifex com-2019 12 (11)](https://user-images.githubusercontent.com/57072303/70685825-cc8c8280-1caa-11ea-92e3-6656cf6ae3ec.png)

strings.yml
translated: 11 strings (876 words) $61.32 USD
![screenshot-www transifex com-2019 12 (12)](https://user-images.githubusercontent.com/57072303/70685826-cc8c8280-1caa-11ea-834f-5a34cfde72e3.png)

reviewed: 182 strings (3810 words) $133.35 USD
![screenshot-www transifex com-2019 12 (13)](https://user-images.githubusercontent.com/57072303/70685827-cd251900-1caa-11ea-9569-9524a97b2605.png)

vision.md
reviewed: 16 strings (362 words) $12.67 USD
![screenshot-www transifex com-2019 12 (14)](https://user-images.githubusercontent.com/57072303/70685829-cdbdaf80-1caa-11ea-98f2-90de73654916.png)

**translated words total: 1970 words x $0.07 = $137.90 USD / $0.81 USD = 170.25 BSQ
reviewed words total: 10640 words x $0.035 = $372.40 USD / $0.81 USD = 459.75 BSQ**

## Contributions in progress

BISQ Subtitles

## Roles performed
Translator / Proofreader (German)

**Comment by MwithM** [comment]
Closed as accepted
