### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by trigger67** [bisq-network/compensation#430]
## Summary

 - BSQ requested: 361.58 BSQ

## Contributions delivered

**Bisq desktop in French**

3124 words translated

![image](https://user-images.githubusercontent.com/10185784/70736363-75b99400-1d10-11ea-85b7-b5d61cde1da0.png)

2120 words reviewed

![image](https://user-images.githubusercontent.com/10185784/70736534-d5b03a80-1d10-11ea-90c9-1a0175506c86.png)

**Translation work summary (BSQ)**

French is one of the core languages.
Its translation work uses the compensation rate as followed:

Translated: 3124 x 0.07 = 218.68 USD
Edited & Reviewed: 2120 x 0.035 = 74.20 USD

BSQ amount: 292.88 / 0.81 = 361.58 BSQ

**Other things**

- In parallel of translations, I started to fill the French glossary (https://www.transifex.com/bisq/bisq-desktop/glossary/fr/) [0 USD]
- I created an issue about a bug : https://github.com/bisq-network/bisq/issues/3663  [0 USD]
- I created an issue about a bug/improvment: https://github.com/bisq-network/bisq/issues/3728  [0 USD]

Should I ask something for raising an issue that was fixed ? That will be implemented ?

## Contributions in progress

French translations are not finished, I will finish them before the end of the year and get them reviewed.

I have also set up a local dev environment to start digging in the code / contributing.

**Comment by rafaelpac** [comment]
> Should I ask something for raising an issue that was fixed? 

As far as I know, creating an issue doesn't entitle you to ask for compensation. Only merged Pull Requests are allowed for compensation.

**Comment by MwithM** [comment]
Closed as accepted
