### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/compensation#434]
## Summary

 - BSQ requested: 2900
 - BSQ address: B19JoAPk4AHtWzWeyDZMwNFuFwW4hiY6pbS

## Roles performed: Transifex Admin
- Hosted [a monthly translator call](https://www.youtube.com/watch?v=6p1JTfxnSAM&list=PLFH5SztL5cYPPMIBM22SbqrJ01AXTeVY_&index=4).
- Updated [translator documentation](https://github.com/arunasurya/bisqtransifex) (under review to be merged to Bisq documentation).
- Held calls with several contributors (admins, translators) to get up-to-date information, engage them in the project, etc.
- Addressed some issues on Transifex, updated teams.
- Created [a monthly translator report](https://github.com/bisq-network/roles/issues/20#issuecomment-558416032).

**Comment by ripcurlx** [comment]
> * Created a monthly translator report.

Could you please reference the report in this issue. Thanks!

**Comment by arunasurya** [comment]
Here is the link to the report: https://github.com/bisq-network/roles/issues/20

**Comment by ripcurlx** [comment]
> Here is the link to the report: [bisq-network/roles#20](https://github.com/bisq-network/roles/issues/20)

Could you please directly link the report (comment) for this PR inside of the issue description? In your case it would be: https://github.com/bisq-network/roles/issues/20#issuecomment-558416032.
We also switched from monthly reports to cycle reports. It would be good also to take the cycle duration as reporting timeframe from now on to be consistent with other reports.

**Comment by MwithM** [comment]
Closed as accepted
