### ISSUE TITLE
For cycle 8

### ISSUE THREAD

**Issue by burning2019** [bisq-network/compensation#443]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 1000 
 
 

## Contributions delivered

I have burnt 66 000 BSQ in my role as donation address holder. For this work I have bought a SSD and use a dedicated computer which is seldom connected to the internet in order to increase security. My compensation request includes this expense.

## Contributions in progress

My work is continuous and I have so far burnt BSQ two times.

## Roles performed

> 
I am the donation address holder. In this capacity I buy BSQ for BTC sent to the donation address. The BSQ is then burnt, increasing the value of the remaining BSQ. My work is reported in https://github.com/bisq-network/roles/issues/80

**Comment by ripcurlx** [comment]
> My work is reported in [bisq-network/roles#80](https://github.com/bisq-network/roles/issues/80)

It would be great if you could directly link to your comment in that case: https://github.com/bisq-network/roles/issues/80#issuecomment-561786952. Doing it that way it directly jumps to the comment. This is especially useful as lots of communication took place in this issue.

**Comment by MwithM** [comment]
Closed as accepted
