### ISSUE TITLE
Cycle 8

### ISSUE THREAD

**Issue by bisquser** [bisq-network/compensation#444]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 5200. 
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

I have mediated 104 finished cases so far, during about 1.5 cycles. I request 50 BSQ/case.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

This work goes on daily.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

My summary of my work is given on https://github.com/bisq-network/roles/issues/83
I will improve the report during the coming days, but need to finish the compensation request before the voting begins. I will also give some suggestion how to decrease the rather large number of mediation cases.

**Comment by ripcurlx** [comment]
> My summary of my work is given on [bisq-network/roles#83](https://github.com/bisq-network/roles/issues/83)

It would be great if you could directly link to your comment in that case: https://github.com/bisq-network/roles/issues/83#issuecomment-565570073. Doing it that way it directly jumps to the comment. This is especially useful if this issue grows over time.

**Comment by MwithM** [comment]
Closed as accepted
