### ISSUE TITLE
For cycle 8

### ISSUE THREAD

**Issue by francov99** [bisq-network/compensation#445]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 425
 
 

## Contributions delivered

I carried out a BTC to MXN operation in a face-to-face method of which I created a report talking about the procedure and the experience I had when performing it. I wrote it in the Spanish language East with the objective of informing the Spanish-speaking Bisq community, and encouraging users to know the platform and the options that bisq offers.
That serves as a review and guide for people to be encouraged to use Bisq.

- [medium](https://medium.com/@lofravaz99/mi-primera-experiencia-con-bisq-f24aa6b09e5c) (75 BSQ)
- [DiarioCripto.com](https://diariocripto.com/mi-primera-experiencia-con-bisq/) (175 BSQ)

I wrote an introduction of Bisq for DiaroCripto.com users

- [DiarioCripto.com](https://diariocripto.com/bisq-un-exchange-descentralizado/) (175 BSQ)

## Contributions in progress

> _I am designing a collaborative marketing plan for LATAM and how to grow the market in this area; what means to use, strategies and stuff like that._

**Comment by m52go** [comment]
Appreciate the work, but for future reference, I don't think cross-posting the same article should be charged more than once.

**Comment by MwithM** [comment]
Closed as accepted

**Comment by francov99** [comment]
allright @m52go

**Comment by francov99** [comment]
I will continue to collaborate, thanks =)
