### ISSUE TITLE
For cycle 8

### ISSUE THREAD

**Issue by luisantoniocrag** [bisq-network/compensation#446]
## Summary

 - BSQ requested: 1184
 
 

## Contributions delivered

**Website**
- Fix fr/dao/ button "En savoir plus": [PR](https://github.com/bisq-network/bisq-website/pull/298) (180)
- Fix es/dao/ button "Ver más": [PR](https://github.com/bisq-network/bisq-website/pull/297) (180)
> _It's not just the number of lines changed, I checked the entire bisq website in all languages ​​to get the error. And in the perspective of a developer if you have a button it has to work.
The buttons draw a lot of attention to the users. What expectations would be given if a simple button fails on something that claims to be so technological?._

**Docs**
- Review of Bisq website translated into Spanish: [PR](https://github.com/bisq-network/bisq-website/pull/296/files) (209 BSQ)
- Fix typos of Bisq website translated into Spanish: [PR](https://github.com/bisq-network/bisq-website/pull/296/files) (1 BSQ)
- Translate to Spanish some lines in the Bisq Website: [PR](https://github.com/bisq-network/bisq-website/pull/296/files) (7 BSQ)
> _Review: 4837words × 0.035/0.81 = 209 BSQ‬_
> _Fix typos: 20 × 0.04/0.81 = 1.7 BSQ‬‬_
> _Translations: 83 words × 0.07/0.81 = 7.17 BSQ‬_
> _Unfortunately I made a bad practice by creating only one PR instead of one for each type. That makes reviewing more difficult.I will not repeat it again._

-  [Bisq Article](https://www.morocotacoin.com/2019/12/bisq-un-exchange-descentralizado-y-sin-necesidad-de-registro/) (189 BSQ)
> _ Morocotacoin the main crypto medium of Venezuela, an area that needs to be covered because they already use cryptocurrencies and mainly for remittances_

- I translated Spanish subtitles of bisq videos (73 BSQ)
![2019-12-13_1358](https://user-images.githubusercontent.com/42625753/70828295-ba950780-1db0-11ea-9bf7-af660ae0e83b.png)

> _Translations: 847 words × 0.07/0.81 = 73.19 BSQ‬_

**Videos translation**
-  [BisqDao in Brief playlist translated to spanish](https://www.youtube.com/watch?v=pNvOZlIDYEQ&list=PLFH5SztL5cYPAXWFz-IMB4dBZ0MEZEG_e&index=1) (345 BSQ)

## Contributions in progress 
- I am seeing with other users a strategy to implement bisq in LATAM
- I am currently working to integrate the official [telegram channel for bisq in Spanish](https://t.me/bisqenespanol) and I am looking for places to give workshops on how to trade in bisq.

**Comment by MwithM** [comment]
The article in morocotacoin is written by Akenka Lima. I assume it's a pseudonym.

Did you plan or discuss the creation of this doc somewhere in Bisq?

**Comment by luisantoniocrag** [comment]
is published by Alenka Lima - but I wrote it. (I have proof of it by a telegram conversation)
I'm sorry, I didn't discuss it to the community.

**Comment by MwithM** [comment]
DAO rejected this proposal. I'll keep this issue open a few days for discussion.

**Comment by luisantoniocrag** [comment]
ok, thank you

**Comment by chimp1984** [comment]
@luisantoniocrag 
In the vote details you can see that very few people have voted on your request and those have used very small BSQ amounts. That is the reason why it was rejected as it did not reach the min. required quorum. 
The people who are involved with translations should ask themself why they simply ignored it? If they don't agree with the request they should reject it and post a feedback why. Simply ignoring request in the area where one is active is not the right behaviour from a DAO perspective.
We are all learning with the DAO but we are makeing also too many mistakes and should push ourself a bit harder to get the management of the DAO on track.

**Comment by MwithM** [comment]
Closed as rejected
