### ISSUE TITLE
BTC/USD liquidity week

### ISSUE THREAD

**Issue by jdonmoyer** [bisq-network/compensation#45]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 20
 - BSQ address: B1G3RTdM2tSwkSB5tgno3aETHDdR3Cc2r92

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

**Comment by cbeams** [comment]
Thanks @jdonmyer. I gather you’re claiming the bounty for market making last week, then?

Any further comments you have, experience reports, feedback?

**Comment by jdonmoyer** [comment]
@cbeams yes, for market making.  I had three sells and a buy execute.  More than I expected.  I'm a convert and can't wait for more liquidity especially in other coins.  My experience was positive.  The inability to use national bank transfer in 0.6.6 threw me at first (I didn't realize it was a bug and thought I was doing something wrong), but that got me to check out Cash App which I feel was probably an overall better end to end experience.  I started lurking in slack and on the live streams to see how I can help things grow.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
