### ISSUE TITLE
For Cycle 9

### ISSUE THREAD

**Issue by PortfelKowalskiego** [bisq-network/compensation#453]
## Summary

 - BSQ requested: 1500
 
 

Film and article in Polish

BISQ - A real decentralized exchange:
YouTube: https://youtu.be/NZzOBUcTI6E

Bisq - decentralized P2P exchange
Article: https://bitcoinpl.org/bisq-zdecentralizowana-gielda-p2p/

/// My Issuse For Cycle 8 #419 was not accepted. I forgot compensation request.

**Comment by chimp1984** [comment]
I consider that request in relation to the extent and quality of the delivery too high.

**Comment by PortfelKowalskiego** [comment]
@chimp1984 #419 there was no problem. my friend Kamil from Poland also made films and received 1800. now the bsq price is a lot lower

**Comment by chimp1984** [comment]
Yes we have been too uncritical in the past, that does not mean we should not learn and improve with out management decisions.

**Comment by PortfelKowalskiego** [comment]
@chimp1984 ok I understand, please decide for yourself what sum will be good

**Comment by chimp1984** [comment]
Professional writers (btc journalists) charge about 20 USD/hour. An article like yours would not take them more then 2-3 hours. So for the article (I cannot verify quality as its not my language) I think about 50 USD would be justified. For the video I would not pay more then 100 USD if it would be a freelance job and I am the customer.

**Comment by MwithM** [comment]
Rejected through DAO vote. Open for discussion.
