### ISSUE TITLE
For Cycle 9

### ISSUE THREAD

**Issue by ifarnung** [bisq-network/compensation#454]
## Summary

 - BSQ requested: 1000
 
 

## Contributions delivered

I claim the Russia RUB / BTC Market Maker Bounty  (https://github.com/bisq-network/growth/issues/160)

Maintained at least 4 orders in the RUB/BTC market for September, October, November, December (F2F buy and sell, Electronic bank transfer buy and sell)
Completed 5 trades
Incentivized trading with negative spread.
Wrote summary here: (bisq-network/growth/issues/160)
I plan to participate in the Bisq brief call this month to summarize.

## Contributions in progress

Continuing to provide liquidity and market making RUB/BTC

**Comment by chimp1984** [comment]
I will support that request as a bounty was set, but I think we have to reconsider such bounties and rather bind it to trade statistics rather then offers. 
 
See: https://github.com/bisq-network/growth/issues/160

**Comment by flix1** [comment]
I agree to reconsider future bounties and extant unclaimed ones. This one should be paid out.

**Comment by MwithM** [comment]
Closed as accepted.
