### ISSUE TITLE
BTC/USD liquidity week

### ISSUE THREAD

**Issue by flix1** [bisq-network/compensation#46]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 20
 - BSQ address: B1Pdq17bL5GiitCsNybi3Fc3V8qa7btYnPe

## Details

Participated in USD Liquidity week with multiple buy and sell offers using Cash App, Revolut and OKPay.

Completed orders with Cash App and Revolut. Both have instant payments which is significantly better than slower payment method. The user experience is much improved by this speed of settlement.

Revolut was a bit confusing at first because a payment made to an e-mail is not complete until the other uses clicks on the link and accepts. Some users had a phone number and others an e-mail... you actually have to add the user to your contacts before paying.

Cash App was much simpler. As long as you have the $Username ID there is little room for error.

**Comment by ManfredKarrer** [comment]
@flix1 I would appreciate if you add a compensation request for all your efforts on Bisq growth!

**Comment by flix1** [comment]
@ManfredKarrer I look forward to doing so in the future, when I have time to actually spend more than a few minutes per day helping out. 

Hopefully in a few months I'll have that availability and will ask to become more involved.

**Comment by ManfredKarrer** [comment]
Your "few minutes" are already worth a lot! Doubt that its just minutes...

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
