### ISSUE TITLE
For Cycle 9

### ISSUE THREAD

**Issue by bisquser** [bisq-network/compensation#464]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 3250
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

I have mediated 65 cases in this cycle at a cost of 50 BSQ/case. This includes support on Keybase. 

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I have 9 pending cases.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._
https://github.com/bisq-network/roles/issues/83

**Comment by chimp1984** [comment]
Can you provide a more detailed report which helps devs to find out how to reduce cases?

**Comment by MwithM** [comment]
Closed as accepted.
