### ISSUE TITLE
BTC/USD liquidity week

### ISSUE THREAD

**Issue by ghubstan** [bisq-network/compensation#47]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 20
 - BSQ address: B1N8bDbnGwxC4gi2DLSttRNvxPan1kYWynW

## Details

Participated in USD Liquidity week with multiple buy and sell offers using Zelle, and approximately 1/6 of the trade volume for the week.  (The estimate of my part of the week's total BTC/USD trade volume is an 'honest' one, but you have the statistics to verify.)

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
