### ISSUE TITLE
[WIP] For Cycle 10

### ISSUE THREAD

**Issue by trigger67** [bisq-network/compensation#473]
## Summary

 - BSQ requested: xxx.xx BSQ
 
## Contributions delivered

**Bisq desktop in French**

I finished the translation of Bisq desktop.

After I did my translations and reviews, and before this compensation request, @arnaudfr86 did a lot of small changes, like removing the space before ":" in many strings. So the number in the screenshots below are lower as they were initially.
**But I do not want to explain all changes, so I will just apply the filter today, and earn less BSQ than initially.** It can be considered as a small help to prevent having too much inflation on BSQ :)

1177 words translated

![image](https://user-images.githubusercontent.com/10185784/72376408-2c44d600-370e-11ea-81fa-ca9dc23244a3.png)

307 words reviewed

![image](https://user-images.githubusercontent.com/10185784/72376508-5b5b4780-370e-11ea-97ef-d0a76e6c17a3.png)

**Translation work summary (BSQ)**

French is one of the core languages.
Its translation work uses the compensation rate as followed:

Translated: 1177 x 0.07 = 82.39 USD
Reviewed: 307 x 0.035 = 10.74 USD

BSQ amount: 93.13 / XXX= XXXBSQ

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by MwithM** [comment]
You'll have to wait to Cycle 10 to submit proposals, proposal phase has now ended. Please change title to [WIP] For Cycle 10.

**Comment by trigger67** [comment]
Oh my bad, I thought I had more time :)

**Comment by ArnaudFR86** [comment]
I confirm @trigger67 explanation about minors changes related to punctuation. I will submit my compensation request once new translations will be upload to customers.

**Comment by cbeams** [comment]
This compensation request is still listed as [WIP]. @trigger67, is it your intention to actually submit this request for Cycle 10?

**Comment by MwithM** [comment]
Compensation Request not submitted on time. It can be re-requested for next Cycle.
