### ISSUE TITLE
For cycle 10

### ISSUE THREAD

**Issue by lusarz** [bisq-network/compensation#476]
## Summary

 - BSQ requested: 300
- DAO proposal transaction ID: 310ac994ceaa07d8eaf304d10d3b2fc68ea8229ca2bcc53516337eb74e9dfea0
 
## Contributions delivered
- [Use only EUR when creating a SEPA payment account](https://github.com/bisq-network/bisq/pull/3833)
BSQ requested: 300

**Comment by ripcurlx** [comment]
@lusarz As this covers one of our main payment methods and might reduce unnecessary arbitration cases it falls IMO into our new prioritized budget. But I think the amount is a little bit high compared to other compensation requests.

**Comment by lusarz** [comment]
@ripcurlx Yes, setting such a price I considered mainly value for Bisq. Reducing unnecessary arbitration cases seems quite important.

I'm ok to reduce the price - do you have proposition ?

**Comment by ripcurlx** [comment]
> I'm ok to reduce the price - do you have proposition ?

For me it would be more in the 200 USD area.

**Comment by lusarz** [comment]
I just tried to change it, but the field is not editable in application:
![requested-amount](https://user-images.githubusercontent.com/10059264/74231411-d0e31500-4cc6-11ea-8bfa-7914c4d7ad32.png)

:(

**Comment by MwithM** [comment]
@lusarz You need to remove this request at the DAO and edit the first post with the new requested amount.
Then, when approved, submit a new request to the DAO and post the txid this way: `DAO proposal transaction ID: <txid>`
You can see how compensation request review process works here: https://github.com/bisq-network/admin/issues/28

**Comment by lusarz** [comment]
OK, I understand. I was not aware of that process before but it sounds reasonable to me.


I have one question about removing request in DAO, regarding this information from [documentation](https://docs.bisq.network/dao-user-reference.html#proposal-phase) :

![satoshis](https://user-images.githubusercontent.com/10059264/74236995-cd558b00-4cd2-11ea-8988-47f23f7feed2.png)

Will I get this money back when I remove the request from DAO?

**Comment by MwithM** [comment]
> OK, I understand. I was not aware of that process before but it sounds reasonable to me. Seems like I submitted this request before this process was established.

Yes, you submitted the request before this process, but it's not very different as it was before. There's been cases before where suggestions from other contributors have made the compensation request issuer to remove, edit and resubmit a new request.

> Will I get this money back when I remove the request from DAO?

Yes, but only after this cycle is complete, not just when you remove the request.

**Comment by lusarz** [comment]
Ok, thank you for explanation. I updated price in accordance to [@ripcurlx suggestion](https://github.com/bisq-network/compensation/issues/476#issuecomment-584532075)

**Comment by lusarz** [comment]
I created new request in DAO, and posted txid.

**Comment by MwithM** [comment]
Tx ID is edited at first post. It should be on a new post, but it's OK.

**Comment by MwithM** [comment]
Was accepted
