### ISSUE TITLE
For March 2018

### ISSUE THREAD

**Issue by leomcy** [bisq-network/compensation#48]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:

BSQ amount requested: 200
BSQ address: B1NEAhGPQveHjsvvetFQSdmpLvnyAdeMiV6

## Details
> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value.

Youtube tutorial bounty.

Produce a "How to buy bitcoin with GBP using Bisq" video https://github.com/bisq-network/youtube/issues/5

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
