### ISSUE TITLE
For March 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#49]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: **14750**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value. **Please include only completed work!**_

### Development work:
- Work on Bisq DAO [1]
- Maintainer of Bisq Github repositories
- Maintain 8 seed nodes (6 BTC, 2 LTC), 2 Bitcoin nodes, 2 price nodes, monitor node, market server and BSQ explorer (15 * 50 BSQ)

See complete Github activity at: https://github.com/ManfredKarrer

[1] https://github.com/ManfredKarrer/bisq-core/tree/voting

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
