### ISSUE TITLE
For Cycle 10

### ISSUE THREAD

**Issue by RadishXN** [bisq-network/compensation#494]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested:1000
 
 

## Contributions delivered
> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its [value._](url)

I have provided Chinese market growth.
I have been Keeping at least 2 BUY and 2 SELL offers live during 1 month. 
![20200214000305](https://user-images.githubusercontent.com/45912686/74453789-dd7d8e00-4ebd-11ea-9ad0-d945d4b5858a.png)
![20200214000301](https://user-images.githubusercontent.com/45912686/74453798-e1111500-4ebd-11ea-8f2c-4117afeba6f0.png)
I have completed at least 5 trades.
![20200213234538](https://user-images.githubusercontent.com/45912686/74451748-0d776200-4ebb-11ea-8bcf-d9b20c88b389.png)
Introducing more Chinese to use bisq.
Provide feedback about how bisq work in China.

I request 1000 BSQ for the bounty of Chinese growth.

## Contributions in progress
> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I will continue introduce bisq and I am keeping 2 BUY and SELL live.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

My summary of my work is given on https://github.com/bisq-network/growth/issues/135# and I have get some feedback on it

**Comment by m52go** [comment]
Good work! Approved...side note, market making bounties are going to be tough to budget for.

Anyway, please post your txid here when you get a chance.

**Comment by RadishXN** [comment]
> Good work! Approved...side note, market making bounties are going to be tough to budget for.
> 
> Anyway, please post your txid here when you get a chance.

Here it is ca85f9ceb7393bb0b797366fb76fecead984d9d700a36ae074a02db97b6a4f87
Thx

**Comment by MwithM** [comment]
Was accepted
