### ISSUE TITLE
For October 2017

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#5]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 800
 - BSQ address: B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

Setup of two servers: one Pricenode and one Seednode 
Running the Pricenode and one Seednode servers.
Paying for a $12 USD / Mounth bitcoinaverage.com Subscription (for the Pricenode)

Setup und running the bisq-contrib mailinglist server:
https://github.com/bisq-network/lists/issues/1

**Comment by cbeams** [comment]
I've entered this request in the [stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=0) at 800 BSQ for address B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#8
