### ISSUE TITLE
[Withdrawn] For Cycle 11

### ISSUE THREAD

**Issue by dmos62** [bisq-network/compensation#502]
## Summary

 - BSQ requested: 800 USD / 0.66 = 1212 BSQ

## Contributions delivered

- Add local Bitcoin node configuration detection [#3982](https://github.com/bisq-network/bisq/pull/3982), 800 USD: 
Bisq automatically connects to a locally running Bitcoin node; however, the node requires non-default configuration to be usable by Bisq. This PR adds automatic detection of a local BTC node's mis/configuration and appropriate handling.

- Changes to local BTC node reminder in Settings > Network info [#4024](https://github.com/bisq-network/bisq/pull/4024), 0:
Under "Settings" > "Network info" we have a list of connected Bitcoin nodes. Under this list we provide a reminder in small font about Bisq being able to use a local Bitcoin node. These changes principally make the reminder more accurate.

**Comment by MwithM** [comment]
@ricpcurlx I guess @dmos62 can now submit request to DAO and comment here the TXID.

**Comment by dmos62** [comment]
Proposal TX ID: 5fbc9d7edd04b74c9c1422225d86af2543603101c8d123ec452fc0b3ee9011f8

**Comment by dmos62** [comment]
Proposal / compensation request withdrawn.

The LocalBitcoinNode contribution turned out to be unstable in certain setups, so we reverted it. I'll see about getting a better implementation merged for the next cycle.
