### ISSUE TITLE
[WIP] For Cycle 11

### ISSUE THREAD

**Issue by RiccardoMasutti** [bisq-network/compensation#507]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 870 BSQ
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

### Code Review
https://github.com/bisq-network/bisq-website/pull/339 | 50 BSQ
https://github.com/bisq-network/bisq-website/pull/341/ | 35 BSQ
https://github.com/bisq-network/bisq/pull/3992 | 35 BSQ

### Growth
[Italian Community Manager](https://github.com/bisq-network/roles/issues/95) | 750 BSQ

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

### Code Development

Bisq Website:
https://github.com/bisq-network/bisq-website/pull/328
https://github.com/bisq-network/bisq-website/pull/347
https://github.com/bisq-network/bisq-website/pull/348
https://github.com/bisq-network/bisq-website/pull/349
https://github.com/bisq-network/bisq-website/pull/350

### Code Review
https://github.com/bisq-network/bisq-website/pull/303

### Translation:
Bisq-desktop italian translator
https://www.transifex.com/bisq/bisq-desktop/viewstrings/#it/displaystringsproperties/110522284?q=translator%3ARiccardo

Bisq website italian translator
https://www.transifex.com/bisq/bisq-website/translate/#it/strings/174374724?q=translator%3ARiccardo

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by ifarnung** [comment]
I will be voting **NO** on another heavily-padded compensation request from Riccardo. He pulls scarce budget resources away from BISQ for non-critical functions, simple as that.

100 BSQ + 100 BSQ a month to manage a Twitter account and a Telegram channel?  No really, but also, 750 BSQ for the same work under a community manager title. Let's at least try to quantify the value of what we receive because the value we give is easy to price on the BSQ market.  It just isn't proportional.

Can I run Bisq_Finland, Bisq_Sri Lanka and Bisq_Russia accounts and get paid a full monthly salary for that?  Sounds too good to be true.

It does bring up a larger discussion though about how much BISQ is going to spend on specific country and language adaptation though?  It's a big commitment to maintain all these languages on a web based platform, when Google translate does a 98% effective job for free.

It's time to drive home the notion that BISQ is on a strict budget at the moment and there must be a triage of things that we need and things that would be nice to have.

**Comment by RiccardoMasutti** [comment]
> I will be voting **NO** on another heavily-padded compensation request from Riccardo. He pulls scarce budget resources away from BISQ for non-critical functions, simple as that.
> 
> 100 BSQ + 100 BSQ a month to manage a Twitter account and a Telegram channel? No really, but also, 750 BSQ for the same work under a community manager title. Let's at least try to quantify the value of what we receive because the value we give is easy to price on the BSQ market. It just isn't proportional.
> 
> Can I run Bisq_Finland, Bisq_Sri Lanka and Bisq_Russia accounts and get paid a full monthly salary for that? Sounds too good to be true.
> 
> It does bring up a larger discussion though about how much BISQ is going to spend on specific country and language adaptation though? It's a big commitment to maintain all these languages on a web based platform, when Google translate does a 98% effective job for free.
> 
> It's time to drive home the notion that BISQ is on a strict budget at the moment and there must be a triage of things that we need and things that would be nice to have.

This is still a WIP. I still have to make several changes.

**Comment by m52go** [comment]
NACK.

Don't bother finishing the request. See [here](https://github.com/bisq-network/compensation/issues/463#issuecomment-597069076) for reference.

But for the record, I would have rejected this request anyway—

The [Community Manager role](https://github.com/bisq-network/roles/issues/95#issuecomment-597018219) is an assigned one, and you aren't assigned. In any case, [a key responsibility of that role](https://bisq.wiki/Community_Manager#Duties) is posting your activity and findings on the #pulse Keybase channel, which you aren't even a part of.

> [bisq-network/bisq-website#341](https://github.com/bisq-network/bisq-website/pull/341) | 35 BSQ

Charging any money to review a release update for the website is a joke.

**Comment by RiccardoMasutti** [comment]
> NACK.
> 
> Don't bother finishing the request. See [here](https://github.com/bisq-network/compensation/issues/463#issuecomment-597069076) for reference.
> 
> But for the record, I would have rejected this request anyway—
> 
> The [Community Manager role](https://github.com/bisq-network/roles/issues/95#issuecomment-597018219) is an assigned one, and you aren't assigned. In any case, [a key responsibility of that role](https://bisq.wiki/Community_Manager#Duties) is posting your activity and findings on the #pulse Keybase channel, which you aren't even a part of.
> 
> > [bisq-network/bisq-website#341](https://github.com/bisq-network/bisq-website/pull/341) | 35 BSQ
> 
> Charging any money to review a release update for the website is a joke.

Regarding the community manager role, I think I confused it with the evangelist/ambassador role. The first message between me, you and @mwithm in our private chat, referred to "community management".

Regarding code reviews, as I said, it's still WIP as I took the template from a previous Contribution Request and pasted it quickly as soon as I realized that are missing 7 days until Votes
