### ISSUE TITLE
BTC/USD liquidity week

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/compensation#51]
## Basic information

BSQ amount requested: 20
BSQ address: B16kMZonmnNXrZvSqGuXVjpWWTZnSVG3xJb

## Details

Participated in USD Liquidity week with multiple buy and sell offers using Revolut and SEPA.  Completed 7 trades in revolut. There was a trade problem with revolut bank transfers, swift is not active and banks reject it. Problems following trade history, did not find placed margin (e.g. 5%) on closed trades. Had to go through links to find trader / mining fees. An aggregate view would be convenient. Also, had to make my own calculations to estimate fees and fees %, an estimation would be useful for traders.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
