### ISSUE TITLE
For Cycle 11

### ISSUE THREAD

**Issue by bisquser** [bisq-network/compensation#517]
## Summary
I am the mediator
> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 2000
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._
The discussion appears to give at hand that the compensation for this role should be 1000 BSQ/cycle instead of 50 BSQ/case. I follow the crowd and thus request 2000 BSQ given that I did not do any compensation request last cycle.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._
Report at: https://github.com/bisq-network/roles/issues/83

**Comment by MwithM** [comment]
This compensation request has been submitted long past the deadline.

**Comment by MwithM** [comment]
closing as accepted
