### ISSUE TITLE
For March 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#52]
## Basic information

 - BSQ amount requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**

### Forum operator:
- Maintaining the forum, including backups,updates, server upgrades, etc.
(forum operator https://github.com/bisq-network/roles/issues/19)

### Support:
- Providing support for users on the forum, reddit, bitcointalk, Slack
(forum profile https://bisq.community/u/alexej996/summary)

### Moderation:
- Moderating Bisq forum and subreddit (reddit moderator https://github.com/bisq-network/roles/issues/25)

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
