### ISSUE TITLE
For Cycle 12

### ISSUE THREAD

**Issue by RadishXN** [bisq-network/compensation#525]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested:1200
 
 

## Contributions delivered
> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its [value._](url)

I have compeleted 11 trades so far and got AD on telegram channel.
I have been Keeping at least 2 BUY and 2 SELL offers live during 1 month. 
![20200411235244](https://user-images.githubusercontent.com/45912686/79049365-c1267500-7c12-11ea-8989-10a72cf7ceb5.png)
Introducing more Chinese to use bisq.
Provide feedback about how bisq work in China.

I request 1200 BSQ for the bounty of Chinese growth.

## Contributions in progress
> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I will continue introduce bisq and I am keeping 2 BUY and SELL live.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

My summary of my work is given on https://github.com/bisq-network/growth/issues/187 and I have get some feedback at there.

**Comment by m52go** [comment]
[Approved](https://bisq.wiki/Compensation#Team_Lead).

Please paste the transaction ID of the compensation request tx here as a comment.

**Comment by RadishXN** [comment]
> [Approved](https://bisq.wiki/Compensation#Team_Lead).
> 
> Please paste the transaction ID of the compensation request tx here as a comment.

Here it is 2067b8a75a44d47bdf87538fddb36ce818752c30850cbc38f2c84ecce05b9f11
THX

**Comment by MwithM** [comment]
Closing as accepted.

**Comment by sqrrm** [comment]
There are some inconsistencies with the vote result calculation for cycle 12. We are looking into it. Please avoid moving any BTC in your BSQ wallet for now, they might actually be BSQ that failed to get colored.
