### ISSUE TITLE
For March 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#53]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 4100
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._
- Working on DAO, mainly review and fixing bugs
- Maintain 2 bitcoin nodes (2x50)
- Investigation of running tor nodes as a role

Activity at https://github.com/sqrrm

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
