### ISSUE TITLE
For March 2018

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#54]
Basic information
Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:

BSQ amount requested: 400
BSQ address: B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE
Details
Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value.

Running of 3 Bitcoin Fullnodes.
3 onion address
3 clearnet address
3 VPS servers and one dedicated server.
See: bisq-network/roles#67

Running one Pricenode and one Seednode server.
Paying for a $12 USD / Mounth bitcoinaverage.com Subscription (for the Pricenode)

Running the bisq-contrib mailinglist server

Compensation calculation:
no Setup

Monthly costs nodes: 5* VPS (50 / node) -> 250
Monthly costs dedicated node 100
Monthly costs mailinglist server: 50
=400

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
