### ISSUE TITLE
For cycle 12

### ISSUE THREAD

**Issue by Bayernatoor** [bisq-network/compensation#548]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 500$ / 0.56 = 893

## Contributions delivered

- Handled L1 support throughout cycle 12 on Keybase, Reddit and the Bisq forums.

- Created several wiki pages.

## Contributions in progress

- Continuing L1 support.

- Working on additional Wiki pages (Failed trades).

## Roles performed

- L1 Support Agent - [report](https://github.com/bisq-network/roles/issues/64#issuecomment-616644665)

**Comment by Bayernatoor** [comment]
Oops - missed the Proposal Phase, will resubmit in Cycle 13.

**Comment by Bayernatoor** [comment]
Missed the Proposal Phase, will resubmit in Cycle 13.

**Comment by sqrrm** [comment]
There are some inconsistencies with the vote result calculation for cycle 12. We are looking into it. Please avoid moving any BTC in your BSQ wallet for now, they might actually be BSQ that failed to get colored.
