### ISSUE TITLE
For March 2018

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#55]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 2050
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### API

Slow coding month, mainly discussions and PR reviews.

17 PR's were reviewed/merged
[PR's reviewed and merged in March 2018](https://github.com/mrosseel/bisq-api/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+updated%3A2018-03-01..2018-04-01+
)
### Hosting
Monthly costs nodes: 50 / node * 5: 250 BSQ

Running:
1 Price node + bitcoinaverage subscription
1 Seed node
2 Bitcoin full nodes
1 Monitoring node + 1 messaging sync node (on one server)
  
### Roles

Report for this month:
https://github.com/bisq-network/roles/issues/22#issuecomment-378513604

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/56#issuecomment-379738802.
