### ISSUE TITLE
For Cycle #13

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/compensation#554]
## Summary

**BSQ requested**
2500 USD = 3968 BSQ @ 0.63 USD/BSQ
+2500 BSQ to be sent in the next cycle)

**Total**
5000 USD = 7936 BSQ (0.63 USD per 1 BSQ)

## Contributions delivered

1. Story boards
2. Animation reusing the previously designed eye still on hold for the Bitcoin Magazine back cover ad. 
3. Individual shapes layered and some animated individually.
4. VO script
5. VO creation with text to speech
6. quick run through the UI.
7. Cut-down GIF/MP4 for a shorter hit.
8. Short Halving celebration GIF/MP4
9. 6800 views on twitter as of Sunday, May 10, 11pm EST

https://drive.google.com/open?id=1i2-8_7DZ_ZbrXBJr-rtWf4ocaEN-gXNb

<img width="2672" alt="1" src="https://user-images.githubusercontent.com/807505/81516388-b7715980-9305-11ea-9b35-3ab7d138e30e.png">
<img width="2096" alt="2" src="https://user-images.githubusercontent.com/807505/81516394-ba6c4a00-9305-11ea-8698-248ecf6a2085.png">
<img width="1980" alt="3" src="https://user-images.githubusercontent.com/807505/81516397-bb9d7700-9305-11ea-9fe2-d4385d26d35f.png">
<img width="1980" alt="4" src="https://user-images.githubusercontent.com/807505/81516400-bd673a80-9305-11ea-9457-d2d3664c5bf7.png">
<img width="1980" alt="5" src="https://user-images.githubusercontent.com/807505/81516406-c0622b00-9305-11ea-936b-f3c03acebf8a.png">

<img width="1980" alt="bisq - bitcoin halving 30 sec spot 10Mbps" src="https://user-images.githubusercontent.com/807505/81516409-c22bee80-9305-11ea-9a37-0767d98028ea.gif">

<img width="1980" alt="bisq - bitcoin halving SHORT - Bitcoin Halving, Stack Privately" src="https://user-images.githubusercontent.com/807505/81516414-c6580c00-9305-11ea-88c4-4ebfe3e77e55.gif">

<img width="1980" alt="bisq - bitcoin halving SHORT - KYC is the Illicit Activity" src="https://user-images.githubusercontent.com/807505/81516416-c7893900-9305-11ea-89e7-eecfee38b5fe.gif">

![IMG_129BD91BE604-1](https://user-images.githubusercontent.com/807505/81521109-47b69b00-9314-11ea-947a-473dd1f717e3.jpeg)
![IMG_E301AC60CCC1-1](https://user-images.githubusercontent.com/807505/81521111-484f3180-9314-11ea-9645-cef0030951c7.jpeg)

**Comment by ifarnung** [comment]
A great video!  I thought it was really well done. Thanks for that contribution.

**Comment by m52go** [comment]
[Approved](https://bisq.wiki/Compensation#Team_Lead).

The video was indeed incredible, and was delivered unbelievably quickly too. In addition, the GIFs were never requested but delivered anyway. I'm saying all this to point out that the amount Pedro is requesting here is well below the market rate for an over-delivery of what I consider to be world-class design.

All items not only helped Bisq have a huge voice during the time of the halving, but will probably be useful one way or another going forward 🙏

**Comment by wiz** [comment]
The video was amazing, excellent job 🏆

**Comment by pedromvpg** [comment]
Thanks everyone!
I hope that with this time of remote content, we'll find more opportunities to use the video and promote bisq!

**Comment by burningman2** [comment]
@pedromvpg Thanks for your great contribution! World class as always!

**Comment by MwithM** [comment]
Don't forget to submit compensation request and comment the TXID.

**Comment by MwithM** [comment]
There's two DAO proposals pointing to this issue, one for 3968 BSQ and another one for 2500 BSQ, which equals 6468 BSQ.
Why is it split? I don't understand how this amount is calculated based on BSQ requested on summary: 

> 2500 USD = 3968 BSQ @ 0.63 USD/BSQ
> +2500 BSQ to be sent in the next cycle).

**Comment by MwithM** [comment]
`ea298460a97f9ab06a04ab182d06e9226b68e7df57af93467b51290d383c90e4` was accepted
`c958d01674961ab4dbbd0731d5a2930b85b06779bfc4503af988e0876958e154` was rejected

Closing as accepted
