### ISSUE TITLE
For Cycle 13

### ISSUE THREAD

**Issue by petrhejna** [bisq-network/compensation#576]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: `79 BSQ` (50 USD / 0.63 ~ 79 BSQ)
 
**Note**: Please not this is my first contribution and first compensation request. My primary motivation is to test and get familiar with the Bisq workflow and processes. I am more than open to any feedback, corrections and additional info. Defining the price was quite hard for me, because I spend quite a lot of time and effort on learning the stuff (just make Bisq stack running took whole Saturday). At the end, I did it by comparing the PR to other PRs which were requested for compensations. Again, I am open to any corrections and Ill be very happy for any feedback.

 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

* Add memo field to withdrawal transaction (https://github.com/bisq-network/bisq/pull/4229) `50 USD`

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

* Opening a take/create offers closes previously openned tab (https://github.com/bisq-network/bisq/pull/4263)

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

None.

**Comment by sqrrm** [comment]
As stand in [team lead](https://bisq.wiki/Compensation#Team_Lead) I approve this request. Please submit your DAO proposal and paste the transaction ID here as a comment when complete, thanks.

A note: it is expected that compensation requests are posted a few days before the end of the proposal phase to give time for review and feedback of the compensation request. There is usually a notification of this for all contributors. As this is your first compensation, it's one small PR and I reviewed it myself I don't mind acking this.

**Comment by MwithM** [comment]
Here you can find how the compensation request process works, for next cycle keep in mind that this compensation requests should be ready for review one week before end of proposal phase. https://bisq.wiki/Compensation

You only have a few hours to submit your request to DAO https://docs.bisq.network/compensation.html#file-your-compensation-request-in-the-dao

**Comment by petrhejna** [comment]
Tx: `98b94075b8a4384553361dd160086b420723e90e6d65bd5d7942cfd3d12f42e3`

@MwithM @sqrrm Thank you for info. I'll do sooner next month. 

Is there please any "Calendar" or some timeline (other then Governance tab in Bisq). Thank you.

**Comment by MwithM** [comment]
Yes, this calendar alerts about deadline for compensation request submission (1 week before end of proposal phase).

**Comment by petrhejna** [comment]
@MwithM thank you for the link. However is there some way how to subscribe to it but ICS link?

I don't have Google stuff on my phone, so I need some standard way of subscribing to the calendar.

Thank you a lot.

**Comment by MwithM** [comment]
was:accepted

**Comment by MwithM** [comment]
> I don't have Google stuff on my phone, so I need some standard (iCal, ICS, ...) way of subscribing to the calendar so I can use some FOSS sruff. :+)

Hope this works: https://bisq.wiki/Events_calendar
