### ISSUE TITLE
For Cycle 13

### ISSUE THREAD

**Issue by oscarguindzberg** [bisq-network/compensation#577]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: USD 4000 / 0.63 = BSQ 6349.20
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._
- Segwit support plan: https://github.com/bisq-network/proposals/issues/226 . Project: https://github.com/bisq-network/projects/issues/34 (USD 4000)

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by oscarguindzberg** [comment]
txid: 97be9337e9283745c458d81a4f735088b33241e78964afffd5dd208e39c7041a

**Comment by oscarguindzberg** [comment]
I just found out I should have waited before publishing my compensation request tx.

**Comment by oscarguindzberg** [comment]
Previous compensation request: https://github.com/bisq-network/compensation/issues/283

**Comment by MwithM** [comment]
The proposal phase has ended and there's no proposal submitted to DAO.

Closing as "not submitted".

**Comment by oscarguindzberg** [comment]
@MwithM I am a bit confused:
What is the proposal to DAO?
Isn't this tx enough https://bsq.bisq.cc/tx.html?tx=97be9337e9283745c458d81a4f735088b33241e78964afffd5dd208e39c7041a ?

**Comment by oscarguindzberg** [comment]
<img width="1194" alt="dao2" src="https://user-images.githubusercontent.com/1145132/82764393-b3086e80-9de4-11ea-9b2e-345bf82b7e7b.png">

**Comment by MwithM** [comment]
Sorry did not see it.

**Comment by sqrrm** [comment]
This is in accordance with what we have discussed. Only published a bit late, but delivered very much according to specification. I approve this.

**Comment by MwithM** [comment]
was:accepted
