### ISSUE TITLE
For Cycle 14

### ISSUE THREAD

**Issue by petrhejna** [bisq-network/compensation#584]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`48`** 
- USD requested: 30 
- BSQ rate: 0.63 USD per BSQ 
- Previous compensation request (if applicable): #576  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Bugfix: Opening a take/create offers closes previously openned tab. | dev* | 30 | https://github.com/bisq-network/bisq/pull/4263 |  |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by sqrrm** [comment]
As stand in dev team lead that forgot this is part of the duty I approve this request.

Please submit your DAO proposal and paste the transaction ID here as a comment when complete, thanks.

**Comment by ripcurlx** [comment]
> There is a [new template for compensation requests](https://github.com/orgs/bisq-network/teams/dao/discussions/14) using a tabular format that can be parsed by bisq-bot. Would you consider switching your request to the new format. A good example is #586.
> Thanks in advance.

@petrhejna Could you please update your compensation request to match the new template? Doing it like that it can be automatically be parsed and used for reporting and budgeting. Thanks!

**Comment by ghost** [comment]
@ripcurlx The link for template says 404. Where I can find valid one?

**Comment by MwithM** [comment]
Just open a new issue at compensation repository. Also, you can take it from [here](https://github.com/bisq-network/compensation/pull/585/files).
Or contact me at keybase and I'll copy/paste it.

**Comment by ghost** [comment]
@ripcurlx @MwithM thx, done

**Comment by MwithM** [comment]
Don't forget ot post the TXID of your DAO proposal.

**Comment by ghost** [comment]
transaction Id: `fcad15e0cb0cc6899a283fce549d6e8342e35ba0df15cd8590dd07e2d431fe56`

**Comment by MwithM** [comment]
Closed as: accepted
