### ISSUE TITLE
For April 2018

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#59]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 5950
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

Everything except development efforts in April is included in this compensation request.

### Development/UX
bisq-network/roles#63

Moderation of all gui issues and #ux channel.

None of my PRs this month haven't been released. Fingers crossed that we've the new release setup ready soon. The compensation of everything Development/UX related will be filed after the release of v0.7.0

### Testing
Extended and restructured [test scenarios](https://docs.google.com/spreadsheets/d/18n6wV0g5MPTs9Xni0cFji8U34xV3O1IRPDEYZrluBuU/edit#gid=1386834576) for new release v0.7.0 

Although the testing effort for v0.7.0 so far are documented I'll wait for compensation until the new release is out and all the test scenarios are fulfilled successfully.

### Growth
https://github.com/bisq-network/roles/issues/42

### Analytics
https://github.com/bisq-network/roles/issues/40

### YouTube Admin
https://github.com/bisq-network/roles/issues/56

### Bitcoin Fullnode Operator
Maintenance of full core node btc.christophatteneder.com:8333.

**Comment by ripcurlx** [comment]
I updated this compensation request after a discussion on Slack with @cbeams (see https://github.com/bisq-network/proposals/issues/19#issuecomment-385369054).

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/58#issuecomment-387381841.
