### ISSUE TITLE
For Cycle #14

### ISSUE THREAD

**Issue by pedromvpg** [bisq-network/compensation#598]
## Summary

- **BSQ requested**: **`3968`** 
- USD requested: 2500
- BSQ rate: 0.63 USD per BSQ (at the time of the first com request)
- Previous compensation request: #554

## Contributions delivered

Second installment for Bitcoin Halving video and other materials presented here: https://github.com/bisq-network/compensation/issues/554

**Comment by ripcurlx** [comment]
@pedromvpg There is a new template for compensation requests using a tabular format that can be parsed by bisq-bot. Would you consider switching your request to the new format. A good example is #586.
Thanks in advance!

**Comment by m52go** [comment]
Yes would be great (but not necessary) if you could switch your request to the new format. It's already the default for new issues in this repository, and will probably be mandatory in the next cycle.

[Approved](https://bisq.wiki/Compensation#Review_team_member_requests) for voting. Please post your transaction ID here when possible.

**Comment by MwithM** [comment]
Hey @pedromvpg don't forget to submit your proposal to the DAO and comment here the TXID.

**Comment by MwithM** [comment]
closed as: accepted
