### ISSUE TITLE
For October 2017

### ISSUE THREAD

**Issue by JesusMcCloud** [bisq-network/compensation#6]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 1000*
 - BSQ address: B12o6yZnPeiCZwrWfBFBsyiqWmUm5wmeq4w

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### Development Work
*While most work was done prior to October, the new version was released in October and integrated by @mrosseel by the end of October / beginning of November. Therefore, I find it hard to judge the value of the work done in October, as past compensation already happened, but did not cover the work released in October.

Rewriting and enhancing the [Tor library](https://github.com/JesusMcCloud/netlayer) Bisq's netlayer is based on. 
What's new:
- API enhancements
- Automatic inclusion of the official Tor releases based on initial [work by cedricwalter](https://github.com/cedricwalter/tor-binary) and some [additional fixes](https://github.com/JesusMcCloud/tor-binary).
- Support for bridges
- Support for pluggable transports
- Tor stream Isolation
- Various other fixes

While currently being integrated into Bisq, this provides the foundation to fix
 - [#893](https://github.com/bisq-network/exchange/pull/893)
 - [#483](https://github.com/bisq-network/exchange/issues/483)
 - [#492](https://github.com/bisq-network/exchange/issues/492)
 - [#731](https://github.com/bisq-network/exchange/issues/731)
 - [#771](https://github.com/bisq-network/exchange/issues/771)
 - [#971](https://github.com/bisq-network/exchange/issues/971)

The the new Tor library has already been integrated by @mrosseel (see [#987](https://github.com/bisq-network/exchange/pull/987)).

While I have provided feedback and answered some questions, I did not perform the actual integration work. However, the Tor library rework was done specifically with Bisq use cases and requirements in mind.

**Comment by cbeams** [comment]
Thanks, @JesusMcCloud. I've entered this request in the [stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=0) at 1000 BSQ for address B12o6yZnPeiCZwrWfBFBsyiqWmUm5wmeq4w.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#8
