### ISSUE TITLE
For Cycle 14

### ISSUE THREAD

**Issue by lyyva** [bisq-network/compensation#605]
## Summary

- **BSQ requested**: **`285`** 
- USD requested:180 
- BSQ rate: 0.63 USD per BSQ 
- Previous compensation request (if applicable): #278  

## Contributions delivered
![dao testing results](https://user-images.githubusercontent.com/49204861/85413072-3e029300-b562-11ea-8d0b-7565210ada82.png)

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| DAO Testing | dev | 180 |  | Picture attached |

**Comment by lyyva** [comment]
Due to family reasons i was unable to submit this compensation request in due time. This was originally supposed to be for cycle 7.
Looking forward to getting more involved again!

**Comment by MwithM** [comment]
[Compensation requests](https://bisq.wiki/Compensation) should be sent before 19th june, one week before end of proposal phase, to give time to team leads to review them. Also, compensation request title should be the current cycle, not the one your asking compensation for. So, this compensation request should be titled `For Cycle 14`.
There's no such thing as "testing" team, I guess your request fits better into the dev team. I'll ping @ripcurlx  in case he wants to add any comment, but I think this request should be closed and submitted for review on cycle 15.

**Comment by lyyva** [comment]
@MwithM fine with me of course. Seems like a lot has changed since i´ve been here last! Very impressed with the organized workflow, and my apologies, i didn´t realize there was now a deadline where everything had to be submitted (even though i could have found that out of course!)
Fixed everything else you pointed out.

**Comment by MwithM** [comment]
Closed as: rejected
