### ISSUE TITLE
BTC/GBP Liquidity week

### ISSUE THREAD

**Issue by flix1** [bisq-network/compensation#62]
## Basic information

BSQ amount requested: 20
BSQ address: B1Pdq17bL5GiitCsNybi3Fc3V8qa7btYnPe

## Details

 Participated in GBP Liquidity Week keeping 3+ offers online during the week and executing multiple GBP trades using Revolut. 

I was surprised by how fast trades can go when using an instant payment system like Revolut. Sometimes encountered delays while waiting for blockchain confirmations, but the average trade time was incredibly fast. 

Also discovered that it is better to use a phone number than an e-mail as a Revolut ID, as adding a contact via phone number will automatically allow you to make an instant payment. When using e-mail however you cannot pay directly but rather an e-mail is sent to the other user with an unconfirmed payment and they need to claim it. UX is worse/privacy is better with e-mail. I guess it's good to have the choice.

**Comment by cbeams** [comment]
> Also discovered that it is better to use a phone number than an e-mail as a Revolut ID, as adding a contact via phone number will automatically allow you to make an instant payment. When using e-mail however you cannot pay directly but rather an e-mail is sent to the other user with an unconfirmed payment and they need to claim it. UX is worse/privacy is better with e-mail. I guess it's good to have the choice.

Thanks for mentioning this, @flix1.

@alfsbs, I think we should collect this kind of thing in a simple knowledge base for payment methods. We can do this by adding a document to the bisq-network/bisq-docs repository, e.g. `revolut.adoc` that anyone can edit (via a PR), and that over time will capture best practices, tips and tricks, known pitfalls, etc. We can also link to these documents from within the bisq-desktop UI, e.g. when users are setting up a Revolut payment account and when users are making or taking a Revolut-based trade.

@alfsbs, if you'd like to kick start this effort, please submit a PR for the simplest possible `revolut.adoc` you like, containing a description of the payment method, links to its official website, and perhaps a section titled 'best practices' that captures @flix1's comment above. You'll also want to add a link to the new doc from `index.adoc` under the "User Docs" section. Don't worry that this is all very raw. Just do your best to make whatever you do write well-written and well formatted. The idea is to build up the docs site, piece by piece over time, a bit like a wiki that will over time become a full-on Bisq Network operator's manual.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/58#issuecomment-387381841.
