### ISSUE TITLE
For Cycle 15

### ISSUE THREAD

**Issue by softsimon** [bisq-network/compensation#625]
## Summary

* **BSQ requested**: **`6769`**
* USD requested: 4400
* BSQ rate: 0.65 USD per BSQ
* Previous compensation request (if applicable): first-time contributor

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Work on Bisq Explorer | ops | 4400 | https://github.com/bisq-network/projects/issues/37 | https://mempool.space/bisq |

## Code Shipped

https://github.com/mempool/mempool/pull/92
https://github.com/bisq-network/mempool/commits/bisq

**Comment by wiz** [comment]
:+1:

**Comment by MwithM** [comment]
Please post in a comment here the DAO TXID for this compensation request.

**Comment by softsimon** [comment]
e64690c868dee45335441b4f133fc2ba6a6a860323b0dfc438b4ea712028575d

**Comment by MwithM** [comment]
closed as accepted
