### ISSUE TITLE
For Cycle 15

### ISSUE THREAD

**Issue by elkimek** [bisq-network/compensation#627]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`76.92`** 
- USD requested: 50 
- BSQ rate: 0.65 USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Publish blog post about Bisq on Alza blog | Growth | 50 | https://www.alzashop.com/p2p-exchange-bisq-how-to-buy-and-sell-bitcoin-guide | EN version |
| Publish blog post about Bisq on Alza blog | Growth | 0 | https://www.alza.cz/burza-bisq-jak-nakoupit-a-prodat-bitcoin-navod | CZ version (original) |
| Publish blog post about Bisq on Alza blog | Growth | 0 | https://www.alza.sk/burza-bisq-ako-nakupit-a-predat-bitcoin-navod | SK version |

- **About the work**:

I strongly believe bitcoin was never ment to be a KYC coin and that its main value proposition is sovereignty. I'm constantly seeing stronger and stronger informational asymmetry between using Bitcoin as it was designed and as it is marketed by the banking layer in favor of the latter. 

Unfortunately custodial and KYC services are driven by FUD convincing the majority of users that sovereignty is hard and dangerous and the majority is parroting it to the new users. This was my motivation to do a comprehensive write up on Bisq but I realized just a step by step guide would be boring and not many users would really read it. I came up with a concept of wrapping the core in sovereignty nudge (chapters 1, 11 and 12) and it seems to be working. According to GA the czech version has ~38 minutes average reading time which tells me the readers are actually reading it and not just scrolling it through or skipping from start to the end.

You may wonder why ( and this is not an add) an e-tailer would produce such an article. Alza is very progressive company in all directions and we produce ton of content on everything be it our own hardware reviews (that's my main job there) or guides how to _____ . Beside that, we are Bitcoin enthusiasts and we accept bitcoin payments. I'm the main editor of the Bitcoin Alza section and I took it under my wing because I saw it as an interesting asymmetric channel to approach different kind of people who would not be looking for high quality articles this way.

Sidenote: If anyone would like to translate it to HU/DE, we also have  domains where we could publish that. Feel free to contact me.

**This request is a claim for the [[hat-tip bounty](https://github.com/bisq-network/growth/issues/195)]**
 

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by m52go** [comment]
This request is for the [new 'hat-tip' bounty](https://github.com/bisq-network/growth/issues/195). I confirm that I nominated @elkimek to claim it.

A full explanation of the hat-tip bounty is at the link above, but in short: the article on the Alza blog went above and beyond. It's extensive, covering many aspects of what Bisq is, how it works, and even covers the Bisq DAO. As a bonus, it's hosted on the site of a well-known Czech retailer (i.e. probably good SEO and traffic). 

While such an item falls outside of the bounds of traditional compensation, I think it's important that such remarkable contributions be acknowledged. As a bonus for Bisq, such a scheme also allows for folks outside the core contributor base to get a first-hand experience of how the DAO works for compensation.

(monetary impact is meant to be negligible: bounty can only be claimed once per cycle, an individual can only ever claim it once, and bounty amount is capped at 50 USD)

@elkimek this request is [approved](https://bisq.wiki/Compensation#Review_team_member_requests). Please submit your request to the DAO and post the proposal txid here once you have.

**Comment by MwithM** [comment]
Just a reminder: now that the request is approved by team leader, @elkimek should make the DAO request and publish here the TXID.
https://bisq.wiki/Compensation#Submit_your_request_as_a_DAO_proposal

**Comment by elkimek** [comment]
@MwithM thanks I was waiting for the BSQ confirmation because I didn't have any.

txid: 31fa275290f26713dba101543ae32936d378f185e0013f12b97c5ffdad838020

**Comment by MwithM** [comment]
closed as accepted
