### ISSUE TITLE
For April 2018

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#64]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 400
 - BSQ address: B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

Running of 3 Bitcoin Fullnodes.
3 onion address 
3 clearnet address
3 VPS servers and one dedicated server.
See: https://github.com/bisq-network/roles/issues/67

Running one Pricenode and one Seednode server.
Paying for a $12 USD / Mounth bitcoinaverage.com Subscription (for the Pricenode)

Events on one Fullnode: Hard disk failure that left the sever without the blockchain, needed a complete resync.

Running the bisq-contrib mailing list server. Approving and rejecting mails. 
Setup of the GitHub mailing list.
See: https://github.com/bisq-network/lists/issues/5 

## Compensation calculation:

no Setup, only maintenance 

Monthly costs nodes: 5* VPS (50 / node) -> 250
Monthly costs dedicated node 100
Monthly costs mailinglist server: 50
=400

**Comment by cbeams** [comment]
Thanks, @Emzy. Some feedback:

> Per https://github.com/bisq-network/proposals/issues/13, please write up your comments about each role you play as a comment on the respective role issue. I just wrote very similar feedback to @mrosseel in https://github.com/bisq-network/compensation/issues/63#issuecomment-387346124, so I'll just quote it below (with some slight modifications):
> 
> Rather than grouping stuff into a single section directly within your compensation request, please post a monthly update comment on each of the respective roles, e.g.:
> 
>  - Pricenode Operator at https://github.com/bisq-network/roles/issues/14
>  - Seednode Operator at https://github.com/bisq-network/roles/issues/15
>  - Bitcoin Node Operator at https://github.com/bisq-network/roles/issues/67
>  - Mailman Operator at https://github.com/bisq-network/roles/issues/26
> 
> Doing things this way maximizes the usefulness of these reports over time. Mostly, people will not go digging through individual compensation requests to see who has been hosting what, or how much they paid to host those things on various hosting providers. But if all operators consistently post monthly report comments on their respective operator role issues, it becomes very easy for operators new and old alike to see who is hosting what where, which hosting providers are overused from a a censorship resistance / network resiliency perspective, which contributors are overloaded / operating too much stuff, to evaluate which hosting providers are delivering the best "bang for the buck", etc.

Many thanks in any case for all the operations work you're doing here. I think no one outside of Manfred is hosting more nodes than you. Hopefully the changes described above can help in our efforts to decentralize this work further.

**Comment by cbeams** [comment]
@Emzy, I noticed after the fact that you did actually do a monthly Pricenode Operator report at https://github.com/bisq-network/roles/issues/14#issuecomment-386404037. Thanks. If in the future, you backreference your compensation requests from your role report comments, e.g. with a `/cc bisq-network/compensation#64`, it'll ensure that everything is discoverable in a bi-directional way. You can see this in effect in my compensation requests, e.g. this month's at https://github.com/bisq-network/compensation/issues/68. Scroll to the bottom and you'll see the back-references in the issue timeline coming in from the individual role report comments.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/58#issuecomment-387381841.
