### ISSUE TITLE
For April 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#65]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: **2750**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value. **Please include only completed work!**_

### Development work:
Most for my dev work is for the DAO [1] and not shipped code so following the recent policy changes I will not include that in the compensation request.
Other dev work which got merged to master is not shipped as the 0.7.0 release is not out yet.  
So there is no dev work included that month.

### Maintainer:
- Maintain 8 seed nodes (6 BTC, 2 LTC), 2 Bitcoin nodes, 2 price nodes, monitor node, market server and BSQ explorer (15 * 50 BSQ = 750 BSQ)

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1#issuecomment-385694833
- Exchange Maintainer: https://github.com/bisq-network/roles/issues/3#issuecomment-385710006
- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8#issuecomment-385691445
- Seed node maintainer: https://github.com/bisq-network/roles/issues/6#issuecomment-385691250
- Statsnode Maintainer: https://github.com/bisq-network/roles/issues/7#issuecomment-385692543
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14#issuecomment-385686892
- Markets Website+API Operator/Maintainer: https://github.com/bisq-network/roles/issues/9#issuecomment-385706763
- Seed node operator: https://github.com/bisq-network/roles/issues/15#issuecomment-385690917
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10#issuecomment-385692148
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-385689259

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- GitHub Admin: https://github.com/bisq-network/roles/issues/16
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Slack Admin: https://github.com/bisq-network/roles/issues/23
- Freenode Admin: https://github.com/bisq-network/roles/issues/22

I request in total 2000 BSQ for exercising my roles. Specially the work on reviewing and merging PRs takes considerable time and effort. Beside that keeping an eye on the infrastructure monitoring (seed and btc nodes) takes more time and attention as is should (hope we find soon a dev who will make a good monitoring tool).

[1] https://github.com/ManfredKarrer/bisq-core/tree/voting

**Comment by cbeams** [comment]
Many thanks, @ManfredKarrer, for moving to report comments on the role issues themselves per https://github.com/bisq-network/proposals/issues/13.

In future months, I'd like to report the costs for operating nodes in these comments as well. That way everybody can see in one place who is paying how much for running, say, seednodes on DigitalOcean vs. Heroku vs. AWS, etc. This will probably mean duplicating this information across both the compensation request and the monthly report comment, but it should be pretty minor, e.g. in the compensation request, we'd see bullet points like this:

> - Seednode Operator: https://github.com/bisq-network/roles/issues/15#issuecomment-385690917 (400 BSQ)

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/58#issuecomment-387381841.
