### ISSUE TITLE
For April 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#66]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 112
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

Running 2 bitcoin nodes x 50 and one subscription to bitcoinaverage at USD12, price node run by Manfred.

This month I tried moving over price node and seed node to my control but the service I used is not the most reputable (at least I would not consider them after this incident). They shut down my VPS quoting cryptocurrency mining when I was only running one seed node and nothing else on that particular instance. I couldn't get an answer to why they actually shut it down but I would have to find a more solid solution to be able to take seed and price node back.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/58#issuecomment-387381841.
