### ISSUE TITLE
For Cycle 17

### ISSUE THREAD

**Issue by acrual** [bisq-network/compensation#660]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[74.62]`** 
- USD requested: [50] 
- BSQ rate: [0.67] USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Experience the DAO | growth | 50 | https://www.rankia.com/blog/aprendiendo-bitcoin-desde-cero/4715938-plataformas-intercambio-descentralizadas-que-bisq-network | Article about Bisq and its DAO in Rankia, one of the most important online financial communities in Spanish speaking countries. As of today it got 1914 page views. I've been promoting Bitcoin from a maximalist pov for the last 6 months |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by MwithM** [comment]
I proposed Adolfo via twitter to ask for this compensation according to the [Tipping Hat](https://github.com/bisq-network/growth/issues/195) promotion. 
The blog is written on an important Spanish financial forum, and it had very good articles about BTC. Even if the article doesn't give the best view of BSQ, it's not supposed to be a promotional paid add but a honest opinion, and the general view of Bisq is positive _"to me, Bisq looks unstoppable. Basically, it replicates Bitcoin model to allow trades between Bitcoin world and fiat world"_.
I just hope that the explanation I gave to Acrual about BSQ value and this experience improves the impression on the coloured coin in which the Bisq DAO relies.

**Comment by acrual** [comment]
> I proposed Adolfo via twitter to ask for this compensation according to the [Tipping Hat](https://github.com/bisq-network/growth/issues/195) promotion.
> The blog is written on an important Spanish financial forum, and it had very good articles about BTC. Even if the article doesn't give the best view of BSQ, it's not supposed to be a promotional paid add but a honest opinion, and the general view of Bisq is positive _"to me, Bisq looks unstoppable. Basically, it replicates Bitcoin model to allow trades between Bitcoin world and fiat world"_.
> I just hope that the explanation I gave to Acrual about BSQ value and this experience improves the impression on the coloured coin in which the Bisq DAO relies.

It has improved my understanding of Bisq indeed, thanks a lot btw for your feedback and help in editing the article!

**Comment by m52go** [comment]
@MwithM and I discussed this a few weeks ago. I [approve](https://bisq.wiki/Compensation#Team_Lead) this submission based on the idea that Rankia is a good medium. For what it's worth, @acrual has been around Bisq for a while ([link](https://github.com/bisq-network/proposals/issues?q=is%3Aissue+author%3Aacrual+is%3Aclosed) and [link](https://github.com/bisq-network/bisq/issues?q=is%3Aissue+author%3Aacrual+is%3Aclosed)).

Go ahead and submit to the DAO and post txid here.

**Comment by acrual** [comment]
Great! Many thanks! :)

DAO txid: f8cd956498f7adc19088af450fcb79bbb81d6182c455ed8032e4a9b8cc31c11d

**Comment by ripcurlx** [comment]
> Great! Many thanks! :)
> 
> DAO txid: f8cd956498f7adc19088af450fcb79bbb81d6182c455ed8032e4a9b8cc31c11d

@acrual You made a mistake in your compensation request posting `https://bisq-network/dao-compensation/660` instead of `https://bisq.network/dao-compensation/660`. I guess most reviewers will be sophisticated enough to find the correct proposal, but it might be the case that you have to re-submit it in the next cycle if it is voted down because of that.

**Comment by acrual** [comment]
> > Great! Many thanks! :)
> > DAO txid: f8cd956498f7adc19088af450fcb79bbb81d6182c455ed8032e4a9b8cc31c11d
> 
> @acrual You made a mistake in your compensation request posting `https://bisq-network/dao-compensation/660` instead of `https://bisq.network/dao-compensation/660`. I guess most reviewers will be sophisticated enough to find the correct proposal, but it might be the case that you have to re-submit it in the next cycle if it is voted down because of that.

Oh thanks, what an idiotic mistake from my side! 

Regards!

**Comment by MwithM** [comment]
Closed as accepted
