### ISSUE TITLE
For April 2018

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/compensation#67]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 20
 - BSQ address: B16kMZonmnNXrZvSqGuXVjpWWTZnSVG3xJb

### BTC/GBP Liquidity

Participated in BTC/GBP Liquidity week keeping 2 positions open. Volume was 0.05 BTC, and there was no transaction match, will adapt volume for next liquidity week

### Payment Method Maintaner

https://github.com/bisq-network/roles/issues/38

**Comment by cbeams** [comment]
@alfsbs, could you also please report on your first (partial) month of work as Payment Method Maintainer in bisq-network/roles#38? Please do so per the instructions at bisq-network/proposals#13, thanks.

**Comment by cbeams** [comment]
Note that there shouldn't be any compensation requested for this work, as no new payment methods have been delivered (per bisq-network/proposals#19), but it's still desirable to have everyone playing roles under the DAO report on those roles every month (however briefly) and to link to that report from their monthly compensation requests.

**Comment by cbeams** [comment]
I just realized, actually, that this compensation request is specific to the GBP liquidity week, so it makes sense that you didn't mention anything about your Payment Method Maintainer work here. In principle it's fine to do per-task compensation requests like this, but in practice, while we're doing everything via the spreadsheet, and things are a bit manual and cumbersome, it's a better in practice to do a single monthly compensation request that itemizes the different tasks you performed and links to the reports on the different roles you played. This gives voting stakeholders a single request to vote on per contributor. So feel free to change the title of this request to "For April 2018" and then do the report as mentioned and update the description of this issue to link to it. Thanks.

**Comment by cbeams** [comment]
Thanks for following up with the report comment at https://github.com/bisq-network/roles/issues/38#issuecomment-385894663, @alfsbs. You'll see my additional comment about it at https://github.com/bisq-network/roles/issues/38#issuecomment-387371388.

In the future, please link directly to these reports from your compensation request issue descriptions. e.g. instead of:

> ## Payment Method Maintaner
> bisq-network/roles#38

as you have it above, you can just do a single line item / bullet point, e.g.:

> - Payment Method Maintainer: https://github.com/bisq-network/roles/issues/38#issuecomment-385894663

Thanks again for your work!

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/58#issuecomment-387381841.
