### ISSUE TITLE
For Cycle 17

### ISSUE THREAD

**Issue by softsimon** [bisq-network/compensation#678]
## Summary

* **BSQ requested**: **`7462`**
* USD requested: 5000
* BSQ rate: 0.67 USD per BSQ
* Previous compensation request (if applicable): #625

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Bisq Markets API re-implementation in NodeJS | ops | 5000 | https://github.com/mempool/mempool/pull/107 | https://github.com/bisq-network/projects/issues/41 milestone 1 |

**Comment by wiz** [comment]
@jmacxx is this because of missing EOL issue?

**Comment by ghost** [comment]
Yes.  It never rains, it pours, right?

**Comment by wiz** [comment]
Approved for ops

**Comment by softsimon** [comment]
a93d9c83aaadf29e1599df19e473da05df2111c014c5c9ef884b37a23a8b04dc

**Comment by MwithM** [comment]
Closed as accepted
