### ISSUE TITLE
For cycle 18

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#697]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`2058`** 
- USD requested: 1400 
- BSQ rate: 0.68 USD per BSQ 
- Previous compensation request (if applicable): #677 

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| 4* Bitcoin node operator | ops* | 200 | bisq-network/roles#67 |  |
| 5* Seed node operator | ops* | 500 | bisq-network/roles#15 |  |
| Pricenode operator | ops* | 100 | bisq-network/roles#14 |  |
| Mailman operator | ops* | 100 | bisq-network/roles#26 |  |
| Mempool operator | ops* | 200 | bisq-network/roles#107 |  |
| Monero Explorer Operator | ops* | 200 | bisq-network/roles#109 | 200 because it is for cycle 17+18  |
| Testing and partly reviewing | dev | 100 | bisq-network/bisq#4492 | merged |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by ripcurlx** [comment]
As stand in [team lead](https://bisq.wiki/Compensation#Team_Lead) I approve this request for dev.

**Comment by wiz** [comment]
Approved for ops

**Comment by Emzy** [comment]
TXID: 1241ea546cd9b857eef1e5e68e95e27037e54c7b4c2fa4698623c7cf47aa7e20

**Comment by cbeams** [comment]
For others' benefit when reviewing and voting: I wondered why this compensation request jumped to running 5 seednodes vs. the usual 3 in previous requests, and I saw by clicking through to @Emzy's seednode operator cycle report at https://github.com/bisq-network/roles/issues/15#issuecomment-715438885 that this is just a temporary measure during the Tor v2 > v3 migration.

@Emzy, in future compensation requests, please link to your specific cycle report comments as opposed to just linking to the role issue. That is the norm (though not formally documented—I just checked), and helps make this kind of reviewing quicker and more precise. Thanks!

**Comment by MwithM** [comment]
Closed as accepted.
