### ISSUE TITLE
For October 2017

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#7]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

Note: this compensation request covers October 2017

 - BSQ amount requested:  11200
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

### Tor integration

Integrating the netlayer lib into Bisq + merge old UI for setting bridges + testing
bisq-network/exchange#971

### Various

* Added a sync bot between IRC/Matrix/Slack/Telegram
* made docker config for setting up of a seed node: PR bisq-network/exchange#977
* [made test-branch for java 9 compilation](https://github.com/mrosseel/bisq-exchange/tree/java9)
* testing and fixing PR bisq-network/exchange#871
* Feedback regarding UI improvements
* DAO paper review
* See complete Github activity at: https://github.com/mrosseel

**Comment by ManfredKarrer** [comment]
As already shortly discussed on Slack it is a good question from when we should start our requests. August was the inofficial DAO genesis start. So maybe we summarize all what happened since August to go into the month? 
@all: What do you think?

**Comment by cbeams** [comment]
The rationale I have been working with is this:

We cut the testnet genesis distribution on October 6th, and individual past contributors' stake was open for adjustment right up until that point, so I've seen the October 6th distribution as representing all work up until that date (or at least up until the beginning of October). 

To keep things clean and simple, then, I think it makes sense to include in this first compensation request only those units of work that were completed in October, and likewise for every month that follows.

@mrosseel, could you in any case, separate these compensation requests into two parts? The stuff you completed in October vs. the stuff you completed earlier? Thanks.

**Comment by cbeams** [comment]
Also, @mrosseel, could you add a BSQ address to your request? Thanks.

**Comment by mrosseel** [comment]
Updated to be October only, added BSQ address

**Comment by cbeams** [comment]
Thanks, @mrosseel. I've entered this request in the [stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=0) at 13200 BSQ for address B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj.

**Comment by ManfredKarrer** [comment]
@cbeams Yes you are right, thought Mikes API work was not reflected. I am not aware of other outstanding work not reflected there.

**Comment by cbeams** [comment]
Closing as complete. See bisq-network/dao#8
