### ISSUE TITLE
For Cycle 19

### ISSUE THREAD

**Issue by Drazen-V** [bisq-network/compensation#714]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **149.25** 
- USD requested: 100 
- BSQ rate: 0.67 USD per BSQ 
- Previous compensation request (if applicable): https://github.com/bisq-network/compensation/issues/302  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| debugging | dev | 100 | https://github.com/bisq-network/bisq/issues/4807 | asking for compensation for my time investigating the issue, which includes testing on a second machine and going over the relevant log files (as reported on the issue itself)|

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by MwithM** [comment]
Debugging must be a dev team compensation request. Parsing should be valid for compensation request review!

**Comment by Drazen-V** [comment]
Thanks. Changed now.
Please note that there's actually a `team:?` label among the labels.

**Comment by ripcurlx** [comment]
Although normally bug reporting is not compensated I as [team lead](https://bisq.wiki/Compensation#Team_Lead) approve this request, as in this case the investigation and repeated testing led to a critical bug, fixed in https://github.com/bisq-network/bisq/pull/4840. Please submit your DAO proposal and paste the transaction ID here as a comment when complete, thanks.

**Comment by MwithM** [comment]
Please submit here the TXID of your proposal for compensation request.

**Comment by Drazen-V** [comment]
Tx id: `e45adcde830fff9aba121a5238dfac7abd4cffc0c7835575011dd4b47138fe64`

**Comment by MwithM** [comment]
Closed as accepted.
