### ISSUE TITLE
For May 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#72]
## Basic information

 - BSQ amount requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**

## Details

- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-392880209
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-392889396
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-392870951

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/70#issuecomment-394830501.
