### ISSUE TITLE
For May 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#75]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: **7750**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value. **Please include only completed work!**_

### Development work:
Most for my dev work is for the DAO [1] and not shipped code so following the recent policy changes I will not include that in the compensation request.
Beside that I did the release 0.7.0 [2] and earlier dev work included in the release which was not included last months as the release was not shipped. 
Also prepared a few new changes for the 0.7.1 release which is not shipped and therefore not included in the request here.
For the dev work on 0.7.0 and the release I request 5000 BSQ. 

### Maintainer:
- Maintain 8 seed nodes (6 BTC, 2 LTC), 2 Bitcoin nodes, 2 price nodes, monitor node, market server and BSQ explorer (15 * 50 BSQ = 750 BSQ)

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1#issuecomment-393213268
- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8#issuecomment-393214773
- Seed node maintainer: https://github.com/bisq-network/roles/issues/6#issuecomment-393215309
- Statsnode Maintainer: https://github.com/bisq-network/roles/issues/7#issuecomment-393215482
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14#issuecomment-393215839
- Markets Website+API Operator/Maintainer: https://github.com/bisq-network/roles/issues/9#issuecomment-393216170
- Seed node operator: https://github.com/bisq-network/roles/issues/15#issuecomment-393216350
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10#issuecomment-393216741
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-393216903

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- GitHub Admin: https://github.com/bisq-network/roles/issues/16
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Slack Admin: https://github.com/bisq-network/roles/issues/23
- Freenode Admin: https://github.com/bisq-network/roles/issues/22

I request in total 2000 BSQ for exercising my roles. Specially the work on reviewing and merging PRs takes considerable time and effort. Beside that keeping an eye on the infrastructure monitoring (seed and btc nodes) takes more time and attention as is should (hope we find soon a dev who will make a good monitoring tool).

[1] https://github.com/ManfredKarrer/bisq-core/tree/voting
[2] https://github.com/bisq-network/bisq-desktop/releases/tag/v0.7.0

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/70#issuecomment-394830501.
