### ISSUE TITLE
For May 2018

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#76]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 400
 - BSQ address: B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- Pricenode Operator at bisq-network/roles#14
- Seednode Operator at bisq-network/roles#15
- Bitcoin Node Operator at bisq-network/roles#67
- Mailman Operator at bisq-network/roles#26

## Compensation calculation:

no Setup, only maintenance 

Monthly costs nodes: 5* VPS (50 / node) -> 250
Monthly costs dedicated node 100
Monthly costs mailinglist server: 50
=400

**Comment by cbeams** [comment]
Thanks, @Emzy for writing monthly reports on your respective role issues. In future compensation requests, please link directly to those comments instead of just linking to the role issue.

So instead of:

> - Pricenode Operator at bisq-network/roles#14

it would read:

> - Pricenode Operator: https://github.com/bisq-network/roles/issues/14#issuecomment-393234591

This makes it easy for stakeholders to review everything during voting.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/70#issuecomment-394830501.
