### ISSUE TITLE
For Cycle 21 [Please reject my proposal as we are over the max issuance limit]

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/compensation#768]
## Summary

Please reject my proposal as we are over the max issuance limit!

- **BSQ requested**: **`31133.33`**
- USD requested: 23350
- BSQ rate: 0.75 USD per BSQ

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| UI improvements | dev | 300 | https://github.com/bisq-network/bisq/pull/4914 | - |
| Property fields must not be set from non JavaFX threads | dev | 50 | https://github.com/bisq-network/bisq/pull/4916 | - |
| Detect and handle invalid maker fee tx | dev | 300 | https://github.com/bisq-network/bisq/pull/4917 | - |
| Revert TTL to original value of 15 days | dev | 0 | https://github.com/bisq-network/bisq/pull/4920 | - |
| Detect missing deposit tx to allow moving to failed trades | dev | 200 | https://github.com/bisq-network/bisq/pull/4921 | - |
| Fix sorting of table columns | dev | 100 | https://github.com/bisq-network/bisq/pull/4923 | - |
| Improve shutdown routine | dev | 100 | https://github.com/bisq-network/bisq/pull/4927 | - |
| Make sign age column sortable | dev | 300 | https://github.com/bisq-network/bisq/pull/4929 | - |
| Use HistoricalDataStoreService for AccountAgeWitnessStorageService  | dev | 300 | https://github.com/bisq-network/bisq/pull/4930 | - |
| Improve funds and portfolio screens | dev | 400 | https://github.com/bisq-network/bisq/pull/4933 | - |
| Add wallet info view | dev | 500 | https://github.com/bisq-network/bisq/pull/4935 | - |
| Refactor http client | dev | 300 | https://github.com/bisq-network/bisq/pull/4942 | - |
| Add tx broadcast to mempool explorer api | dev | 1300 | https://github.com/bisq-network/bisq/pull/4943 | - |
| Improve TransferWise account | dev | 100 | https://github.com/bisq-network/bisq/pull/4944 | - |
| Fix bug with maker fee tx at create offer | dev | 100 | https://github.com/bisq-network/bisq/pull/4947 | - |
| Show price deviation in % for fixed price offers and BSQ | dev | 900 | https://github.com/bisq-network/bisq/pull/4949 | - |
| Allow sending private notifications from avatar icon at trade | dev | 100 | https://github.com/bisq-network/bisq/pull/4952 | - |
| Cache results in account witness domain | dev | 600 | https://github.com/bisq-network/bisq/pull/4953 | Includes Profiling work |
| Various small improvements | dev | 100 | https://github.com/bisq-network/bisq/pull/4954 | - |
| Cache results of isFiatCurrency and isCryptoCurrency | dev | 400 | https://github.com/bisq-network/bisq/pull/4955 | Profiling was main effort here |
| Sort payment methods by display string not by id | dev | 50 | https://github.com/bisq-network/bisq/pull/4956 | - |
| Do not use tx broadcast to mempool nodes if a local btc nodes is used | dev | 100 | https://github.com/bisq-network/bisq/pull/4958 | - |
| Call completeHandler if services in store services is empty | dev | 200 | https://github.com/bisq-network/bisq/pull/4963 | - |
| Avoid resync from genesis in case of dao state issues | dev | 300 | https://github.com/bisq-network/bisq/pull/4971 | - |
| Improve logs | dev | 100 | https://github.com/bisq-network/bisq/pull/4973 | - |
| Fix nullpointer | dev | 0 | https://github.com/bisq-network/bisq/pull/4974 | - |
| Improve CleanupMailboxMessages | dev | 400 | https://github.com/bisq-network/bisq/pull/4975 | - |
| Remove NGN (Nigerian Naira) as their central bank blocked Transferwise | dev | 50 | https://github.com/bisq-network/bisq/pull/4976 | - |
| Add extra note for amazon gift cards | dev | 100 | https://github.com/bisq-network/bisq/pull/4977 | - |
| Fix wrong account age data access | dev | 200 | https://github.com/bisq-network/bisq/pull/4981 | Includes debugging efforts |
| Improve popup text in case a local node is detected | dev | 50 | https://github.com/bisq-network/bisq/pull/4984 | - |
| Improve trade fee display at create and take offer screens and popups | dev | 400 | https://github.com/bisq-network/bisq/pull/4985 | - |
| Remove redundant popup | dev | 50 | https://github.com/bisq-network/bisq/pull/4987 | - |
| Add mediators keybase usernames | dev | 100 | https://github.com/bisq-network/bisq/pull/5004 | - |
| Improve offer publishing | dev | 300 | https://github.com/bisq-network/bisq/pull/4950 | - |
| Move BSQ price in USD at first row | dev | 50 | https://github.com/bisq-network/bisq/pull/4988 | - |
| Add percentage price to open offer view | dev | 200 | https://github.com/bisq-network/bisq/pull/4993 | - |
| Cleanup trade wallet code | dev | 50 | https://github.com/bisq-network/bisq/pull/4997 | - |
| Add generic map (cookie) to UserPayload | dev | 300 | https://github.com/bisq-network/bisq/pull/4999 | - |
| Deactivate open offer if trigger price is reached | dev | 2300 | https://github.com/bisq-network/bisq/pull/5001 | - |
| Add estimated size to log of initial data response | dev | 50 | https://github.com/bisq-network/bisq/pull/5009 | - |
| Dao performance improvements | dev | 50 | https://github.com/bisq-network/bisq/pull/5010 | - |
| Show stacktrace in error popup at view exceptions | dev | 50 | https://github.com/bisq-network/bisq/pull/5011 | - |
| Change trade period for transferwise from 1 day to 4 days | dev | 150 | https://github.com/bisq-network/bisq/pull/5016 | Effort was testing backward compitability |
| Improve getBlocks request handling | dev | 400 | https://github.com/bisq-network/bisq/pull/4851 | - |
| Add dos protection | dev | 200 | https://github.com/bisq-network/bisq/pull/5026 | - |
| We need to use the getMapOfAllData method for HistoricalDataStoreServices | dev | 100 | https://github.com/bisq-network/bisq/pull/5030 | - |
| Access concrete data stores | dev | 100 | https://github.com/bisq-network/bisq/pull/5031 | - |
| Check for duplicate hashes at onBundleOfEnvelopes | dev | 100 | https://github.com/bisq-network/bisq/pull/5032 | - |
| Only publish witness if we are in date tolerance | dev | 100 | https://github.com/bisq-network/bisq/pull/5033 | - |
| Add filter support on network level | dev | 600 | https://github.com/bisq-network/bisq/pull/5038 | - |
| Add option to prevent periodic shutdown for seed nodes | dev | 50 | https://github.com/bisq-network/bisq/pull/5039 | - |
| Request only non-seed nodes if no seed nodes are available | dev | 50 | https://github.com/bisq-network/bisq/pull/5041 | - |
| Select show-all currencies if TransferWise is selected | dev | 100 | https://github.com/bisq-network/bisq/pull/5042 | - |
| Add option to hide non supported payment methods | dev | 200 | https://github.com/bisq-network/bisq/pull/5045 | - |
| Add cache for signature verification results and a lookup map by ownerPubKey| dev | 400 | https://github.com/bisq-network/bisq/pull/5047 | - |
| Add toggle for hiding not takable offers | dev | 300 | https://github.com/bisq-network/bisq/pull/5048 | - |
| Add protection tool| dev | 300 | https://github.com/bisq-network/bisq/pull/5053 | - |
| Add csv export to bsq tx view | dev | 200 | https://github.com/bisq-network/bisq/pull/5054 | - |
| Fix premature disconnections from seeds | dev | 600 | https://github.com/bisq-network/bisq/pull/5057 | - |
| Persist failed attempts of decrypting mailbox messages | dev | 800 | https://github.com/bisq-network/bisq/pull/5061 | - |
| Add toggle for displaying volume in tradestatistics chart in USD | dev | 800 | https://github.com/bisq-network/bisq/pull/5066 | - |
| Improve cleanup tor dir at seeds | dev | 50 | https://github.com/bisq-network/bisq/pull/5070 | - |
| Persist and republish mailbox messages | dev | 3000 | https://github.com/bisq-network/bisq/pull/5072 | - |
| Change rule for "reason for payment" field to not use trade ID but leave it empty | dev | 300 | https://github.com/bisq-network/bisq/pull/5080 | - |
| Fix bug with ignoreLocalBtcNode | dev | 50 | https://github.com/bisq-network/bisq/pull/5094 | - |
| Release testing | dev | 500 | - | - |
| Technical user support | support | 2000 | - | - |

#### Note:
I added contributions from the start of cycle 20 only (9.12.2020). I did not request compensation of my work of the past months, but might add that to future requests.

**Comment by leo816** [comment]
From the support side, My [Team Lead](https://bisq.wiki/Compensation#Team_Lead)  review is complete and I approve this request. Please submit your DAO proposal and paste the transaction ID here as a comment when complete, thanks.

**Comment by chimp1984** [comment]
TxID: 35b06bbbc8f8722ef1a14a2f277a2d54cde1c28bde98f9248db2351307fd7098

**Comment by ripcurlx** [comment]
As [dev team lead](https://bisq.wiki/Compensation#Team_Lead) I approve this request.

**Comment by chimp1984** [comment]
As we are over 300k we need to reduce some expenses. There is a hard limit (DAO param so can be changed) with 300k BSQ to be issued, if we are higher it would invalidate the cycle (again). So to avoid that I will make another request just before the proposal phase ends with a lower amount so we do not exceed that. My initial request need to be down-voted then to invalidate it.

https://docs.google.com/spreadsheets/d/1Mc3-Pf6ud-RhFa_NKqeO2DEOm07K8xsTcEGnfyFsY9U/edit#gid=0

**Comment by Emzy** [comment]
> Read BSQ amount from summary: 3113333

This is a paring error. Somehow the "." from "31133.33" was not parsed.

**Comment by chimp1984** [comment]
> > Read BSQ amount from summary: 3113333
> 
> This is a paring error. Somehow the "." from "31133.33" was not parsed.

I used a `,` for comma, the parser requires anglosaxon `.`.

**Comment by freimair** [comment]
let me just repeat what I commented on your Cycle 20 CR:

> Following Bisq's policy and budgeting efforts render PR (or issues fixed) not marked "bug", "critical" or "priority" to not be up for compensation in order to battle overspending, BSQ inflation, and focus work on what is most important. This has been put in place months ago and enforced ever since.
> 
> Looking at your CR while keeping the aforementioned Bisq policy and budgeting efforts in mind, makes the mind boggle. A number of items, in fact, none of them, are marked "bug", "critical" or "priority". Wouldn't that indicate that the amount your are asking for is somewhat off?

seems to be especially valid now as this CR threatens to fail again because of overspending.

**Comment by chimp1984** [comment]
Those restrictions on expenses have been made in times when Bisq was not sustainable from the revenue stream. Luckily we are in a better situation now and due lack of work force to maintain the projects area those rules have not been updated. I prefer to spend my time on coding instead of management and nobody else took time either. 

As you know Bisq is based on meritocracy, so the merits everyone has earned with their contributions are their voting power. So fee free to use the merit you have earned to down-vote my proposal if you think it is not justified.

I will stop now to comment further as I prefer to spend my time on more productive activitites.

**Comment by chimp1984** [comment]
Please reject my proposal as we are over the max issuance limit!
I will redo it next cycle with exact same numbers/price.

**Comment by MwithM** [comment]
If you edit the first post to ask for 0 BSQ the parser will fail and it will be even more evident that this compensation request should be rejected.

**Comment by MwithM** [comment]
Closed as rejected.
