### ISSUE TITLE
For May 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#77]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 112
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

This month has been very slow as I've been sick for most of the time. Currently reviewing the DAO code in @ManfredKarrer's repo.

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for.

- Pricenode subscription - https://github.com/bisq-network/roles/issues/14
- Bitcoin Node Operator - https://github.com/bisq-network/roles/issues/67

Requesting:
BSQ12 for subscription to price node that manfred is running
BSQ100 for running two bitcoin nodes, 50x2

**Comment by cbeams** [comment]
Thanks, @sqrrm. Please see I just left on @Emzy's report at https://github.com/bisq-network/compensation/issues/76#issuecomment-394821593, as it applies to you too.

Also, for consistency, please use `2018.05 report` headings instead of `May 2018 report`. Scroll through the other recent reports in https://github.com/bisq-network/roles/issues/14, and you'll see what I mean about this.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/70#issuecomment-394830501.
