### ISSUE TITLE
For Cycle 21

### ISSUE THREAD

**Issue by stopfeds** [bisq-network/compensation#777]
## Summary

- **BSQ requested**: **282**
- USD requested: 212
- BSQ rate: 0.75 USD per BSQ
- Previous compensation request (if applicable):

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| German Bisq-website translation | Growth | 150 | --- | --- |
| German Bisq-desktop translation | Growth | 62 | --- | --- |

![Cycle 21 Website strings yml](https://user-images.githubusercontent.com/71401614/106339214-2fb5eb80-6296-11eb-8eb1-5d3614aaec73.JPG)
![Cycle 21 Desktop](https://user-images.githubusercontent.com/71401614/106339221-32184580-6296-11eb-8bdb-dc8110567389.JPG)

## Contributions in progress

No untranslated strings left

**Comment by MwithM** [comment]
Hi, you're submittin this [late](https://github.com/orgs/bisq-network/teams/dao/discussions/21) for review. Please do it on time next time.
For budgeting reasons, could you make it 150 USD for website and 62 USD for desktop?
The compensation request is approved. Submit the proposal to DAO and comment here the resulting TXID.

**Comment by stopfeds** [comment]
`cdeaa65584a565e148b8b150add5c98d7cf4511a4c88894fc440c0e7bc09c96b`

**Comment by stopfeds** [comment]
> Hi, you're submittin this [late](https://github.com/orgs/bisq-network/teams/dao/discussions/21) for review. Please do it on time next time.

Hey, don't really get what you mean (link doesn't work) because there are still 3-4 days left (Proposal Phase). 
Sorry for the inconvenience.

**Comment by ripcurlx** [comment]
@stopfeds The link doesn't work for you as you are not part of the Bisq GitHub organisation right now. I've just sent you an invitation to it.

**Comment by MwithM** [comment]
You should submit the proposal for review 7 days before end of proposal phase. https://bisq.wiki/Compensation#Create_your_compensation_request_issue

**Comment by MwithM** [comment]
Closed as accepted.
