### ISSUE TITLE
For May 2018

### ISSUE THREAD

**Issue by rex4539** [bisq-network/compensation#78]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 1370
 - BSQ address: B153NNHXQxnH5v6AXv8F5zdhPsdjkQfxB7v

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- https://github.com/bisq-network/bisq-docs/pull/49
350 BSQ. Went through the whole repo and fixed 35 typos in 10 files.
- https://github.com/bisq-network/bisq-website/pull/52
320 BSQ. Went through the whole repo and fixed 32 typos in 15 files.
- https://github.com/bisq-network/bisq-core/pull/109
340 BSQ. Went through the whole repo and fixed 34 typos in 10 files.
- https://github.com/bisq-network/bisq-desktop/pull/1533
270 BSQ. Went through the whole repo and fixed 27 typos in 17 files.
- https://github.com/bisq-network/roles/pull/71
40 BSQ. Went through the whole repo and fixed 4 typos in 4 files.
- https://github.com/bisq-network/bisq-docs/pull/45
50 BSQ. Reviewed and left valuable feedback that was accepted and helped merge the pull request.

**Comment by cbeams** [comment]
Update: bisq-network/roles#71 is actually merged now, and it's fine to include it in this compensation request (please update the issue description accordingly, @rex4539). It was my bad as the Roles Maintainer that I didn't see and merge this earlier. Thanks.

**Comment by cbeams** [comment]
Also, @rex4539, it's very interesting how you approached valuing your work here. It's clear that you valued each typo fixed at 10 BSQ (and 1 BSQ is currently valued at 1 USD during Phase Zero).

For the benefit of stakeholders voting during this round, and also for the benefit of future contributors who may submit compensation requests for similar work, could you please describe your rationale for this valuation, i.e. why 10 BSQ per typo and not 5 or 15? Thanks, and thanks again for the work!

**Comment by rex4539** [comment]
@cbeams I just thought it is a fair compensation for the work performed.

Especially the typo fixes required A LOT of work, I can assure you :)

But if anyone thinks it's too much, we can discuss it. I'm totally open.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/70#issuecomment-394830501.

**Comment by rex4539** [comment]
I just checked the DAO tab in the Bisq client and I still have 0 BSQ.

Was my compensation request rejected?

**Comment by ManfredKarrer** [comment]
The BSQ is not distributed yet: See https://docs.bisq.network/dao/phase-zero.html
