### ISSUE TITLE
For Cycle 22 (old)

### ISSUE THREAD

**Issue by doitsu232** [bisq-network/compensation#780]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`77.40`**
- USD requested: 185.78
- BSQ rate: 2.40 USD per BSQ
- Previous compensation request (if applicable): #610 #780

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| DE Translation for Bisq Desktop | growth | 104.23 | see screenshot | after 16.07.2020 |
| DE Translation for Bisq Website | growth | 81.55 | see screenshot | after 16.07.2020 |

![Screenshot_2021-01-17 #bisq-desktop Transifex Editor](https://user-images.githubusercontent.com/7280760/107211785-4ed71a80-6a06-11eb-97de-ef49b80430c5.png)
1489 Words x 0.07 USD = 104.23 USD

![Screenshot_2021-01-17 bisq-website Transifex Editor](https://user-images.githubusercontent.com/7280760/107211905-79c16e80-6a06-11eb-8f1f-bce99ae40f4d.png)
1165 Words x 0.07 USD = 81.55 USD

## Contributions in progress
none

**Comment by doitsu232** [comment]
will request this for cycle 22

**Comment by m52go** [comment]
@doitsu232 the [rate for this cycle is 1.21](https://github.com/bisq-network/compensation/issues/782).

**Comment by doitsu232** [comment]
> @doitsu232 the [rate for this cycle is 1.21](https://github.com/bisq-network/compensation/issues/782).

edited.

**Comment by MwithM** [comment]
All the website budget was already claimed on #777 and there was [none](https://github.com/bisq-network/roles/issues/20#issuecomment-779689002) left for it.
Reduce the amount for the web to 40USD and make regular reports although the amount to claim is too low to request compensation for every cycle.

**Comment by MwithM** [comment]
was:not submitted

**Comment by doitsu232** [comment]
would like to reopen this one with an updated rate of 2.4USD/BSQ

**Comment by MwithM** [comment]
@doitsu232 I think it's much better if you open a new issue with the Title "For Cycle 24" and copy-paste the compensation request, linking this issue as well.

**Comment by doitsu232** [comment]
> @doitsu232 I think it's much better if you open a new issue with the Title "For Cycle 24" and copy-paste the compensation request, linking this issue as well.

done
