### ISSUE TITLE
For May 2018

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#80]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 250
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### API

Nothing that has been delivered.

### Hosting
Monthly costs nodes: 50 / node * 5: 250 BSQ

Running:
1 Price node + bitcoinaverage subscription
1 Seed node
2 Bitcoin full nodes
1 Monitoring node + 1 messaging sync node (on one server)
  
### Roles + reports

Pricenode Operator at bisq-network/roles#14
Seednode Operator at bisq-network/roles#15
Bitcoin Node Operator at bisq-network/roles#67
Monitoring Operator / Maintainer at bisq-network/roles#10
Freenode IRC Admin at bisq-network/roles#22

**Comment by cbeams** [comment]
Thanks, @mrosseel. A minor nit for future compensation requests, please see the feedback I gave @Emzy and others at https://github.com/bisq-network/compensation/issues/76#issuecomment-394821593.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/70#issuecomment-394830501.
