### ISSUE TITLE
For Cycle 23 

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/compensation#816]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`619.27`** 
- USD requested: 1350 
- BSQ rate: 2.18 USD per BSQ 

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
|L1 Support Agent| Support | 1350 | https://github.com/bisq-network/roles/issues/64#issuecomment-812643482 |  |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by leo816** [comment]
Please go in more depth as to why you have raised the compensation request of L1 support agent from 500 to 1350

**Comment by RififiCastorjunior** [comment]
L1 support agent compensation is 500 for 10 hours, so i done this :

                                  - 500/4 = 125         number of weeks
                                  - 125/10= 12,5        number of hours

So `12,5` is the average compensation done per hour for the role of L1 support agent.

This month i done more than 28 hours per week :

                              - 12,5 * 28 =  350        compensation per week
 	                          - 350 * 4   =  1400

**Comment by MwithM** [comment]
I've never asked for more than 500USD per cycle as a support agent, that's a fixed price independent of the min 10 hours per week required.

**Comment by leo816** [comment]
Personally, I agree with @MwithM . As of right now, I believe we all do extra hours that are not accounted for. Almost triple what all other support agents are asking for is too much. In the future when Bisq reaches a higher volume I would consider this to be more adequate. I would like to hear from other support team members and have an open discussion. If you strongly believe this is justified, you will need to add everything extra you've done here https://github.com/bisq-network/roles/issues/64#issuecomment-812643482 other than just available hours.

**Comment by RififiCastorjunior** [comment]
>  that's a fixed price independent of the min 10 hours per week required.

So it's a min 10 hours, what if people doing more than 10 hours ? for the last 3 month i done more than 25 hours available hours and help on every issue that happen when i attended to the shift. Less than 10min to respond to the users. 

On my proposal last month, i also ask if is too munch of compensation for those 21+ hours, there were no respond to that point.
>https://github.com/bisq-network/proposals/issues/315#issue-818355867

Also ask about if i should stick on those 10 hours to stay on the boundary of the compensation rules, still no answers to that.

Do i have to pull all the logs and chats i done for those 3 months or this month alone ? Plus those extras hours outside of the shift attended ?

**Comment by RififiCastorjunior** [comment]
I think i get the idea now, thanks for all. i was wondering why Dev doesn't want to touch to BSQ, i get it now.
 
i have to be known and i don't have any credibility, so Bisq is an another "death march" project. Thnx for all i will move to other stuff.  

> @wiz sat 03/04/21 at 4:52 CET " IMO one important thing to understand about the Bisq compensation process is that everything we do here is a free contribution, and then maybe later you can color some sats from the Bisq DAO, but it shouldn't be the primary motivation for anyone to get assigned a project or role, and it's not guaranteed either - for example, if someone regularly contributes high quality PRs that get merged, maybe we would allocate budget to their project, or as another example if someone is regularly providing help to others in support, then maybe we would offer them a paid position, but you don't simply "get hired" to work for Bisq without having credibility in the Bisq community first. "

Like the CEO says all i done its free.
