### ISSUE TITLE
For June 2018

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#83]
## Summary

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 300
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

### Hosting
Monthly costs nodes: 50 / node * 5: 250 BSQ

Running:
1 Price node + bitcoinaverage subscription
1 Seed node
2 Bitcoin full nodes
1 Monitoring node + 1 messaging sync node (on one server)
  
## Roles performed

Pricenode Maintainer at https://github.com/bisq-network/roles/issues/5#issuecomment-401298964
Pricenode Operator at https://github.com/bisq-network/roles/issues/14#issuecomment-401299419
Seednode Operator at https://github.com/bisq-network/roles/issues/15#issuecomment-401303828
Bitcoin Node Operator at https://github.com/bisq-network/roles/issues/67#issuecomment-401337756
Monitoring Operator / Maintainer at https://github.com/bisq-network/roles/issues/10#issuecomment-401338254
Freenode IRC Admin at https://github.com/bisq-network/roles/issues/22#issuecomment-401338777

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.
