### ISSUE TITLE
For Cycle 25

### ISSUE THREAD

**Issue by viperperidot** [bisq-network/compensation#847]
## Summary

- **BSQ requested**: **`35`** 
- USD requested: 78.05 
- BSQ rate: 2.23 USD per BSQ 
- Previous compensation request (if applicable):   

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Migrate test spreadsheet off Google and write up README | dev | 78.05 | https://github.com/bisq-network/projects/issues/51 | A test spreadsheet was created for the linked project by flix1 on Google drive. I migrated this spreadsheet to a more private, secure and censorship resistant alternative that better lines up with Bisq. I also wrote up a README for the use of this temporary spreadsheet and cleaned up the sheet a bit to make it look better. Before starting this project I got confirmation from chimp1984 that this was something we wanted done. I did not spend that much time on this, the main content of the spreadsheet was completed by flix1, but I spent a couple hours migrating to the new platform, making small changes and writing up the README. I am happy to do this small contribution work for free but I thought it would be interesting to submit a compensation request to see how the DAO works. Hopefully the BSQ amount is considered reasonable but please let me know if not. The platform I used is called CryptPad and the link to the delivered and live spreadsheet is here: https://cryptpad.fr/sheet/#/2/sheet/edit/tE42iuR--PZ3PsQOyayt9JFo/embed/ Note: the conversations surrounding me working on this took place on Keybase in the #misq-dev channel and also in direct messages.|

## Contributions in progress
There will be a small amount of ongoing work associated with this in case moderation is required to prevent spam.

**Comment by viperperidot** [comment]
Update: I originally requested 20 BSQ but I asked a Bisq contributor about this amount and they thought that was low, I am not too sure how everyone would value this contribution so I started out on the low side. I changed the request to asking for 50 BSQ, please let me know if this is more accurate.

**Comment by MwithM** [comment]
I had issues with data consistency with cryptpad spreadsheets in the past. The info there is not very important to be saved, but regular backups would be necessary.
I find that 50-60 USD would be more accurate, since the main task as I see it was to perform the migration from one platform to another. I assign this to @bisq-network/growth team lead as it's not yet a dev intensive task, but an experiment.

**Comment by MwithM** [comment]
Please update the BSQ rate for Cycle 25. #850

**Comment by viperperidot** [comment]
> Please update the BSQ rate for Cycle 25. #850

Completed, thank you.

**Comment by m52go** [comment]
@viperperidot thanks for your work! I followed the conversation as it took place, appreciate your initiative, and I know you've been an active part of the community for a while now. 

Your request is [approved](https://bisq.wiki/Compensation#Team_Lead). If you don't think you'll be making any additions to this request, feel free to [submit it to the DAO](https://bisq.wiki/Making_a_compensation_request#Submit_your_request_as_a_DAO_proposal) whenever you like.

If you haven't already, check out [these guidelines](https://bisq.wiki/Making_a_compensation_request#Tips_on_valuing_your_work) for valuing work. It's imperfect and unclear but as long as everyone is reasonable and communicates, as you've been doing, we should be ok ;)

**Comment by m52go** [comment]
@viperperidot thanks for that work! I followed the conversation as it took place, appreciate your initiative, and I know you've been an active part of the community for a while now. 

I agree the amount requested of 50 BSQ might be a bit high, but your initial request of 20 BSQ is probably too low. I'm not sure it's worth haggling over, so given the factors I listed above, I'll leave the final amount up to you. Maybe something in the middle?

If it helps, keep in mind that a [rule of thumb](https://bisq.wiki/Making_a_compensation_request#Tips_on_valuing_your_work) is to value what you did as freelance/contract work done on a milestone/deliverable basis in terms of its value to the end user (as opposed to time spent / valuing that time).

There's no technically correct answer here, but the goal is to make it as easy for DAO voters to accept as possible. In my opinion, you've done everything right so far (talking to contributors beforehand, describing your contribution well here, etc). I'm just skeptical that voters will agree to value making a spreadsheet at 111.50 USD.

**Comment by viperperidot** [comment]
Awesome thanks @m52go, I really enjoy being a part of the Bisq community and try to contribute in ways that I can. This is the first thing I have done that I thought might actually qualify as a real contribution with the DAO and i'm excited to see how to DAO works first-hand! Bisq is by far one of the most important projects in the bitcoin space in my opinion so I will keep trying to find ways to help. I did have a look at the guidelines to try and value the work but like you said it is difficult to do at first, I think talking to contributors and getting a few compensation requests approved is the best way to figure out what is appropriate. 

I agree with all the input from everyone so I have adjusted the amount of BSQ requested down to 35 (spit the difference). It seems like a good rule of thumb for me is to ask for a bit more than the lower end but not too much more, so i'll keep that in mind for the future. :)

**Comment by m52go** [comment]
Sounds great. Guidelines for valuing work are imperfect but as long as everyone is reasonable and communicates, as I think we've been doing, we should be ok ;)

[Approved](https://bisq.wiki/Compensation#Team_Lead). Unless you expect to add more items to this request, feel free to [submit this request to the DAO](https://bisq.wiki/Making_a_compensation_request#Submit_your_request_as_a_DAO_proposal) whenever you like and post the TXID here.

**Comment by viperperidot** [comment]
Thanks and sounds good, I am just waiting for the mempool to calm down a bit (I guess I should have submitted it when it was at 35 sats/vbyte) but I think I still have time to wait before I need to submit this request. Maybe this weekend is will be cooled off a bit...

**Comment by ripcurlx** [comment]
@viperperidot Could you please confirm that  `23b12fc1e403ea67be9b7909e9fc96acc952b473ecb926e54c9ff32d6a33b35d` is the correct transaction ID? Thanks!

**Comment by viperperidot** [comment]
Yes that is correct, thank you!

**Comment by MwithM** [comment]
Close as accepted.
