### ISSUE TITLE
For June 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#85]
## Basic information

 - BSQ amount requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**

## Details

- Support Staff: https://github.com/bisq-network/roles/issues/64#issuecomment-401329837
- Forum operator: https://github.com/bisq-network/roles/issues/19#issuecomment-401325972
- Reddit moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-401326857

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.
