### ISSUE TITLE
For June 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#86]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 100
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Asking 50 x 2 for running two bitcoin nodes.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Working on DAO implementation in https://github.com/ManfredKarrer/bisq-core/tree/voting

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bitcoin Node Operator https://github.com/bisq-network/roles/issues/67#issuecomment-395713902
Took over Bitcoin Node Maintainer https://github.com/bisq-network/roles/issues/66#issuecomment-401347559

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.
