### ISSUE TITLE
For cycle 25

### ISSUE THREAD

**Issue by flybylow** [bisq-network/compensation#864]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`224`** 
- USD requested: 500 USD
- BSQ rate: 2.23

## Contributions delivered

https://github.com/bisq-network/projects/issues/57#issuecomment-839515541
(Prototype for offer book and create offer UX for Bisq 2.0 (Misq) #57)

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Prototype for offer book  | dev | 500 | https://github.com/bisq-network/projects/issues/57

**Comment by MwithM** [comment]
BSQ rate should be 2.23, as indicated at the beginning of this cycle. https://github.com/bisq-network/compensation/issues/850

**Comment by ripcurlx** [comment]
@chimp1984 Could you please approve this CR as it is part of the misq project. Thanks!

**Comment by chimp1984** [comment]
ACK

**Comment by ripcurlx** [comment]
As team lead I approve this CR based on the ACK by @chimp1984. Please update the incorrect BSQ rate mentioned in https://github.com/bisq-network/compensation/issues/864#issuecomment-85778801, submit your DAO proposal and paste the transaction ID here as a comment when complete, thanks.

**Comment by flybylow** [comment]
Updated the rate to 2.23.

Do i need to provide a wallet address or take other steps?

**Comment by MwithM** [comment]
No, submit the compensation request to the DAO so it can be voted at the voting phase of this cycle, and comment here the resulting TXID of the proposal.
https://bisq.wiki/Making_a_compensation_request#Submit_your_request_as_a_DAO_proposal

Contact me at Keybase if your doubts persist.

**Comment by MwithM** [comment]
Was not submitted.

**Comment by flybylow** [comment]
Is the first time i tried making a request.  It says i need BSQ funds to make the request. How do i get some?

**Comment by ripcurlx** [comment]
> Is the first time i tried making a request. It says i need BSQ funds to make the request. How do i get some?

On Bisq in the BTC/BSQ market. :wink:

**Comment by MwithM** [comment]
This [guide](https://bisq.wiki/Trading_BSQ) will help you to buy small amounts. As first time contributor you could also have asked for help too.
