### ISSUE TITLE
For June 2018

### ISSUE THREAD

**Issue by m52go** [bisq-network/compensation#87]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 1800
 - BSQ address: B1FGfKZQrpbLN9UNMogyJAVTR5PJNRkGPXJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Finished docs:
- [Getting Started Guide](https://docs.bisq.network/getting-started.html) - 1500 BSQ
- [Secure Your Wallet](https://docs.bisq.network/secure-wallet.html) - 300 BSQ

I would imagine the Getting Started Guide was a bit of an exception in the time it took to write and the scrutiny it was put under, considering its importance in promoting & growing Bisq.

Context:
- [Here's the PR for both items](https://github.com/bisq-network/bisq-docs/pull/45).

- [Here's the tweet thread announcing both items](https://twitter.com/bisq_network/status/1001086255277531136). Based on likes and retweets, it seems like it got above-average engagement.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

I'm working on a doc for backup & recovery, and hope to get at least one more doc done this month in addition to that. I'll also propose to take responsibility for a role...not sure which one yet.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

N/A.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.
