### ISSUE TITLE
For June 2018

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#89]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 1760
 - BSQ address: B1HGxmhfWJwwvvDgTRrWpZ1QsEZn7rMEaVE

The 1760 above is calculated as 10 for pricenode hosting, 250 for my delivered docs contributions, and 1500 for my Twitter Admin work. I've never put a specific valuation on operating the Twitter handle before, but I think that if I were not doing the work I'm doing there, I would pay at least 1500 / mo to have someone do an equivalent job. I actually think I'd pay considerably more, too, as this is our most important communications channel and I think the quality of our presence there matters a lot, but I'd like to get a gauge from other stakeholders about this first. Comments welcome.

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

### Bisq Docs

 - Expand docs index into a comprehensive table of contents (Part I: User Docs): https://github.com/bisq-network/bisq-docs/pull/60

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

### Bisq Docs

 - [WIP] Produce 'Glossary' doc: https://github.com/bisq-network/bisq-docs/pull/76
 - [WIP] Produce 'Roles' doc: https://github.com/bisq-network/bisq-docs/pull/46
 - [WIP] Produce 'Payment Methods' doc: https://github.com/bisq-network/bisq-docs/pull/73 
 - [WIP] Produce 'GitHub' doc: https://github.com/bisq-network/bisq-docs/pull/64 
 - [WIP] Produce 'Compensation' doc: https://github.com/bisq-network/bisq-docs/pull/62
 - [WIP] Produce 'Voting' doc: https://github.com/bisq-network/bisq-docs/pull/65 
 - [WIP] Produce 'Support' doc: https://github.com/bisq-network/bisq-docs/pull/66 
 - Produce Bisq HTTP API Getting Started guide: https://github.com/bisq-network/bisq-docs/pull/54
   - Reviewing @blabno's original work
   - Part of larger effort to deliver Bisq HTTP API

### Bisq Assets

 - Reviewed a handful of asset PRs
 - Shipped releases [0.7.1](https://github.com/bisq-network/bisq-assets/releases/tag/v0.7.1) and [0.7.2](https://github.com/bisq-network/bisq-assets/releases/tag/v0.7.2) and integrated into Bisq Core in time for the 0.7.1 Bisq Desktop release (which will now ship early next month, thus my placing these contributions here "in progress")

### Bisq Pricenode

 - I am still holding off on requesting any BSQ for the refactoring / rewriting of bisq-pricenode until all @bisq-network/pricenode-operators have upgraded. I asked everyone to make doing so a priority last month. I'm still not sure whether everyone has upgraded. (UPDATE per https://github.com/bisq-network/compensation/issues/89#issuecomment-401546222: looks like all operators have updated, but I'll still wait until next month to claim this work).

### Lists
 - Create a bisq-announce mailing list to replace now-defunct MailChimp newsletter: https://github.com/bisq-network/proposals/issues/20
   - I need to hand this off

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

### Substantive reports

 - Arbitrator: https://github.com/bisq-network/roles/issues/13#issuecomment-401549925 (not for compensation)
 - Bisq Docs Maintainer: https://github.com/bisq-network/roles/issues/29#issuecomment-401550212
 - Bisq Pricenode Operator: https://github.com/bisq-network/roles/issues/14#issuecomment-401550697
 - Founder: https://github.com/bisq-network/roles/issues/1#issuecomment-401551457
 - Proposals Maintainer: https://github.com/bisq-network/roles/issues/30#issuecomment-401552483
 - Roles Maintainer: https://github.com/bisq-network/roles/issues/28#issuecomment-401552875
 - Slack Admin: https://github.com/bisq-network/roles/issues/23#issuecomment-401553865
 - Twitter Admin: https://github.com/bisq-network/roles/issues/21#issuecomment-401554300

### Nothing to report

 - Ambassador: https://github.com/bisq-network/roles/issues/35#issuecomment-401549517
 - Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63#issuecomment-401549975
 - Bisq Pricenode Maintainer: @mrosseel gave update this month (thanks!)
 - Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12#issuecomment-401550827
 - DAO Maintainer: https://github.com/bisq-network/roles/issues/4#issuecomment-401550909
 - DNS Admin: https://github.com/bisq-network/roles/issues/18#issuecomment-401551077
 - Keybase Admin:

### Secondary roles

The following are roles where I play a _secondary_ role, and do not (necessarily) do monthly reports:

 - Bisq Desktop Maintainer: bisq-network/roles#63
 - Compensation Maintainer: https://github.com/bisq-network/roles/issues/31 (@ripcurlx took over primary ownership this month—thanks!)
 - Events Maintainer: https://github.com/bisq-network/roles/issues/65 (@ManfredKarrer took over primary ownership this month—thanks!)
 - Freenode IRC Admin: bisq-network/roles#22
 - Support Staff: bisq-network/roles#64
 - YouTube Admin: bisq-network/roles#56

### New roles

The following are new roles that, as per my comments in my last compensation requests (#68 and #74), I have been meaning to create, but have not yet in fact done. I won't be owning these roles, just creating them (as part of the Roles Maintainer role, actually).

 - [x] Bisq Design Maintainer
 - [x] Bisq Assets Maintainer
 - [x] Bisq Common Maintainer
 - [x] Bisq P2P Maintainer (actually renaming existing 'P2P Developer' role)
 - [x] Bisq Core Maintainer
 - [x] Support Maintainer (for the support repo, not the 'Staff' role above)

## Notes to self
<details>

My contributions this month were created by reviewing the results of this GitHub Issues search query: [org:bisq-network involves:cbeams updated:2018-06-01..2018-06-30 sort:updated-desc](https://github.com/issues?utf8=%E2%9C%93&q=org%3Abisq-network+involves%3Acbeams+updated%3A2018-06-01..2018-06-30+sort%3Aupdated-desc+)

The list of roles above was generated by the following `ghi` command run within my clone of the bisq-network/roles repository:

```
ghi list --assignee=cbeams --no-labels \
| grep -v '^#' \
| cut -b7- | rev | cut -d' ' -f3- | rev | sort \
| xargs -Irole echo " - role: "
```

Also useful to opening all of these issues is the following command:
```
for role in $(\
ghi list --mine \
  | grep -v '^#' \
  | cut -d'[' -f1 \
  | sed 's/^ *//' | sed 's/  /:/' \
  | awk -F':' '{print $2 ":" $1}' \
  | sort | cut -d':' -f2\
); do ghi show --web $role; done;
```
</details>

**Comment by ManfredKarrer** [comment]
Regarding pricenodes: Seems all have already updated (http://188.166.2.139:8080/status)

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.
