### ISSUE TITLE
For Cycle 27

### ISSUE THREAD

**Issue by bisqubutor** [bisq-network/compensation#899]
Hello everybody, this is my first time of this kind of request.
I hope I'm not too hasty with this current cycle.

## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **33** 
- USD requested: 41 
- BSQ rate: 1.23 USD per BSQ 
- Previous compensation request (if applicable): # (_None, this is my first and single one._)  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Design fixes #4019 Dark mode ColoredDecimalPlacesWithZerosText|	dev	|	 01	|	[bisq-network/bisq/#5198](https://github.com/bisq-network/bisq/pull/5198)	|	Small JavaFX CSS fix|	
|Tor relay operator	|	ops*	|	40	|	[bisq-network/roles#72 (comment)](https://github.com/bisq-network/roles/issues/72#issuecomment-901840730) 	|	New Tor Relays|

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Would be happy to use the compensation to cover costs of course to keep running the newly added and also do like to setting up some more new nodes soon.

**Comment by sqrrm** [comment]
@bisqubutor I wasn't involved in the css fix, but I suspect you're not asking enough for that fix, @ripcurlx what do you think?

The ask for tor relays for the first month looks fine to me, but I assume you will ask somewhat more once they're all up and running, could you give an indication of how much?

**Comment by bisqubutor** [comment]
> 
> The ask for tor relays for the first month looks fine to me, but I assume you will ask somewhat more once they're all up and running, could you give an indication of how much?


@sqrrm Since I'm not sure yet what would be reasonable, I chose this value resulting based on the number of the 4 previously announced relays for the beginning I chose, thus 10 apiece to start with that would be helpful. But you will know it from experience with the operation of your own best.
The costs arise evenly multiplied by the number of running nodes.

**Comment by sqrrm** [comment]
I basically ask for the cost of servers plus a little bit for the work to keep them running. I see it as a service I do for the community. If you're more experienced running nodes I assume it'll be even less work. USD10 per instance sounds very reasonable for the performance of your nodes.

**Comment by ripcurlx** [comment]
@bisqubutor I agree with @sqrrm that you asked too little for this work as it was tricky to find (although to fix seems easy).  Sorry that I missed to review earlier (I had personal issue the last days).

**Comment by ripcurlx** [comment]
If you are not able to submit your CR for this cycle please try it again for next cycle and I'll review it in time (big promise) 😬

**Comment by bisqubutor** [comment]
Okay, here is my BSQ Transaction ID: `adfb0da353711a7dd7b1df2eec24d277d55507ff80b73054b2767756c6fa78d7`

**Comment by MwithM** [comment]
Closed as accepted.
