### ISSUE TITLE
For June 2018

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/compensation#90]
## Summary					
					
- BSQ requested: 1450		
- BSQ address: B16kMZonmnNXrZvSqGuXVjpWWTZnSVG3xJb					
					
## Contributions delivered					
					
- [Payment Methods Slack](https://bisq.slack.com/messages/C89R6FQS3/) —> 100
- [Payment Methods Community](https://bisq.community/c/payment-methods) —> 100
- [Payment Methods Tracking and Report](https://docs.google.com/spreadsheets/d/1AeWAz5w_IzIQ3-QS9yEzZBOTH_83DT503IhLg_PQD10/edit?usp=sharing) —> 550
- [Adding Moneygram] (https://github.com/bisq-network/payment-methods/issues/11) —> 700
					
## Contributions in progress					
					
- [Payment Methods Knowledge Base: Cash Deposit](https://github.com/bisq-network/bisq-docs/pull/52)					
- [Payment Methods Knowledge Base: Revolut](https://github.com/bisq-network/bisq-docs/pull/51)					
- [Adding Payeer] (https://github.com/bisq-network/payment-methods/issues/14)					
- [Adding Serve] (https://github.com/bisq-network/payment-methods/issues/7)					
					
## Roles performed					
					
- Payment Methods Maintainter. Report for May: https://github.com/bisq-network/roles/issues/38#issuecomment-401537623

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.
