### ISSUE TITLE
For Cycle 28

### ISSUE THREAD

**Issue by bisqubutor** [bisq-network/compensation#908]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **444** 
- USD requested: 675 
- BSQ rate: 1.52 USD per BSQ 
- Previous compensation request (if applicable): For Cycle 27 #899

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Tor relay operator | ops* | 675 | [bisq-network/roles#72 (comment)](https://github.com/bisq-network/roles/issues/72#issuecomment-920497141) | 90 nodes (86 new set up) |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by xanoni** [comment]
heroes

**Comment by wiz** [comment]
This is not approved for any budget allocation by the Bisq ops team

**Comment by Emzy** [comment]
As team lead for ops I reject this compensation request!
There is no budget for it.  
It is rejected.

**Comment by xanoni** [comment]
Sad! Still a hero. 

Life sucks sometime @bisqubutor
