### ISSUE TITLE
For June 2018

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/compensation#91]
BSQ amount requested : 2850
BSQ address : B19yxYCRTVaDfRfucrH6aEzeZpoVTv8Je8S
This is my first compensation request. I read other compensation requests+doc in order to try to provide a pertinent evaluation. 
I applied the 1BSQ=1USD rule.
I looked also full-time peoples average numbers as a rough referential.
My evaluation has many approximations, but hopefully I’m roughly conforming to custom. 
I’ll read more experimented stakeholder’s comments with attention to correct what must be.

Details are below :

**Support : (BSQ  requested = 1750)**
I put details here, because it was explicitely asked, 
https://github.com/bisq-network/roles/issues/64#issuecomment-394813470 
I survey : the discourse forum, the slack (all channels), github, and freenode. 
I tried to reduce as much as possible the answering delay for the questions, because I think this is useful in helping the usability of Bisq. Users know they are not alone. (I have a big messy faq which helps me). I intervened in 43 support threads this june. Discourse (22), slack (13), github (4), and freenode (4). 
It must be pointed also that while I’m present 07:00-20:00 GMT, this realizes/helps a good coverage with alexej996. Alexej has also encouraged me, and this was a good help.
My activity summary on discourse : https://bisq.community/u/Homard/activity
Support on GH is as comments, which don’t appear in the summary.
slack has no summary, neither the Freenode IRC.
Evaluation is based on https://github.com/bisq-network/compensation/issues/24 which I think is a good least estimation, since support is imo a necessary task for bisq’s growth … but rather tedious and not really exciting. (We had a nice jerk example just today on discourse !)
(Answering fastly is also rather demanding in that it cuts other tasks)
June was my 1st month so I don’t ask 2000 BSQ. If I continue, this is the least I’ll ask next month.

**Documents : (BSQ requested = 300)**
As suggested, I read carefully many documentations and profited to mark some remaining typos.
I opened 3 issues + 3 PR/merged.
https://github.com/HarryMacfinned?tab=overview&from=2018-06-01&to=2018-06-28
NB : I could have provided more Prs, but I’m not familiar with GH, and prefered to wait for merges before submitting/empiling new PRs.

**Transifex : (BSQ requested = 300)**
I translated 143 words in may (to french). I browsed thru the words, and translated a most easy bunch first. If I continue, remaining translation will certainly require much more time.

**Development work : (BSQ requested = 500)**
I participated in many discussions about debugging/features/not features/improvements.
GH summary says I opened 5 issues on bisq-desktop (I though it was more).
Leads to myself being currently coding (in python) a pricenode monitor (prices+ fees). Should be delivered in july. My plan is to have it able to run on a raspberry.
I build/maintain a dedicated (0% userland) hardware infrastructure to help the bisq-network (2 Pcs, 1 raspberry, 2 VPS). I have other material already ready if needed (and room for some more).
I have one VPS running munin-master (was a GH/bisq-network suggestion) … but no bisq-nodes are using it at the moment.
I explored many bounties/roles. Preparing to code. 
My GH : https://github.com/HarryMacfinned?tab=overview&from=2018-06-01&to=2018-06-28
I didn’t tune my GH account very well, which probably explains missing things.

**Ecosystem : (BSQ requested=0)**
- I spent some time on a complementary P2P solution to youtube (peertube) … Got alas 0 returns.
- I spent some time exploring onion solutions for Bisq’s ecosystem. Imo some part of Bisq’s ecosystem would be more safe being onioned. And we shouldn’t wait for problems to do that.
- I looked for a own gitlab repo. Not a general one, but maybe some non crucial things.
- I looked for P2P chat : scuttle ( https://www.scuttlebutt.nz/ )

**Other : (BSQ requested=0)**
I made some little advertising for Bisq here and there. I’m targeting some people who may help in developing Bisq in France (as paper writer) and as contributor(s). But I’m doing that softly (because myself I’m not mastering enough the thing right now).
I spent also time for exploring (by raw order of deliverability) : market-price-feed-agregator, analytics, API, regtest, install a gitlab, bisq for debian , bisq for raspberry, etc.

**Hour based evaluation :**
As suggested by MK at https://github.com/bisq-network/compensation/issues/24 ) + in order to cross-check the above global evaluation.
(At least 1 week in may was also fully devoted to Bisq, but ~100 % learning/training.)
→ See the table : http://164.132.198.50/table-june2018.pdf
Approximate repartition for june’s 185 hours : 
~30 % = 55 hours = delivered = BSQs requested
~70 % = 129 hours = non-delivered + learning/training = 0 BSQ requested

**Additionnal :**
- I devoted the whole june 2018 exclusively to the Bisq project. I participated to no other projects. 
If my compensation request is agreed by a majority of stakeholders, my intention is to devote also july 2018 entirely to Bisq, but changing hopefully significantly the repartition percentages.
- I could probably take over some other tasks, but it must not hurt my privacy policy. This is a great personal point.  But I think it also concerns the project globally.
- more things to say, but other places are more appropriate I think.
Sorry for being probably a bit long. Thanks for reading !

**Comment by cbeams** [comment]
@HarryMacfinned, everything looks good above, with the exception of the "Development work" being considered as [delivered](https://github.com/bisq-network/proposals/issues/19). No big deal this time around, but please do review the proposal I just linked to if you haven't already, and adjust future compensation requests accordingly, thanks.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.
