### ISSUE TITLE
For June 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#92]
## Basic information

 - BSQ amount requested: **4650**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

### Development work:
Most for my dev work is for the DAO [[1](https://github.com/ManfredKarrer/bisq-core/tree/voting)] and not shipped code so I will not include that in the compensation request. Also i implemented a few new features for the 0.7.1 release which is not shipped yet and therefore not included in the request here.

### Maintainer:
- Maintain 6 seed nodes, 2 Bitcoin nodes, 2 price nodes, monitor node, market server and BSQ explorer (13 * 50 BSQ = 650 BSQ)

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1
- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8
- Seed node maintainer: https://github.com/bisq-network/roles/issues/6
- Statsnode Maintainer: https://github.com/bisq-network/roles/issues/7
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14
- Markets Website+API Operator/Maintainer: https://github.com/bisq-network/roles/issues/9
- Seed node operator: https://github.com/bisq-network/roles/issues/15
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67
- Events Maintainer: https://github.com/bisq-network/roles/issues/65
- Ambassador: https://github.com/bisq-network/roles/issues/35

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- GitHub Admin: https://github.com/bisq-network/roles/issues/16
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Slack Admin: https://github.com/bisq-network/roles/issues/23
- Freenode Admin: https://github.com/bisq-network/roles/issues/22
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31
- Transifex Admin: https://github.com/bisq-network/roles/issues/20
- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Support Staff: https://github.com/bisq-network/roles/issues/64
- Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12

I request in total 4000 BSQ for exercising my roles (this month got added quite a few roles). Specially the work on reviewing and merging PRs takes considerable time and effort. Beside that keeping an eye on the infrastructure monitoring (seed and btc nodes) takes more time and attention as is should (hope we find soon a dev who will make a good monitoring tool).

[1] https://github.com/ManfredKarrer/bisq-core/tree/voting

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.
