### ISSUE TITLE
For July 2018

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#93]
## Basic information

 - BSQ amount requested: **10650**
 - BSQ address: **B1N15prE63ZHC7grk2hyuVDLNfrQYCkDT84**

### Development work:
Some past dev work from previous months got shipped with 0.7.1:
- Ack messages for all trade, offer- and dispute messages
- Add referrer Id for external Bisq market makers
- Fix bug with Sepa offers and Sepa instant taker
- Fix reuse of change addresses
- Don’t treat RBF transactions as risky
- Fix wrong dust limit values in Bitcoinj
- Deactivate Venmo and CashApp
- Add popup for feedback after trade completion
- Show popup if local Bitcoin core is running
- Don’t include assets with diff. network type
- Ignore “Alert key compromised” message from old nodes in Bitcoinj

Request for past dev work shipped in 0.7.1: 8000 BSQ

Most for my dev work that month was for the DAO [[1](https://github.com/ManfredKarrer/bisq-core/tree/voting)] and not shipped code so I will not include that in the compensation request. 
Beside that I did a few PRs for the Master branch but it is not shipped yet.
Beside DAO work I helped Joachim with the Mobile notification app. Desktop integration and server is mostly complete. Iphone version is also in a pretty good state. Android app needs a bit more dev effort and will be probably completed when Joachim is back from holiday. I estimate that we can launch it mid or end of August.
Added a few new proposals as well.
Request for dev work: 0 BSQ (nothing is shipped)

### Maintainer:
- Maintain 6 seed nodes, 2 Bitcoin nodes, 2 price nodes, monitor node, market server and BSQ explorer (13 * 50 BSQ = 650 BSQ)

Requested as nodes maintainer: 650 BSQ

### Roles:
The following are roles I am responsible for, with links to my monthly report about each.

- Founder: https://github.com/bisq-network/roles/issues/1
- BitcoinJ Maintainer: https://github.com/bisq-network/roles/issues/8
- Seed node maintainer: https://github.com/bisq-network/roles/issues/6
- Statsnode Maintainer: https://github.com/bisq-network/roles/issues/7
- Pricenode Maintainer: https://github.com/bisq-network/roles/issues/14
- Markets Website+API Operator/Maintainer: https://github.com/bisq-network/roles/issues/9
- Seed node operator: https://github.com/bisq-network/roles/issues/15
- Monitoring Operator/Maintainer: https://github.com/bisq-network/roles/issues/10
- Bitcoin Node Operator: https://github.com/bisq-network/roles/issues/67
- Events Maintainer: https://github.com/bisq-network/roles/issues/65

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- GitHub Admin: https://github.com/bisq-network/roles/issues/16
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Reddit Moderator: https://github.com/bisq-network/roles/issues/25
- Slack Admin: https://github.com/bisq-network/roles/issues/23
- Freenode Admin: https://github.com/bisq-network/roles/issues/22
- Compensation Maintainer: https://github.com/bisq-network/roles/issues/31
- Transifex Admin: https://github.com/bisq-network/roles/issues/20
- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63
- Bitcoin Node Maintainer: https://github.com/bisq-network/roles/issues/66
- Support Staff: https://github.com/bisq-network/roles/issues/64
- Bisq Website Operator/Maintainer: https://github.com/bisq-network/roles/issues/12

Requested for all the listed roles: 2000 BSQ

[1] https://github.com/ManfredKarrer/bisq-core/tree/voting

**Comment by ripcurlx** [comment]
@ManfredKarrer Maybe for next time you could directly link to the report comments, so it is quicker to go through your reports (e.g. https://github.com/bisq-network/roles/issues/1#issuecomment-408156846) 😄

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/94#issuecomment-410437521
