### ISSUE TITLE
For December 2018

### ISSUE THREAD

**Issue by initCCG** [bisq-network/compensation#95]
## Summary

 - BSQ requested: 2203 BSQ
 - BSQ address: B1Q9UGZyuoQJ7tGSjFx11D64dvz47RY86XM
 
 - 7 real people have been involved in the work below - most as paid contractors, others as volunteers.

## Details
 
 - For professional, technical translation by native speakers, the prevailing real market rate we encountered was 0.05 - 0.07 USD / word. We request 0.015 USD / word.
After all, we paid 0.025 USD / word for initial Thai review, and to  complete  Vietnamese to current level, additional of $76 + $44 = $120.

 
 - Liquidity weeks pay 20 BSQ / week. So at that rate, we request:
    - For XMR 8 month * 4 weeks * 20 BSQ =  640 BSQ
    - For VND 2 months * 4 weeks * 20 BSQ = 160 BSQ
    - For THB and USD 4 months * 4 weeks * 10 BSQ = 160 BSQ  
 
### Contributions delivered

 - Funded and delivered full initial translations of 2 languages -- Vietnamese, Thai.
    - Approximately 28295 words translated total
    - Requesting: 473 BSQ.
 - Funded and delivered full initial reviews of 2 languages -- Vietnamese, Thai.
    - Approximately 23500 words reviewed total and corrected as necessary
    - Requesting:  470 BSQ.
 - Delivered more than 10 percent translation and completion of Russian translation
 - Delivered 85 percent review of Russian translation
    - Approximately 10,000 words reviewed total and corrected as necessary
    - Requesting:  150 BSQ.
 - Hiring and management of translators and reviewers in all above languages
    - Requesting:  150 BSQ
 - More than 8 months of market making in XMR
 - More than 2 months of low-spread market making in VND 
 - More than 4 months sell-side liquidity in USD and THB, including first THB-BTC trade
 (our trader node address available upon request)
    - Requesting: 960 BSQ
 
 - _Links to contributions you have [delivered](https://www.transifex.com/bisq/bisq-desktop/dashboard/):_
https://www.transifex.com/bisq/bisq-desktop/dashboard/
 - _The amount of BSQ requested for each: Please see above._
 - _Comments that will help stakeholders understand its value:_

As most know, and many liquidity weeks show, the developed world doesn't need Bitcoin very much, much less decentralized Bitcoin exchanges. We propose that Bitcoin is most needed and has the most potential on territories owned by groups with unwise and antiquated governing philosophies.

3 examples featured in this block of our work:

- Thailand: The Southeast Asia economic leader, with tremendous wealth and potential, and relatively open to trade. However, the ruling elite is militaristic, exceptionally hierarchical and medieval in their mindset. The general population is industrious, but incredibly brainwashed, and the epitome of the word "sheeple". The ruling gang has just instituted a tax on Bitcoin trading, which can be as high as 22%: 15% capital gains, and 7% VAT. The traders are not yet concerned, because of the "live in the moment" idiosyncrasy of the Buddhist culture...
THB is not weak, and did surprisingly well during GFC, but it's not stronger than Bitcoin. 
The centralized exchange operators - as their colleagues worldwide - are not interested in decentralized Bitcoin trading, or any of Bitcoin's core ideology. In fact, they are staunchly opposed to it. They only need Bitcoin to become part of the wealthy elite, without changing the status-quo. They are consolidating their power, and will use the government gang to protect their business from competition, including Bisq...
Thai language is rather different from English, and few there know the latter well. Even those that think that they do, really don't, and the desire to learn English among the general population seems rather low, compare to learning Chinese for example.

- Vietnam: The new destination of choice for business - big and small - fleeing the worsening business conditions in China.
Incredibly well positioned and endowed with such a long coastline and relatively industrious, educated population - not stuck in an entrenched, centuries-old caste system, the way for example Thailand and India are.
Much Bitcoin trading goes on in Vietnam, but most of it through shady Vietnamese language Telegram and other social network apps, without the protection that Bisq can offer.
The Vietnamese ding dong (VND) has been irresponsibly wrecked by the usual suspects, and all who come there instantly become millionaires in it...
The rulers are unwise, militant, and prone to unpredictable, knee-jerk parroting of regulators in surrounding authoritarian territories.
The Vietnamese language is impossibly difficult and different from English - both in pronunciation and for example in the insane number of personal pronouns. There is a great desire among the population and young elite to learn and speak English, but it's very difficult even for them to learn due to the languages being so different. 

- Russia: Basically continues to be a Franco-Pinochet style dictatorship, which is essentially in a geopolitical situation similar to that of Iran, but with more power and resources to cope with it. Much of the elite holds rather libertarian views, consistent with Bitcoin's core ideology, and has been the source of much libertarian thought for more than a hundred years - Kropotkin, Bakunin, etc.
The RUR was of course demolished - yet again during our lifetime - in 2014. And it seems personal with the Russian leadership to be able to get out of the USD hegemony in some way they can control - same as it seems with the Iranians.
Russians have been relatively active in Bitcoin from the OG days - second only to the Anglos and Germans maybe. The leadership is incredibly backwards and unenlightened, however, and could crack down on every kind of Bitcoin trading under any insane pretext. 
A lot of the educated population understands English enough to be able to use Bisq in it, but of course Cyrillic alphabet is significantly different and Russia is like the US in language conditions: one can travel through several time zones, and never need to use anything besides Russian. So, there's little incentive to learn English for those who don't travel out of Russia and former Soviet republics much...

That is our view, and why we consider it imperative for Bisq to gain every possible foothold in these markets, before the powers that should not be in them are able to consolidate their control over the Bitcoin trade.
These Bisq translations are meant to facilitate Bisq advancement there.

### Contributions in progress

 - Funding second-opinion review of Persian translation
 https://www.transifex.com/bisq/bisq-desktop/language/fa/
 - Continuing review and improvement of Russian translation
 
> _**This section is optional**._

### Roles performed

 - Not Applicable

> _._

**Comment by ManfredKarrer** [comment]
Hi, I just want to give a quick feedback (traveling and not enough time to read all).
- The calculation with bond does not make sense. The arbitration bonds are not defined either atm. So please remove that as that adds just confusion.
- 1 BSQ is considered as 1 USD - as there is no market nobody knows the real value (will likely be higher) but that is what all contributors base on their contribution. 

190k USD for translations is far off. I would not accept such a request with my voting power. Calculation based on words and past numbers is not a good metric. Why not just take what you have paid to the translators as your base and use that? I know it is hard and probably past contributions have been over-paid. But when you look at other requests (e.g. a request for a full month dev work is about 7-14k BSQ) you will see that this is not in balance.

**Comment by HarryMacfinned** [comment]
Concerning : https://github.com/bisq-network/compensation/issues/91
- this was my very first comp. request here, 
- and I never did professionnal paid translation before (not my job), 
- and I didn't find myself a reference for what to ask
- and it only concerned a small number of words
- and I didn't suggest using this "evaluation" as a reference

I'll (of course) adapt my june request to what is the proper standard for this job.

I think however that the price/word is not the same when you translate pages and full sentences, than when you translate just one isolated word and the other.
I don't say that for the small task I've done (doesn't seriously matter), but for wanting to have the translations done.

Since it's not a big amount, I think/suggest maybe the best is I'll simply annulate the BSQ request for this june translation task. (Others may use it as a wrong reference).
And I may ask it later when we have better reference for how the translation task should be valued.

**Comment by initCCG** [comment]
We don't begrudge any contributor what they were paid.

In fact your valuation seems reasonable, because it seems rather a
stretch to arbitrarily set a token that doesn't yet exist and has no
market value at 1 USD equivalent.

Even Bitcoin didn't start that way; hence 10000 BTC pizzas back then... :)
At this stage 1 BSQ = 0.01 USD or even 1 satoshi seems more appropriate.
However, Bisq is not our organization.
So, we naturally accept whatever the founders consider appropriate.

Perhaps, the bigger question then is what else has been wildly
overcompensated in BSQ, since compensation in it began, and overlooked,
because it was paid for small task blocks to individuals.

We just highlighted this question by delivering so quickly such a large
and complete block of initial work as a group effort.
i
CCG


gpg: B03B 3301 83F3 A497 F433 CCD3 4424 816B 8323 5B37

**Comment by ManfredKarrer** [comment]
@initCCG The 1 USD = 1 BSQ valuation is what we use since the beginning of the DAO and to change that would render all past requests incompatible as well all requests of other contributors. I also dont think that this is over valued, there will be 2.5 M BSQ which will represent the project value. Compared to OpenBazaar which got valuation of about 20-30M by the investment they received from VCs I think Bisq's project value is likely higher than 2.5M USD. Your 0.01 USD would render it to 25 000 USD, that is even less as what we have on the donation address and would be also the "printing costs of a BSQ in BTC (e.g. the 2.5 BTC used for funding the genesis tx). 

Your numbers you mentioned above with 0.07 USD / word and 45k words would result in 3150 USD, so that would be very far away from 190k BSQ (USD). I understand that the confusion is coming from a different USD valuation you are using but as said that would render requests from different persons incompatible.

Please try to find a realistic USD value which you feel good with convert that to BSQ according to the "consensus exchange rate" of 1 USD/BSQ and adjust the request.

**Comment by initCCG** [comment]
@ManfredKarrer Thank you. Understood. Adjusted.

**Comment by ManfredKarrer** [comment]
@initCCG Thanks for the update! And thanks for the overview about the different markets.

**Comment by ripcurlx** [comment]
@initCCG Thanks for your detailed compensation request and contribution! The only thing I want to discuss is, if we should/want to have the same incentive structure as for development work. For development, only code that is actually shipped in a release is up for compensation. So the pull request might be merged to master already, but not shipped and thus not available to the end user. The reason for this is, that we only want to compensate anything that has direct end user value. If we do it for translations the same, it would mean you could do a  compensation request after next release, which will happen this month. What do you think?

**Comment by cbeams** [comment]
+1 for [delivered work](https://github.com/bisq-network/proposals/issues/19) in the context of translations meaning that they are included in a Bisq release.

**Comment by HarryMacfinned** [comment]
As for the delivering, I would consider words being on the transifex as delivered,
because :
1/ What happens after is no more in translators's control.
Let's imagine that Bisq needs 6 months to propose a next version, this is Bisq's affair and no more dependent on translators. 
So imo they should not be impacted/punished by that.

2/ Also, translation may concern people happening to have just some hours this or this day 
to do a part of the job, and not at all planning to finish completely a translation.
If they think they will be paid in 6 months ... who will candidate ?

3/ translations may be done by people having 0 knowledge about Bisq, and just arriving
here by hazard. If the rules are not straightforward, I fear they will not deepen a lot.
They'll simply jump to something else.

We have to navigate between 2 reefs : overpaying ... and haven translations not done,
even not beginning.
The 2 reefs are bad, but being stucked with no translations even starting is really hurting for Bisq imo. The soft is here (lot of work done) ... but it misses some countries cause of no translation. 
I don't know what other stakeholders think about that.

**Comment by ManfredKarrer** [comment]
I agree that the price of @initCCG is very low and he deserves a higher compensation. Thanks @BravoIndia to bring that up!
I see in the feedback that the model with getting paid when software is shipped gets quite a bit of friction and I think we should reconsider that model and/or make it more flexible. I have not a very strong opinion on either side. The goal with the strict model is that Bisq is not producing stuff which never is getting used but to focus on the value for the users of anything we do. But not applying that model everywhere does not mean it ends up in that negative situation automatically. If we take care and keep an extra eye on areas which might have an exception from that rule it still might work well if that areas is productive with what is paid for in BSQ. So I think we should be pragmatic here and see what works best. 

I personally would like to delegate that to one who feels responsible to the translation area and come up with a suggestion which works for all who are currently involved. Simplicity of the model is for sure a great plus.

**Comment by HarryMacfinned** [comment]
I have the same feeling.
200.000 BSQ was imo a far too high evaluation, but I feel a problem with 2000 BSQ for several persons realizing 4 translations. (Even if the cost of life varies indeed greatly from country to country.)
It's also in Bisq's long term interest, we must no discourage future translations.

It's also true that having languages translations ... without arbitrators in the given language, is certainly a really hard issue (speaking from the support cubicle !).

**Comment by initCCG** [comment]
As we mentioned, we are not in a hurry to receive this compensation. We
thought that we had to meet some kind of July deadline, and put
submitted it now.
We will change it to whichever month you wish.
i
CCG

gpg: B03B 3301 83F3 A497 F433 CCD3 4424 816B 8323 5B37

**Comment by ManfredKarrer** [comment]
@initCCG 
You can add a WIP (work in progress) to the title if you want to postpone it for next month and change title to August instead of July.
There is no expiry data on completed work, so no issue if you move it to next month.
I would recommend to do it as there are quite a bit of discussion going on to find a proper model how to compensate translation work and your current amount feels too low to me (and others). We are all in a learning period here as the model of our DAO is new and we need to find the best practice...

**Comment by initCCG** [comment]
One member of our alliance has followed Bisq since hearing an interview
about it in 2016.
This trial involvement has been useful for us, and we understand much
more about the status of Bisq project and its organizational structure.

It is difficult to absorb so much verbose, complicated discussion in a
foreign language.

We have a professional spokesperson in English, but we would have to
bring him up to date on this, and expend his man-hours to work it,
further increasing our costs, which we don't consider worthwhile doing yet.

We have already endangered ourselves and our subcontractors enough
simply by funding Bisq translations for our significant markets that are
ruled by soldiers and other militants, where Bisq/BTC are actually
needed. So, we respectfully decline to join any calls at this time.

The compensation mechanism proposal we have would add complexity, as you
indicated regarding compensation in arbitrator bonds, which seems
similar to the way "gas" and "Eth" are are used.
That debate would draw attention from development, which would be
counterproductive for us and Bisq.

We are sure that our initial translations are not perfect, and continue
to be "WIP".

We humbly accept whatever compensation will be awarded us by the
stakeholders, under the rules of Bisq founders and your organization.

Buddha Nature tells us that "When words are the same as silence, better
to be silent".
We apologize that we cannot spend more man-hours and be more helpful on
the compensation mechanism.
We don't expect to have further comments on this matter at this time.

Thank you for your attention and consideration.
CCG
---
#Plow with Carabao!
#Plow like Carabao!
gpg: B03B 3301 83F3 A497 F433 CCD3 4424 816B 8323 5B37

**Comment by ManfredKarrer** [comment]
@initCCG I am sorry to hear that it gets too complicated for you but understand it.
A small suggestion from my side to make your request more realistic is to increase it to 3000 BSQ. But no worry if you don't want to. I will vote for your request anyway. You added a lot of value by providing the translations and the market making. All the details how we deal exactly with the requests and estimations are secondary at the end. Have understanding that we are exercising a new model and we are all learning how to do that best - both for contributors and BSQ stakeholders.

**Comment by initCCG** [comment]
Moved to September due to Thai formatting problem, new strings, and Persian review second opinion.

**Comment by initCCG** [comment]
Persian and Vietnamese new strings still not finished. Thai pending Java 10 integration.

**Comment by ripcurlx** [comment]
Java 10 support will be part of release 0.9.0 mid of October.

**Comment by initCCG** [comment]
Not yet delivered, pending 0.9.0 release and Persian review.
Thai and Vietnamese ready to release.

**Comment by initCCG** [comment]
Not yet delivered, pending 0.9.0 release.
Persian review still in progress.
Thai and Vietnamese no longer ready to release due to latest 391 strings changed and added.
We will not have manpower to do these prior to next release, except maybe Persian, if we're lucky.
Latest strings and changes done in Russian, except for 1 new string for an obscure altcoin.

**Comment by initCCG** [comment]
Vietnamese and our part of Thai initial delivered.
Persian has been removed, because still WIP.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/183#issuecomment-451638745.
