### ISSUE TITLE
For July 2018

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/compensation#97]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 490
 - BSQ address: B1EFcs4HsAijnxFwZB8QudD5wNTRwTUnNGJ

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Only code review has been delivered this month, see https://github.com/sqrrm?tab=overview Requesting 300 for June and July reviews as I didn't request any for the reviews last month.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Currently working on the DAO in @ManfredKarrer's repo, will request for that once merged to master.

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bitcoin node maintainer - https://github.com/bisq-network/roles/issues/66#issuecomment-408768168
Bitcoin node operator - https://github.com/bisq-network/roles/issues/67#issuecomment-408775261
Tor relay operator - https://github.com/bisq-network/roles/issues/72#issuecomment-408778908

Requesting 190 for the roles
- 50x2 = 100 for running two bitcoin nodes
- 50 for the node maintainer
- 10x4=40 for the tor relay operator

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/94#issuecomment-410437521
