### ISSUE TITLE
For July 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#99]
## Summary
 - BSQ requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**
## Roles performed
- Support Staff | https://github.com/bisq-network/roles/issues/64#issuecomment-408930722 | 2800 BSQ
- Forum operator | https://github.com/bisq-network/roles/issues/19#issuecomment-408936000 | 150 BSQ
- Reddit moderator | https://github.com/bisq-network/roles/issues/25#issuecomment-408937029 | 50 BSQ

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/94#issuecomment-410437521
